### ISSUE TITLE
[Feat]: Footer Color 

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1006]
### Curent
https://github.com/priyankarpal/ProjectsHut/assets/101205226/3b3bc7a9-f538-4616-b9d7-864337ac2060

### Change 
<img width="960" alt="2023-05-30 (1)" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/7ddd7578-bcf2-4fa7-aa57-a5a0441aed2b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @parasss19 we will change the footer soon so I think we don't need to change the colour right now.

https://github.com/priyankarpal/ProjectsHut/issues/979 (hasn't been ready yet)
