### ISSUE TITLE
Feat: Create a custom scrollbar 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#101]
- Create a custom scrollbar
- if you want to work just ask & after completing this work share the screenshots.

**Comment by ydv-ankit** [comment]
can you give more details, how scrollbar should be?

**Comment by priyankarpal** [comment]
> can you give more details, how scrollbar should be?

just It should be simple like this 

![image](https://user-images.githubusercontent.com/88102392/226917331-2cea83e4-5b57-4459-984c-8cfe8669f6ee.png)

**Comment by priyankarpal** [comment]
> white scrollbar with black background??

it's just a demo. try to make a white scrollbar.

**Comment by ydv-ankit** [comment]
okay

**Comment by priyankarpal** [comment]
Done
