### ISSUE TITLE
data: project addition by 

### ISSUE THREAD

**Issue by pankajktech** [priyankarpal/ProjectsHut#1014]
### Add a new project to the list

I want to add a MERN Stack Job Portal Website Project.
This is Project Link: [https://landyourjob.netlify.app/](url)
I am a GSSoC'23 Contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
