### ISSUE TITLE
data: project addition by  Google-Ka-Dinosaur

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [priyankarpal/ProjectsHut#1016]
### Add a new project to the list

I would like to add another web3 based application which is a decentralized card game on the avalanche-c testnet. I feel that this project will be of great value to anyone starting out on his web3 journey and looking to explore more ways of using the web3 technology.

Here is the Link to the Website : https://celadon-selkie-e01f71.netlify.app/
![Screenshot (194)](https://github.com/priyankarpal/ProjectsHut/assets/98577878/9dc7e9ba-4f00-439b-9d32-926a4262537d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
