### ISSUE TITLE
Fault in route path

### ISSUE THREAD

**Issue by JasonDsouza212** [priyankarpal/ProjectsHut#102]
The route to the projects page appears as **https://projectshut.vercel.app/#/ProjectsPage**,
 but it would be better to use a link like  **https://projectshut.vercel.app/ProjectsPage** instead.

**Comment by priyankarpal** [comment]
> The route to the projects page appears as **https://projectshut.vercel.app/#/ProjectsPage**, but it would be better to use a link like **https://projectshut.vercel.app/ProjectsPage** instead.

Yes. Currently I'm using Hashrouter instead of Browser router.

**Comment by priyankarpal** [comment]
> The route to the projects page appears as **https://projectshut.vercel.app/#/ProjectsPage**, but it would be better to use a link like **https://projectshut.vercel.app/ProjectsPage** instead.

Would you love to fix it?
