### ISSUE TITLE
Docs: Add Repository Contribution Graph

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1022]
### what's wrong in the documentation?

- There's nothing wrong in documentation, we're just adding a new feature which shows the contributors as images
- It will give more professional look to the repository, this encourages the contributors to contribute more to this repository

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/30901c31-a920-45e9-bd86-81c60eff435c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
previously we had & we remove because of lots of profile

**Comment by 0xabdulkhalid** [comment]
But why can't we set it up with a dropdown like this, could be more encouraging to the contributors

<details>
<summary>Contributors</summary>

![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/30901c31-a920-45e9-bd86-81c60eff435c)

</details>

**Comment by priyankarpal** [comment]
> But why can't we set it up with a dropdown like this @priyankarpal, could be more encouraging to the contributors
> 
> Contributors

yeah! cool assigned to you

**Comment by Ritika8081** [comment]
is this issue still open ?

**Comment by 0xabdulkhalid** [comment]
@Ritika8081, Issue is still open but i'm already assigned and opened a PR though.

So you can find/create a new issue to contribute, Thanks!
