### ISSUE TITLE
Feat: Refactor search functionality to use searchParams

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#1023]
### What feature?

We can use search Params and append `?filter=filter-value&q=search-value` at the end of the URL whenever the user wants to search for something.

### Add screenshots

No Screenshots.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we can add
