### ISSUE TITLE
Feat: Maintaining the filter

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#1024]
### What feature?

Currently, the projects are filtered if we apply any of the filters.
If we click the `More ->` button on any of the filtered projects, we will be able to see all the projects of the user.
On this page, there will be a `< Back to Projects` button if we click on that button we'll be taken back to the projects page.
But, the filter we applied earlier will be gone. 
We can improve this and maintain the applied filter when the user clicks on the `< Back to Projects` button.

### Add screenshots

No screenshots.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to change the path
