### ISSUE TITLE
Feat: Scrolling Animation

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1025]
### What feature?

I want to add scrolling animation on Banner and Footer for better UI

## Currently no Animation and the landing page looking so simple

https://github.com/priyankarpal/ProjectsHut/assets/101205226/d121f943-22d7-4d07-b9c8-3dd29e3ee1c8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, we need to add framer motion animation. 

also can you share a demo?

**Comment by parasss19** [comment]
> hey, we need to add framer motion animation.
> 
> also can you share a demo?

Right now i have no sample work but i will try to implement the framer motion on banner.jsx

**Comment by priyankarpal** [comment]
> > hey, we need to add framer motion animation.
> > also can you share a demo?
> 
> Right now i have no sample work but i will try to implement the framer motion on banner.jsx

ok ok cool
