### ISSUE TITLE
Bug: search input with white background

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#1028]
### What happened?

There is a bug in the search input where it has a white background, which negatively impacts the user experience by reducing visibility and contrast.

### Add screenshots

![Screenshot (97)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/129db2a1-6577-46f0-a3de-9a3fc9d9eb9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I don't think it is a bug. we need to change the opacity of the white colour.

**Comment by jibola2588** [comment]
> I don't think it is a bug. we need to change the opacity of the white colour.

I think making the background transparent, and adding focus to the input when the page is loaded for the first time will aid more user experience

**Comment by priyankarpal** [comment]
> > I don't think it is a bug. we need to change the opacity of the white colour.
> 
> I think making the background transparent, and adding focus to the input when the page is loaded for the first time will aid more user experience

yeah we can do 

assigned to you

**Comment by jibola2588** [comment]
Sir, the search input has been removed

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
