### ISSUE TITLE
Data: project addition by KALEPU-OMKAR 

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [priyankarpal/ProjectsHut#1029]
### Add a new project to the list

I want to add a new project to this repository. 
The project identifies as event_keycodes.
This is a simple project using HTML, CSS and JavaScript that displays the keycodes when a key is pressed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by OMKAR-KALEPU** [comment]
May I know the reason why the labels have been removed?

**Comment by priyankarpal** [comment]
> May I know the reason why the labels have been removed?

according to the GSSoC rules it's invalid. You've added the same projects in two different repositories.

**Comment by OMKAR-KALEPU** [comment]
Oh, my apologies. I didn't know.
