### ISSUE TITLE
To improve responsiveness in mobile mode

### ISSUE THREAD

**Issue by anamrani0832** [priyankarpal/ProjectsHut#1035]
![image](https://github.com/priyankarpal/ProjectsHut/assets/111300005/eff54423-1c83-4625-80c8-f67294d731f0)
There is some problem in responsiveness in the projects page at the bottom like page buttons are not much user friendly.
So I guess there is need to improve that.

**Comment by priyankarpal** [comment]
hey @anamrani0832 we will remove the pagination in a few days so I think we don't need to change it right now.
