### ISSUE TITLE
Bug: Overlapping Layout of Project Details Page on mobile screen

### ISSUE THREAD

**Issue by vishnu9865** [priyankarpal/ProjectsHut#1040]
### What happened?

Sampe URL: `https://projectshut.vercel.app/projects/[username]`
 - The Left panel containing profile picture, Social Media Links and username have non responsive layouts on mobile view

### Add screenshots

Non-Mobile View
![image](https://github.com/priyankarpal/ProjectsHut/assets/91585213/a0b633b6-737b-421a-a364-ea54244c9d1a)
Mobile View
![image](https://github.com/priyankarpal/ProjectsHut/assets/91585213/5334e200-a881-4192-bb9a-9b3d1a27d448)
![image](https://github.com/priyankarpal/ProjectsHut/assets/91585213/5d97b99f-b564-4d2b-bddb-4d4a87312eda)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @vishnu9865 thanks for raising the issue. we already assigned someone & he also created a PR https://github.com/priyankarpal/ProjectsHut/pull/1003

so I'm closing this issue
