### ISSUE TITLE
Feat: Adding a preloader to the website

### ISSUE THREAD

**Issue by Akanksha-202** [priyankarpal/ProjectsHut#1041]
### What feature?

Adding a creative preloader will enhance the beauty of the website.

### Add screenshots

https://www.davidhu.io/react-spinners/storybook/iframe.html?id=climbingboxloader--main&viewMode=story
Preview of what I want to add, and will make adjustments to it according to the theme of the website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @Akanksha-202 we already have a loading screen & removed it. also, we will add framer motion animation & skeleton effects later https://github.com/priyankarpal/ProjectsHut/issues/907
