### ISSUE TITLE
[Gssoc23]: hover effect on the scroll to top button

### ISSUE THREAD

**Issue by aditya-stoic-sharma** [priyankarpal/ProjectsHut#1044]
### What feature?

 hover effect on the scroll to top button

### Add screenshots

![project hub original](https://github.com/priyankarpal/ProjectsHut/assets/109134266/f2ed5a8b-9ab4-4340-aa0e-f7a58212d2a3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
is it really helpful?

**Comment by priyankarpal** [comment]
> yeah it will make user experience better

assigned to you.

also, make sure to add our theme color(purple)
