### ISSUE TITLE
Data: project addition by SJ-Kumar

### ISSUE THREAD

**Issue by SJ-Kumar** [priyankarpal/ProjectsHut#1046]
### Add a new project to the list

The project is focused on promoting and supporting the cinema industry. It aims to create a platform that engages cinema lovers and encourages them to contribute to the well-being of those involved in the film-making process. The webpage showcases information about the project and provides a donation form for users to contribute.

Tech Stack:

HTML: The project uses HTML as the markup language for structuring the webpage.
CSS: CSS stylesheets are employed to define the visual appearance and layout of the webpage. Bootstrap framework is utilized for responsive design.
JavaScript: The project utilizes JavaScript for dynamic functionality, such as implementing the navigation menu and integrating the payment form.
Razorpay: The payment form is powered by Razorpay, a popular online payment gateway.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
