### ISSUE TITLE
Feat: Add Filter Button

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#1047]
### What feature?

Add a filter button that will have both search by project name and search by tech stack, as we see in zomato or any other popular sites.

### Add screenshots

Currently is in this format:

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/30a0b5c8-0ddf-4381-86e6-badb83536e7b)

Somewhat this:

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/f23fca5c-8e12-4b94-899b-e294076f949a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you @suzy-g38

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
