### ISSUE TITLE
Docs: Getting started Section

### ISSUE THREAD

**Issue by TRIPLE-ADE** [priyankarpal/ProjectsHut#1049]
### what's wrong in the documentation?

a. Prerequisites:  The prerequisites that users need to have before they can get started with the project. This may include software dependencies, programming languages, libraries, or any other requirements.

b. Commands to run:  The specific commands that users need to run to set up the project, or perform other necessary tasks.

c. Expected behavior: Description of what users should expect to see or achieve when they successfully run the commands and set up the project.

### Add screenshots

![readme](https://github.com/priyankarpal/ProjectsHut/assets/99979436/326002a2-bb04-43eb-821f-01cf44d910b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @TRIPLE-ADE we already have contributing guide we don't need local setup details in README.md. we need to add the Prerequisites section.

what do you think?

**Comment by TRIPLE-ADE** [comment]
Okay would push that today
