### ISSUE TITLE
Footer is not well designed

### ISSUE THREAD

**Issue by ansh-star** [priyankarpal/ProjectsHut#1050]
### What feature?

The text in the footer is not well aligned.It is not looking good. I want to add another font style and wish to make it more attractive and descent

### Add screenshots

![Screenshot (48)](https://github.com/priyankarpal/ProjectsHut/assets/96314656/9e7e5111-0295-4fd1-a86e-96a06cc79cd1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently we are using inter font by default & we don't want to change the font

**Comment by AbhiramJogimahanthi** [comment]
I want to work on this issue
