### ISSUE TITLE
Feat: Clear filters button

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#1053]
### What feature?

We can provide a button to clear all the applied filters

### Add screenshots

No screenshots

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @kailashchoudhary11 we will add a new filter button soon & will add the clear button there.
also, assigned someone https://github.com/priyankarpal/ProjectsHut/issues/1047
