### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by kalashvasaniya** [priyankarpal/ProjectsHut#1056]
### What feature?

navbar text not changing in dark mode!

### Add screenshots

<img width="1440" alt="Screenshot 2023-06-01 at 10 23 08 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/88212870/503bbefe-aabd-49e5-947b-cc6e412ab950">
<img width="1440" alt="Screenshot 2023-06-01 at 10 23 10 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/88212870/c9b86e82-5d90-4701-9295-f5fa3417ebf1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
also, try to add a valid issue title it helps is to quickly undestand your issue

**Comment by kalashvasaniya** [comment]
> also, try to add a valid issue title it helps is to quickly undestand your issue

this navbar issue happen when you are using dark mode!

**Comment by priyankarpal** [comment]
> > also, try to add a valid issue title it helps is to quickly undestand your issue
> 
> this navbar issue happen when you are using dark mode!

I'm also, using dark mode

**Comment by kalashvasaniya** [comment]
> > > also, try to add a valid issue title it helps is to quickly undestand your issue
> > 
> > 
> > this navbar issue happen when you are using dark mode!
> 
> I'm also, using dark mode

I guess this only in MacOS

**Comment by priyankarpal** [comment]
> > > > also, try to add a valid issue title it helps is to quickly undestand your issue
> > > 
> > > 
> > > this navbar issue happen when you are using dark mode!
> > 
> > 
> > I'm also, using dark mode
> 
> I guess this only in MacOS

but how to solve only for macOS?

**Comment by kalashvasaniya** [comment]
> > > > > also, try to add a valid issue title it helps is to quickly undestand your issue
> > > > 
> > > > 
> > > > this navbar issue happen when you are using dark mode!
> > > 
> > > 
> > > I'm also, using dark mode
> > 
> > 
> > I guess this only in MacOS
> 
> but how to solve only for macOS?

Yaa that i have to figure out!!

**Comment by priyankarpal** [comment]
> > > > > > also, try to add a valid issue title it helps is to quickly undestand your issue
> > > > > 
> > > > > 
> > > > > this navbar issue happen when you are using dark mode!
> > > > 
> > > > 
> > > > I'm also, using dark mode
> > > 
> > > 
> > > I guess this only in MacOS
> > 
> > 
> > but how to solve only for macOS?
> 
> Yaa that i have to figure out!!

ok ok assigned to you
