### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by chanleeip** [priyankarpal/ProjectsHut#1057]
### What happened?

When changing dark to light theme or vice versa. Some elements are not visibile in light theme.

https://github.com/priyankarpal/ProjectsHut/assets/116068253/a01ce841-f6d8-4805-a3b2-eaa6651ab595

I'm in GSSOC'23

### Add screenshots

when clicking on light theme some elements are hidden

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @chanleeip could you check once again?

https://github.com/priyankarpal/ProjectsHut/assets/88102392/ae47304d-71b5-454d-8f0d-cd555863e37a

I'm not getting any error.
