### ISSUE TITLE
Bug: Footer's appearance when changed from dark mode to light mode. 

### ISSUE THREAD

**Issue by AbhiramJogimahanthi** [priyankarpal/ProjectsHut#1059]
### What happened?

- In dark mode, we can distinguish the footer but on the other hand we cannot distinguish the footer in the light mode.
- The footer design is not at all good and I would like to change the design.

### Add screenshots

![Screenshot 2023-06-01 110906](https://github.com/priyankarpal/ProjectsHut/assets/98203694/9a6b2f36-8e44-4fb3-8166-06da64f7618e)
![Screenshot 2023-06-01 110848](https://github.com/priyankarpal/ProjectsHut/assets/98203694/1e7d8bf3-cc18-4bc1-a862-a2d08cd1ae6e)

### What browsers are you seeing the problem on?

Chrome, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it got fixed previously 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/cee2a3cb-9146-48ba-b599-d34ebde0deb2
