### ISSUE TITLE
Data: project addition by Abhinav kumar

### ISSUE THREAD

**Issue by Abhinavcode13** [priyankarpal/ProjectsHut#1061]
### Add a new project to the list

Game-Of-Thrones-Personality-Matcher ⚔️

This is a project based on data science and machine learning which used TSNE algorithm and the main aim of this project is to match the personality of the game of thrones characters and this app is hosted on streamlit framework in pycharm IDE

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
you can add multiple projects in a single PR

**Comment by Abhinavcode13** [comment]
Fine @priyankarpal

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
