### ISSUE TITLE
Data: project addition by Jyoti Rani

### ISSUE THREAD

**Issue by Jranii** [priyankarpal/ProjectsHut#1063]
### Add a new project to the list

Hello Sir/Ma'am,
I'm in GSSOC'23 and want to contribute to this particular repository by adding one project to it. 
Kindly consider it.
Regards,
Jyoti Rani

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by Jranii** [comment]
Thank you 😊
