### ISSUE TITLE
Bug: TypeError: Cannot read properties of null (reading 'filter')

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1066]
### What happened?

when we share the user profile page link it's not working showing a `type error`

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/88102392/7ad6e427-09df-4cfd-88e0-fedd899fa018

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/c380d595-65f6-4d0f-b1f4-34f79cee3709)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by HarshPanchal26** [comment]
Can you assign it to me ?

**Comment by suzy-g38** [comment]
> Can you assign it to me ?

Can I work with you?

**Comment by priyankarpal** [comment]
> > Can you assign it to me ?
> 
> Can I work with you?

yeah sure we need work together

**Comment by priyankarpal** [comment]
> Hello, I am interested in making a contribution towards addressing this issue. The error seems to be originating from the code snippet below, found in ProjectList.jsx at line 12-13:
> 
> ```js
> const data = useLocation();
> const filter = data.state.filter;
> ```
> 
> It appears that the filter state is being passed through the URL and the error occurs while reading its property. To resolve this issue, I recommend utilizing the `FilterContext`. I have previously worked on implementing the `FilterContext` feature, which should streamline my efforts in addressing this matter.
> 
> # Resolved video:
>  ProjectHub-error-fix.mp4

hey I have already assigned

**Comment by Rohan3011** [comment]
Certainly, please feel free to let me know if you require any assistance. Given that this is a high-priority task, I thought I could offer my help.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
