### ISSUE TITLE
Feat: Designing and Adding a footer section with Figma and React [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [priyankarpal/ProjectsHut#1068]
### What feature?

The website's homepage has no footer section where links to "terms and conditions" , "privacy" , "license","trandemark" can be added. I can design a footer for the website.

### Add screenshots

A sample footer design in Figma:
![sample footer design](https://github.com/priyankarpal/ProjectsHut/assets/116020663/f20caf50-ea99-469d-93c6-4aa89ed5fead)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @1Shubham7 we already have a footer section where we added Licences link also, it's an open-source project also, I think we don't need to add trademarks, privacy policy

**Comment by 1Shubham7** [comment]
I thought a well defined footer with links (not necessarily trademarks) would enhance the look of the website. But as you wish, dp you want me to close the issue?
