### ISSUE TITLE
Docs: Fix Text in README

### ISSUE THREAD

**Issue by Sriparno08** [priyankarpal/ProjectsHut#1069]
### what's wrong in the documentation?

I have noticed typos in README.

In the below sentence, 'the' and the extra space before '?' need to be removed.

In total, the sentence needs to be:

> Wanna see our contributors? (then click on below dropdown)

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89148144/47703d3e-03ee-469a-99f7-25fe609bb022)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
