### ISSUE TITLE
Feat: add Backend

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1070]
### What feature?

we need to add a backend. 
we will store data 
github auth
API
like dislike button
we will create separate issues for backend

etc

### Add screenshots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by suzy-g38** [comment]
I would like to work on this issue

**Comment by Sahilll15** [comment]
I to want to work on this for gssoc23
