### ISSUE TITLE
Bug: Project page giving 404 error on small screens

### ISSUE THREAD

**Issue by ujjawaltyagii** [priyankarpal/ProjectsHut#1074]
### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/115401171/e0e13449-15ec-447e-afda-cee590ce4ae9

### What browsers are you seeing the problem on?

Chrome, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, we need to change the url path. 

assigned to you
