### ISSUE TITLE
Bug: Site is taking a lot of time to load because of high-res images

### ISSUE THREAD

**Issue by Swpn0neel** [priyankarpal/ProjectsHut#1075]
### What happened?

Site is taking a lot of time to load because of high-res unoptimized images, which can be improved by lossless downscaling.

### Add screenshots

High-res images are also causing over-pixelation on smaller devices too resulting in non anti-aliased shimmering.
![image](https://github.com/priyankarpal/ProjectsHut/assets/121167506/3976868c-ac88-4821-8484-cb3888974569)
![image](https://github.com/priyankarpal/ProjectsHut/assets/121167506/fff710ce-6875-4b76-8f47-08c3e2bd3ac2)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we need to fix.

assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
