### ISSUE TITLE
Bug: Back to projects button resets the selected filters

### ISSUE THREAD

**Issue by Rohan3011** [priyankarpal/ProjectsHut#1076]
### What happened?

The `Back to [selected filters] projects` button on the project details page is not working.

I'm a GSSOC'23 contributor and I'd like to work on this issue. 

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/76813454/be549e74-a8b5-4092-bda8-083c0f0f99b7

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
