### ISSUE TITLE
Data: project addition by jyoti pandey

### ISSUE THREAD

**Issue by pjyoti121** [priyankarpal/ProjectsHut#1079]
### Add a new project to the list

I want to add a new project 
it is a food ordering website which shows options which are healthy to our food.
This site does not contain any junk food only suggest healthy option this way it is unique from other food ordering website 

please assign me this
I will follow the code of codunct 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by pjyoti121** [comment]
i am working in it.
fixing some issues occured in my project within 2-3 days i will submit it

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
