### ISSUE TITLE
Data: project addition by harshal2002

### ISSUE THREAD

**Issue by harshal2002** [priyankarpal/ProjectsHut#1082]
### Add a new project to the list

Hello Priyankar,
I want to add my static Netflix Clone project
Technologies used: HTML, CSS
Repository Link: https://github.com/harshal2002/NetflixClone

This is a beginner-level yet effective project where I cloned the frontend part of Netflix website using Html and CSS. ProjectsHut is a great open-source initiative so please let me add my project to ProjectsHut's list of projects. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
