### ISSUE TITLE
Bug: Clicking on the Logo Redirects to Footer Instead of Homepage

### ISSUE THREAD

**Issue by Saurav-Pant** [priyankarpal/ProjectsHut#1084]
### What happened?

When navigating through the website's documentation section and then scrolling down to the footer, clicking on the logo redirects the user to the homepage as intended. However, instead of displaying the top of the homepage, the footer is shown. This behavior is causing confusion and inconvenience to users. The issue needs to be resolved to ensure a seamless and consistent user experience.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/103263909/85cf3940-ac93-42ed-bd6a-33f7571c4ea3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

**Comment by priyankarpal** [comment]
thank you for creating this issue. we will add soon.

**Comment by priyankarpal** [comment]
also, if you want to fix this issue you can.

## How to solve this issue?
- go to `src/pages/HomePage.jsx` 
- add the code top the line 

https://github.com/priyankarpal/ProjectsHut/blob/5f18ea828f85e4fcff134eff8fad5517522de6eb/src/pages/HomePage.jsx#L11

### Sample code 
  ```
  window.scrollTo(0, 0);
  ```

**Comment by Saurav-Pant** [comment]
assign it to me, I will do it.

**Comment by priyankarpal** [comment]
> assign it to me, I will do it.

assigned to you
