### ISSUE TITLE
Feat: Refactor the filter projects logic

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#1093]
### What feature?

We can remove the use of useState hook for filtering the projects and can do it by just using the useSearchParams hook.

### Add screenshots

No screenshots

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, we are adding a new filter option so ig we don't need to refactor right now.

**Comment by kailashchoudhary11** [comment]
> hey, we are adding a new filter option so ig we don't need to refactor right now.

okayy
