### ISSUE TITLE
Data: project addition by coderhersh

### ISSUE THREAD

**Issue by coderhersh** [priyankarpal/ProjectsHut#1099]
### Add a new project to the list

Hi, there.

I want to add a project called pinax. It is a landing page made in angular and tailwind css.

Kindly, include it under GSSOC 23.

https://github.com/priyankarpal/ProjectsHut/assets/56130865/ef36df7f-1ffc-4db0-94f3-6cf7505f5c7c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
