### ISSUE TITLE
Docs: Add Badges to ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [priyankarpal/ProjectsHut#1100]
### what's wrong in the documentation?

 - I would like to add Badges to ReadMe.md file to provide more information at a glance about the repo and at the same time improve the look of ReadMe.md
 - I would like to work on this issue under GSSoC'23. Could this be assigned to me?

### Add screenshots

 - After making changes ReadMe.md would look like this 
<img width="625" alt="badges" src="https://github.com/priyankarpal/ProjectsHut/assets/112561024/ff9206da-e0f5-4e22-a6d3-2b602ffeb8af">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @VSatwika previously we had a few badges & we removed them because of overwhelming. ig currently we don't need badges right now. if we need we will add

Thank you for understanding
