### ISSUE TITLE
Bug: the hero images are not positioned in the center on mobile screens 

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#1113]
### What happened?

The hero images are not positioned in the center on mobile screens 

### Add screenshots

![Screenshot (100)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/67878c69-02bf-4df1-98c8-ffc536705228)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1032
