### ISSUE TITLE
[Feat]: featured projects slider section

### ISSUE THREAD

**Issue by itsmohit097** [priyankarpal/ProjectsHut#1114]
### What feature?

I'm a GSSOC'23 contributor and have an idea of adding a featured projects section before the footer section on the home page . I created a design you can see it here (https://www.canva.com/design/DAFk85l5j0c/UPE6SJ1WHrPuZIWRrJsBTA/edit?utm_content=DAFk85l5j0c&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
Please assign this issue to me.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/125040386/e4f1aa89-063e-4314-a58e-176a6080b24d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, we don't want to add the feature right now.

It is best practice to mention that you have taken the idea from the previous issue.https://github.com/priyankarpal/ProjectsHut/issues/443 (you just edited the image)
