### ISSUE TITLE
Feat: Use GitHub API to get accurate Data.

### ISSUE THREAD

**Issue by murtazajoo** [priyankarpal/ProjectsHut#1119]
### I think we should automate some things, actually most of the things like,

- User data should be on the profile page meaning including bio, but the user does not need to add the bio, we will get it from GitHub using GitHub API.

-  Same goes for the repos he adds, he only needs to add the correct repo name and then we will fetch the rest of the details.

- We can get the languages used to build that repo.

- We can also fetch user's social media account, eliminating the need of user adding their account manually

### The below are the responses from the API.

delete issue :( number, I forgot to add the title
#1118 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/80580f2e-f3b3-444d-8ab3-ee1aecddef24)
![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/cb4cf5f2-d4f6-4309-8672-8d7906cb0b0e)
![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/2fd138b8-a798-447f-894d-3b5571e13d14)
![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/a568e3ae-0e24-4c49-a166-d390730847b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yes. someone is working on this same feature(redesigning the profile page)
