### ISSUE TITLE
Bug: Search bar is not working properly

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#1121]
### What happened?

Here if you search with t, all the options related to t will be shown, and in this project as far as my knowledge toaster UI and the themes both start with t should come, but only toaster UI is coming.

If you search with the then thea theme should come but completely a different project is coming.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/4d894bce-a7bc-4a17-8013-b87592b6d195)

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/61421505-8d48-4c59-9fff-14859b0c97a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to show all projects regarding to a letter(if available)

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
