### ISSUE TITLE
Feat: migrate to NextJs & Typescript

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1122]
### What feature?

- we need to migrate projectshut to NextsJs & Typescript
- refactor code
- remove unneeded components etc

### Add screenshots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by suzy-g38** [comment]
I would like to work on this.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
