### ISSUE TITLE
modifications in the contributing.md file to enhance my Contributions

### ISSUE THREAD

**Issue by Man07har** [priyankarpal/ProjectsHut#1123]
### what's wrong in the documentation?

Read contributing.md file and adding my descriptions into the projects.json file so that I can contribute further into the other issues

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89695803/fde72981-72b0-4beb-a994-a19b69211910)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you elaborate this?

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
