### ISSUE TITLE
Feat: Workflow to remove PRs without linked issues

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1126]
### What feature?

- I will write the workflow to automatically close pull requests (PRs) that do not have any linked issues in a repository.
- It will add a comment on the PR explaining why it was closed and providing instructions to add the required issue information.
- If no linked issue is found, it updates the state of the PR to `closed` using the GitHub API.
- The workflow will utilize the `secrets.GITHUB_TOKEN` secret.
- I am using `async/await` so it will run in this JavaScript repository.

> It should be a documentation update, but the problem field was mandatory. Therefore, I am submitting the issue using this issue form.

### Add screenshots

> This should not be a mandatory field, as this isn't useful in every scenario.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @Anmol-Baranwal we can ask for the issue number from the users ig most of the users add their issue numbers. also, we have another workflow that will close PRs after a certain time if the user not giving any updates. but we can add a github action that will check the issue number if not then the github bot will add a comment(no close)

**Comment by Anmol-Baranwal** [comment]
I am busy with semester exams, so it might be too late to complete the issue. I will make a PR on 16th June.

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. we would like to kindly inform you that we will be closing this issue. 


Thank you for your understanding.

**Comment by Anmol-Baranwal** [comment]
Yep, thanks for closing this. 

I am contributing to another project, so I didn't really researched this properly. Hope you understand
