### ISSUE TITLE
Data: project addition by Swetha Paleti

### ISSUE THREAD

**Issue by swethapaleti** [priyankarpal/ProjectsHut#1129]
### Add a new project to the list

I would like to add my project jobs search portal, which is live at https://swethajobby.ccbp.tech/ 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swethapaleti** [comment]
I just made a pull request . can some one please review it. Thanks

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
