### ISSUE TITLE
BUG: scroll-bar style not apply to all browsers

### ISSUE THREAD

**Issue by ydv-ankit** [priyankarpal/ProjectsHut#113]
**Describe the bug**
scroll-bar not working in all browser windows

**To Reproduce**
yarn run dev

**Expected behavior**
a white scroll-bar should be there

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux Mint 21.1
- Browser - chrome, brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by priyankarpal** [comment]
could you add screenshots?

**Comment by ydv-ankit** [comment]
![Screenshot from 2023-03-25 12-58-13](https://user-images.githubusercontent.com/85311495/227703627-cc7421f6-f5bf-4435-ae5a-50543f5b93f5.png)

**Comment by ydv-ankit** [comment]
i can corret this issue

**Comment by priyankarpal** [comment]
> i can corret this issue

OK do it.

**Comment by priyankarpal** [comment]
PR merged. Thanks for your contribution ❤️ 🎉
