### ISSUE TITLE
Bug: Fix multiple errors

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#1131]
### What happened?

There are multiple errors in the page:

1. On clicking on the profile page left section the copy profile modal is showing.
2. Add a cursor pointer on the share button
3.  show random projects in the project section.on

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/ab1d8639-1592-4041-919c-cee5f1d2963c)

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/09712e4e-d6ea-4d32-86c8-d3600664c0d5)

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/a06c719e-156f-4bce-acba-0f261a57fb24)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
