### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by murtazajoo** [priyankarpal/ProjectsHut#1134]
### What happened?

In the Profile page, when clicking on the user card anywhere the modal of share you profile open, which is supposed to only open when a user clicks on the share icon .

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/e796dea3-9013-4a79-ba98-e949a6de07a1)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate issue https://github.com/priyankarpal/ProjectsHut/issues/1131
