### ISSUE TITLE
Bug: Filter is not working as Supposed

### ISSUE THREAD

**Issue by murtazajoo** [priyankarpal/ProjectsHut#1135]
### What happened?

When I select two filter it means the project should contain both, languages not only one

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98375522/4c1bd442-21eb-4932-9145-9970764d9b75)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @murtazajoo please check we already fixed the bug
