### ISSUE TITLE
Bug: Unoptimized User Card a user profile page. 

### ISSUE THREAD

**Issue by Sanchitbajaj02** [priyankarpal/ProjectsHut#1136]
### What happened?

Hey, After checking the responsiveness of the user profile page, I found out that the left side card which shows user info is not aligned for some screens. There is also uneven padding, making the card look bad.

> **Note** I am a GSSOC'23 contributor and love to fix this issue😊.

### Sample screenshots for uneven gaps
![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/3e7088cf-7a7b-4daf-a0e7-d68dc738013a)

![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/35b29ee0-e55b-4f31-866e-f8a784868224)

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you @Sanchitbajaj02

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
