### ISSUE TITLE
Feat: Add Live Project Link along with GitHub Repository Link

### ISSUE THREAD

**Issue by pankajktech** [priyankarpal/ProjectsHut#1137]
### What feature?

So, The Feature is we will add Live Project Link also so that user can directly see how the project Looks Like.

### Add screenshots

![Screenshot from 2023-06-08 12-07-23](https://github.com/priyankarpal/ProjectsHut/assets/89023470/2bc4726a-a622-41bd-8d06-58ab8665d5ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are changing our UI soon & some projects don't have any live links so I think currently don't needed.
