### ISSUE TITLE
Feat: adding "go to up" on hover on the scroll up button.

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [priyankarpal/ProjectsHut#1139]
### What feature?

On hover on the scroll up button of the website I want to add "scroll up" message. please assign this to me so that I can work on this issue under gssoc'23

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/118244809/ac7fc3ff-8654-440b-90bf-af3d45926693)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it's unnecessary
