### ISSUE TITLE
Feat:Adding a chat bot 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [priyankarpal/ProjectsHut#1140]
### What feature?

Adding a side by chat bot to help people which FAQs.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98320971/611f75c3-4f85-4f3d-b7f4-3dfc4248b2bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have docs & thinking of changing our project's UI so ig it's not needed right now.
