### ISSUE TITLE
Data: project addition by shagunZ

### ISSUE THREAD

**Issue by shagunZ** [priyankarpal/ProjectsHut#1141]
### Add a new project to the list

Built using React, this app provides a user-friendly interface and real-time score updates and displays the winner when the score limit is reached.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
