### ISSUE TITLE
Data: project addition by Jigar

### ISSUE THREAD

**Issue by Jiggy9** [priyankarpal/ProjectsHut#1144]
### Add a new project to the list

I would like to add flutter voice assistance application which is multiplatform and can help in assist by answering in text to voice or through creating image if asked of image.

<img width="206" alt="github" src="https://github.com/priyankarpal/ProjectsHut/assets/112299754/8582a5cd-f10e-4866-aa33-c72e5e2d1cce">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
