### ISSUE TITLE
Data: project addition by prachisingh1008

### ISSUE THREAD

**Issue by prachisingh1008** [priyankarpal/ProjectsHut#1151]
### Add a new project to the list

THIS WEBSITE IS A ONESTOP DESTINATION FOR LATEST TRENDS

![Screenshot (231)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/db380441-4134-4fc8-9854-dfb8872dedfa)
![Screenshot (232)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/03e30d90-a441-4b82-b5a5-b2f38069d580)
![Screenshot (233)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/0414e97c-8c51-4a7b-aa71-2a4e1f8c5050)
![Screenshot (234)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/2c045bf9-82f7-443e-b706-d7c20f0adeca)
![Screenshot (235)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/faecdead-808b-46bc-81fc-1e03934ca446)
![Screenshot (236)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/5a963e85-e827-4ffe-827e-4c68963d2c2e)
![Screenshot (237)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/34fbe252-6bd4-4304-bd0d-b9a818b7e0cf)
![Screenshot (238)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/57c9a0b4-53b9-4a38-a3be-266f39385221)
![Screenshot (239)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/19b787bd-c4dc-41c1-a410-92d86ce0be39)
![Screenshot (240)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/3b5d1332-e024-4250-9d9a-2b22ae43fc28)
![Screenshot (241)](https://github.com/priyankarpal/ProjectsHut/assets/89354933/0981bc96-4c01-434a-8b5b-533206ef8f65)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by prachisingh1008** [comment]
Thankyou for assigning me
