### ISSUE TITLE
Data: project addition by HartzFrequency [GSSoC 23'] [Python & GUI]

### ISSUE THREAD

**Issue by HartzFrequency** [priyankarpal/ProjectsHut#1155]
## About The Project (UTTS)
The Unified Travelling and Transport System is a project aimed at developing a unified platform for all transportation-related activities. It is designed to provide a seamless experience for users, whether they are commuting locally or traveling long distances. The platform provides features such as route planning, real-time tracking, fare estimation, and payment options for different modes of transport.

## Features Of UTTS
The Unified Travelling and Transport System provides the following features:

- Route planning: Users can plan their travel routes by selecting their starting and destination points.
- Real-time tracking: Users can track their current location and the location of their ride in real-time.
- Fare estimation: Users can get an estimate of the fare for their ride before booking it.
- Payment options: Users can pay for their rides using various payment options, including credit/debit cards and mobile wallets.
- Multi-modal transport: The platform supports different modes of transport, including buses, trains, taxis, and private cars.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
