### ISSUE TITLE
Data: project addition by HartzFrequency [GSSoC 23'][CPP & File Handling]

### ISSUE THREAD

**Issue by HartzFrequency** [priyankarpal/ProjectsHut#1156]
## Movie Rental and Buying System
This project is a movie rental and buying system implemented in Cpp. The system allows users to browse catalog of movies, rent and buy movies, manage their rentals and purchases, and store user data using file handling. The program also includes sign-up and sign-in features and is implemented using Object-Oriented Programming (OOP) methodology.

## Features
Some of the key features of the system include:

1. Browse movies by genre, release date, and popularity.
2. Rent movies for a specified period of time.
3. Buy movies for unlimited access.
4. Manage rentals and purchases through a user dashboard.
5. Sign-up and sign-in features for user authentication.
6. Data persistence using file handling.
7. Genre access according to your age

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @HartzFrequency you don't need to create multiple issues at a time. You can add multiple projects in a single issue.

**Comment by HartzFrequency** [comment]
Sorry I didn't knew about that
