### ISSUE TITLE
Data: project addition by HartzFrequency[GSSoC 23'][Discord API & Python]

### ISSUE THREAD

**Issue by HartzFrequency** [priyankarpal/ProjectsHut#1157]
## Wave
I want to add my Discord bot which is made using Python to resolve the problem which is an external software requirement for recording voice chats of DIscord channels
this discord bot will  allow you to record the conversations and can give provide you the recording 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @HartzFrequency you don't need to create multiple issues at a time. You can add multiple projects in a single issue.
