### ISSUE TITLE
Defining the boundary of the divs in the projects section in dark mode

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1159]
### What feature?

The divs in the projects section in the dark mode look mixed as there borders are not clearly visible and not properly separated.
They are looking a bit sticked to each other which gives the page a congested look.

### Add screenshots

![2023-06-10 (3)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/e9d3e232-e90d-49cc-98fd-1f2cb8e36292)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, we are changing the UI designs so I think we don't need to change right now.
