### ISSUE TITLE
Feat: Improve the share button on profile page 

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#1160]
### What feature?

We can provide a list of various social medias to share the link of profile page along with the copy link option.

### Add screenshots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I believe users can share the link to the various platforms.
