### ISSUE TITLE
Redesigning the navbar section

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1161]
### What feature?

Adding shadow effects and aligning the buttons properly.

### Add screenshots

![2023-06-10 (4)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/112a6796-1337-4062-b8d4-ad6d21043aea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, @Illaf which buttons?

**Comment by Illaf** [comment]
@priyankarpal the home, projects,docs, github and darkmode button at the top. I want to place them properly in  a navbar

**Comment by priyankarpal** [comment]
> @priyankarpal the home, projects, docs, github and dark mode buttons at the top. I want to place them properly in a navbar

ig all are in a good position & if we change UI it wouldn't look good.

**Comment by Shahil093** [comment]
can I redesign the navbar section?

**Comment by priyankarpal** [comment]
> can I redesign the navbar section?

currently we don't need
