### ISSUE TITLE
Data: project addition by coderhersh

### ISSUE THREAD

**Issue by coderhersh** [priyankarpal/ProjectsHut#1169]
### Add a new project to the list

I want to add a weather app in this repository which I made in React JS.

Kindly, assign this issue to me  under GSSOC'23.

https://github.com/priyankarpal/ProjectsHut/assets/56130865/ba744a46-e907-42f7-9270-5b65ca0ded5a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
