### ISSUE TITLE
Feat: Copy feature to Docs 

### ISSUE THREAD

**Issue by vaibhav-xt** [priyankarpal/ProjectsHut#1171]
### What feature?

We can add a feature of copying code to every code snippet on the docs page. 

### Add screenshots

![Screenshot (44)](https://github.com/priyankarpal/ProjectsHut/assets/90946899/f4e24cf5-42b4-42d9-a3ed-a05d7ee44a5e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, we need to add a copy button.

assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
