### ISSUE TITLE
Feat: Their should be a feature of total repository view and contributor 

### ISSUE THREAD

**Issue by omk-coder** [priyankarpal/ProjectsHut#1174]
### What feature?

This feature can help the contributor to know how many forks this repository have and also lt us know that how many contributor does this repository have.. 
I have added an screenshot for more clearlity..

### Add screenshots

<img width="515" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/93393539/3a85d41f-5a9c-4cc1-be69-17ad5e691396">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's unnecessary
