### ISSUE TITLE
Feat: About Section of the website

### ISSUE THREAD

**Issue by Rohit-osc** [priyankarpal/ProjectsHut#1175]
### What feature?

I want to add a about section in the website.

### Add screenshots

![Screenshot (64)](https://github.com/priyankarpal/ProjectsHut/assets/130088934/8091bda2-de40-4fb9-a7e9-a49d429d3264)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we had lengthy text & we removed also, added good descriptions about the projects to the readme so I think we don't need it.

we are thinking to change the UI design if we need then we will create an issue.
