### ISSUE TITLE
Data: project addition by siddarthdayala

### ISSUE THREAD

**Issue by siddarthdayala** [priyankarpal/ProjectsHut#1181]
### Add a new project to the list

I want to add my encryption/decryption website named Encipher | Decipher developed using Html, Css and Javascript.
You can find the Github repo link of this project here - https://github.com/siddarthdayala/Encipher-Decipher
Here is the hosted link - https://siddarthdayala.github.io/Encipher-Decipher/

- Encipher | Decipher is a simple encryption/decryption website 
- It allows users to encrypt and decrypt messages using three different ciphers namely, RailFence, Caesar and Vernam
- This website is highly responsive to the varying screens

Please feel free to explore the source code and more details in the Github repository..

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
