### ISSUE TITLE
Data: project addition by  sumitkr2000 

### ISSUE THREAD

**Issue by sumitkr2000** [priyankarpal/ProjectsHut#1185]
### Add a new project to the list

Hey @priyankarpal I want to add neuralmind to your repo. Please assign me this issue. Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
