### ISSUE TITLE
Suggestion: Fix GitHub link button at the bottom

### ISSUE THREAD

**Issue by rupali-codes** [priyankarpal/ProjectsHut#120]
Hey, I just noticed that button for Project card is not aligned well, it would be better if we can fix/align the button at bottom of the card either the card have a long or short description

### Screenshot
![image](https://user-images.githubusercontent.com/78981177/228238325-421de725-2a45-4fd4-acbf-c9330b62cf8c.png)

**Comment by priyankarpal** [comment]
> Hey, I just noticed that button for Project card is not aligned well, it would be better if we can fix/align the button at bottom of the card either the card have a long or short description
> 
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/78981177/228238325-421de725-2a45-4fd4-acbf-c9330b62cf8c.png)

Yes. would you like to work on it?

**Comment by rupali-codes** [comment]
Yeah sure, but i might take some time

**Comment by priyankarpal** [comment]
> Yeah sure, but i might take some time

ok, not a problem take your time.
