### ISSUE TITLE
[Feature]:  Add Like Button Using  Either Thumb OR Love Symbol put on Project Card UI

### ISSUE THREAD

**Issue by NarendraKoya999** [priyankarpal/ProjectsHut#1200]
### Issue Description:
- **Add Like Button Using Thumb  OR Love Symbol and Put on Particular Project Card UI (Sample Image Shown on Screenshot Section).**
- **Suppose, When Click on One Time on this Like Button and At A Time Digit Count Appears like 1 on Either Left Side OR Right Side of Like Button.**
- **Filled with this Like Button If Thumb Button used, this Symbol Filled With Blue. Otherwise Love Symbol is Used, this Symbol filled with Reddish Color Only this behaviors happens whenever Clicked on Like Symbol.**
- **And Again Click on this Like Symbol Immediately . Shown Empty Filled Symbol and Decreased Count By 1.**

### Screenshot of My Feature Request

<img width="895" alt="projectshut-1" src="https://github.com/priyankarpal/ProjectsHut/assets/84512164/b661c90a-27a9-43cf-bbde-c3c613ad3882">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
we will add after adding backend

**Comment by NarendraKoya999** [comment]
Thank You @priyankarpal
