### ISSUE TITLE
Data: Discrod Bot project addition by killerraj369

### ISSUE THREAD

**Issue by killerraj369** [priyankarpal/ProjectsHut#1201]
### Add a new project to the list

Hey Project Admin, 
I want to add my Discord Bot project to this repo. Kindly assign me this issue.

Description:- This is a  Discord Bot for Coders & Competitive Programmers. Now Contests and Hackathons related Information under your command. Executes Code in Discord Itself. Provides Jokes, News, Quotes and fun things. Supported - C, C++, Python, Java, JavaScript, Golang, C# etc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
