### ISSUE TITLE
Feat: add codeql workflow

### ISSUE THREAD

**Issue by harmeetsingh11** [priyankarpal/ProjectsHut#1206]
### What feature?

Your repository does not have workflow for code scanning. 

I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

### Add screenshots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
> > TBH I'm not familiar with CodeQL. Could you share resources & demo?
> 
> Yeah sure! Please checkout this [article](https://medium.com/mycostech/lets-analyze-your-code-repository-in-github-via-codeql-engine-dd196354f77e).

cool 
you can work on it.

**Comment by MisterMickey** [comment]
@harmeetsingh11 Can we connect? I want to know more about this CodeQL thing and how you incorporated CodeQL in this ProjectsHut repo.

**Comment by harmeetsingh11** [comment]
> @harmeetsingh11 Can we connect? I want to know more about this CodeQL thing and how you incorporated CodeQL in this ProjectsHut repo.

Yeah sure @MisterMickey. Checkout my github for social links. Please checkout this [article](https://medium.com/mycostech/lets-analyze-your-code-repository-in-github-via-codeql-engine-dd196354f77e).

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
