### ISSUE TITLE
Share on Linkedin

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#121]
There is option to share on twitter same we can create share on linkedin

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-03-29 02-12-25](https://user-images.githubusercontent.com/108119109/228362420-78613076-5c0a-425b-af41-ae0c63001f6d.png)

**Comment by priyankarpal** [comment]
> There is option to share on twitter same we can create share on linkedin

+1. Would you like to work on it?

**Comment by Bharadwajshivam28** [comment]
> > There is option to share on twitter same we can create share on linkedin
> 
> +1. Would you like to work on it? 

Yes

**Comment by priyankarpal** [comment]
Ok done. Work on it.

**Comment by Bharadwajshivam28** [comment]
> Ok done. Work on it. 

Ok thanks

**Comment by Bharadwajshivam28** [comment]
@priyankarpal  The code is not running buy npm start or npm run. I  have also installed by npm install but then also its not running

**Comment by priyankarpal** [comment]
> @priyankarpal  The code is not running buy npm start or npm run. I  have also installed by npm install but then also its not running

Use 
- yarn  
- yarn run dev

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by priyankarpal** [comment]
hi
@Bharadwajshivam28 also please check the discussion. [#125](https://github.com/priyankarpal/ProjectsHut/discussions/125)

**Comment by Deva-1903** [comment]
If you didn't get the desired output, Can I work on this issue @priyankarpal

**Comment by priyankarpal** [comment]
> If you didn't get the desired output, Can I work on this issue @priyankarpal

he is working on this issue.

**Comment by Bharadwajshivam28** [comment]
> hi
> @Bharadwajshivam28 also please check the discussion. [#125](https://github.com/priyankarpal/ProjectsHut/discussions/125)

Okay

**Comment by priyankarpal** [comment]
are you working on this issue?

**Comment by Deva-1903** [comment]
If not, I can, which is why I asked it before @priyankarpal

**Comment by Bharadwajshivam28** [comment]
> are you working on this issue?

Yes i am due to some personal issue I was not able to do..but I will do it fast

**Comment by priyankarpal** [comment]
> > are you working on this issue?
> 
> Yes i am due to some personal issue I was not able to do..but I will do it fast

ok take your time

**Comment by Bharadwajshivam28** [comment]
@priyankarpal can you share me some resource how to create a pre written linkedin post like you have made for twitter same for linkedin

**Comment by priyankarpal** [comment]
> @priyankarpal can you share me some resource how to create a pre written linkedin post like you have made for twitter same for LinkedIn

😢 chatGPT

**Comment by Bharadwajshivam28** [comment]
i did it but not find it valueable .. okay i will try once more

**Comment by priyankarpal** [comment]
ok, so I would say that stop this work here. We're working on another feature. We will remove share on twitter button also

**Comment by Bharadwajshivam28** [comment]
we can create a good responsive footer

**Comment by Bharadwajshivam28** [comment]
can i work on creating this??

**Comment by priyankarpal** [comment]
> can i work on creating this??

check the issue https://github.com/priyankarpal/ProjectsHut/issues/226

**Comment by Bharadwajshivam28** [comment]
okay
