### ISSUE TITLE
Feat:contact us & feedback form section

### ISSUE THREAD

**Issue by iamparas0** [priyankarpal/ProjectsHut#1214]
### What feature?

your site needs a contact us section and a feedback form , please assign me for this.

### Add screenshots

![Screenshot (50)](https://github.com/priyankarpal/ProjectsHut/assets/45733116/c689acf9-4712-4a6a-8783-125800a42873)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on a new UI design & if contact forms needed then we will add
