### ISSUE TITLE
Feat: Website does not have proper meta tags

### ISSUE THREAD

**Issue by Avinash905** [priyankarpal/ProjectsHut#1215]
### What feature?

**Issue:** The website does not have meta tags with descriptions.

**Impact:** This means that the website is not as visible in search results, and users are less likely to click on the website's links.

**Resolution:** The website should contain important meta tags. This will help the website rank higher in search results and attract more visitors.

### Add screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
