### ISSUE TITLE
Data: project addition by debsouryadatta

### ISSUE THREAD

**Issue by debsouryadatta** [priyankarpal/ProjectsHut#1224]
### Add a new project to the list

I want to add a video streaming webapp project which is made up of React + Tailwind CSS + Firebase.
Project name - souryax-streaming.

### Screenshot of the same:
![Screenshot (249)](https://github.com/priyankarpal/ProjectsHut/assets/91617309/d6601105-6523-4230-8ee8-af1bdec4a032)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
