### ISSUE TITLE
Data: project addition by Prashu-01

### ISSUE THREAD

**Issue by Prashu-01** [priyankarpal/ProjectsHut#1225]
### Add a new project to the list

I want to add a weather website. With clean and user friendly UI, the website shows real time weather conditions. Build using HTML, CSS and JavaScript.

![image](https://github.com/priyankarpal/ProjectsHut/assets/107640576/8a0ec763-b49d-48cc-a21f-cabc6b9aff3c)

 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
