### ISSUE TITLE
Bug: Undefined github issue

### ISSUE THREAD

**Issue by Sanchitbajaj02** [priyankarpal/ProjectsHut#1226]
### What happened?

While browsing through the project cards, when clicking on some profiles, it doesn't open the profile page but shows the error below mentioned in the screenshot.
Also, there is a bug that is showing all the social icons for a user, although he/she doesn't add any link to it(Refer to screenshot#2).

I am a GSSOC'23 contributor and would love to work on this.

### Add screenshots

Bug 01:
![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/5acb5831-2fc2-4e41-9a24-f7324b6b58da)

Bug 02:
![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/352a6f53-f609-4c3b-817e-6464457dae45)

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
