### ISSUE TITLE
Feat: Add hover effect on tech-stack buttons

### ISSUE THREAD

**Issue by MisterMickey** [priyankarpal/ProjectsHut#1228]
### What feature?

I want to add a beautiful hover effect over the tech-stack buttons in the projects section.

### Add screenshots

![Screenshot from 2023-06-16 16-27-59](https://github.com/priyankarpal/ProjectsHut/assets/93720428/95bfb6e9-b310-428b-860a-9f6b4ef32159)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
previously we had hover effects & we removed so we don't need right now.
