### ISSUE TITLE
Data: Login form project addition by MisterMickey

### ISSUE THREAD

**Issue by MisterMickey** [priyankarpal/ProjectsHut#1230]
### Add a new project to the list

This is a landing page login form made using HTML, CSS and BootStrap.

Kindly assign me this issue under gssoc23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @MisterMickey thanks for creating the issue we will add github auth after adding the backend
