### ISSUE TITLE
Pagination and Search Language Buttons' Hover Effect and Styling

### ISSUE THREAD

**Issue by manaver** [priyankarpal/ProjectsHut#1238]
I would like to request an enhancement for the pagination and search language buttons on the website. Currently, these buttons lack visual feedback when interacted with, and their styling could be improved to enhance the user experience. Below are the expected behaviors and desired changes:

### Current Behavior:
![image](https://github.com/priyankarpal/ProjectsHut/assets/78682260/386bedb2-34cb-4d3a-af72-6ad36d6959a0)

### Modified Behavior:
I suggest to implement pagination in the project section to make it more interactive for user to work.

### Current Behavior:  
[Screencast from 17-06-23 09:59:05 AM IST.webm](https://github.com/priyankarpal/ProjectsHut/assets/78682260/e40d3cd6-088c-42e5-9b77-324958adcc6b)

### Modified behavior:
When hovering over the pagination and search language buttons, I suggest implementing a subtle "pop-up" effect to provide visual feedback to the user.
The buttons should slightly elevate or increase in size when hovered, giving them a responsive and interactive feel.

### Current Behavior:
[Screencast from 17-06-23 09:59:05 AM IST.webm](https://github.com/priyankarpal/ProjectsHut/assets/78682260/d39c6ebe-7527-4fbc-b8d4-1ef9c9e65966)

### Modified Behavior:
Upon clicking on a button, I propose implementing a slight "pop-down" effect to indicate that the button has been selected or activated.
Currently, when a button is clicked, the background color changes, but the border is removed This inconsistency affects the visual appeal.
I suggest modifying the button styling so that when a button is clicked, not only the background color changes but also the border is there or adjusted accordingly for a cleaner appearance.

Overall, these enhancements will improve the interactivity and aesthetics of the pagination and search language buttons, creating a more user-friendly experience.

I am a GSSOC'23 contributor. Please assign this issue to me. I'd love to work on this issue. Thanks!

**Comment by priyankarpal** [comment]
hey @manaver thanks for raising the issue.

- previously we had pagination & we removed it also, now we don't want to add pagination 
- for the search bar button problem we are working on a filter feature where we will add a popup & change the button's UI.
- after adding the feature if you find any problems you can raise an issue.

**Comment by manaver** [comment]
> hey @manaver thanks for raising the issue.
> 
> * previously we had pagination & we removed it also, now we don't want to add pagination
> * for the search bar button problem we are working on a filter feature where we will add a popup & change the button's UI.
> * after adding the feature if you find any problems you can raise an issue.

ok! I'll check on another issues
