### ISSUE TITLE
Data: project addition Unit converter

### ISSUE THREAD

**Issue by PatilHarshh** [priyankarpal/ProjectsHut#1241]
### Add a new project to the list

i want to add the Unit Converter Project to your website @priyankarpal 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
