### ISSUE TITLE
Data: project addition by Judge-Paul

### ISSUE THREAD

**Issue by Judge-Paul** [priyankarpal/ProjectsHut#1245]
### Add a new project to the list

I want to add two new projects, One is an NFT marketplace that displays nft tokens, prices and collections, The second one is a cover letter generator that uses GPT-3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
