### ISSUE TITLE
Feat: Project backend

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#1247]
### What feature?

@priyankarpal I Hope you will be fine. I want to Know if you are working on project backend. Can i help you in this. I have experience in Node.js

### Add screenshots

nill

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure. https://github.com/priyankarpal/ProjectsHut/issues/1070
