### ISSUE TITLE
Bug: Fix UI Alignments for Project Cards

### ISSUE THREAD

**Issue by Xaid-vfx** [priyankarpal/ProjectsHut#1248]
### What happened?

 The GitHub Link button and More button shifts upwards when the description is of single line. This creates a bad UI impression. 
The above can be fixed by fixing the position of both Buttons with respect to the project card.

Below image shows the misalignment of Buttons in one of the cards

### Add screenshots

<img width="784" alt="Screenshot 2023-06-18 at 10 12 14 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/77684943/abc4aa08-696d-4681-8a70-a9f4b32374dc">

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, we need to fix this problem. assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
