### ISSUE TITLE
Feat: Replace the Copy button text with a clipboard icon

### ISSUE THREAD

**Issue by Xaid-vfx** [priyankarpal/ProjectsHut#1249]
### What feature?

The copy button just has a copy text which can be replaced by a clipboard to create a better UI impression.
Below Screenshot represents the issue:

### Add screenshots

Before:
<img width="1088" alt="Screenshot 2023-06-18 at 10 22 21 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/77684943/fa16d675-0dd5-487d-bd2f-e93475392901">
After:
<img width="1108" alt="Screenshot 2023-06-18 at 10 32 56 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/77684943/4c5b0cb1-f1f9-4647-90ce-2c0d60d40505">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on a new feature after completing the feature we will ping it here.

**Comment by priyankarpal** [comment]
hey, we've updated the docs. can you replace to copy button?

**Comment by Xaid-vfx** [comment]
At it 🚀
