### ISSUE TITLE
Data: project addition by swarajzz

### ISSUE THREAD

**Issue by swarajzz** [priyankarpal/ProjectsHut#1255]
### Add a new project to the list

I want to add a new project "Meme Generator" which basically lets users add top and bottom text to the top 100 trending memes dynamically using ReactJS.

Please assign me this, I will follow the code of conduct.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swarajzz** [comment]
@priyankarpal  Hey, can you help me with Vercel? My project is failing to deploy, and I'm wondering if I'm missing something. Initially, I tried using the Netlify project link and then the GitHub repo link, but both failed the Vercel check. Do I need to upload my project to Vercel first? I also noticed some pull requests that used Netlify/GitHub links and were merged successfully.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
