### ISSUE TITLE
Feat: I want to make text:{Share Your Projects} animated which looks more attractive to users.

### ISSUE THREAD

**Issue by akshaysoni10** [priyankarpal/ProjectsHut#1257]
### What feature?

I want to add animation in text:{Share Your Projects}.

### Add screenshots

Attractive animated text.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, where is the text {Share Your Projects}?

**Comment by akshaysoni10** [comment]
@priyankarpal On home page.

**Comment by priyankarpal** [comment]
> @priyankarpal On home page.

oh! got it. also, we are working on new UI design so we will change the homepage I think we don't need

**Comment by akshaysoni10** [comment]
@priyankarpal ok, if you need my help in UI then you can assign it to me.

**Comment by priyankarpal** [comment]
> @priyankarpal ok, if you need my help in UI then you can assign it to me.

I'm working on it :)
