### ISSUE TITLE
Data: project addition by mswat5

### ISSUE THREAD

**Issue by mswat5** [priyankarpal/ProjectsHut#1260]
### Add a new project to the list

I would love to add Amazon Web Scrapper @priyankarpal can you please assign

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey ig you have created two separate issues now I can't assign this issue to you when your first PR get merged then you can work on this issue. (according to GSSoC'23 rules)

**Comment by mswat5** [comment]
ok! np

**Comment by mswat5** [comment]
i've raised PR for my previous so hoping to get assigned for this

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

Thank you for your understanding.
