### ISSUE TITLE
Text Utility ReactAPP

### ISSUE THREAD

**Issue by raghav1482** [priyankarpal/ProjectsHut#1261]
### Add a new project to the list

This is a react app which provides text utility feature like :

UPPERCASE TEXT 
LOWERCASE TEXT 
REMOVE SPACES 
COPY TEXT 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Looks Good 🎉
