### ISSUE TITLE
Data: Animated Coffee Machine project addition by 5h0ov

### ISSUE THREAD

**Issue by 5h0ov** [priyankarpal/ProjectsHut#1263]
### Add a new project to the list

I wanted to add an Animated Coffee Machine using HTML & CSS and a little bit of Javascript.

# Preview:

![machine](https://github.com/priyankarpal/ProjectsHut/assets/83227649/595a8742-dcfc-4020-96cc-fd87a39021d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
