### ISSUE TITLE
pet store: project addition by rajendra

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#1266]
### Add a new project to the list

pet store is a e-commerce website for buying pet

owner - rajendra mandliya 
tech stack - react js 

github repo link - 
https://github.com/mandliyarajendra11/pet-store.git
deploy link - [raj-pet-store.netlify.app/](https://raj-pet-store.netlify.app/)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
