### ISSUE TITLE
Simon Game: project addition by Sabhi Sharma

### ISSUE THREAD

**Issue by sabhisharma-ise** [priyankarpal/ProjectsHut#1269]
### Add a new project to the list

Hello, I would like to contribute to this project by an addition of project called "SImon Game" which is made using HTML, CSS and JavaScript.

Kindly allow me to do so.
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
You can create PR for Projects addition. @sabhisharma-ise
