### ISSUE TITLE
💡feat:  Show whether the project has a live demo

### ISSUE THREAD

**Issue by andrewkykoo** [priyankarpal/ProjectsHut#127]
At the moment, users have to click on GitHub Link button to learn whether the project has a live demo link. It would be nice if we could include the live demo link (if available) in each project box component, preferably right below the summary/description. As a solution, we could add "live-demo-link" field in src/DB/projects.json file

**Comment by priyankarpal** [comment]
> At the moment, users have to click on GitHub Link button to learn whether the project has a live demo link. It would be nice if we could include the live demo link (if available) in each project box component, preferably right below the summary/description. As a solution, we could add "live-demo-link" field in src/DB/projects.json file

yes. good idea but some of the projects don't have live links(they haven't deployed yet)  then what should we do?

**Comment by andrewkykoo** [comment]
> 

We can ask contributors to enter empty string for "live-demo-link" if they don't have active live demos. Projects without the demos will simply not show any info about the demo in the box, and those with the links will show the link.

**Comment by priyankarpal** [comment]
> > 
> 
> We can ask contributors to enter empty string for "live-demo-link" if they don't have active live demos. Projects without the demos will simply not show any info about the demo in the box, and those with the links will show the link.

could you share a demo?

**Comment by andrewkykoo** [comment]
> > > 
> > 
> > 
> > We can ask contributors to enter empty string for "live-demo-link" if they don't have active live demos. Projects without the demos will simply not show any info about the demo in the box, and those with the links will show the link.
> 
> could you share a demo?


https://user-images.githubusercontent.com/47183818/229212042-7613b16c-7101-4778-bf5f-301d756d3a8d.mov

We can also wrap the text inside a button like tech buttons.

**Comment by priyankarpal** [comment]
> > > > 
> > > 
> > > 
> > > We can ask contributors to enter empty string for "live-demo-link" if they don't have active live demos. Projects without the demos will simply not show any info about the demo in the box, and those with the links will show the link.
> > 
> > could you share a demo?
> 
> 
> https://user-images.githubusercontent.com/47183818/229212042-7613b16c-7101-4778-bf5f-301d756d3a8d.mov
> 
> We can also wrap the text inside a button like tech buttons. 

If we want to add the link we need to change the card design. In the card if we add extra link it will look boring. 

So if you want to change the card design you can work on this issue & remember to share the new card design. 

Thankyou ❤️
