### ISSUE TITLE
Bug: GitHub Repo of 'React Quiz' project links to 404 error page

### ISSUE THREAD

**Issue by sabhisharma-ise** [priyankarpal/ProjectsHut#1270]
### What happened?

The Github of React Quiz projects, leads to a 404 error, possibly due to addition of a wrong link!

Can you assign this issue to me, so that I'll set it up to the right link!

Current Link:- https://projectshut.vercel.app/react-quiz-six-steel.vercel.app/

Actual Link:- https://github.com/sshiwangi/React-Quiz

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/100849696/929b42ac-937a-41af-bc88-c4c0900f05ec

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you @sabhisharma-ise

**Comment by sabhisharma-ise** [comment]
Hey @priyankarpal can you remove this stale tag of github-actions. It did not work on my issues right now as you said that website will be upgraded to next.js and ts. Can you do something about this? Or it will close this issue
