### ISSUE TITLE
💡fix:  add hover effect on the GitHub Link button

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#128]
#### 💡  We need to add a hover effect on the GitHub Link button using tailwind css

![image](https://user-images.githubusercontent.com/88102392/229188260-0f19a3f2-048b-41e3-adf6-da2aa74c0a6f.png)

**Comment by priyankarpal** [comment]
> Hey @priyankarpal , mind if I contribute by handling this?

yeah you can work on this issue.

**Comment by RLTek** [comment]
Thanks! I just submitted the pull request.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by RLTek** [comment]
Happy to help!
