### ISSUE TITLE
Bug: Added Project under Wrong username

### ISSUE THREAD

**Issue by Killer2OP** [priyankarpal/ProjectsHut#1289]
### What happened?

The projects which were added by "Killer2OP" came under the username of "killerraj369".

### Add screenshots

# Code
![image](https://github.com/priyankarpal/ProjectsHut/assets/111378171/322491b4-a401-447d-a14a-132a30469745)
# **How it should be:**
![image](https://github.com/priyankarpal/ProjectsHut/assets/111378171/b46cbf68-47b6-416e-92ed-2ec13f7aae7e)
# **How it is:**
![image](https://github.com/priyankarpal/ProjectsHut/assets/111378171/b367e86d-eba3-418c-b8fb-442d8847751a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
