### ISSUE TITLE
Bug: Images added in home section are broken

### ISSUE THREAD

**Issue by ManishaSwain8** [priyankarpal/ProjectsHut#1294]
### What happened?

As the images are directly from Chrome/Internet , that's why the images are not visible in Google chrome neither Avast browser  so better to add a separate file for images rather than the direct links from internet.
If these changes required to assign it under GSSOC 2023,Changes will be done !

### Add screenshots

![Screenshot (73)](https://github.com/priyankarpal/ProjectsHut/assets/96622693/b0b37855-ca34-457c-ab2c-edb2de3e4bd9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, but I'm not getting any issues. maybe your internet issue 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/a6ef0809-a1b5-443b-bcef-3a20891f3b9d
