### ISSUE TITLE
Docs: Improvements in Readme

### ISSUE THREAD

**Issue by iqrafirdose** [priyankarpal/ProjectsHut#1298]
### what's wrong in the documentation?

As Readme is an important file, it helps users understand the project's purpose.

If the projectHut team agrees, I will add a logo before the name of the project.

And, I will highlight some important words that describe the project's purpose.

### Add screenshots

![s1](https://github.com/priyankarpal/ProjectsHut/assets/114678694/10b8af7e-0cc6-46df-a8b0-cbee072146e7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig we don't need to change any things in the readme, we have mentioned all points already. :)
