### ISSUE TITLE
Docs: To add Urdu translation

### ISSUE THREAD

**Issue by iqrafirdose** [priyankarpal/ProjectsHut#1299]
### what's wrong in the documentation?

As ProjectHut is now available in French, Tamil, German, and many more languages that will be helpful to the users to understand easily. So, I want to add an Urdu translation that will be helpful to Urdu speakers to understand ProjectHut easily.

### Add screenshots

I would like to add an Urdu translation.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sorry to say that we have removed all translations & we decided to use only one language so currently we don't need 

thanks for understanding
