### ISSUE TITLE
Feat: Projects of the Month section on home page

### ISSUE THREAD

**Issue by Varghab** [priyankarpal/ProjectsHut#1301]
### What feature?

A new section of "Projects of the Month" can be implemented that will help in two ways - 
**- **Encourage people to submit new projects.****
**- Inspire others in their journey of building new projects.** 

If the idea is appropriate then please assign me, I will be more than happy to contribute. 

### Add screenshots

I don't have any screenshots now as this is a feature request, but definitely going to attach screenshots with the PR if I get assigned. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @Varghab thanks for creating the issue currently we are working on new features so I think we don't need the projects of the month section now. 

Also, we will add a new UI soon after new UI if anything is needed you can raise an issue.
