### ISSUE TITLE
Feat: Add close old issue bot

### ISSUE THREAD

**Issue by k-deepak04** [priyankarpal/ProjectsHut#1304]
### What feature?

Proposal: Close Old Issue Bot
Description: The Close Old Issue Bot is an automated tool designed to identify and close inactive or resolved issues in a timely manner. It improves issue management efficiency by reducing clutter and ensuring active focus on relevant tasks.
Features:
1. Issue Tracking: Monitors issue activity and identifies those that have remained inactive for a specified period.
2. Automatic Closure: Closes old or resolved issues based on predetermined criteria, promoting a clean and organized issue tracker.
3. Customizable Settings: Allows users to define their own criteria for determining issue activity and closure, adapting to the specific needs of their project.

### Add screenshots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have a stale issue checker.
