### ISSUE TITLE
🚨 IMPORTANT NOTICE FOR CONTRIBUTORS 🚨

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1305]
hey contributors we are working on the next & typescript migration, so please try to avoid creating issues/PRs at that time.

- after migration, you can create issues/ PRs. 
- if you have created an issue then don't create a PR at that moment.
- or if you have created a PR we can't merge the PR right now.

**Comment by s2sharpit** [comment]
Hey @priyankarpal 

I would love to contribute and help with migrating the website to Next.js and TypeScript. I have experience with both Next.js and TypeScript, and I'm confident in my ability to assist in the migration process.

Please let me know if there's any specific area or task you would like me to focus on, or if there are any guidelines or instructions I should follow. I'm eager to collaborate and make the migration a success.

Looking forward to working with you!

**Comment by priyankarpal** [comment]
> Hey @priyankarpal
> 
> I would love to contribute and help with migrating the website to Next.js and TypeScript. I have experience with both Next.js and TypeScript, and I'm confident in my ability to assist in the migration process.
> 
> Please let me know if there's any specific area or task you would like me to focus on, or if there are any guidelines or instructions I should follow. I'm eager to collaborate and make the migration a success.
> 
> Looking forward to working with you!

we are working on that issue.  After next & ts migration if you find any problems you can raise an issue.

**Comment by s2sharpit** [comment]
Okay then, I will wait till that.
धन्यवाद 😊
