### ISSUE TITLE
Data: project addition by 5h0ov

### ISSUE THREAD

**Issue by 5h0ov** [priyankarpal/ProjectsHut#1319]
### Add a new project to the list

I wanted to add an Animated Envelope Animation using HTML & CSS.

# Preview

![envelope](https://github.com/priyankarpal/ProjectsHut/assets/83227649/82d147b9-7109-46d4-8a74-521544a605c0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig you have created an issue before so I'm closing this issue. You can add multiple projects in a single issue
