### ISSUE TITLE
Feat:Enhance UI of  the cards in projects page

### ISSUE THREAD

**Issue by Pragati-3003** [priyankarpal/ProjectsHut#1322]
### What feature?

I would to change the Ui of the card by adjusting margin and padding and  by applying hover effects and box-shadows ,so,please assign this issue to me under GSSoC'23.

### Add screenshots

![Screenshot 2023-06-21 202123](https://github.com/priyankarpal/ProjectsHut/assets/132778037/b599f3a0-f269-4d73-8368-95008ec718ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig there are nothing wrong so we don't need to change anything :)
