### ISSUE TITLE
Feat: want to add animation on hover to cards

### ISSUE THREAD

**Issue by MrSahilShaikh** [priyankarpal/ProjectsHut#1326]
### What feature?

problem - when cursor goes on cards it will show any hover effect or animation. 
solution - 
adding css to cards & on hover effect

### Add screenshots

![projecthub](https://github.com/priyankarpal/ProjectsHut/assets/60029854/90bc9e80-d3a8-4b4c-b21f-dd71ba293fe4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on new card designs so I think we don't need to change anything
