### ISSUE TITLE
Data: project addition by SyedImtiyaz-1

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [priyankarpal/ProjectsHut#1328]
### Add a new project to the list

Hello @priyankarpal ,
I'm adding 4 Projects based on **HTML5, CSS3, JavaScript, API**

### Projects -
1. The Code Shop [E-Commerce Website]
2. Talent-In [Recruiting Website]
3. Netflix-Replica [Netflix Clone]
4. Portfolio Template [Template]
5. Meme Generator [Fetches data from `Reddit` {API}]

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
