### ISSUE TITLE
💡feat:  Add eslint into the code

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#133]
### Need to add `eslint` into the code and also share demo after adding.

**Comment by AniketNS** [comment]
Hey @priyankarpal, assign this to me. I'm working on it.

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, assign this to me. I'm working on it.

You can work on it 🤝

**Comment by AniketNS** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/91371143/229464057-6cde3f66-c5e8-4bd8-9056-a0a334ea9c5b.png">

Hey @priyankarpal, I'm getting this error while initializing eslint to the root directory of the project. 
Can you tell me, why I'm having this error?

**Comment by AniketNS** [comment]
<img width="725" alt="added eslint" src="https://user-images.githubusercontent.com/91371143/229469547-c876bba1-9127-4d39-a5f5-5d1d6049a580.png">

Hey @priyankarpal, I've added eslint. See this and tell me what else I should do Or this is correct or not?

**Comment by AniketNS** [comment]
I've done some changes in a tailwind.config.cjs after installing eslint. It was showing the error that the String should be in a single coat. I did that and some more minor changes.

**Comment by priyankarpal** [comment]
> I've done some changes in a tailwind.config.cjs after installing eslint. It was showing the error that the String should be in a single coat. I did that and some more minor changes.
ok just create a PR I will check

**Comment by AniketNS** [comment]
Hey @priyankarpal, I've created a PR. Will you please check it and tell me if it works or not?

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by AniketNS** [comment]
Thanks to you too. I learned a new thing today. Just because of you @priyankarpal. I'd love to work on more issues or rather I'd create the issue or any addition to the website.

**Comment by AniketNS** [comment]
Sure @priyankarpal 🖤🖤
