### ISSUE TITLE
Data: project addition by  Harshu467

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1334]
### Add a new project to the list

A ReactJs Web Project of CryptoCurrency which has various features of graphs live data , rankings and many more.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Harshu467** [comment]
@priyankarpal  Can you update the level from 1 to level 2 as the project is very big

**Comment by priyankarpal** [comment]
> @priyankarpal Can you update the level from 1 to level 2 as the project is very big

first of all, you're adding projects here :)

**Comment by Harshu467** [comment]
@priyankarpal  Please Check my PR , and merge it as soon as possible. Thank You

**Comment by Harshu467** [comment]
@priyankarpal  Please Add tags of GSOC and level 1
