### ISSUE TITLE
Data: project addition by Harshu467

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1335]
### Add a new project to the list

I want to add web project based on Gym. It is frontend project and with responsive design and best userfriendly interface

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
you don't need to create multiple issues for project addition at a time. you can add multiple projects
