### ISSUE TITLE
Feat: Adding Contact Section 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [priyankarpal/ProjectsHut#1338]
### What feature?

Hello @priyankarpal ,
I'm adding a Contact Section 👍🏻 
Through which any body can contact if there is an issue regarding the website or the projects or any kinda things.

Also fixing the Code-base to work more robustly.

## Screenshot -
Fixing this and adding a contact form 👍🏻 

![Screenshot from 2023-06-23 09-57-04](https://github.com/priyankarpal/ProjectsHut/assets/121503426/4cf35e7c-7e55-48ae-aa9f-2c8351c7aea5)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently, we don't need a contact section we will add it later if needed.
