### ISSUE TITLE
Feat:

### ISSUE THREAD

**Issue by OmAgarwal8979** [priyankarpal/ProjectsHut#1348]
### What feature?

Add a like and dislike button on to the projects displayed

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89903819/d9f16e58-b88f-4879-a8bf-6f31848cc637)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/1200
