### ISSUE TITLE
Bug: Home page images not showing

### ISSUE THREAD

**Issue by anamika7153** [priyankarpal/ProjectsHut#1350]
### What happened?

Images are not displayed 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/66116440/b7691e1d-8a69-429d-88b1-801ff653e1c9)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey, but I'm not getting any issues. maybe your internet issue

**Comment by priyankarpal** [comment]
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1294
