### ISSUE TITLE
Feat: Create a about us page

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#1355]
### What feature?

about us page for website 
with some feature like - 
some line about project
project admin
our contributors

### Add screenshots

none

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently we are working on new feature after if we need we will create
