### ISSUE TITLE
adding social media profiles and Improving footer section 

### ISSUE THREAD

**Issue by gaur15** [priyankarpal/ProjectsHut#1373]
### What feature?

adding some features in footer section adding social media profiles and some more features.

### Add screenshots

<img width="752" alt="Screenshot 2023-06-25 102956" src="https://github.com/priyankarpal/ProjectsHut/assets/133087361/c8c54cfe-7a35-4ac5-94eb-6ef19494902f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently, we have only a github link & also we are working on a new feature so not needed now
