### ISSUE TITLE
Feat: Making Beautiful Search Bar

### ISSUE THREAD

**Issue by PatilHarshh** [priyankarpal/ProjectsHut#1378]
### What feature?

adding hovering methods and cool looking search bar @priyankarpal 

### Add screenshots

![Screenshot (109)](https://github.com/priyankarpal/ProjectsHut/assets/120102234/73ffdee5-7478-442f-89e7-0d75e01e0da4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently, we are working on new features so currently don't need
