### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by PatilHarshh** [priyankarpal/ProjectsHut#1379]
### Add a new project to the list

Full Fleldge Restaurent Website @priyankarpal 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
assigned to you
