### ISSUE TITLE
Feat: Setting theme based on the system theme by default

### ISSUE THREAD

**Issue by kartikjoshi267** [priyankarpal/ProjectsHut#1386]
### What feature?

I want to add a feature so that the website changes theme based on the system default theme.
Till now the default theme of the website is `Light`. Suppose a user's system theme is `Dark`, then he/she would like the website to be in `Dark` mode by default.

### Add screenshots

_N/A_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
after the nextjs & typescript migration, we will remove the dark & light mode features so I think we don't need to change it right now.
