### ISSUE TITLE
Feat: Make Filter and Clear button more attractive.

### ISSUE THREAD

**Issue by akshaysoni10** [priyankarpal/ProjectsHut#1388]
### What feature?

Filter and Clear button looks very simple. I want to make it more attractive. Please assign me this task under **GSSoC'23**.

### Add screenshots

Make button more attractive.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig buttons are ok we don't need to change anything
