### ISSUE TITLE
Docs: Add contributors list to the readme file

### ISSUE THREAD

**Issue by sumitkr2000** [priyankarpal/ProjectsHut#1394]
### what's wrong in the documentation?

Hey @priyankarpal I want to add the contributors list on the readme.md file. PLease assign me this issue. Thank you!

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/100675296/6db01330-55f7-418e-b409-a870fbe749f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have a contributors list 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/3d399b8b-fac1-4c16-887b-6538d0ceccce
