### ISSUE TITLE
chore: project addition by anamika

### ISSUE THREAD

**Issue by anamika7153** [priyankarpal/ProjectsHut#1399]
### Add a new project to the list

I want to add my portfolio project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
hey, @anamika7153 you've created PR in your forked repo. Please make it in our repo so that we can merge. also, we have migrated our website to Next.js and TypeScript, so the file path has changed. Please have a look at our updated contributing guidelines for more information.
