### ISSUE TITLE
Bug: Home page images not displaying correctly

### ISSUE THREAD

**Issue by harshit-tiwaari** [priyankarpal/ProjectsHut#1415]
### What happened?

Will fix  the above issue along with more minimalistic home page

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/104323483/c4fce974-a577-4dda-9ae3-c89cdbb4d07f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's an internet issue, I'm not getting any problem
