### ISSUE TITLE
Feat: Name Logo for the ProjectsHut Website

### ISSUE THREAD

**Issue by Tisha6661** [priyankarpal/ProjectsHut#1420]
### What feature?

I would like to add name logo to the project, which would look more professional.

### Add screenshots

Some of the logos I've made are these, to give you the idea-

![Screenshot 2023-06-27 011300](https://github.com/priyankarpal/ProjectsHut/assets/98682478/a9998081-c7b0-4b48-b2a1-7e37349f15d5)

![Screenshot 2023-06-24 005041](https://github.com/priyankarpal/ProjectsHut/assets/98682478/d1228940-5e5a-48ab-a6c1-bd4b270ae027)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently we're working on migration so after the migration I will ping here

**Comment by priyankarpal** [comment]
hiii @Tisha6661 we've migrated the code base. Now you can work on this issue. make sure to share demos with us so that we can finalize the logo.

**Comment by Tisha6661** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/9e499ef0-58b5-407e-9d40-3a4ee19e7b8e)

Let me know the reviews or any changes required.

**Comment by Tisha6661** [comment]
That's how it looks on the site-
![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/382a8d9a-a62a-4cfa-a46b-96667601edee)
![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/b67ef641-0d87-4182-8d8c-c94a68bd1734)

It complements the page, I have not justified the css for now, it's just a look of it.

**Comment by priyankarpal** [comment]
> @priyankarpal Here is the logo-
> 
> ![image](https://user-images.githubusercontent.com/98682478/251298131-8d1bbefb-f401-4c5e-af77-e933eb6deae1.png)
> 
> Let me know the reviews or any changes required. Also the watermark will be removed completely, this is just for demo.

can you make it simple? like avoid adding these icons

**Comment by Tisha6661** [comment]
How about this
![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/10af1971-82da-4fb5-b21c-32a7bb53b8a5)

**Comment by priyankarpal** [comment]
> How about this ![image](https://user-images.githubusercontent.com/98682478/251767500-10af1971-82da-4fb5-b21c-32a7bb53b8a5.png)

we are using `inter` font, please use the theme font

**Comment by Tisha6661** [comment]
I used the inter font now, is the design good for you-

![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/e75c3f05-a709-4648-8c4e-0809cbd8cf3c)

**Comment by priyankarpal** [comment]
> I used the inter font now, is the design good for you-
> 
> ![image](https://user-images.githubusercontent.com/98682478/251777665-e75c3f05-a709-4648-8c4e-0809cbd8cf3c.png)

please add the logo to the website & check

**Comment by Tisha6661** [comment]
That's how it look-

![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/19287a48-e91e-4a7a-89a3-2bf544332104)

**Comment by priyankarpal** [comment]
I think `ph.` is looking clear

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/da91c8d5-8824-4cfd-b308-0680d9877c8b)

**Comment by Tisha6661** [comment]
@priyankarpal I have created a PR for this task, please have a look and decide.

**Comment by priyankarpal** [comment]
> @priyankarpal I have created a PR for this task, please have a look and decide.

in my opinion simple `ph.` is looking clear :)

**Comment by Tisha6661** [comment]
@priyankarpal It's upto you, but i feel there is very much free space around it, which is not looking good, that's why I generated this issue in the first place. Also the name reflects the motive of the site better, I have designed name logo for several projects in GSSOC'23 itself.

**Comment by priyankarpal** [comment]
> @priyankarpal It's upto you, but i feel there is very much free space around it, which is not looking good, that's why I generated this issue in the first place. Also the name reflects the motive of the site better, I have designed name logo for several projects in GSSOC'23 itself.

yeah I understand
