### ISSUE TITLE
Feat: Better Ui of the Footer

### ISSUE THREAD

**Issue by Tisha6661** [priyankarpal/ProjectsHut#1421]
### What feature?

Right now the Footer is simple, and doesn't include the social media handles in it. I would like to add those and make a better Ui of the footer. 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98682478/18ba2429-213c-49ed-a824-f7e77a597ac3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are thinking to redesign the UI design so ig currently we don't need to change the existing one.
