### ISSUE TITLE
Bug: Missing Instagram, Youtube links causing error

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [priyankarpal/ProjectsHut#1427]
### What happened?

A lot of users may not have all the social media details asked. So they are leaving their username as "YOUR_YOUTUBE_ACCOUNT_LINK".

The bug can be solved by creating an option to have social links as optional.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/68057995/f00651bf-a260-458f-ba3b-e81b08fe83d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to fix assigned to you

**Comment by Siddhesh-Agarwal** [comment]
Done
