### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by Siddhesh-Agarwal** [priyankarpal/ProjectsHut#1428]
### Add a new project to the list

1. [Matmath](https://github.com/Siddhesh-Agarwal/matmath)
2. [Cryptmoji](https://github.com/Siddhesh-Agarwal/Cryptmoji)
3. [Sierra](https://github.com/BrainStormYourWayIn/sierra)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

Thank you for your understanding.
