### ISSUE TITLE
Feat: Improve footer section

### ISSUE THREAD

**Issue by gaur15** [priyankarpal/ProjectsHut#1439]
### What feature?

adding social media links to better to connect better 

### Add screenshots

<img width="835" alt="Screenshot 2023-06-28 104624" src="https://github.com/priyankarpal/ProjectsHut/assets/133087361/cc63a0a3-d9b1-43ae-b175-c45a16ec9c14">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on new feature so we don't need to change right now
