### ISSUE TITLE
Feat: New Ui requirement

### ISSUE THREAD

**Issue by Ks103** [priyankarpal/ProjectsHut#1441]
### What feature?

The website looks amazing but the main page ui is something which makes the visitor to be connected with the page till the end.
I request you to please assign me this issue so that I can start contributing to it.

### Add screenshots

![Screenshot (199)](https://github.com/priyankarpal/ProjectsHut/assets/86292101/509b80ae-9d71-459a-8a69-bee209c14986)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @Ks103 thanks for creating the issue. basically, we will add a new UI soon so we don't need to change. Also, there are few images on the homepage


https://github.com/priyankarpal/ProjectsHut/assets/88102392/8f59366e-49a8-4580-a89b-54ffd7a179f0
