### ISSUE TITLE
closed button

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#1446]
### What feature?

When we click on the filter button, a pop-up box appears with tech stack, but there is no close button/search/done . I know that clicking on the background will close it, but having a close/search/done(any one) button would be better and more visually appealing.

### Add screenshots

![Screenshot (157)](https://github.com/priyankarpal/ProjectsHut/assets/119125519/c2d6ff01-cf74-4376-a43c-82765d653d84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's not necessary also, we are working on new features.
