### ISSUE TITLE
chore: project addition by Shivam

### ISSUE THREAD

**Issue by panditshivammishra** [priyankarpal/ProjectsHut#1455]
### Add a new project to the list

I want add a react project Textutils
![textimage](https://github.com/priyankarpal/ProjectsHut/assets/109903290/1f67f60a-3ada-44ac-b0e1-d8ead3f92b00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
assigned to you

**Comment by panditshivammishra** [comment]
@priyankarpal kindly review my PR.
I have hosted my project on netlify app because of errors at github. so, please review my PR
