### ISSUE TITLE
Feat: Smooth Scrolling feature in website

### ISSUE THREAD

**Issue by Killer2OP** [priyankarpal/ProjectsHut#1461]
### What feature?

Hey, I want to make some improvements to the code and added a smooth scroll feature that provides users with a seamless navigation experience when clicking on links in the navigation bar. I believe this enhancement would greatly benefit our project. Therefore, I kindly request you to assign me this issue.

### Add screenshots

none

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on nextjs migration so I think we don't need to change any code right now. if needed we will create an issue
