### ISSUE TITLE
chore: project addition by rajendra

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#1464]
### Add a new project to the list

book store 

book store is a online book purchasing app

i create this with the help of google book api
it have 4-6 book category pages
about us page
user review and search box option on the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
you don't need to create multiple issues for projects addition at a time
