### ISSUE TITLE
chore: project addition by tayyab-ilyas

### ISSUE THREAD

**Issue by tayyab-ilyas** [priyankarpal/ProjectsHut#1465]
### Add a new project to the list

I would like to add my project [PomTasker](https://github.com/tayyab-ilyas/pomtasker)

<img width="1120" alt="pomtasker" src="https://github.com/priyankarpal/ProjectsHut/assets/110786036/9e374204-b45b-4e9f-9948-3cce72a6e29d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.

**Comment by tayyab-ilyas** [comment]
hi @priyankarpal this project got merged in another repository, I don't think it would be a good practice to create a PR for it here as well, really sorry for wasting your time.

**Comment by priyankarpal** [comment]
> hi @priyankarpal this project got merged in another repository, I don't think it would be a good practice to create a PR for it here as well, really sorry for wasting your time.

No problem at all! Thank you for letting me know. There's no need to apologize for anything.
