### ISSUE TITLE
Bug: Search function not working fine

### ISSUE THREAD

**Issue by GayathriManeksha** [priyankarpal/ProjectsHut#1468]
### What happened?

The contents loaded after scrolling down for a particular search query changes and irrelevant content also displayed under a search query

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/85406626/e9db1b86-7063-41c6-bba7-b392eebba25a)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we've migrated the code base ig there is no problem with the search bar. if exists you can raise an issue.  

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/1f4d574f-82d4-49d2-a59d-be04e7ce1c7d)
