### ISSUE TITLE
Feat:The scrollbar is very simple.

### ISSUE THREAD

**Issue by Shreyans2004** [priyankarpal/ProjectsHut#1469]
### What feature?

The scrollbar is very simple.I can add styling to scrollbar so that it looks better and attractive.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/128773151/ed0fe879-605d-4b24-b8a7-726ba6b3bbd8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it's ok we don't need to change
