### ISSUE TITLE
Bug: The github icon hover

### ISSUE THREAD

**Issue by Shreyans2004** [priyankarpal/ProjectsHut#1471]
### What happened?

The github icon is just increasing in size on hovering.Not behaving same like home icon and others.I can add some styling so that it behaves in the same way as other icons.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/128773151/2940e35c-9304-4bed-9579-1929fbe0c4af)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
for now we don't need to change
