### ISSUE TITLE
chore: project addition by aparna03dubey

### ISSUE THREAD

**Issue by aparna03dubey** [priyankarpal/ProjectsHut#1475]
### Add a new project to the list

This project is a Body Mass Index, made using HTML, CSS and Javascript.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.
