### ISSUE TITLE
chore: project addition by Illaf

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1481]
### Add a new project to the list

A fully functional daily personal journal writing website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.
