### ISSUE TITLE
chore: project addition by Pro-18

### ISSUE THREAD

**Issue by Pro-18** [priyankarpal/ProjectsHut#1495]
### Add a new project to the list

Project Name: wallpaper viewer gui 
Description : wallpaper viewer is a gui which is made by using tkinter.

![issue6APS](https://github.com/priyankarpal/ProjectsHut/assets/92087279/a51f2ee5-4aa6-43c5-9381-c468bb9b0542)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.
