### ISSUE TITLE
Feat: Adding Animations To The Rendering Of Projucts cards.

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1512]
### What feature?

 Adding Animations To The Rendering Of Projucts cards.

### Add screenshots

If you can assign me thie issue, Ill provide them very soon.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Currently, we are in a maintenance phase, where our primary focus is on specific improvements and bug fixes. In order to maintain alignment with our current goals and objectives, we have decided to prioritize other aspects of the project for now.
