### ISSUE TITLE
refactor: Improved docs page codebase

### ISSUE THREAD

**Issue by adity2911** [priyankarpal/ProjectsHut#1517]
Improve the readability and removing the redundant parts of the codebase should be a top priority for the code. 
I can do both of them to the file. The code file has way too many redundant code and it hampers the readability of the code.

Proposed Changes:
Add a component Step which accepts fields like text, image link, code, and icon and render it.
This allows us to only maintain the data in a json object and map all the data to the Step component.

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.

**Comment by adity2911** [comment]
@priyankarpal Can i work on it now?
