### ISSUE TITLE
Feat: Add options button to the Docs tab

### ISSUE THREAD

**Issue by adity2911** [priyankarpal/ProjectsHut#1519]
### What feature?

Please refer the video provided. 
I want to give options to the user to choose the methods to contribute. 
This is a nice UI improvement, that, I think will be cherished by many.
This eliminates some confusion while reading the docs too.
The video shown is working fine, I just need the issue to be assigned to me.
If you want me to change anything, please let me know.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/72987111/c90ed64a-3839-46f2-a623-533fc2ebec38

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, it's an amazing feature. we will add it later. Currently, we are in a maintenance phase. I will ping you here after the migration

**Comment by adity2911** [comment]
@priyankarpal Let me know what you think about the proposal now!

**Comment by priyankarpal** [comment]
we need to add good UI here is the demo there will be a tab or cards for separate sections
- add projects from GitHub
- how to set up the project locally? 
 
> If you want we can discuss about the UI 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/f1b0214f-2505-4f1e-a222-cb0cd1ff2e61)

**Comment by adity2911** [comment]
I will surely improve the ui. Could you confirm that the project uses bootstrap or something else?

**Comment by priyankarpal** [comment]
> I will surely improve the ui. Could you confirm that the project uses bootstrap or something else?

nextjs, typescript, tailwind css

**Comment by adity2911** [comment]
Just to be sure, I am supposed to make the PR to also also?
I have completed the code.
