### ISSUE TITLE
Bug: Button color mismatch and text size inconsistency on different devices

### ISSUE THREAD

**Issue by Saurav-Pant** [priyankarpal/ProjectsHut#1520]
### What happened?

in PageNotFound The button color doesn't match the design, and on small devices, the text size remains the same, while it should be smaller in small, medium, and larger on large devices. Looking for suggestions on button color and am willing to work on resolving the issue.

### Add screenshots

![GOtoHOme](https://github.com/priyankarpal/ProjectsHut/assets/103263909/e982a4e0-4f99-4abc-924e-bd581ccb7d78)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we removed the page & migrated to nextjs & typescript so it's not neededd
