### ISSUE TITLE
chore: project addition by bharti nagpure

### ISSUE THREAD

**Issue by BhartiNagpure** [priyankarpal/ProjectsHut#1524]
### Add a new project to the list

I would like to add quote generator mini project, which shows qoute after clicking get qoute button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by BhartiNagpure** [comment]
@priyankarpal I am added project but my pull request is not visible in main project.

**Comment by priyankarpal** [comment]
> @priyankarpal I am added project but my pull request is not visible in main project.

cause you've created PR in your forked repo

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/30b8c2be-9d41-4ea0-899b-5286c9d88869)

**Comment by BhartiNagpure** [comment]
> > @priyankarpal I am added project but my pull request is not visible in main project.
> 
> cause you've created PR in your forked repo
> 
> ![image](https://user-images.githubusercontent.com/88102392/250492359-30b8c2be-9d41-4ea0-899b-5286c9d88869.png)

I am created new PR.
