### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1528]
### What happened?

Filters are not working properly. when we unselecting the tags results are not come properly or not updating.

### Add screenshots

![Screenshot (662)](https://github.com/priyankarpal/ProjectsHut/assets/68702055/d7f553db-eb0f-44c6-b379-a9c79ba58501)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's already fixed
