### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1529]
### What happened?

while applying filters same Data repeating.

### Add screenshots

![Screenshot (663)](https://github.com/priyankarpal/ProjectsHut/assets/68702055/8907cad5-17a9-4764-9721-ea4ca7e8c9c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's already fixed
