### ISSUE TITLE
chore: project addition by  bharti nagpure

### ISSUE THREAD

**Issue by BhartiNagpure** [priyankarpal/ProjectsHut#1532]
### Add a new project to the list

I would like to add restauranat website, which shows different types of services , variety of food , reveiwers etc.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by BhartiNagpure** [comment]
@priyankarpal is there problem in my PR you are closed my all PR, also not added level tag.

**Comment by priyankarpal** [comment]
> @priyankarpal is there problem in my PR you are closed my all PR, also not added level tag.

- we've migrated to nextjs & typescript so we need to close all PRs from all contributors. 
- for project addition, we're not providing the `gssoc23` `label1` tag. (according to the GSSoC'23 it's not related to fixing any issue)

**Comment by BhartiNagpure** [comment]
ok
