### ISSUE TITLE
Bug: Search feature isn't working properly

### ISSUE THREAD

**Issue by ShikhaaT44** [priyankarpal/ProjectsHut#1535]
### What happened?

When i search for resume related projects by entering 'Resume' in the searchbar, the results are not static. I mean when i try to scroll down, the projects keep refreshing and also the major projects displayed don't follow the keyword entered.
Also there must be a search button adjacent to the searchbar in order to provide a smooth user experience.

### Add screenshots

![bug2](https://github.com/priyankarpal/ProjectsHut/assets/89783531/e396d7d6-ee9b-4b70-93a9-3f1d7faa0262)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ig it's already fixed
![Screenshot from 2023-07-04 18-07-13](https://github.com/priyankarpal/ProjectsHut/assets/88102392/2bc13b40-01bc-4e49-af5c-757c0d9e73de)
