### ISSUE TITLE
chore: project addition by Kritika

### ISSUE THREAD

**Issue by Kritika0804** [priyankarpal/ProjectsHut#1542]
### Add a new project to the list

I would like to add news website made using ReactJS

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] My project has contribution guidelines
- [X] My project has a Code of conduct
- [X] My project has README
- [X] My project has a License

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.
