### ISSUE TITLE
Data: project addition by Dimple-Choudhary

### ISSUE THREAD

**Issue by Dimple-Choudhary** [priyankarpal/ProjectsHut#1549]
### Add a new project to the list

I want to add a New project.
It's a headphone landing page using  JavaScript.

Hey @priyankarpal, will you assign this issue to me?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
We have migrated our website to Next.js and TypeScript, so the file path has changed. Please check our updated contributing guidelines for more information.
