### ISSUE TITLE
💡feat:  redesign this page 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#155]
- We need to redesign the particular area in the projectspage

![image](https://user-images.githubusercontent.com/88102392/230784025-ab14325d-6f43-44e0-8c7d-36e4d22d1f28.png)

**Comment by Deveesh-Shetty** [comment]
### How about this just a slight change

![image](https://user-images.githubusercontent.com/89470104/230824776-431bc9b8-fc3f-4814-8d8f-dd0f98d6b15e.png)
 
<br>

### On hover
![image](https://user-images.githubusercontent.com/89470104/230824611-569f071d-d6ba-4bf4-9688-caa261105d39.png)

<br>

**Comment by priyankarpal** [comment]
> ### How about this just a slight change
> ![image](https://user-images.githubusercontent.com/89470104/230824776-431bc9b8-fc3f-4814-8d8f-dd0f98d6b15e.png)
> 
> 
> ### On hover
> ![image](https://user-images.githubusercontent.com/89470104/230824611-569f071d-d6ba-4bf4-9688-caa261105d39.png)

Looks Good 🎉

**Comment by Deveesh-Shetty** [comment]
Will send a PR then...closing this issue

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
