### ISSUE TITLE
Feat: Light mode switch

### ISSUE THREAD

**Issue by adity2911** [priyankarpal/ProjectsHut#1552]
### What feature?

There is no option to change dark mode to light mode. I would like to add it.

### Add screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
thanks for creating the issue. previously we had light mode & dark mode. after migration, we've decided to use only dark theme.
