### ISSUE TITLE
📙doc: add a point after 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#156]
- Add a point under the `How to contribute section?`
- the point will be `Don't spam if you do it your PR/issue will be closed.`

![image](https://user-images.githubusercontent.com/88102392/230784216-b8d15b8a-7f03-4d1b-982d-01a0019e7201.png)

**Comment by SurajPratap10** [comment]
Assign this to me.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
