### ISSUE TITLE
Feat: Copy Code Snippet

### ISSUE THREAD

**Issue by vaibhav-xt** [priyankarpal/ProjectsHut#1560]
### What feature?

I can see that copy code snippet is not working. Even is not visible. Also, the blue text has a gap, not starting from the position where the image is. 

### Add screenshots

![Screenshot (145)](https://github.com/priyankarpal/ProjectsHut/assets/90946899/81b03dd2-3bb9-4835-8019-614c06850176)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @vaibhav-xt we're working on the docs page so we will change the whole Ui so currently we don't need to change
