### ISSUE TITLE
Feat: Project Contributors List Page

### ISSUE THREAD

**Issue by vaibhav-xt** [priyankarpal/ProjectsHut#1561]
### What feature?

This is to create a new page for the project contributors. It will contain all the unique contributors with their profile pictures, names, and social handles. The page will look similar to the project page. It will contain a navbar, search bar, and footer but not a filter. The data will fetch from project.json. 

### Add screenshots

![Screenshot (147)](https://github.com/priyankarpal/ProjectsHut/assets/90946899/1ffef6c9-0e0b-4ee0-a857-e8bf3e51afdd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
previously we had contributors list, we don't want to add now
