### ISSUE TITLE
Feat: fetch data from github

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1562]
### What feature?

currently, we're collecting data using `json` format so data is becoming too long we need to fetch details from the github API 

- fetch social media
- repository details
- etc

### Add screenshots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by suzy-g38** [comment]
Can I work on this issue with you?

**Comment by priyankarpal** [comment]
> Can I work on this issue with you?

ok
