### ISSUE TITLE
Data: project addition by Rohan mittal

### ISSUE THREAD

**Issue by rohanmittal1163** [priyankarpal/ProjectsHut#1571]
### Add a new project to the list

@priyankarpal 
I want to add a music player in the list that will create a seamless ui experience for the users.
it will have variety of options including previous, next, music queue, shuffle, play/pause, downlaod, collapse etc.
I have seen a porject like this in your github repo but trust me it is far way organized and more features than it.

#screenshorts
![image](https://github.com/priyankarpal/ProjectsHut/assets/97821844/56c16915-5cd4-42e0-8200-2aa38b2d5a2a)

pls assign this issue under GSSOC'23 as its contributor to contributein your github repo
thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@rohanmittal1163 We are not providing any labels for project additions as they are not associated with solving any issues. previously we've added but currently,

**Comment by rohanmittal1163** [comment]
@priyankarpal Do i get points to make the project and create a PR for this github repo

**Comment by priyankarpal** [comment]
> @priyankarpal Do i get points to make the project and create a PR for this github repo

nope

**Comment by priyankarpal** [comment]
It appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

Thank you for your understanding.
