### ISSUE TITLE
Data: project addition by Rohan mittal - image editor

### ISSUE THREAD

**Issue by rohanmittal1163** [priyankarpal/ProjectsHut#1572]
### Add a new project to the list

Add a new project to the list
@priyankarpal
I want to add a image editor in the list that will create a seamless ui experience for the users.
it will have variety of options including brightness, saturation, contrast, blur, sepia, rotaet(left,right),inversion,grayscale etc.
I have not seen a porject like this in your github repo.

#screenshorts
![image](https://github.com/priyankarpal/ProjectsHut/assets/97821844/9bbf088d-8327-4255-9acf-4a82a20f2e80)

pls assign this issue under GSSOC'23 as its contributor to contributein your github repo
thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@rohanmittal1163 
We are not providing any labels for project additions as they are not associated with solving any issues.

**Comment by priyankarpal** [comment]
It appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue.

Thank you for your understanding.
