### ISSUE TITLE
Feat: improve SEO

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1575]
### What feature?

here we need to improve the SEO. 

### Add screenshots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by biplavmz** [comment]
here we can use server side rendering(ssr) or React Server Components in Next js

**Comment by parasss19** [comment]
Hey @priyankarpal I will work on this issue as I will add proper meta tags to improve the SEO score of the website

**Comment by priyankarpal** [comment]
> here we can use server side rendering(ssr) or React Server Components in Next js

yeah do you want to work on it?

**Comment by priyankarpal** [comment]
> Hey @priyankarpal I will work on this issue as I will add proper meta tags to improve the SEO score of the website

assigned to you @parasss19
