### ISSUE TITLE
📙doc: Add prerequisite in the readme file

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#158]
- Add prerequisite after the `How to contribute section?`

![Screenshot from 2023-04-09 21-48-38](https://user-images.githubusercontent.com/88102392/230784601-a33fcfc2-de65-44be-9272-ab15bf377bb8.png)

### points
  1. Make sure you installed `NodeJs` in your system.
  2. Also, you have installed `pnpm`

**Comment by Jatan88** [comment]
I want to work on this issue, can you please assign it to me?

**Comment by priyankarpal** [comment]
> I want to work on this issue, can you please assign it to me?

You can work on it 🤝

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Jatan88** [comment]
Thank you for providing this opportunity and looking forward to contributing more.
