### ISSUE TITLE
Data: project addition by Siddhant Patil : StichHub

### ISSUE THREAD

**Issue by Siddhant-Patil0203** [priyankarpal/ProjectsHut#1581]
### Add a new project to the list

# Project Description
<p align="left"><img src="https://user-images.githubusercontent.com/77800620/217613866-35741ca4-a2a2-4d19-a0ad-5315a5e5a02a.png" alt="Stichhub Logo" width="100px" height="100px" align="center"/> </p>

We bridge the physical gap between a tailor and the customers through our platform. <br> Providing customers a choice of tailors and the tailors with an increased reach for customers.

- Checkout this [Video](https://youtu.be/dE3RYo23eSY) for the Glimpses of StichHub
- This [blog post](https://medium.com/@sidd0203/stichhub-38d01da27f37) provides a comprehensive look at the project's implementation and in-depth insights.
- Project Landing Page : 
![image](https://github.com/priyankarpal/ProjectsHut/assets/77800620/a1b9d639-7434-46be-bc3c-de986dca7bd9)

## Tech Stack : 
- MERN 
- AR
- Threejs
- TailwindCSS

## Links : 
- **GitHub**: https://github.com/UBA-GCOEN/StichHub
- **Web Application**: https://stichhub.vercel.app or https://uba-gcoen.com

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
