### ISSUE TITLE
Bug: on scroll search result changes 

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1585]
### What happened?

after searching for keyword like book we are getting 3 results but when we scroll down we are getting lot's of different results which is not related to my keyword 

### Add screenshots

<img width="875" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/68702055/521dd06a-b57b-44e9-99f2-8211651cd87e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
