### ISSUE TITLE
fix: change the button style 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#159]
- In the main page we need to change the button style & also need to change the button hover colour
- add an arrow icon 

![image](https://user-images.githubusercontent.com/88102392/230789503-ae786df0-824b-4ca1-bbe9-aa9736f6516b.png)

**Comment by Bharadwajshivam28** [comment]
@priyankarpal I want to work on it ??please assign to me

**Comment by Bharadwajshivam28** [comment]
which style of button you want please suggest some

**Comment by Bharadwajshivam28** [comment]
and what is the meaning of arrow icon adding where to add it

**Comment by priyankarpal** [comment]
check the image you can change the color to white if it looks good then continue or try another color. And add arrow like this 

![image](https://user-images.githubusercontent.com/88102392/230789903-809f986a-bec4-4a07-9ff6-4226fbcf8a6a.png)

**Comment by Bharadwajshivam28** [comment]
ok thanks

**Comment by Bharadwajshivam28** [comment]
@priyankarpal 

 While making push i am facing this issue please help me??
![Screenshot from 2023-04-10 01-15-04](https://user-images.githubusercontent.com/108119109/230793668-e486e3a0-236a-464b-bbb9-750ff96c4ac9.png)

**Comment by Bharadwajshivam28** [comment]
I have done the task but facing issue in pushing it kindly  help

**Comment by priyankarpal** [comment]
> @priyankarpal
> 
> While making push i am facing this issue please help me?? ![Screenshot from 2023-04-10 01-15-04](https://user-images.githubusercontent.com/108119109/230793668-e486e3a0-236a-464b-bbb9-750ff96c4ac9.png)

just sun the command to format files. `pnpm format`

**Comment by Bharadwajshivam28** [comment]
> > @priyankarpal
> > 
> > While making push i am facing this issue please help me?? ![Screenshot from 2023-04-10 01-15-04](https://user-images.githubusercontent.com/108119109/230793668-e486e3a0-236a-464b-bbb9-750ff96c4ac9.png)
> 
> just sun the command to format files. `pnpm format`

Please elaborate didn't understood

**Comment by priyankarpal** [comment]
sorry for the typo. just run the command `pnpm format`

**Comment by Bharadwajshivam28** [comment]
> 
> 
> sorry for the typo. just run the command `pnpm format`

Thanks 👍

**Comment by RahulRana701** [comment]
hi @priyankarpal is someone still working on this issue. if not I would like to work on this..

**Comment by priyankarpal** [comment]
> hi @priyankarpal is someone still working on this issue. if not I would like to work on this..

@Bharadwajshivam28 are you working on this issue ?

**Comment by Bharadwajshivam28** [comment]
yes i am @priyankarpal

**Comment by Bharadwajshivam28** [comment]
i have crreated an pr but that was closed by you due to some reasons

**Comment by Bharadwajshivam28** [comment]
will make a pr by today

**Comment by priyankarpal** [comment]
> will make a pr by today

sounds good 🎉

**Comment by priyankarpal** [comment]
> hi @priyankarpal is someone still working on this issue. if not I would like to work on this..

you can check another issue

**Comment by Bharadwajshivam28** [comment]
> > i have crreated an pr but that was closed by you due to some reasons
> 
> oh! yeah I remembered just creating another one. cry I mentioned some topics there.

yes sir

**Comment by Bharadwajshivam28** [comment]
sir how can i dm you on twitter i need some serious guidnace

**Comment by Bharadwajshivam28** [comment]
i follow you but my message cant reach

**Comment by priyankarpal** [comment]
> > > i have crreated an pr but that was closed by you due to some reasons
> > 
> > 
> > oh! yeah I remembered just creating another one. cry I mentioned some topics there.
> 
> yes sir

you mean bro 😂

**Comment by priyankarpal** [comment]
> i follow you but my message cant reach

bugs I think

**Comment by RahulRana701** [comment]
Can I work on this issue..

**Comment by priyankarpal** [comment]
> Can I work on this issue..

@Bharadwajshivam28 working on this issue. you can check others

**Comment by Bharadwajshivam28** [comment]
> > > > i have crreated an pr but that was closed by you due to some reasons
> > > 
> > > 
> > > oh! yeah I remembered just creating another one. cry I mentioned some topics there.
> > 
> > 
> > yes sir
> 
> you mean bro joy

no sir i meant sir

**Comment by RahulRana701** [comment]
@priyankarpal Np

**Comment by Bharadwajshivam28** [comment]
can you grant me permission to send message in your dm

**Comment by Bharadwajshivam28** [comment]
without granting i CANT DM YOUR SIR

**Comment by priyankarpal** [comment]
> can you grant me permission to send message in your dm

everyone can msg me. but why you can't do it?

**Comment by RahulRana701** [comment]
hey @priyankarpal I am new to open source , my tech stack inclueds full stack web development, can you suggest me some projects to contribute in the field of web development.....

**Comment by Bharadwajshivam28** [comment]
can you text me hi sir can i drop my id?

**Comment by Bharadwajshivam28** [comment]
i am not able to

**Comment by priyankarpal** [comment]
> can you text me hi sir can i drop my id?

ok ok

**Comment by priyankarpal** [comment]
send here

**Comment by Bharadwajshivam28** [comment]
thannks alot sir my id is - CodeItShivam

**Comment by RahulRana701** [comment]
@priyankarpal can you suggest me some projects to contribute in the field of web development

**Comment by priyankarpal** [comment]
> @priyankarpal can you suggest me some projects to contribute in the field of web development

check it https://github.com/stars/priyankarpal/lists/open-source-projects

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Bharadwajshivam28** [comment]
> Completed. Thanks for your contributions 🎉 ❤️

THANKS sir ☺️
