### ISSUE TITLE
Feat: Add color theme

### ISSUE THREAD

**Issue by BhartiNagpure** [priyankarpal/ProjectsHut#1592]
### What feature?

I would like add theme button and on click that button it gives different color to choose  and after clicking one of color it shows that theme.
Like now the project has purple color theme if user choose green color wherever purple color occur it change into green it gives beautiful look to project.

### Add screenshots

![Screenshot 2023-07-05 225821](https://github.com/priyankarpal/ProjectsHut/assets/104631882/afee65ff-9496-40d6-a7fb-f9809a78eafc)

Like this !

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently, we've decided to maintain a single theme color (black). so far we don't want to add multiple theme colors.

**Comment by BhartiNagpure** [comment]
> currently, we've decided to maintain a single theme color (black). so far we don't want to add multiple theme colors.

No you didn't get my concept  website will be in black theme only think that wherever you provide purple color  only that color will be change in colir selected by user.

**Comment by priyankarpal** [comment]
> > currently, we've decided to maintain a single theme color (black). so far we don't want to add multiple theme colors.
> 
> No you didn't get my concept website will be in black theme only thing is that wherever you provide purple color only that color will be change in color selected by user so its give new look to website.

yeah I understood but our theme colours are black & purple & we don't want to change
