### ISSUE TITLE
Data: project addition by Suraj Pratap : CoinMeter

### ISSUE THREAD

**Issue by SurajPratap10** [priyankarpal/ProjectsHut#1594]
### Add a new project to the list

*CoinMeter* is a completely responsive and functional real-time Cryptocurrency data fetching app. This app gives you the facility to analyze the top cryptocurrencies across the world and see their real-time market cap and exchanges with the help of a properly designed historical chart for each coin with a clean UI experience.It also has a trending section where the last 24 hours profitable coins are shown.

**MockUp:**
![image](https://github.com/priyankarpal/ProjectsHut/assets/92919173/60384bd1-3916-4b57-810d-001b5adec328)

**Technologies Used:**
- React JS
- Material UI
- Chart JS
- Context API
- Coingecko API

**Links:**
- GitHub: https://github.com/SurajPratap10/CoinMeter_Project6
- Live Site: https://coin-meter-react-js.netlify.app/

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by SurajPratap10** [comment]
> assigned to you

Thanks, do assign the `gssoc` label when completed

**Comment by priyankarpal** [comment]
> > assigned to you
> 
> Thanks, do assign the `gssoc` label when completed

previously we've added but currently, We are not providing any labels(according to gssoc23 rules) for project additions as they are not associated with solving any issues.
