### ISSUE TITLE
fix: remove hover effect from the card & cursor pointer

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#160]
- Remove the hover effect from the projects card & github link button also remove the cursor pointer from only the card.
- Cursor pointer will be only on the github link button.

https://user-images.githubusercontent.com/88102392/230790268-fc17c2fe-1ab1-44f1-8f0e-c201938cc736.mp4

**Comment by Bharadwajshivam28** [comment]
@priyankarpal Please assign to me i have knowledge of it

**Comment by priyankarpal** [comment]
> @priyankarpal Please assign to me i have knowledge of it

/
sounds good 🎉

**Comment by Bharadwajshivam28** [comment]
> > @priyankarpal Please assign to me i have knowledge of it
> 
> 
> sounds good 🎉

Thanks

**Comment by priyankarpal** [comment]
ok so I did it in the recent update you can work on other issues.

**Comment by Bharadwajshivam28** [comment]
> ok so I did it in the recent update you can work on other issues.

Okay
