### ISSUE TITLE
feat: 3D design to the homepage cover

### ISSUE THREAD

**Issue by Piyusharora2003** [priyankarpal/ProjectsHut#1607]
### What feature?

The home page of the site is having a few images which are placed normally. I would like to add 3D effect to the images and better Ui to give enhancing look to the website cover page.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/74443858/3e043283-8892-48f8-b33d-00106291505f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you show a demo? also, we are thinking to add 3d design later.

**Comment by Piyusharora2003** [comment]
yeah sure ! 
I did work on it and here is what i come up with 

https://github.com/priyankarpal/ProjectsHut/assets/74443858/749fd291-dda8-4184-8cea-76a6db56912e

Also with i would be working with some hovering effect 

Note : This is just a demo

**Comment by priyankarpal** [comment]
> yeah sure ! I did work on it and here is what i come up with
> 
>  WhatsApp.Video.2023-07-07.at.23.36.13.mp4 
> Also with i would be working with some hovering effect
> 
> Note : This is just a demo

I think it's just changing the positions & there is no 3d design.
