### ISSUE TITLE
fix: remove extra padding/margin from both side for mobile view in the projects section

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#161]
- remove extra padding/margin from both sides for mobile view in the projects section
- also fix the navbar logo(just using the text) position to the right side a little bit

![Screenshot from 2023-04-10 00-07-13](https://user-images.githubusercontent.com/88102392/230790672-5284b3e7-9eb3-498c-aacc-b9408278e3c3.png)

**Comment by SanketKumarLaha** [comment]
I want to work on this issue, can you please assign it to me?

**Comment by priyankarpal** [comment]
> I want to work on this issue, can you please assign it to me?

You can work on it 🤝

**Comment by SanketKumarLaha** [comment]
Thanks

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
