### ISSUE TITLE
 feat: Adding no matches found feature in search button.

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1610]
### What feature?

In the projects section, When the user tries to search for the option which is not present in the website , he or she gets the result as "No matches found"  below the search bar.

### Add screenshots

Right now it shows nothing when there is no such project.
![Screenshot (42)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/2924d9a0-cd0b-454e-a422-1e853c4cee19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, we need to show text message `nothing found` like this.
