### ISSUE TITLE
feat:Adding hover effect in the projects section.

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1611]
### What feature?

We can add hover effect in the projects section so that when the user hovers over the projects, he or she can see a box shadow with some glow. The purpose of the issue is to enhance the overall UI of the website.
Also we can give in some extra padding between the projects so they have some space in between them. Right now they look a bit conjested.

### Add screenshots

As you can see there is no proper clarity and space in between the projects column
![Screenshot (43)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/d116ef49-d267-41e7-bb99-eec4372a9fa0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we need to add a hover border(color `primary`) for the project card.

**Comment by priyankarpal** [comment]
@Illaf we have assigned you to a few issues so we're unable to assign you to this issue now. so you need to work on those issues first.

**Comment by Illaf** [comment]
@priyankarpal Okay I'll complete them soon

**Comment by Illaf** [comment]
@priyankarpal please assign this issue to me

**Comment by priyankarpal** [comment]
I've fixed 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/1881fef7-1d86-4f37-b186-c5289c2c1148)
