### ISSUE TITLE
feat: Adding step numbers in docs section

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1612]
### What feature?

The docs section consists of steps to follow but there are no step numbers assigned. It would be more understandable for the contributor if we number the steps. Also The page can be made more representable by improving the designing.

### Add screenshots

![Screenshot (44)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/6240ba18-5cea-43db-98cb-3750d422c884)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we're working on the docs page so currently we don't need to change anything right now
