### ISSUE TITLE
Bug: css issue card Text alignment is not proper

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1613]
### What happened?

align Text is not proper when content is less

### Add screenshots

<img width="859" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/68702055/c0b41ba9-a914-46c1-9945-88f3d89121d7">

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah, we need to fix it. assigned to you

**Comment by biplavmz** [comment]
Hii @priyankarpal can please  you add GSSoC'23 tag
