### ISSUE TITLE
Add gym website 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [priyankarpal/ProjectsHut#1617]
### Add a new project to the list

I want to add gym using HTML CSS javascript
Can you please assign me this task under GSSOC'23 contribution @pri

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Kalivarapubindusree We are not providing any labels for project additions as they are not associated with solving any issues.

**Comment by Kalivarapubindusree** [comment]
@priyankarpal will you consider and give marks if I do pr for this ??

**Comment by priyankarpal** [comment]
> @priyankarpal will you consider and give marks if I do pr for this ??

nope

**Comment by priyankarpal** [comment]
there are no updates so I'm closing this issue
