### ISSUE TITLE
Improving the NavBar

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#162]
I want to Improve the Navbar by adding more sections like Home, Contact us, About, team etc....If it is Valueable then kindly assign it to me

![Screenshot from 2023-04-10 01-33-19](https://user-images.githubusercontent.com/108119109/230794534-3bc2e49a-a672-45c9-90b1-633c3c066911.png)

**Comment by priyankarpal** [comment]
> I want to Improve the Navbar by adding more sections like Home, Contact us, About, team etc....If it is Valueable then kindly assign it to me
> 
> ![Screenshot from 2023-04-10 01-33-19](https://user-images.githubusercontent.com/108119109/230794534-3bc2e49a-a672-45c9-90b1-633c3c066911.png)

yeah, but on the website, there is only two pages homepage & projects page. Previously there is a home button we removed it now the home button works working logo. 

So I think you don't need to add these links.

**Comment by Bharadwajshivam28** [comment]
> > I want to Improve the Navbar by adding more sections like Home, Contact us, About, team etc....If it is Valueable then kindly assign it to me
> > 
> > ![Screenshot from 2023-04-10 01-33-19](https://user-images.githubusercontent.com/108119109/230794534-3bc2e49a-a672-45c9-90b1-633c3c066911.png)
> 
> yeah, but on the website, there is only two pages homepage & projects page. Previously there is a home button we removed it now the home button works working logo. 
> 
> So I think you don't need to add these links. 

Ok
