### ISSUE TITLE
feat: add sort by feature

### ISSUE THREAD

**Issue by kartikjoshi267** [priyankarpal/ProjectsHut#1628]
### What feature?

Till now the projects are displayed randomly but if a user wants to sort the projects A-Z or Z-A, they cannot do that. So, I want to add a sort by feature.

### Add screenshots

_N/A_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
currently, we don't need it.
