### ISSUE TITLE
docs: adding dynamic gssoc banner 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1631]
### what's wrong with the documentation?

- The GSSOC Banner image is on low quality so that the image is showed as very small is size on monitors with high resolution.
- And also the image is not dynamic, meaning the image is not changed according to Dark/Light Theme of Github

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/19d9a004-f5b2-42a0-a132-265670b04675)

## Changes i want to make

| DESIRED STATE IN LIGHT THEME | DESIRED STATE IN DARK THEME |
|  :-----:   | :-----:  |
| ![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/79446834-60ae-4394-b743-ae4e782c134e) | ![](https://user-images.githubusercontent.com/63473496/213306279-338f7ce9-9a9f-4427-8c2a-3e344874498f.png) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
ok. assigned to you.
