### ISSUE TITLE
feat: Adding Newsletter Feature Connected to Hashnode for Project Hut

### ISSUE THREAD

**Issue by Nishitbaria** [priyankarpal/ProjectsHut#1632]
### What feature?

1. Integration with Hashnode: I will develop such a functionality ,that when user submits email in your website,they will recive email from your hashnode newslettter,where you can show blogs of projects,latest open source projects.
2. User Subscription: Implement a subscription form for users to opt-in to receive updates about new projects via email.
3. Newsletter Management: Develop a secure backend system to manage subscriptions and handle user data.
4. Newsletter Template: Design an appealing template showcasing project names, descriptions, and links.
5. Automation and Scheduling: Set up automated processes to fetch projects periodically and schedule newsletter delivery.
6. Personalization: Explore options for personalizing newsletter content based on users' interests.
7. Opt-out and Privacy: Include an opt-out option and ensure compliance with data protection regulations.

I believe this newsletter feature will enhance user experience, attract and retain users, and foster collaboration within the Project Hut community.
I am excited to collaborate seamlessly integrate this feature. 
@priyankarpal ,please assign me this issue

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/85815172/df1cc601-e380-41be-8631-86f2b226beac)
This is an example

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
but we're not publishing any newsletters. so why should we add the feature?

**Comment by Nishitbaria** [comment]
@priyankarpal ,You can update your audience with your latest open source projects and about updates of Project Hut and any future events on Projecthut in thier email .

**Comment by priyankarpal** [comment]
> @priyankarpal ,You can update your audience with your latest open source projects and about updates of Project Hut and any future events on Projecthut in thier email .

yeah, I understood but the main point is currently we're not publishing any newsletter for projectshut. In future if we need to add we will raise an issue.
