### ISSUE TITLE
Bug: getting server error while redirecting to event page 

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1633]
### What happened?

whene on click on all event button getting server error. using npm to start the server 

### Add screenshots

<img width="712" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/68702055/cb896b54-52a8-4d33-a50f-011f13f4b3e5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
event page? but we haven't added it. @biplavmz

**Comment by biplavmz** [comment]
Hii @priyankarpal can you please close the bug by mistakenly. I have raise this bug

**Comment by priyankarpal** [comment]
> Hii @priyankarpal can you please close the bug by mistakenly. I have raise this bug

I'm deleting the issue
