### ISSUE TITLE
style: modify the colour of active links in the navigation bar

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1635]
### What feature?

Using Tailwind CSS, modify the colour of active links in the navigation bar to `primary`.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/cc5c4438-3144-47ef-8f6c-f14ce4d6dbfc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by saakshiraut28** [comment]
Hey @priyankarpal, I would like to work on this issue.

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, I would like to work on this issue.

sure assigned to you.
