### ISSUE TITLE
feat:Redesigning the project authors page

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1639]
### What feature?

There is a lot of scope for improvement in the projects author page which opens up with more button in the projects section.
If you give a chance then I will style it differently so that it looks unique and attractive.

### Add screenshots

![Screenshot (54)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/a21cba41-c8d2-4fa7-8e53-0a48f250bbdd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are working on a new feature `fetch data from github API #1562` & also, we are adding a few thigs. after that if need any things we will raise the issue
