### ISSUE TITLE
Giving a Box/Button

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#164]
Same like fork repository we can also give a box/button to Documentation.. currently it is not much attractive ...Please assign it is valueable...
![Screenshot from 2023-04-10 01-49-44](https://user-images.githubusercontent.com/108119109/230794781-0faa1005-df82-4731-998e-ce20538c0940.png)

**Comment by priyankarpal** [comment]
> Same like fork repository we can also give a box/button to Documentation.. currently it is not much attractive ...Please assign it is valueable... ![Screenshot from 2023-04-10 01-49-44](https://user-images.githubusercontent.com/108119109/230794781-0faa1005-df82-4731-998e-ce20538c0940.png)

Will it look good?

**Comment by Bharadwajshivam28** [comment]
> > Same like fork repository we can also give a box/button to Documentation.. currently it is not much attractive ...Please assign it is valueable... ![Screenshot from 2023-04-10 01-49-44](https://user-images.githubusercontent.com/108119109/230794781-0faa1005-df82-4731-998e-ce20538c0940.png)
> 
> Will it look good?

Yes it will ...let's try one time and i will drop the ss of changes

**Comment by priyankarpal** [comment]
> > > Same like fork repository we can also give a box/button to Documentation.. currently it is not much attractive ...Please assign it is valueable... ![Screenshot from 2023-04-10 01-49-44](https://user-images.githubusercontent.com/108119109/230794781-0faa1005-df82-4731-998e-ce20538c0940.png)
> > 
> > 
> > Will it look good?
> 
> Yes it will ...let's try one time and i will drop the ss of changes

sounds good 🎉

**Comment by Bharadwajshivam28** [comment]
> > > > Same like fork repository we can also give a box/button to Documentation.. currently it is not much attractive ...Please assign it is valueable... ![Screenshot from 2023-04-10 01-49-44](https://user-images.githubusercontent.com/108119109/230794781-0faa1005-df82-4731-998e-ce20538c0940.png)
> > > 
> > > 
> > > Will it look good?
> > 
> > Yes it will ...let's try one time and i will drop the ss of changes
> 
> sounds good 🎉

Thanks

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Bharadwajshivam28** [comment]
welcome
