### ISSUE TITLE
feat: Adding animation features in the front page

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1643]
### What feature?

I have shown an example below in order to explain how can we add this feature and even more to this website. This gives a dynamic look and  user friendly experience to the visitors. I addition, it also makes the website impressive.

### Add screenshots

@priyankarpal I would like you to check this out

https://github.com/priyankarpal/ProjectsHut/assets/114517448/58adef59-1a7e-4e9c-ba9b-ef0f6d8f6e64

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
if we add the animation it will change the UI looks. so currently we don't need to change this.
