### ISSUE TITLE
feat: Not Found Page

### ISSUE THREAD

**Issue by PriyansuMaurya** [priyankarpal/ProjectsHut#1645]
### What feature?

I would like to add a custom not found page.

### Add screenshots

Previous Version

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/6f653222-835b-444c-9388-fabb76c6f78a)

Proposed

![image 38](https://github.com/priyankarpal/ProjectsHut/assets/101447544/c6abf413-d867-4ccc-808c-79eb1d55caad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah it's great to show a custom 404 page for no link 
assigned to you
