### ISSUE TITLE
feat: improve footer

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1646]
### What feature?

we need to improve the footer.

will add all details later. 

### Add screenshots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by lalitkumawat1m** [comment]
Hey @priyankarpal,
I want to work on this issue as a GSSoC'23 contributor.

**Comment by priyankarpal** [comment]
completed
