### ISSUE TITLE
Bug: clear button  should be disable when there is no filter tags applied or search input is empty

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1654]
### What happened?

while clicking on close or clear button every time data get changes without applying any filter or search.

### Add screenshots

<img width="596" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/68702055/5d1024d3-2162-48bd-9991-d71c27af3b3d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
good catch @biplavmz 👏🏻
