### ISSUE TITLE
feat: Improve Search bar UI of Landing page

### ISSUE THREAD

**Issue by Geeta259** [priyankarpal/ProjectsHut#1657]
### What feature?

Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Add some border radius and increase width

here is demo:
![Screenshot (540)](https://github.com/priyankarpal/ProjectsHut/assets/75520947/b22b5f4b-56ad-4052-8f89-58489922cb9d)
@priyankarpal I would like to contribute on this project under GSSOC'23

### Add screenshots

![Screenshot (565)](https://github.com/priyankarpal/ProjectsHut/assets/75520947/26b0884e-ba43-42cc-bc9a-68e5990f010c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it's ok we don't need to change anything. If we add border-radius it will change the look.
