### ISSUE TITLE
docs: remove unwanted texts

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1660]
### what's wrong with the documentation?

remove the unwanted lines from contributing.md file.

> if you're a `GSSoC23` contributor please mention 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/52599f5b-52ef-4ccc-9069-5578af6f00a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Ijaiswalshivam** [comment]
can you please assign it to me?

**Comment by Ijaiswalshivam** [comment]
can you please brief that what i have to remove, as everything looking fine.
