### ISSUE TITLE
Bug: Layout is not used efficiently 

### ISSUE THREAD

**Issue by PriyansuMaurya** [priyankarpal/ProjectsHut#1667]
### What happened?

We don't need to include the `<Navbar/>` and `<Footer/>` components in every page. We can simply place them in `layout.tsx`, and they will be present on every page. No need to use it in every page.

### Add screenshots

this is how the code will look like after changes 

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/c3931caf-5190-4c98-9ea4-bb3b94c010b4)

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/d4655a69-c152-4d29-9951-a2e29924fe6a)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
good spot 👏🏻 @PriyansuMaurya 
yeah we just need to add to the layout file.

assigned to you
