### ISSUE TITLE
InfiniteScroll not working when applying filter

### ISSUE THREAD

**Issue by biplavmz** [priyankarpal/ProjectsHut#1668]
### What happened?

while applying  it show all related profile card data. It should show 15 profile card after that when scrolling it should show more remaining profile card data and so on.

### Add screenshots

<img width="868" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/68702055/a7b08a16-22ad-4830-bf86-e599df2c5bf3">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Hi, @biplavmz could you share a preview video about the problem?

**Comment by priyankarpal** [comment]
there are no updates so I think we need to close this issue.
