### ISSUE TITLE
Bug: Github link should open in new tab 

### ISSUE THREAD

**Issue by PriyansuMaurya** [priyankarpal/ProjectsHut#1670]
### What happened?

If you click on the GitHub tab, it opens in the current tab only. It would be great if it opens in a new tab.  

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/0b91c1d3-7a91-4e00-aa65-1b173534ae48)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we can do it. @PriyansuMaurya

**Comment by sajdakabir** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by priyankarpal** [comment]
> I would like to work on this issue. Can you assign it to me?

I have assigned @PriyansuMaurya for this issue.

**Comment by Sahilll15** [comment]
Can it be assigned to me !!

**Comment by PriyansuMaurya** [comment]
@priyankarpal Let him do, If he is interested.

**Comment by priyankarpal** [comment]
> @priyankarpal Let him do, If he is interested.

ok sure

**Comment by priyankarpal** [comment]
> Can it be assigned to me !!

you can work on it.

**Comment by Sahilll15** [comment]
@priyankarpal please review it!!
