### ISSUE TITLE
feat: Adding contact links in the footer

### ISSUE THREAD

**Issue by Illaf** [priyankarpal/ProjectsHut#1676]
### What feature?

We can add the social media links and some more information about the org in the footer.Also The footer has a light slate background with white text on it which makes it barely visible to read. We can change the font color of the text or plan a new footer. If you agree then I can make a new design for the footer

### Add screenshots

![Screenshot (57)](https://github.com/priyankarpal/ProjectsHut/assets/114517448/2714464b-dd10-4803-8b8c-5260178528bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we removed light mode theme from footer & also, we are working footer improvement feature. https://github.com/priyankarpal/ProjectsHut/issues/1646
