### ISSUE TITLE
feat: Add GitHub icon in the Footer

### ISSUE THREAD

**Issue by blindaks** [priyankarpal/ProjectsHut#1680]
### What feature?

I want to add a GitHub link in the footer section to make it more accessible.

### Add screenshots

![Screenshot (54)](https://github.com/priyankarpal/ProjectsHut/assets/128223364/2e038b4e-2352-4761-a3b5-ecba6fc96c01)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we are on new footer adding feature so currently we don't need
