### ISSUE TITLE
docs: Update readme

### ISSUE THREAD

**Issue by Shikhar9425** [priyankarpal/ProjectsHut#1695]
### what's wrong with the documentation?

Wants to add some more features and wants to make readme more impressive

### Add screenshots

Wants to add some more features and wants to make readme more impressive

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Hi, I think we already have a well & clear README file so we don't need to change
