### ISSUE TITLE
feat: Add scroll to top button

### ISSUE THREAD

**Issue by sumitkr2000** [priyankarpal/ProjectsHut#1696]
### What feature?

Hey, @priyankarpal I want to add scroll to top button to your website. Please assign me this issue. Thank you!

### Add screenshots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yup we need to add. assigned to you
