### ISSUE TITLE
🐞Bug: Product Cards are too wide to read at big screen size

### ISSUE THREAD

**Issue by SteveSayantan** [priyankarpal/ProjectsHut#170]
**Describe the bug**
The product cards grow extensively for large screen size, which hampers the user experience. 

**To Reproduce**

1. Open 'Chrome Devtools'
2. Click on 'Responsive Mode'
3. Expand the screen

**Expected behavior**
The cards and the card container should have a maximum width.

**Screenshots**
![CaptureProjectHub](https://user-images.githubusercontent.com/92118155/230898451-3b67047c-bc48-438b-a6b9-d7ef1ad6b454.JPG)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by priyankarpal** [comment]
> **Describe the bug** The product cards grow extensively for large screen size, which hampers the user experience.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open 'Chrome Devtools'
> 2. Click on 'Responsive Mode'
> 3. Expand the screen
> 
> **Expected behavior** The cards and the card container should have a maximum width.
> 
> **Screenshots** ![CaptureProjectHub](https://user-images.githubusercontent.com/92118155/230898451-3b67047c-bc48-438b-a6b9-d7ef1ad6b454.JPG)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser: Chrome

what would be the solution?
- do we need to add 4 cards in a row?
- need to add a small size?

**Comment by SteveSayantan** [comment]
I would like to fix it, could you assign this to me?

**Comment by priyankarpal** [comment]
> I would like to fix it, could you assign this to me?

yeah sure work on it.

**Comment by SteveSayantan** [comment]
> 



> > **Describe the bug** The product cards grow extensively for large screen size, which hampers the user experience.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Open 'Chrome Devtools'
> > 2. Click on 'Responsive Mode'
> > 3. Expand the screen
> > 
> > **Expected behavior** The cards and the card container should have a maximum width.
> > **Screenshots** ![CaptureProjectHub](https://user-images.githubusercontent.com/92118155/230898451-3b67047c-bc48-438b-a6b9-d7ef1ad6b454.JPG)
> > **Desktop (please complete the following information):**
> > 
> > * OS: Windows
> > * Browser: Chrome
> 
> what would be the solution?
> 
> * do we need to add 4 cards in a row?
> * need to add a small size?

The cards container should have a certain max width, beyond which the container would not grow, thereby maintaining the width of each card.

**Comment by priyankarpal** [comment]
> > 
> 
> > > **Describe the bug** The product cards grow extensively for large screen size, which hampers the user experience.
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Open 'Chrome Devtools'
> > > 2. Click on 'Responsive Mode'
> > > 3. Expand the screen
> > > 
> > > **Expected behavior** The cards and the card container should have a maximum width.
> > > **Screenshots** ![CaptureProjectHub](https://user-images.githubusercontent.com/92118155/230898451-3b67047c-bc48-438b-a6b9-d7ef1ad6b454.JPG)
> > > **Desktop (please complete the following information):**
> > > 
> > > * OS: Windows
> > > * Browser: Chrome
> > 
> > 
> > what would be the solution?
> > 
> > * do we need to add 4 cards in a row?
> > * need to add a small size?
> 
> The cards container should have a certain max width, beyond which the container would not grow, thereby maintaining the width of each card.

sounds good 🎉

**Comment by SteveSayantan** [comment]
Take a look at  #174 , let me know if it needs any modification

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
