### ISSUE TITLE
feat: The project card should also have an link to the website

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1700]
### What feature?

Adding an section inside an card for the deployed link of the project.

### Add screenshots

![Screenshot 2023-07-15 at 1 02 16 AM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/d448864e-3726-4130-8bfd-281213bd2c8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we can do it but lots of projects don't have any deployment link. Also, after backend addition there will be an option for adding live link @Sahilll15

**Comment by Sahilll15** [comment]
okay
