### ISSUE TITLE
feat:Direct Project addtion

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1703]
### What feature?

rather then making the task to tidious lets make it direct add an form that can add the data durectlt to the project.json file

### Add screenshots

no screenshots

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we started working on backend part & we will add soon.

**Comment by Sahilll15** [comment]
> yeah we started working on backend part & we will add soon. #1070

can i join you all to ??

**Comment by Sahilll15** [comment]
It will be my pleasure to work with you!!

**Comment by priyankarpal** [comment]
we will add soon after you can check

**Comment by Sahilll15** [comment]
okay!!
