### ISSUE TITLE
Bug: Specify the link type by adding an attribute `rel="noopener noreferrer"`

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#1711]
### What happened?

bug: **External links without noopener/noreferrer are a potential security risk**

solution:

- add `rel="noopener noreferrer"` to these lines https://github.com/priyankarpal/ProjectsHut/blob/b33472820ebf8bec73168bc4197761e930c6802d/components/Footer.tsx#L129
- also, add the same code to this line https://github.com/priyankarpal/ProjectsHut/blob/b33472820ebf8bec73168bc4197761e930c6802d/components/Footer.tsx#L111

### Add screenshots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by suzy-g38** [comment]
I would like to work on it

**Comment by priyankarpal** [comment]
> I would like to work on it

sure
