### ISSUE TITLE
Bug: Mobile Mode Some Text is not visible 

### ISSUE THREAD

**Issue by crocmons** [priyankarpal/ProjectsHut#1718]
### What happened?

In Mobile Mode also in desktop mode, Some Text is not visible I want to make it visible...Could you assign this issue to me as a GSSOC23 contributor?

### Add screenshots

![Screenshot (499)](https://github.com/priyankarpal/ProjectsHut/assets/106610322/eb108c62-501b-4603-9368-fd829fcfb2d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hey @crocmons but I'm not facing any issue.

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/282a7f9c-3c13-4b4b-b473-069d2e65fa81)

**Comment by priyankarpal** [comment]
@crocmons I got the problem. we are facing when we are using light mode. just we need to set the default text color to white for dark or light mode(footer bg is black).  

assigned to you
