### ISSUE TITLE
feat: Add Theme Component for Toggling light/dark mode

### ISSUE THREAD

**Issue by crocmons** [priyankarpal/ProjectsHut#1719]
### What feature?

Want to add a Theme Component for Toggling light/dark mode in Next.js 13 ...Could you assign this issue to me as a GSSOC23 contributor? I want to make it this way when users click the moon icon UI will appear in dark mode & when it is the sun icon the UI will appear in a light mode

### Add screenshots

![Screenshot (17)](https://github.com/priyankarpal/ProjectsHut/assets/106610322/4327888d-2150-4b06-b16d-db039cb2a01f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@crocmons We decided to use only the dark mode, so we removed the option to switch between dark and light modes that we had before.

**Comment by crocmons** [comment]
ok
