### ISSUE TITLE
📙 docs: Add vercel logo

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#172]
- In the README.md file just add the vercel logo![vercel logo](https://camo.githubusercontent.com/37b009b52b3a9af7886f52e75cd76d1b32fef331ab1dc2108089c0ced0b7635f/68747470733a2f2f7777772e6461746f636d732d6173736574732e636f6d2f33313034392f313631383938333239372d706f77657265642d62792d76657263656c2e737667)

- Copy the link `![vercel logo](https://camo.githubusercontent.com/37b009b52b3a9af7886f52e75cd76d1b32fef331ab1dc2108089c0ced0b7635f/68747470733a2f2f7777772e6461746f636d732d6173736574732e636f6d2f33313034392f313631383938333239372d706f77657265642d62792d76657263656c2e737667)`

- Above the License heading. 
![image](https://user-images.githubusercontent.com/88102392/230919192-44f7e857-6bed-4165-8a85-120b86b4bf30.png)

**Comment by SurajPratap10** [comment]
Assign it to me.

**Comment by priyankarpal** [comment]
> Assign it to me.

done

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
