### ISSUE TITLE
feat: Want to add Next Auth Signup Google provider in Next.js 13 

### ISSUE THREAD

**Issue by crocmons** [priyankarpal/ProjectsHut#1720]
### What feature?

Want to add Next Auth Signup Google provider in Next.js 13 ...Could you assign this issue to me as a GSSOC23 contributor?

### Add screenshots

![Screenshot (500)](https://github.com/priyankarpal/ProjectsHut/assets/106610322/e1f007ad-63e0-4bf0-a9fc-640351207fd1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hi, @crocmons we have started working on backend part & we will add only github auth to fetch data.

**Comment by crocmons** [comment]
yeah, sure I can work also GitHub auth to fetch data. @priyankarpal

**Comment by priyankarpal** [comment]
> yeah, sure I can work also GitHub auth to fetch data. @priyankarpal

someone is working on it.

**Comment by crocmons** [comment]
> > yeah, sure I can work also GitHub auth to fetch data. @priyankarpal
> 
> someone is working on it.

ok, it's all right
