### ISSUE TITLE
feat: Adding a scroll to top button

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [priyankarpal/ProjectsHut#1723]
### What feature?

This button will allow the user to scroll to the top using a button click

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/85278243/7e2ebb93-a741-4958-8751-fddb8a0d96e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate https://github.com/priyankarpal/ProjectsHut/issues/1696
