### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ankit-0369** [priyankarpal/ProjectsHut#1727]
### What happened?

On home page footer section the link "Documentation " is not active. i.e. after hovering no color change effect observed also link has not been added.

to check the bug "just go to home page -> footer section -> hover on Documentation".

### Add screenshots

![Screenshot (183)](https://github.com/priyankarpal/ProjectsHut/assets/98079557/32368776-eb35-4d90-9d97-52306448d04b)
<img width="856" alt="Screenshot 2023-07-16 130606" src="https://github.com/priyankarpal/ProjectsHut/assets/98079557/eb026783-eb0e-47f7-8922-1147893840da">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@ankit-0369 this is not a bug. `Documentation` is just the heading not a link under the `Documentation` we have added few links & if you hover these links the color will change to `primary` color.

**Comment by ankit-0369** [comment]
Ooh silly mistake 😅 in observation @priyankarpal . I thought documentation is about Docs section.
