### ISSUE TITLE
Bug: projects section scrolling issue

### ISSUE THREAD

**Issue by 777Prabhjot** [priyankarpal/ProjectsHut#1730]
### What happened?

Projects section is not getting auto scrolled to the top as of now user have to manually scroll to top of the projects section.

**To reproduce**
1. Go to home page.
2. Then scroll down on home page
3. After that click on projects section

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/68184118/1e34a79b-71a5-41e8-badb-f3b0d2b366fd

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
good spot @777Prabhjot 👏🏻 we need to fix this.

assigned to you
