### ISSUE TITLE
feat:Adding hover effect on the links

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1732]
### What feature?

addition of the hover effect on the links will look great!!

### Add screenshots

![Screenshot 2023-07-16 at 10 32 15 PM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/9b2c8d07-3d82-4497-9830-2426f7df5b9b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we just need to add `hover:text-primary` to this line
https://github.com/priyankarpal/ProjectsHut/blob/e2ad174502ef46ee6e133c7e5147174906109126/components/Footer.tsx#L87

assigned to you
