### ISSUE TITLE
feat:Addition of Express and Firebase in the filters

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1735]
### What feature?

As an express dev i think adition of express and firebase will great

### Add screenshots

![Screenshot 2023-07-16 at 10 36 58 PM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/25332f5a-b64c-4818-8c2c-8a560a89e911)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we can add 
assigned to you
