### ISSUE TITLE
feat:change navbar text to text-bold

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1740]
### What feature?

The text of the navbar in text-bold looks better

### Add screenshots

<img width="1000" alt="Screenshot 2023-07-17 at 1 08 33 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/73483ff3-e82c-4d92-b008-1c9418d9c02f">

Text Bold:- looks better
<img width="971" alt="Screenshot 2023-07-17 at 1 08 41 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/108ef037-3617-4bc5-b1ae-93810f085082">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
i think @Sahilll15 without `font-bold` looks clear & good, so we don't need to change it.
