### ISSUE TITLE
Bug:browse projects button is not properly visible in mobile mode 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1741]
### What happened?

Its not visible in mobile mode specifically in iphone cr

### Add screenshots

![IMG_5264](https://github.com/priyankarpal/ProjectsHut/assets/109215419/4d060dd1-afb8-4445-8495-1331dafb5120)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Sahilll15 yeah we need to fix the problem.
