### ISSUE TITLE
Adding Aria-Label in Social Icons

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1743]
### What happened?

- aria-label attribute is used by screen readers to know about the crawler link, in this case the social images wrapped with a must want aria-label on footer of Homepage
- The purpose of this technique is to provide aria-label for a can be read by assistive technology. It provides the text label for an object, such as a images inside it. When a screen reader encounters the object, the aria-label text is read so that the user will know what it is.
- Peoples with vision can identify the social link, but visually impaired persons can't able to understand for the link is to used

### Add screenshots

na

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah!

assigned
