### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by ritik2358** [priyankarpal/ProjectsHut#1753]
### Add a new project to the list

Hey @priyankarpal, 
I want to add a new project in the project section. i.e, 
Automatic-Nodemailer : It is a Node.js based application that allows you to automatically respond to emails sent to your Gmail mailbox while you're away on a vacation or unavailable. This application checks for new emails in a specified Gmail ID, sends replies to emails that have no prior responses, and adds a label to the email before moving it to the labeled folder. The entire process is repeated automatically at random intervals between 45 to 120 seconds.
Tech : Node.js, GmailAPI, Express.js

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
This issue has been closed because it has not received any activity in the last few days
