### ISSUE TITLE
chore: project addition by palakkgoyal

### ISSUE THREAD

**Issue by Palakkgoyal** [priyankarpal/ProjectsHut#1756]
### Add a new project to the list

I want to add a new project to projects hut. It is a python project in which user can give their number and details of that number will be provided to the user such as country of the number, which sim it uses, timezone etc.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
This issue has been closed because it has not received any activity in the last few days
