### ISSUE TITLE
chore: project addition by Mansi

### ISSUE THREAD

**Issue by Mansi209aps** [priyankarpal/ProjectsHut#1761]
### Add a new project to the list

Please assign me this issue under GSSCO'23.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Mansi209aps We are not providing any labels for project additions as they are not associated with solving any issues.

**Comment by priyankarpal** [comment]
This issue has been closed because it has not received any activity in the last few days
