### ISSUE TITLE
Bug: Improper pointer actions on user profile page 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1762]
### What happened?

- The user's profile will have set of social links which are linked to icons, during hover some of the icons have pointing cursor some of have not that.
- This imbalance is a severe drawback in terms of User Experience.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/92252895/6e1a549f-b75b-4b26-b421-77773795150a

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by priyankarpal** [comment]
> Hey there @priyankarpal 👋🏻
> 
> Please make sure to assign this issue to me as soon possible so that i can make the work done!
> 
> Thank you.

I haven't added other links so that's why it's not working. Also, we need to fix it. 
assigned
