### ISSUE TITLE
docs: Update Readme

### ISSUE THREAD

**Issue by khushimarothi** [priyankarpal/ProjectsHut#1763]
### what's wrong with the documentation?

Want to update the contributors section so that it displays all the valuable contributors of the repo.

### Add screenshots

![Screenshot (167)](https://github.com/priyankarpal/ProjectsHut/assets/85816852/58242529-1029-4f27-8eb2-df33baf0379c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@khushimarothi we need to add a toggle option so open contributors section.

**Comment by khushimarothi** [comment]
> @khushimarothi we need to add a toggle option so open contributors section.

Sure. Something Like this.
![Screenshot (170)](https://github.com/priyankarpal/ProjectsHut/assets/85816852/dfaa1407-470d-435f-927a-8ffd61931d66)
![Screenshot (171)](https://github.com/priyankarpal/ProjectsHut/assets/85816852/8c242e8c-0c02-4a0e-8cd0-91b025918e20)

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
