### ISSUE TITLE
chore: project addition by khushi

### ISSUE THREAD

**Issue by khushimarothi** [priyankarpal/ProjectsHut#1766]
### Add a new project to the list

I want to add a Fiverr Clone project by creating a new card.
please assign under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@khushimarothi We are not providing any labels for project additions as they are not associated with solving any issues.

**Comment by khushimarothi** [comment]
Okay so I am closing this one and will create a new that will address an issue 😊
