### ISSUE TITLE
[Feat]: Improve the layout of footer section.

### ISSUE THREAD

**Issue by Mayank-Sharma17** [priyankarpal/ProjectsHut#1767]
### What feature?

- The UI of the ProjectsHut is really nice and simple.
- I think some minor changes can be made in the footer section to enhance the overall UI and symmetry of the webpage, I inspected in my browser and did some changes using dev-tools like reduced the margin and the font size of the copyright paragraph.
- I attached the screen shots, kindly review it and let me know how it looks.

### Add screenshots

Before:
![Screenshot 2023-07-19 233847](https://github.com/priyankarpal/ProjectsHut/assets/113251342/47f0dbb2-21a5-45ae-89ff-7dc800252e16)

After:
Also can we change the color of the copyright para to gray, so that the main content stands out!
![Screenshot 2023-07-19 233704](https://github.com/priyankarpal/ProjectsHut/assets/113251342/b1a561a1-fe09-4267-8a3d-4a6420304869)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
i think its not needed.
