### ISSUE TITLE
Add hover to make it attractive

### ISSUE THREAD

**Issue by akanksha984** [priyankarpal/ProjectsHut#1770]
### What happened?

![image](https://github.com/priyankarpal/ProjectsHut/assets/97845909/af132adf-23be-4b38-ba65-dafafeedda16)

I would like add hover effects to this section. Please assign it to me under gssoc'23

### Add screenshots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@akanksha984 yes, we can do this. Just add small amount of shadow when hovering

**Comment by akanksha984** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/97845909/aa1ac19c-11b3-4e29-9a53-e3530f1c6d74)

**Comment by akanksha984** [comment]
@priyankarpal  https://github.com/priyankarpal/ProjectsHut/pull/1775 please check this
