### ISSUE TITLE
Bug: footer in projects

### ISSUE THREAD

**Issue by BhartiNagpure** [priyankarpal/ProjectsHut#1778]
### What happened?

As on projects page there are number of projects increase and it this page shows Infinitescroll,
and when user goes on footer it flip to any above project.
So according to developer point of view there is no need to add footer I want to remove it.

### Add screenshots

![Screenshot 2023-07-21 062702](https://github.com/priyankarpal/ProjectsHut/assets/104631882/c1382426-4df8-4a21-a81d-13fe4ddc5edf)
This page not stop on footer.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I understand your concern about removing the footer, but it serves an important purpose on the projects page. The infinite scroll feature allows users to browse through numerous projects seamlessly, but the footer provides additional functionality and navigation options. It helps users quickly access other parts of our website.
