### ISSUE TITLE
feat: add logo 

### ISSUE THREAD

**Issue by BhartiNagpure** [priyankarpal/ProjectsHut#1779]
### What feature?

I would like to add logo in footer also want to make underline for headings like license and documentation

### Add screenshots

![Screenshot 2023-07-21 063259](https://github.com/priyankarpal/ProjectsHut/assets/104631882/1a24d4b9-1b7d-439c-b1ae-2f50eda00335)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@BhartiNagpure yeah we need to add the logo. also, just increase the font a little bit & bold heading( documentation, license).
