### ISSUE TITLE
💡feat:  Pagination 

### ISSUE THREAD

**Issue by SteveSayantan** [priyankarpal/ProjectsHut#178]
**Is your feature request related to a problem? Please describe.**
With the addition of new projects the projects page is getting lengthy.

**Describe the solution you'd like**

A pagination system with a certain number of projects on each page can be implemented.

**Comment by SteveSayantan** [comment]
I would like to work on this

**Comment by priyankarpal** [comment]
> **Is your feature request related to a problem? Please describe.** With the addition of new projects the projects page is getting lengthy.
> 
> **Describe the solution you'd like**
> 
> A pagination system with a certain number of projects on each page can be implemented.

good idea 💡 

Assigned @SteveSayantan

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
