### ISSUE TITLE
feat:Theme customiser

### ISSUE THREAD

**Issue by khushimarothi** [priyankarpal/ProjectsHut#1781]
### What feature?

I want to add a theme customizer that allows the user to switch the theme o the website according to their will.

### Add screenshots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we have decided to use only black, & white theme for our website.
