### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1784]
### Add a new project to the list

On hover can change the background of the button to text-primary or change the text of the button to text-primary it might look cool

![Screenshot 2023-07-21 at 11 39 29 AM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/eba4a22b-400b-4c4c-a592-b32a169e5ace)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
i think white is looking good.
