### ISSUE TITLE
Bug: Copy functionality in Share profile 

### ISSUE THREAD

**Issue by Akanksha-202** [priyankarpal/ProjectsHut#1786]
### What happened?

Clicking on "Copy" in the Share profile feature does not successfully copy the link to the clipboard.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/100708686/8da7eca5-24b0-427b-b4ca-ddac0b90a744

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
good spot @Akanksha-202 👏🏻 we need to fix this issue. assigned to you.
