### ISSUE TITLE
feat:addition of hover effect

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1787]
### What feature?

On hover can change the background of the button to text-primary or change the text of the button to text-primary it might look cool

### Add screenshots

![Screenshot 2023-07-21 at 11 39 29 AM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/5a93731e-bbc3-49aa-905f-cc2b1b7ac595)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate https://github.com/priyankarpal/ProjectsHut/issues/1784
