### ISSUE TITLE
feat:On click of profile picture should go on to the github

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1788]
### What feature?

as due to use of the most of social media apps the first instinct is to click on the profile photo so we should add github link od the account to the profile image

### Add screenshots

<img width="493" alt="Screenshot 2023-07-21 at 2 40 34 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/56ac8174-c2bb-4ba6-8088-d53a83a17102">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have github link & i think we don't need to add the github link to the avatar.
