### ISSUE TITLE
Bug: using border for elements on intro page 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1798]
### What happened?

- This issue is about using `border` for the elements on intro page which will be active during `:hover` state.
- `border` will naturally consumes extra space from outer region of the element so that other element's positions are affected.
- And also this might cause unwanted movements to the components, they are showned in the below video dropdowns.
- We need to use `outline` property of css instead of `border` to prevent the unwanted space consuming.

### Add screenshots

<details>
<summary><h3>&nbsp; Current State</h3></summary>

https://github.com/priyankarpal/ProjectsHut/assets/92252895/f29eda04-9e46-4119-98d6-b15d6a19fee6

</details>

<details>
<summary><h3>&nbsp; Desired State</h3></summary>

https://github.com/priyankarpal/ProjectsHut/assets/92252895/9d07ff09-4ee9-4bb6-a058-f328fcc84506

</details>

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by priyankarpal** [comment]
yeah we need to fix this issue. assigned
