### ISSUE TITLE
Prevent Text Selection In Landing Page

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1799]
### What feature?

In the landing page, cards get a sort of border on hover state but in Mobile devices, Hover work on long tap or click but on clicking the card, the text get selected which opens the google translate for the word which is sort of so annoying. 

The idea is to prevent text selection in these cards.

### Add screenshots

![Uploading Screenshot_2023-07-22-14-09-02-771-edit_com.android.chrome.jpg…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you share a demo?

**Comment by Souravvmishra** [comment]
Sure, Give me some time. 
This would just require preventing the text selection so that, it doesn't select the text which in turn would prevent opening the google.

**Comment by priyankarpal** [comment]
could you share update on this issue?

**Comment by Souravvmishra** [comment]
I'm a little busy. Will update you as soon as possible

**Comment by Souravvmishra** [comment]
I can't find a way to show you this thing here. should i  make the pr and then you can see this live in action in preview

**Comment by Souravvmishra** [comment]
check discord

**Comment by priyankarpal** [comment]
assigned
