### ISSUE TITLE
Bug: copyright is not properly visible for mobiles 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1801]
### What happened?

- The nav bar is placed at the bottom due to this reason the copyright is not properly visible for mobile devices.
- We need to add some extra margins for the copyright so that it could visible.
- Additionally i would like to minimize the font size a little bit so that it could looks good on mobile otherwise it looks much bigger than other components text sizes.

### Add screenshots

|BEFORE| AFTER |
| :---: | :---: |
| ![Screenshot_2023-07-22-15-27-44_1366x768](https://github.com/priyankarpal/ProjectsHut/assets/92252895/92689225-d6fe-4e58-972d-b40b065c9ee9) | ![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/4ef2ec6a-e590-4a87-b965-107c7c0613f5) |

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by priyankarpal** [comment]
I thinks it's too high

**Comment by priyankarpal** [comment]
> Actually this is how it looks on Mobile devices, the before part on above screenshot is slightly modified i totally forget about that.
> 
> ![Screen Shot 2023-07-24 at 20 31 35](https://user-images.githubusercontent.com/92252895/255630308-eccf5e85-503d-4b4d-954e-388235431d24.png)
> 
> We can set up a level of height for that, no problem.

sure assigned to you
