### ISSUE TITLE
Bug: Icon hover

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1802]
### What happened?

Icons in footer section has similar icon hover colour , It must be according to the social media colors of respective apps

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/3db1ef04-488d-4a9b-b7ed-ccd97fc9d038)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah sure. assigned
