### ISSUE TITLE
feat: Enhance Sharing Popup with Sharing Profile on Various Platforms

### ISSUE THREAD

**Issue by Nishitbaria** [priyankarpal/ProjectsHut#1809]
### What feature?

**Issue Description:**
Currently, the sharing popup on our platform lacks support for sharing profiles on various social media platforms. We should enhance the sharing popup by including icons for popular social media platforms, such as Twitter, Facebook, LinkedIn, Reddit, WhatsApp, Email, Telegram, Pinterest, Tumblr, Slack, and Discord. Additionally, we need to implement the functionality to open a popup with the respective social media sharing option when the corresponding icon is clicked.

**Proposed Enhancements:**

1. **Included Icons for Social Media Platforms:** Add icons for the following social media platforms within the sharing popup:
   - Twitter
   - Facebook
   - LinkedIn
   - Reddit
   - WhatsApp
   - Email
   - Telegram
   - Pinterest
   - Tumblr
   - Slack
   - Discord

2. **Social Media Sharing Popup:** Implement functionality to open a popup window with the appropriate sharing option for each social media platform. When a user clicks on a social media icon in the sharing popup, a new window should appear, allowing them to share the project link or content to the chosen platform directly.

3. **Copy Button Functionality:** Add a "Copy" button to the sharing popup to enable users to copy the project link to the clipboard when clicked. This will provide an additional sharing option for users who prefer to manually share the link.

## DEMO

![WhatsApp Image 2023-07-23 at 00 22 30](https://github.com/priyankarpal/ProjectsHut/assets/85815172/bb01c556-2a92-4af8-9019-d665f0295c51)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it's not needed we already have link & user can share the link to any platform
