### ISSUE TITLE
feat: "Start Contribution" with "Star on GitHub" and Total Stars ✨🤝🌟

### ISSUE THREAD

**Issue by Nishitbaria** [priyankarpal/ProjectsHut#1810]
### What feature?

The proposed logo type for the ProjectHunt Project will feature the text "Start Contribution" ✨ prominently displayed at the top. Beneath it, the text "Star on GitHub" 🤝 will be showcased to encourage users to engage with the repository. Additionally, the logo will incorporate a visual element to indicate the total number of stars the project has received, providing users with a quick overview of its popularity 🌟. This logo aims to enhance user engagement and promote contributions to the project on GitHub, fostering a thriving and active open-source community. 🚀💻🌈

### Add screenshots

I purposed to add like this
![image](https://github.com/priyankarpal/ProjectsHut/assets/85815172/e039d0bc-ff3a-49cd-8119-5b938f38209d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you share your progress on this issue?

**Comment by Nishitbaria** [comment]
@priyankarpal I was busy I will make PR for it till tomorrow morning ?

alright?

**Comment by priyankarpal** [comment]
> @priyankarpal I was busy I will make PR for it till tomorrow morning ?
> 
> alright?

yeah ok

**Comment by Nishitbaria** [comment]
@priyankarpal can you help me with the position of the icon on footer ?

**Comment by Nishitbaria** [comment]
ok!!! Cool

**Comment by Nishitbaria** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/85815172/2f578f04-2992-4894-86d4-60b07b3df8b5)
This is correct let  me asap so I should work on responsive @priyankarpal

**Comment by priyankarpal** [comment]
> ![image](https://user-images.githubusercontent.com/85815172/258190913-2f578f04-2992-4894-86d4-60b07b3df8b5.png) This is correct let me asap so I should work on responsive @priyankarpal

change the bg color to white & remove the text `start contributing`

**Comment by Nishitbaria** [comment]
@priyankarpal That is in that image ? 
![Github-share](https://github.com/priyankarpal/ProjectsHut/assets/85815172/502dcfd1-b037-4e05-b1e7-10e5676ee89c)

**Comment by priyankarpal** [comment]
remove the text start contributing

**Comment by Nishitbaria** [comment]
> remove the text start contributing

ok then I need to crop the image.... Thanks

**Comment by Nishitbaria** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/85815172/b74bdbc1-74a2-4284-9220-3d259253b59f)
this will work ?

**Comment by priyankarpal** [comment]
use this @Nishitbaria  & make sure use only cdn link of this image `https://github.com/priyankarpal/ProjectsHut/assets/88102392/0fa9e8f0-349d-4cc8-8e01-1b6e2c27dbbb`

![Group 1](https://github.com/priyankarpal/ProjectsHut/assets/88102392/0fa9e8f0-349d-4cc8-8e01-1b6e2c27dbbb)

**Comment by Nishitbaria** [comment]
> use this @Nishitbaria & make sure use only cdn link of this image `https://github.com/priyankarpal/ProjectsHut/assets/88102392/0fa9e8f0-349d-4cc8-8e01-1b6e2c27dbbb`
> 
> ![Group 1](https://user-images.githubusercontent.com/88102392/258204146-0fa9e8f0-349d-4cc8-8e01-1b6e2c27dbbb.png)

ok !! I got it
