### ISSUE TITLE
feat:🎯 Enhancing UI with Animation Component for "No Project Found" Search Result 🔍✨🚀

### ISSUE THREAD

**Issue by Nishitbaria** [priyankarpal/ProjectsHut#1811]
### What feature?

🚀 Add an animation component to the "No Project Found" search result UI to enhance user experience and visual appeal. The animation will provide a smooth and engaging transition while maintaining accessibility for all users. 🎨✨🔍

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/85815172/c9659f03-b995-47f8-93be-7450812a2dc5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Nishitbaria could you share demo?(animations)

**Comment by Nishitbaria** [comment]
![image](https://github.com/amupedia2021/Project-Amupedia/assets/85815172/0e254904-9f27-4f97-86a0-f7e801c6eb01)
![image](https://github.com/amupedia2021/Project-Amupedia/assets/85815172/664f003f-4473-49b8-bcc2-74f31e965e90)
 and Many more like https://colorlib.com/wp/free-404-error-page-templates/

**Comment by Nishitbaria** [comment]
@priyankarpal, I believe a simple and minimalist design is best for your website, and animation is not necessary as it may feel overwhelming.

**Comment by priyankarpal** [comment]
> @priyankarpal, I believe a simple and minimalist design is best for your website, and animation is not necessary as it may feel overwhelming.

yeah

**Comment by Nishitbaria** [comment]
@priyankarpal Why you closed it I was Working on It

**Comment by priyankarpal** [comment]
> @priyankarpal Why you closed it I was Working on It

> @priyankarpal, I believe a simple and minimalist design is best for your website, and animation is not necessary as it may feel overwhelming.

I thought you are not working so I closed

**Comment by priyankarpal** [comment]
It appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we are closing this issue. 

Thank you for your understanding.
