### ISSUE TITLE
docs: update checklist in all the issue forms

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1813]
### what's wrong with the documentation?

> Contributing guidelines is the first thing that a new contributor should look at, before contributing to the project

So, adding a proper checklist would be good:
- to check whether the contributors has checked for existing duplicate issues
- read contribution guidelines

> I will add other mandatory changes, and you can review the PR for any changes.

### Add screenshots

> For these two points
![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/092c12e7-c1b5-49ef-a90b-e7e71088b313)

> Current
![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/313ec924-f065-4a29-b463-58fff8bce181)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Anmol-Baranwal we can do this too. assigned
