### ISSUE TITLE
feat: show number of stargazers for every project

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1814]
### What feature?

We need to do things to incorporate this:

- We need to truncate the title earlier, and showing the stars with an appropriate icon.

I believe, in the current system good projects are not highlighted, adding number of stars will give them good visibility.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/e03a21ec-4940-4aac-95f8-a67d1403e0a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah currently we are working on backend part so I think we need to skip now. Also, after backend there will be more options & the star feature

**Comment by Anmol-Baranwal** [comment]
> yeah currently we are working on backend part so I think we need to skip now. Also, after backend there will be more options & the star feature

Yeah, I thought that displaying stars would be easier for implementing sorting feature.

> How about this, can we implement the sorting feature, by caching the data about stars in a file, and then using it for sorting functionality.

**Comment by priyankarpal** [comment]
> > yeah currently we are working on backend part so I think we need to skip now. Also, after backend there will be more options & the star feature
> 
> Yeah, I thought that displaying stars would be easier for implementing sorting feature.
> 
> > How about this, can we implement the sorting feature, by caching the data about stars in a file, and then using it for sorting functionality.

star do you mean github star or like button type?

https://github.com/priyankarpal/ProjectsHut/issues/1200

**Comment by Anmol-Baranwal** [comment]
> > > yeah currently we are working on backend part so I think we need to skip now. Also, after backend there will be more options & the star feature
> > 
> > 
> > Yeah, I thought that displaying stars would be easier for implementing sorting feature.
> > > How about this, can we implement the sorting feature, by caching the data about stars in a file, and then using it for sorting functionality.
> 
> star do you mean github star or like button type?
> 
> #1200

GitHub Stars on their respective repositories

**Comment by priyankarpal** [comment]
> > > > yeah currently we are working on backend part so I think we need to skip now. Also, after backend there will be more options & the star feature
> > > 
> > > 
> > > Yeah, I thought that displaying stars would be easier for implementing sorting feature.
> > > > How about this, can we implement the sorting feature, by caching the data about stars in a file, and then using it for sorting functionality.
> > 
> > 
> > star do you mean github star or like button type?
> > #1200
> 
> GitHub Stars on their respective repositories

we will use github API to fetch

**Comment by Anmol-Baranwal** [comment]
That is what, I was telling you in the first place. Like I wanna add a feature, to show stars fetched from the API.

No worries, I will look for other features to work on. If you have some in mind, feel free to let me know.

**Comment by priyankarpal** [comment]
> That is what, I was telling you in the first place. Like I wanna add a feature, to show stars fetched from the API.
> 
> No worries, I will look for other features to work on. If you have some in mind, feel free to let me know.

after adding backend we will add new features, UI so I think we need to add the feature later. if we add the star feature we need to change according to the new UI

**Comment by priyankarpal** [comment]
for now I'm closing the issue
