### ISSUE TITLE
feat: current navigation link is not highlighted

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1815]
### What feature?

As shown in the picture, it is not visible on which navigation link I am currently.

Also, I believe using icons is not a good way to show navigation since there is no additional information to tell what each icon represents.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/3ac55dfa-3f7d-484c-87a8-fdf8a561913a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to add the active link feature & also the sub title for icons.

**Comment by Anmol-Baranwal** [comment]
> yeah we need to add the active link feature & also the sub title for icons. what do you think?

Sure, please assign me.

I will make a PR till tomorrow.

**Comment by priyankarpal** [comment]
> > yeah we need to add the active link feature & also the sub title for icons. what do you think?
> 
> Sure, please assign me.
> 
> I will make a PR till tomorrow.

assigned
