### ISSUE TITLE
feat:Add hover effect to the buttons on project cards

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#1819]
### What feature?

I propose to add hover effect similar to the following button I implemented in one of my projects:
The hover effect could be added to both the github button and more button on projects card

https://www.awesomescreenshot.com/video/19348044?key=f92857a5e1170fdbee31891a1fb4bf82

### Add screenshots

https://www.awesomescreenshot.com/video/19348044?key=f92857a5e1170fdbee31891a1fb4bf82

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@karthiknadar1204 I think we don't need to change the button style. If we change it will change the whole UI design
