### ISSUE TITLE
chore: Adding Animations to the website

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1823]
### What feature?

Currently The Page Loads Statically But In Order To Improve the User Experience, We Can Add Animations To The Website. 

### Add screenshots

Sure, Once Get Assigned 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Souravvmishra which page?

**Comment by Souravvmishra** [comment]
All The Pages. 

Yes It Will Improve The User Experience.

There's always an extra joy in watching animations rather than static boxes & texts.

**Comment by priyankarpal** [comment]
> All The Pages.
> 
> Yes It Will Improve The User Experience.
> 
> There's always an extra joy in watching animations rather than static boxes & texts.

ok ok but can you share a demo? so that we can discuss about animations. also, are you using Framer Motion?

**Comment by Souravvmishra** [comment]
Yes I'll Be Using Framer Motion. I Am thinking of Animating the boxes as coming from left to right. Or we can go with a bottom to top one. As you say

**Comment by priyankarpal** [comment]
> Yes I'll Be Using Framer Motion. I Am thinking of Animating the boxes as coming from left to right. Or we can go with a bottom to top one. As you say

Sure! Yes, we will add animations that are appropriate.

**Comment by Souravvmishra** [comment]
Do You Have Any Particular Animation Or Should i Try One Mentioned?

**Comment by priyankarpal** [comment]
> Do You Have Any Particular Animation Or Should i Try One Mentioned?

currently I have nothing try yours. if we need to change we will do
