### ISSUE TITLE
Bug: Icon Hover in Profile Section

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1829]
### What happened?

The Icons below profile does not have proper hover effect according to their social media color, We need to make it correct, I am sharing screenshot for all

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/d08fefa5-2bc6-406a-b042-fb1ac20dbcac)
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/d161ba28-b821-4b99-9b94-64e1c1473412)
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/2ccdaabb-09da-4456-bd31-1f7e32a99bbd)
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/5180d033-f539-41fa-90f5-491df042b295)
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/cc72e8e4-ef6d-446c-be5a-217bdbddefa2)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Harshu467** [comment]
Assign it to me

**Comment by priyankarpal** [comment]
> Assign it to me

done
