### ISSUE TITLE
docs: Adding a MIT Licenses badge and some more text to Licenses section in readme

### ISSUE THREAD

**Issue by 1Shubham7** [priyankarpal/ProjectsHut#1837]
### what's wrong with the documentation?

The readme file of the repo should have a MIT Licenses badge and some more text regarding licenses in the  Licenses section to make it more professional.

### Add screenshots

![afters](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/df57e4ed-2b1c-4236-b95d-17c9f3190e5a)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@1Shubham7 thanks for creating the issue. I think it's unnecessary
