### ISSUE TITLE
feat: Adding Light Mode to the Website

### ISSUE THREAD

**Issue by Mahitej28** [priyankarpal/ProjectsHut#1840]
### What feature?

Hello, I am Mahima Churi a proud contributor at GSSoC ' 23.
I would like to work on this project by adding a feature of Light theme to the website along with a toggle button, which would help the user set the website's theme as per his/her need.
If you think it's legit, do assign me this issue under GSSoC ' 23 with a level of PR as well.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/98276915/71511edf-8cea-4eea-8b65-c77300e0a3cb)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
previously we had that feature & after nextjs migration we removed. We have decided to use only dark mode for this project.
