### ISSUE TITLE
Bug: Wrong Aria-Label

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1841]
### What happened?

- In Projects page all the links have same aria label (Github)

### Add screenshots

<img width="677" alt="Screenshot 2023-07-25 155412" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/66e5b39b-98bb-4898-8736-d2e8a322e8a2">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
