### ISSUE TITLE
chore: project addition by PVBharadwaj

### ISSUE THREAD

**Issue by PVBharadwaj** [priyankarpal/ProjectsHut#1842]
### Add a new project to the list

I would like to add a new space themed website project to the repository. I am a GSSoC'23 contributor. 

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@PVBharadwaj We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by priyankarpal** [comment]
any updates? @PVBharadwaj

**Comment by PVBharadwaj** [comment]
@priyankarpal please review my pr
Sorry for the delay. I was a bit confused in creating the pull request. So, it become late.
