### ISSUE TITLE
feat: Request for Adding Contributor Page to Repository

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#1847]
### Description:
I would like to kindly request the addition of a dedicated "Contributor Page" to our website. This page will serve as a simple yet meaningful way to recognize and appreciate the efforts of all the contributors who have played a valuable role in the development of our project.

### Features:
- **List of Contributors:** The page will display the usernames and total contributions of all the individuals who have made valuable contributions to our project. This serves as a token of gratitude and acknowledgment for their efforts and dedication.

- **Contributors' Information:** For each contributor listed, a link to their GitHub profile will be provided. This enables visitors to easily access the profiles of contributors they are interested in and learn more about their work.

The addition of this "Contributor Page" will not only honor our contributors but also encourage further contributions from the community, fostering a positive and inclusive environment.

Thank you for considering this request. Your support in implementing this feature is highly appreciated.

Best regards,
Tushar

### Add screenshots

It will be something like this. And I will ensure to apply the same theme as our website has.

<img width="203" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/104740281/38567e61-14f0-4e18-b8f6-5d2e36ef04e2">

For more examples, you can check these websites:
- https://icons.bookingjini.tech/contributors.html
- https://webxdao.xyz/contributors
- https://gyanaguru.vercel.app/static/contributors

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@s2sharpit Before migrating to Next.js, we had a contributors page. However, after the migration, we decided to remove it, and we have chosen not to reintroduce it.

**Comment by s2sharpit** [comment]
> @s2sharpit Before migrating to Next.js, we had a contributors page. However, after the migration, we decided to remove it, and we have chosen not to reintroduce it.

Okay, Sure @priyankarpal
