### ISSUE TITLE
feat: Category Tag

### ISSUE THREAD

**Issue by pranshugupta54** [priyankarpal/ProjectsHut#1849]
### What feature?

Add tags to the project. Basically a button like UI on each project which shows the tag.

### Add screenshots

. 

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
## we already have the tag options in every project. 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/4f6dc28a-e747-48b1-aab6-a2ea529a09ca)

## We will redesign cards so we removed the tags from here. 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/47a286e4-e158-4629-a40c-883790ce3f71)
