### ISSUE TITLE
chore: project addition by Deepak

### ISSUE THREAD

**Issue by k-deepak04** [priyankarpal/ProjectsHut#1850]
### Add a new project to the list

Add IOT project of Making the Real time temperature and humidity detection using ESP32 and DHT11.

![Screenshot 2023-05-04 033139](https://github.com/priyankarpal/ProjectsHut/assets/96341431/ee78a438-a820-4a29-9033-c823dd16d2ab)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by k-deepak04** [comment]
@priyankarpal please add the gssoc tag and level :)

**Comment by priyankarpal** [comment]
> @priyankarpal please add the gssoc tag and level :)

We are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by k-deepak04** [comment]
Okay no worries :)
just merge the pr
