### ISSUE TITLE
Bug: browse projects button cutt-off on mobile devices 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1853]
### What happened?

- The `Browse Projects` Button which can be found on Homepage is cutted off for Mobile Devices.
- We want to resolve this issue, because this bug looks weird to the end user and affects the UI.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/92252895/8d8a4f79-325a-44de-a04f-f16565b88d27)

### What browsers are you seeing the problem on?

Firefox

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by priyankarpal** [comment]
assigned to you
