### ISSUE TITLE
💡feat: Add Dark & light mode

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#186]
- We need to add dark & light modes to the project.
- Add a toggle switch on the navbar for dark & light mode.  
![image](https://user-images.githubusercontent.com/88102392/231483162-91a6a76c-1541-482e-8619-4eb822643f24.png)

**Comment by Saurav-Pant** [comment]
@Bharadwajshivam28 are you working on this?

**Comment by Bharadwajshivam28** [comment]
@priyankarpal Sir unassign me due to some personal issue  i cant work on it right now

**Comment by Bharadwajshivam28** [comment]
> @Bharadwajshivam28 are you working on this?

go with it

**Comment by priyankarpal** [comment]
> @priyankarpal Sir unassign me due to some personal issue i cant work on it right now

ok

**Comment by Saurav-Pant** [comment]
Thanks, I will work on it

**Comment by Saurav-Pant** [comment]
@priyankarpal, how is this?
https://user-images.githubusercontent.com/103263909/233665161-9dc66937-132b-4173-8813-77522d07d38d.mp4

**Comment by priyankarpal** [comment]
> @priyankarpal, how is this? https://user-images.githubusercontent.com/103263909/233665161-9dc66937-132b-4173-8813-77522d07d38d.mp4

looks good 🎉 

change the bg color to white
also send the responsive demo

**Comment by Saurav-Pant** [comment]
updated, but on the "AddYourProjectsGuide " page, we have the text in white what different color I should use here?
https://user-images.githubusercontent.com/103263909/233669216-ceff0e32-67d5-427f-9810-0c955f6504cb.mp4

**Comment by priyankarpal** [comment]
> updated, but on the "AddYourProjectsGuide " page, we have the text in white what different color I should use here? https://user-images.githubusercontent.com/103263909/233669216-ceff0e32-67d5-427f-9810-0c955f6504cb.mp4


Use this color for light bg `#f5f6fa`

all things ok but you need to change something: 
- change the Button bg color to dark for light bg 
- change the whole website light theme not just a container/div
- change texts color to dark for light bg 
- don't forget to responsive mode for every device.

**Comment by Saurav-Pant** [comment]
All right, but "change the whole website light theme not just a container/div "How can I achieve this?

**Comment by priyankarpal** [comment]
> All right, but "change the whole website light theme not just a container/div "How can I achieve this?

change the pages such as projects page also after

**Comment by HarshPanchal26** [comment]
Hey Is this issue still open , I want to work on it , or If any other task , I would like to do it .

**Comment by priyankarpal** [comment]
> Hey Is this issue still open , I want to work on it , or If any other task , I would like to do it .

@Saurav-Pant working on this issue. You can check another issue.

**Comment by Saurav-Pant** [comment]
> > updated, but on the "AddYourProjectsGuide " page, we have the text in white what different color I should use here? https://user-images.githubusercontent.com/103263909/233669216-ceff0e32-67d5-427f-9810-0c955f6504cb.mp4
> 
> Use this color for light bg `#f5f6fa`
> 
> all things ok but you need to change something:
> 
> * change the Button bg color to dark for light bg
> * change the whole website light theme not just a container/div
> * change texts color to dark for light bg
> * don't forget to responsive mode for every device.

I think some things are done in this, but I am facing one issue with/ContributorsPage and also /ProjectsPage, here my theme is applied only in div/container, not in the app.
how do you think is going? @priyankarpal 

https://user-images.githubusercontent.com/103263909/233783468-d6e35cd8-2b00-4822-9fb7-7511b3e610a9.mp4

**Comment by priyankarpal** [comment]
> > > updated, but on the "AddYourProjectsGuide " page, we have the text in white what different color I should use here? https://user-images.githubusercontent.com/103263909/233669216-ceff0e32-67d5-427f-9810-0c955f6504cb.mp4
> > 
> > 
> > Use this color for light bg `#f5f6fa`
> > all things ok but you need to change something:
> > 
> > * change the Button bg color to dark for light bg
> > * change the whole website light theme not just a container/div
> > * change texts color to dark for light bg
> > * don't forget to responsive mode for every device.
> 
> I think some things are done in this, but I am facing one issue with/ContributorsPage and also /ProjectsPage, here my theme is applied only in div/container, not in the app. how do you think is going? @priyankarpal
> 
>  resend.mp4

create a PR I will check

**Comment by Saurav-Pant** [comment]
How to prevent this error?
(https://user-images.githubusercontent.com/103263909/233788188-5440ed6a-b2ce-4a51-bce5-46dcb1d23b14.png)

**Comment by priyankarpal** [comment]
> How to prevent this error? (https://user-images.githubusercontent.com/103263909/233788188-5440ed6a-b2ce-4a51-bce5-46dcb1d23b14.png)

whenever you face this type of error in ProjectsHut use this command

`pnpm format`

**Comment by Saurav-Pant** [comment]
#231 It  is the PR
