### ISSUE TITLE
chore: project addition by rishabhchaudhary0210

### ISSUE THREAD

**Issue by rishabhchaudhary0210** [priyankarpal/ProjectsHut#1864]
## Admin Dashboard
I want to a fully responsive admin dashboard made by me. It has a friendly UI and provides good UX.
With the aim to help businesses keep track of their expenses the admin dashboard is very useful to track daily business metrics.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we are closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
