### ISSUE TITLE
💡feat:  add splash screen/loading screen

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#187]
- We need to add a splash screen for the project.
- Whenever anyone reloads or visits the page it will show the splash screen first. 
- Add only for HomePage 

If you have any queries you can share them.

**Comment by priyankarpal** [comment]
> Hey Priyank, I just show your tweet about this project. This is a fantastic project & I would love to contribute to it.
> 
> * Actually, I'm **learning react right now** & I thought it's a good issue to work upon.
> * Can you guide me **what other things should I learn** before working on this issue?

- React component lifecycle methods: You can use the componentDidMount() lifecycle method to trigger the splash screen when the component is mounted.

- CSS classes and styles: You can use Tailwind CSS classes and styles to create the splash screen design.

**Comment by Saurav-Pant** [comment]
is this what you need @priyankarpal 
(https://user-images.githubusercontent.com/103263909/231968984-fc4ab136-9d76-4abc-bd8b-074b1c78f531.png)

**Comment by priyankarpal** [comment]
Yeah. Try to add color

**Comment by Saurav-Pant** [comment]
okay, check this color, @priyankarpal 
(https://user-images.githubusercontent.com/103263909/232024188-df158874-0b18-4759-8679-bbb56e2f2e34.png)

**Comment by priyankarpal** [comment]
> okay, check this color, @priyankarpal (https://user-images.githubusercontent.com/103263909/232024188-df158874-0b18-4759-8679-bbb56e2f2e34.png)

I forgot to tell you add this color 

![image](https://user-images.githubusercontent.com/88102392/232056392-83f34cca-f56b-408b-8120-5b0a98ac1c8d.png)

` from-indigo-500 via-purple-500 to-pink-500 bg-gradient-to-r`

**Comment by Saurav-Pant** [comment]
> > okay, check this color, @priyankarpal (https://user-images.githubusercontent.com/103263909/232024188-df158874-0b18-4759-8679-bbb56e2f2e34.png)
> 
> I forgot to tell you add this color
> 
> ![image](https://user-images.githubusercontent.com/88102392/232056392-83f34cca-f56b-408b-8120-5b0a98ac1c8d.png)
> 
> ` from-indigo-500 via-purple-500 to-pink-500 bg-gradient-to-r`
(https://user-images.githubusercontent.com/103263909/232079670-abcffb5d-01f6-4bc6-84a3-de4d20fa65bb.png)
is this okay or I should add color to the text @priyankarpal

**Comment by priyankarpal** [comment]
> > > okay, check this color, @priyankarpal (https://user-images.githubusercontent.com/103263909/232024188-df158874-0b18-4759-8679-bbb56e2f2e34.png)
> > 
> > 
> > I forgot to tell you add this color
> > ![image](https://user-images.githubusercontent.com/88102392/232056392-83f34cca-f56b-408b-8120-5b0a98ac1c8d.png)
> > ` from-indigo-500 via-purple-500 to-pink-500 bg-gradient-to-r`
> > (https://user-images.githubusercontent.com/103263909/232079670-abcffb5d-01f6-4bc6-84a3-de4d20fa65bb.png)
> > is this okay or I should add color to the text @priyankarpal

for text = white

**Comment by Saurav-Pant** [comment]
okay, #196 is the PR  @priyankarpal

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
