### ISSUE TITLE
feat:Contributors

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1870]
### What feature?

As this is open source project it is important to show users who is owner of this project and contributors. I want to create contributors part where all contributors will be shown in card format just like projects and their contributions will be shown.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/e621fe06-7785-4708-8018-7ff6583ca1a5)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1847
