### ISSUE TITLE
feat: Share Project

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1871]
### What feature?

Just like sharing profile , we can create share projects feature to every project created.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/22fc2a0a-c311-4553-a552-378ac7029be1)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think we've added the GitHub repo link & I believe user can check

**Comment by Harshu467** [comment]
Ok then I am closing this issue
