### ISSUE TITLE
chore: project addition by anilkoduru

### ISSUE THREAD

**Issue by anilkoduru** [priyankarpal/ProjectsHut#1873]
### Add a new project to the list

Url shortener project addition to the repo

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you share your progress on this issue?

**Comment by priyankarpal** [comment]
it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we are closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
