### ISSUE TITLE
Bug: Home Page Width Exceeding Screen Width

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#1874]
### What happened?

Currently, when accessing the home page on 13-inch laptop, the content extends beyond the screen boundaries, making it difficult for users to view and interact with the page properly. This issue affects the overall user experience and hampers the accessibility of the project information.

Screen Resolution: 1920 x 1080
Device: Laptop

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/104740281/47095be0-df63-48de-9fb7-104427eab33e

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah assigned to you
