### ISSUE TITLE
feat: Dynamic Page Titles for Consistency

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#1875]
### What feature?

Currently, the homepage title is set as "ProjectsHut," but when navigating to other pages, the title remains the same, lacking the necessary context. To enhance user experience and maintain consistency, it would be beneficial to dynamically update the page titles across the website.

When a user visits the homepage, the title should display "ProjectsHut." However, when navigating to other pages, the page title should follow the format "<page title> - ProjectsHut" to provide clear identification and reinforce the website's branding.

**Benefits:**
1. Improved User Experience: Dynamic page titles give users a clear understanding of their current location within the website.
2. Consistent Branding: By appending "ProjectsHut" to each page's title, we reinforce the brand and maintain a cohesive identity.
3. SEO Optimization: Dynamic page titles with relevant keywords can positively impact search engine rankings, enhancing the website's visibility.

Let's work together to enhance the website's usability and branding by implementing this simple yet effective improvement.

### Add screenshots

.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to fix the issue. Also, after merging `1874` you can work on this issue

**Comment by s2sharpit** [comment]
> yeah we need to fix the issue. Also, if your `1874` issue got merged you can work on this issue

Sure @priyankarpal ☺️

**Comment by s2sharpit** [comment]
Hey @priyankarpal, regarding issue #1875, I'd like to propose using the [Next.js Metadata API](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) for better SEO. However, before we proceed with its implementation, we need to address this issue first. Could you please assign it to me? Once it's done, I'll take care of the SEO improvement. Thanks!
