### ISSUE TITLE
feat: Simple close button for the filter panel

### ISSUE THREAD

**Issue by pewpewnor** [priyankarpal/ProjectsHut#1876]
### What feature?

In the /projects directory, there is a filter button that opens up a dialog panel/pop-up to allow the user to select the desired filter. However, some users may be confused about how to close the filter panel because, currently, the only way to do so is by clicking anywhere outside of the filter panel. In my own experience, I was confused about how to close it since I intuitively looked for a close button.

**Benefits:**
- Reduce confusion regarding how to close the filter panel.
- Increase intuitiveness in the process of selecting filters.

**Solution:**
We can a simple close button on the top right of the filter panel.

### Add screenshots

Demo screenshot of the new close button:

- View for desktop users:
![image](https://github.com/priyankarpal/ProjectsHut/assets/125549982/8180ace7-e2d4-4525-863f-73c6dcb8c0c0)

- View for mobile users:
![image](https://github.com/priyankarpal/ProjectsHut/assets/125549982/641366da-c3ed-4d9b-b6a0-ed05f0d2779f)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we need to add. just remove the text `close` & use only icon

**Comment by pewpewnor** [comment]
Will do @priyankarpal, I have made the PR.
