### ISSUE TITLE
Bug: Missing title Attribute for All Social Links Existed in Respective Web Pages

### ISSUE THREAD

**Issue by NarendraKoya999** [priyankarpal/ProjectsHut#1878]
### What happened?

- **In Our Website, Not added title Attribute for Social Links in Respective Web Pages like Footer Section and Projects Details Section**

### Purpose of Raising this Issue:
- **The title attribute gives users an important indication as to where they will be directed to when they click on a link. If the user hovers with the mouse over a link reference, the title text, which was defined in the attribute, will be displayed.**

### Add screenshots

![projectshut-3](https://github.com/priyankarpal/ProjectsHut/assets/84512164/a21e98a9-f331-49ea-b799-bb684d0ee8c4)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we can do it too. Assigned to you.
