### ISSUE TITLE
feat:Hover Effect for Title

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1883]
### What feature?

Ph. is a name of project, in footer everything has hover effect except project name , if we can add hover effect to Ph. in footer and header , it will look great , As in Navbar every element has hover effect it looks good. I feel if we can add it , it would be good to see and also consistent design across elements like navbar and footer. I am sharing sample of footer. When Hover on Ph. it turn purple

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/75ce13b8-1807-474b-a907-4d0ddc90d7af)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
for logo we don't need to add hover effect

**Comment by Harshu467** [comment]
@priyankarpal But it looks good we can do it ?
