### ISSUE TITLE
feat:Project Focus

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1884]
### What feature?

As of now in project section when hover on project it has border color change to purple which looks nice. What if we can add same effect in profile section it would make consistent design through-out application and it will be nice to see. Sharing one sample when hover. First Image is image of project section of that feature and second is same feature in profile section. It is sample , I will add same color 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/227b47cd-4232-4bb2-bdbb-d499d1c9ae1f)
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/463a6ce1-7967-4ff1-9980-2815497ae0d0)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah sure we can do this too. assigned to you
