### ISSUE TITLE
Bug: Incomplete Image in landing page

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1885]
### What happened?

As I have shared screenshot , we can see that middle image is behind the navbar so we cant see it whole. Other images are visible fully. To make consistency we can make that image fully visible. It is small bug we can fixed it and as we see other professional websites they don't have such kind of things , we can fixed it

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/33b794b9-7a7c-44b7-bd2b-bafe3229d4b8)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
we will change the UI soon so I think currently we don't need to change anything
