### ISSUE TITLE
Bug: Why to use section 

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1886]
### What happened?

The text added in why should you use this. Small text is above large text. My suggestion is that we can interchange their position. As when we read things , top thing is bigger and then comes small thing in professional websites and also in newspaper

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/ae60093b-e609-4a58-a67f-ac653bc73c39)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Harshu467 yeah just we need to change their position
