### ISSUE TITLE
Bug: Navbar Inconsistency

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1887]
### What happened?

In Navbar when clicked on Home it remains purple when user is in home and when click on project its color is white similar to docs. It is In-Consistency. We can either make other section purple or make home section white when clicked. Sharing proofs

## Home Section [ See Navbar Color of Home ]
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/512bd5da-c5af-47ca-841f-821c48bdb1fe)
## Project Section [ See Navbar Color of Project ]
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/bcdd9050-9ff1-4400-962d-b80c871ad32d)
## Docs Section [ See Navbar Color of Docs ]
![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/20810e81-b29a-4b3a-ac76-a066ddd0aaea)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Harshu467 we need to add the active link purple. assigned

**Comment by Amira-Chaabne** [comment]
Hello, is this issue still open ?
