### ISSUE TITLE
Animating The Projects Page

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1894]
### What feature?

As The Initial Landing Page Is Animated, I would like to start working on the projects page. 

If you liked the animation on the cards in landing page, should we kepp the same animation here also.

### Add screenshots

![IMG_20230730_102032](https://github.com/priyankarpal/ProjectsHut/assets/89072785/e8f53787-5737-4782-8138-2c05016464d2)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
