### ISSUE TITLE
feat: revamp hover states for social icons 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1896]
### What feature?

- We want to revamp the hover state of social icons, the current state is not appreciated. Because the color scheme used for every different social icons during hover on our dark themed ProjectsHut Site is just creates bad impression.
- We can revamp the color to site's primary color `#A66EFC` which looks good for all social icons.
- In simple words we don't want to spoil the UI by including different color schemes for icons, instead we can just the color scheme to `#A66EFC`.
- This revamp process will enhance the minimalistic look of ProjectsHut Site

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/92252895/32b6bceb-b5c2-4d1f-90cb-f0f4800a54bc

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻 

Please make sure to assign this issue to me to make the work done!

Thank you.

**Comment by priyankarpal** [comment]
yeah I also thought about this 
assigned
