### ISSUE TITLE
feat: improve home page for small screen devices

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1899]
### What feature?

These are the changes that can improve the overall user experience of the page:

1. Remove large gap and maybe add a distinct light gradient line (let me know about the separation line)

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/b590346d-ca66-445e-bccb-7225fc11da2e)

2. adding a slight box shadow (not excessive)

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/02d595b6-14d8-4f41-92a3-66c8e961f308)

3. center the brand logo

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/92e720a3-0b21-4815-99b1-a21acc902847)

4. Improve visual heirarchy

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/81b7b4a2-8530-4989-83b7-e1ac0472ae3b)

Here, documentation links and license heading seem closer than their respective elements. 

> I don't know about custom hyperlinks, since many people avoid using it for the sake of design and visual appeal.

### Add screenshots

> Already done with the points

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah @Anmol-Baranwal we need to fix these. 

- just we need to remove the extra spaces
- center the logo
- need to align the footer texts
- don't add the box shadow

**Comment by Anmol-Baranwal** [comment]
> could you share your progress on this issue?

I will complete this by tomorrow or till late night today. (I haven't started)

**Comment by priyankarpal** [comment]
> > could you share your progress on this issue?
> 
> I will complete this by tomorrow or till late night today. (I haven't started)

cool

**Comment by Anmol-Baranwal** [comment]
@priyankarpal 
Can you check whether the project is running locally?

Because, there is a error even if package exists.

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/f324a847-c905-416a-80fb-4dc1eb429b83)

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/d9e397db-0a32-4f7b-80eb-3e8a54122d19)

**Comment by priyankarpal** [comment]
let me check

**Comment by priyankarpal** [comment]
@Anmol-Baranwal yeah it's running

**Comment by Anmol-Baranwal** [comment]
> let me check

I was doing this 2 days back as well, I even tried to install the package. By the way, the branch is updated and is on `main`.

I will fork it again.

**Comment by priyankarpal** [comment]
use `pnpm i` to install again
