### ISSUE TITLE
feat: add issue form for refactor code

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1900]
### What feature?

I need to refactor the code, but the problem is which issue form to choose. Since it is not a new feature, creating a new issue form will likely be a good choice. 

I will ensure it follows proper conventions and standards and avoid unnecessary fields.

### Add screenshots

> Similar to this
![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/06fd7496-7d75-4e41-aea2-bade8f551ad2)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure @Anmol-Baranwal we need to add the issue form
