### ISSUE TITLE
feat: separate json data from Banner component

### ISSUE THREAD

**Issue by Anmol-Baranwal** [priyankarpal/ProjectsHut#1901]
### What feature?

As per convention, data should be separate for better organization of code. What we can do is, we can include the data in `DB` directory and fetch it accordingly.

```typescript
const features = [
  {
    name: "Add GitHub link",
    description: "You can add your GitHub repository link to your profile.",
    icon: FaGithub,
  },
  {
    name: "Share your profile",
    description: "Share your profile with your friends and colleagues.",
    icon: FaShareAlt,
  },
  {
    name: "Open Source ",
    description: "This project is open source and you can contribute to it.",
    icon: SlGlobe,
  },
  {
    name: "Free to use",
    description:
      " This project is free to use and you don't have to pay anything. ",
    icon: FaMoneyBillAlt,
  },
];
```

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/74038190/8be42e6b-1d64-42c4-87e8-eb23ee1fdcfe)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think we don't need to separate the code.
