### ISSUE TITLE
Animating The Docs Section 

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1903]
### What feature?

Animating The Docs Part

### Add screenshots

![IMG_20230730_101032](https://github.com/priyankarpal/ProjectsHut/assets/89072785/3a22b139-9ab4-4d38-9b45-c0852ede6744)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Souravvmishra try to add relevant screenshots
