### ISSUE TITLE
bug: add gap between nav links for mobile devices

### ISSUE THREAD

**Issue by Souravvmishra** [priyankarpal/ProjectsHut#1904]
### What feature?

Currently There is a lot of space left on either side of the navlinks in small screen. We can increase the hap between individuals links and let them take the rest of the space 

### Add screenshots

![Screenshot_2023-07-30-21-10-20-031-edit_com android chrome](https://github.com/priyankarpal/ProjectsHut/assets/89072785/44dfad1f-3439-40bf-8b41-74b2268c4223)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah @Souravvmishra assigned
