### ISSUE TITLE
feat:  Animation in docs section

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1907]
### What feature?

As we can see animation feature in both section of home and projects , we must add it in docs section to make design consistency throughout the application

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89975347/c2a0dba0-c4e3-4f39-af3d-0d084cdf5a99)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/1903
