### ISSUE TITLE
docs: Readme

### ISSUE THREAD

**Issue by Parul1606** [priyankarpal/ProjectsHut#1917]
### what's wrong with the documentation?

Current state: -

The Contributing section of the README file requires extra documentation. Some commands that should be applied while contributing to the project are missing.

Desired State: - 

I have checked most of the things are instructed in the contributing.md but commands like git remote -v, pull the upstream main first only to not arise conflicts are missing. So,  I would like to add all those things in correct order and add extra 2-3 commands that are missing.

### Add screenshots

My new Readme will look like this(Demo): -
![image](https://github.com/priyankarpal/ProjectsHut/assets/80768852/0f3c107b-36c9-421c-bdea-ce0c25fb2a5d)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think we don't need to change the `readme` just add the two points to the `contributing` guide
