### ISSUE TITLE
feat: New parameter add (Step feature)

### ISSUE THREAD

**Issue by tanujbordikar** [priyankarpal/ProjectsHut#1920]
### `Under GSSOC'23`

1. As I visited the site I noticed there is not a parameter of Steps in the code which definitely confuses the user. So I wanted to add the feature of steps. 
2. And also the color color looks too bright which doesn't follow the Standards of WCAG so I wanted to change the font color.
   - Factors affecting due to contrasting text color:
      i. Readability:  Dark text on a light background or light text on a dark background is generally preferred for readability.
      ii. Consistency: Consistency in font colors throughout the website helps create a cohesive user experience.

### Before Changes: 
![projectshut_ui](https://github.com/priyankarpal/ProjectsHut/assets/91179998/e8685804-85f9-43aa-9ec2-e447a364a942)
### After Changes:
![projectshut_ui_new](https://github.com/priyankarpal/ProjectsHut/assets/91179998/59d84874-375e-4ef6-9f87-6994b966df70)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have created an issue related to docs so the contributor will add there https://github.com/priyankarpal/ProjectsHut/issues/1661

**Comment by tanujbordikar** [comment]
But still you haven't assigned it to anyone so please assign it to me because i have the code ready for that problem.

**Comment by tanujbordikar** [comment]
As you've have mentioned the previous issue was about the addition of guide in the documentation part not in the code ?

**Comment by priyankarpal** [comment]
> But still you (@priyankarpal ) haven't assigned it to anyone so please assign it to me because i have the code ready for that feature.

Check I have assigned

**Comment by tanujbordikar** [comment]
is it suzy or parul?

**Comment by priyankarpal** [comment]
> Is it suzy or parul? @priyankarpal And my work is to add a feature in it of steps in the [projectshut.vercel.app/docs](https://projectshut.vercel.app/docs) section so that is reason.

suzy

**Comment by tanujbordikar** [comment]
okay No problem!
