### ISSUE TITLE
docs: Add commit husky message format

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1922]
### what's wrong with the documentation?

- The project use husky for proper commit messages 
- But in contributing md file there are no proper information for new contributor 

### Add screenshots

- I want to add the proper husky commit message in contributor md file 

<img width="828" alt="Screenshot 2023-08-01 141106" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/d3eda8ec-39db-4b59-98b1-402d64424ac0">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we added the conventional commits site link to the contributing guide
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/8d3d7344-c82b-4391-baad-cf7afdc86542)

**Comment by parasss19** [comment]
> we added the conventional commits site link to the contributing guide ![image](https://user-images.githubusercontent.com/88102392/257791300-8d3d7344-c82b-4391-baad-cf7afdc86542.png)

But it would be very time consuming too for contributor to open the site link and search

**Comment by priyankarpal** [comment]
> > we added the conventional commits site link to the contributing guide ![image](https://user-images.githubusercontent.com/88102392/257791300-8d3d7344-c82b-4391-baad-cf7afdc86542.png)
> 
> But it would be very time consuming too for contributor to open the site link and search

I can suggest changes or edit the commit message in PR time. Also, the contributing guide will be more lengthy if we add
