### ISSUE TITLE
feat: ReDesign the Navbar

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#1923]
### What feature?

- Right now the navbar is just sticky to its position
- I will apply glass morphism effects 
- And also add hover effect over it 

### Add screenshots

No sample right now

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@parasss19 I think we need to add only `glass morphism effects` we already have the hover effects
