### ISSUE TITLE
feat: Add contributors list on the webite

### ISSUE THREAD

**Issue by sumitkr2000** [priyankarpal/ProjectsHut#1926]
### What feature?

Hey @priyankarpal I would like to add a contributors list on the website. Please assign me this issue. Thank you!

### Add screenshots

.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/1847
