### ISSUE TITLE
[style]:  Changing the the Text and give text typing effect

### ISSUE THREAD

**Issue by PatilHarshh** [priyankarpal/ProjectsHut#1941]
### What's the style idea?

add text typing effect

### Add screenshots

![f](https://github.com/priyankarpal/ProjectsHut/assets/120102234/d4a0128f-968e-4ce0-aa42-d495c64b7a13)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PatilHarshh** [comment]
@priyankarpal

**Comment by priyankarpal** [comment]
if we add the type effect it will change our UI
