### ISSUE TITLE
[style]: Decrease font size of copyright section in footer

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#1944]
### What's the style idea?

At present, the font size of the copyright section looks bigger than the other sections' font-size. I would like to decrease it to `text-sm`. 

### Add screenshots

<img width="960" alt="Screenshot (511)" src="https://github.com/priyankarpal/ProjectsHut/assets/104740281/5abed750-2e62-4b98-ad85-3a75c618aabf">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
