### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1951]
### Add a new project to the list

I want to add 3 new projects 
1.Anynomous social
2.Chat Applicaiton
3.Coupon Code Website

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you share your progress on this issue?

**Comment by Sahilll15** [comment]
Ohh!! Sorry i'll just do it by evening
