### ISSUE TITLE
Bug : The documentation and license are no aligned properly in the footer section

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1952]
### What happened?

The documentation and license are no aligned properly in the footer section

### Add screenshots

![Screenshot 2023-08-04 at 12 30 12 AM](https://github.com/priyankarpal/ProjectsHut/assets/109215419/08afcbfd-ebc4-4a46-81cb-5c953bb26d87)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by Sahilll15** [comment]
working on it!!

**Comment by Sahilll15** [comment]
@priyankarpal have a look
