### ISSUE TITLE
Bug: Issue in footer responsiveness

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1963]
### What happened?

the documentation and license footer is moving to the left in smaller devices

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/109215419/d0744d45-4cf9-4ca8-b742-fa3104577b51

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by Sahilll15** [comment]
Thanks for mearging!!
