### ISSUE TITLE
Bug: maybe we can add a margin left to the license and documentation or add some mt to the start button

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1966]
### What happened?

maybe we can add a margin left to the license and documentation or add some mt to the start button

### Add screenshots

![IMG_5357](https://github.com/priyankarpal/ProjectsHut/assets/109215419/d6c6bd16-1409-4824-b7a5-c9582b199aca)

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah we have to do  assigned
