### ISSUE TITLE
[style]: hover state for github star button 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1969]
### What's the style idea?

- Currently the Github Repository Star Button doesn't have any Hover States.
- So the user could not able to identify that's a Button. Adding Hover states will improve the User Experience and provide a visual clue for the User.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/92252895/559db5b3-4722-4e01-abca-3a4c31944416

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by 0xabdulkhalid** [comment]
Can we modify the Github Star image into Text and (✨) emoji ?

Let me know your thoughts!

**Comment by priyankarpal** [comment]
I believe there's no necessity for changes; it's simply an image and doesn't require any hover effect.
