### ISSUE TITLE
[Refactor]: add project link to name instead of github logo ⚒️✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1970]
### File Name

components/projects/ProjectList.tsx

### Reason for Refactoring the Code

- The visitor's can't touch the Project's Name to navigate to the Project's Page.
- Providing the Project link via Github Logo is tend to confusing to the user, Everyone will hover the card the touches the Project's Name.
- And the Github Logo's hover state also not looks good, we need to change it's hover state from `#6B7280` to `#A66EFC`.
- Otherwise we can change the link from Github Logo to the Card list items itself, It will be more engaging to the User.
- Let me know your thoughts!

### Current State (Video)
https://github.com/priyankarpal/ProjectsHut/assets/92252895/1b883c47-f39b-4129-8d70-8f947dc87ed7

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by priyankarpal** [comment]
good idea @0xabdulkhalid we can add the github link to the card & also, just add the icon to the right top corner like this but the icon will be this 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/91d60204-b587-43d3-8f83-d118005d0e1d)


![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/c8728fe1-a864-49a6-bea1-d06d5c6c2bba)

**Comment by 0xabdulkhalid** [comment]
@priyankarpal if we add the logo you just mentioned above, then what about the Github Logo ?

Can we take if from the card ?

**Comment by priyankarpal** [comment]
ok push if need to change I will update you

**Comment by 0xabdulkhalid** [comment]
Wait i'm improving hover effects, I will make PR once i completed.
