### ISSUE TITLE
Bug: Profile Page bug 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1975]
### What happened?

I Think the main card of the user should stay fixed and just the projects card should move ,maybe that will look better

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/109215419/298b6e9f-3003-4f16-a628-9e820328c979

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure @Sahilll15 assigned
