### ISSUE TITLE
feat: Adding of New parameter - Step feature and improve the UI

### ISSUE THREAD

**Issue by tanujbordikar** [priyankarpal/ProjectsHut#1981]
### `Under GSSOC'23`
1. And this changes are not in the documentation but are in the code.
2. As I visited the site I noticed there is not a parameter of Steps in the code which definitely confuses the user. So I wanted to add the feature of steps. 
3. And also the color color looks too bright which doesn't follow the Standards of WCAG so I wanted to change the font color.
   - Factors affecting due to contrasting text color:
      i. Readability:  Dark text on a light background or light text on a dark background is generally preferred for readability.
      ii. Consistency: Consistency in font colors throughout the website helps create a cohesive user experience.

### Add screenshots

- Before Changes: 
![projectshut_ui](https://github.com/priyankarpal/ProjectsHut/assets/91179998/e8685804-85f9-43aa-9ec2-e447a364a942)
- After Changes:
![projectshut_ui_new](https://github.com/priyankarpal/ProjectsHut/assets/91179998/59d84874-375e-4ef6-9f87-6994b966df70)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you

**Comment by tanujbordikar** [comment]
> remove arrow icons. assigned to you

Okay i will remove that!
