### ISSUE TITLE
Bug: Project showing under a different account

### ISSUE THREAD

**Issue by Judge-Paul** [priyankarpal/ProjectsHut#1984]
### What happened?

One of my projects is being listed under another person's account my project [JobWriteAI](https://github.com/Judge-Paul/jobwrite-ai) is showing under a [different account](https://github.com/mohitparmar1)

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/110723341/dfcf3f8d-c73d-4ee2-8f55-2c314b39bdef)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Judge-Paul could you share your progress on this issue?
