### ISSUE TITLE
feat: Implement "Prefers Reduced Motion" Media Feature for Enhanced Accessibility 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#1991]
### What feature?

- The feature is about to enhance the accessibility of our project by implementing the "Prefers Reduced Motion" media feature. 
- This feature caters to users who experience motion sensitivity or discomfort, ensuring a more comfortable and inclusive user experience.

### What is "Prefers Reduced Motion"?

- "Prefers Reduced Motion" is a media feature in CSS that detects users' preferences for reduced animations and motion effects. When enabled, it informs the website that the user prefers a more static and less animated interface.

### Why Implement "Prefers Reduced Motion"?

- **Enhanced User Comfort**: By respecting users' motion preferences, we create a more enjoyable experience for those who may find motion-heavy interfaces uncomfortable or disorienting.

- **Improved Accessibility**: Supporting "Prefers Reduced Motion" aligns with our commitment to inclusivity, making our project more accessible to users with diverse needs.

- **Compliance with Best Practices**: Implementing this feature demonstrates our dedication to following web accessibility standards, fostering a positive and inclusive digital environment.

### How Does It Work?

- The media feature is used in CSS to apply specific styles when a user prefers reduced motion. This may involve reducing animation durations, disabling certain transitions, or creating static backgrounds.

### Let's Prioritize Accessibility
- At the heart of our project is a commitment to accessibility. By adding the "Prefers Reduced Motion" feature, we can create an environment where everyone can engage with our content comfortably.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/92252895/b03ca706-e9f7-4c77-b994-5227dd4ccfd3

<div align=center>

[Sample working video to demonstrate the motion reducing feature]

</div>

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @priyankarpal 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by priyankarpal** [comment]
but if we make changes, our website's main idea would change. Thank you for understanding

**Comment by 0xabdulkhalid** [comment]
@priyankarpal this change only makes the affects the animations.

In other words, it only disables them. It won't affect any other things on the entire site.

Can i know about this "*our website's main idea would change*" ?
