### ISSUE TITLE
Bug: Add Hover & click Effect to Button 'More' in projects card in projects route

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#1993]
### What happened?

Currently, the button 'More' with arrow lacks a hover effect, which affects the overall user experience. I propose adding a simple hover effect as of left button 'GitHub' has, to enhance the button's interactivity and provide visual feedback to users.

For click effect. I would like to decrease the scale as `scale-95` for both the buttons shown in the project card.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/104740281/69c5ef02-8636-43f6-8767-0b4262359b9a

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
