### ISSUE TITLE
feat: Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [priyankarpal/ProjectsHut#1995]
### What feature?

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

### Add screenshots

na

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
previously we had & currently we don't want to add contributors page
