### ISSUE TITLE
[style]: The Gap on Docs page iss too much

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#1999]
### What's the style idea?

Maybe we should just remove the extra too much space

### Add screenshots

<img width="1411" alt="Screenshot 2023-08-07 at 5 59 05 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/ffbcbd49-3d49-4997-97e4-53b9e2424f94">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it's not needed
