### ISSUE TITLE
🐞Bug: <Documentation button redirects to contributing.md>

### ISSUE THREAD

**Issue by Santhoshmani1** [priyankarpal/ProjectsHut#200]
**Describe the bug**
When pressing the Documentation button, it redirects to contributing.md page into the GitHub.

**To Reproduce**

1. Go to ' the homepage : 'https://projectshut.vercel.app/
2. Click on 'Documentation'
3. Scroll down to 'check out the page'

**Expected behavior**
Instead when clicking on documentation section, redirecting to the readme.md page of the repository makes more sense.
( Or )
A new page can be added to the website itself with a title called as documentation and the content can be added there.

**Additional context**
If the contributing.md file contents are mandatory and must be present then creating seperate button and sections will help the users.

**Comment by priyankarpal** [comment]
hey, @Santhoshmani1 we're creating a new separate page for documentation. You can check the issue 

https://github.com/priyankarpal/ProjectsHut/issues/183

**Comment by Santhoshmani1** [comment]
Okay @priyankarpal 
Then I think it will be good to change  the button name from **Documentation** to **Guidelines for contributing**.
