### ISSUE TITLE
feat: Sharp package recommendation for image optimization in Next.js

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2005]
## Description

Hi there,

I'd like to raise a feature request for the Next.js project. Currently, when using Image Optimization in Next.js for production, a warning message recommends installing the 'sharp' package. This package is known for its efficient image optimization capabilities and is highly recommended by the Next.js team.

To make the optimization process smoother and to ensure users benefit from the best image optimization performance, I propose adding a clearer prompt during the build process, encouraging users to install the 'sharp' package by running 'npm i sharp'.

This small improvement will help users optimize their images more effectively and contribute to better overall performance for Next.js applications.

Thanks for considering this suggestion!

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/eca1bb2a-e6c4-400a-9d45-e96f8bce8240)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@s2sharpit how to see this issue?

**Comment by s2sharpit** [comment]
> @s2sharpit how to check this issue?

@priyankarpal, first you have to build the website locally and after that you have to run the `pnpm start` to preview the build. After that, try to change 2 - 3 route / page. Then, the warning will be visible in the terminal.

**Comment by priyankarpal** [comment]
got it. just we need to install the package ig

**Comment by s2sharpit** [comment]
> got it. just we need to install the package ig

Yup
