### ISSUE TITLE
Bug: Linking issue with external icon in dynamic project route

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2006]
### What happened?

Currently, in the dynamic project route of our GitHub project, the entire project card is hyperlinked to the project's external source, rather than just the external link icon. This setup might lead to some confusion for users and could result in unintended clicks when they try to access the project details.

To improve the user experience and make the link behavior more intuitive, I suggest modifying the project cards so that only the external link icon serves as the hyperlink to the project's external source. The rest of the card area should remain clickable but without the link functionality.

By making this simple adjustment, users will have a clearer indication that the external link icon is responsible for redirecting them to the project's external page, avoiding any accidental clicks that may occur due to the current setup.

I would be happy to contribute and work on implementing this improvement. Let me know if this proposal aligns with your vision for the project. Thank you for considering this enhancement!

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/104740281/2ed55297-195e-461b-a4cb-fd9a246c06cf

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
