### ISSUE TITLE
Bug: Improve image visibility with border in profile section

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2007]
### What happened?

Currently, the profile image in the website is blending with the background, making it difficult to differentiate the image from the website background. To enhance the user interface (UI) and improve image visibility, I suggest adding a subtle border around the profile image.

This small improvement will help create a clear distinction between the image and the background, making it more visually appealing and user-friendly.

Let's enhance the profile section by implementing this change. Thank you for considering this enhancement!

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/33420b44-8655-4649-ad15-98bd5ea6a65d)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah just we need to add a little bit border

**Comment by s2sharpit** [comment]
> yeah just we need to add a little bit border

Yup @priyankarpal
