### ISSUE TITLE
feat: add skeleton effect to `user page` 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#2008]
### What feature?

add skeleton effect according to the `user page` components. You can check existing skeleton effect in this page https://projectshut.vercel.app/projects

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/88102392/f8afb8ad-88de-4871-8d5e-523af528c657

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @priyankarpal, I would like to work on it. Can you assign it to me?

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, I would like to work on it. Can you assign it to me?

sure
