### ISSUE TITLE
Add Docker Image for easier setup 

### ISSUE THREAD

**Issue by Faizan-Alam-1** [priyankarpal/ProjectsHut#2012]
### Add a new project to the list

I would like to propose adding a Docker image to the project.

It will be easier for contributors and users to set up and run the project since they won't have to manually install dependencies.

I would be glad to work on this and create a pull request if the maintainers agree.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Faizan-Alam-1 We aren't utilizing extensive technology, and our project's dependencies are minimal. Therefore, I believe Docker isn't necessary for our project.
