### ISSUE TITLE
feat: Streamlining Social Media Link Collection with GitHub API

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2018]
### What feature?

Hi there,

I've come across a potential enhancement for our social media link collection process. Currently, we manually gather these links from contributors, which can be a bit time-consuming.

However, I've found a solution that might save us time and make things more accurate: the GitHub API. By using a simple GET request to an endpoint like https://api.github.com/users/priyankarpal/social_accounts, we could potentially fetch social media links directly from GitHub profiles.

### Add screenshots

To give you a visual idea, I've attached a screenshot demonstrating a sample API output:

![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/1565a57d-147e-491e-83d0-53acc9a2b001)

I'm eager to hear your thoughts on this approach and whether it's worth exploring further.

Thanks!

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah @s2sharpit correct. we have to show only three social accounts that I already mentioned previously & for custom I think it's not necessary.

**Comment by s2sharpit** [comment]
> yeah @s2sharpit correct.
> 
> we have to show only three social accounts that I already mentioned previously & for custom I think it's not necessary.

Yeah
> * also, we can fetch repository title, description(if user added) from the GitHub API

Yeah Sure

**Comment by s2sharpit** [comment]
Hello @priyankarpal,

I've noticed a minor issue in a few projects where a website link is provided instead of a GitHub URL. As a result, retrieving repository data such as the title and description becomes challenging. To address this, it would be beneficial to update the provided links to GitHub URLs. Additionally, I recommend considering a property name change from link to github_link or github_url. This adjustment would help users clearly understand that the GitHub URL is expected in that field.

On a related note, I've focused my efforts on social accounts within this issue for now.

Check the link of projects in this screenshot:

![image](https://github.com/priyankarpal/ProjectsHut/assets/104740281/db011d2d-f5e2-446e-b13c-e1e7b53d9eec)

**Comment by priyankarpal** [comment]
@s2sharpit 

- yeah we need to change `link` to `github_url`
- need to change to github repo url 
- we can feth github username through the repo url so I think we need to remove `github_username`

**Comment by s2sharpit** [comment]
> @s2sharpit
> 
> * yeah we need to change `link` to `github_url`
> * need to change to github repo url
> * we can feth github username through the repo url so I think we need to remove `github_username`

Hey @priyankarpal, I would suggest work on removing `github_username` in future, not now. I would suggest to work on it after fixing the github repo URL with separate PR as there will be big changes in logic because at present we are using the github username to fetch details like profile picture, bio, social accounts, etc.

**Comment by priyankarpal** [comment]
> > @s2sharpit
> > 
> > * yeah we need to change `link` to `github_url`
> > * need to change to github repo url
> > * we can feth github username through the repo url so I think we need to remove `github_username`
> 
> Hey @priyankarpal, I would suggest work on removing `github_username` in future, not now. I would suggest to work on it after fixing the github repo URL with separate PR as there will be big changes in logic because at present we are using the github username to fetch details like profile picture, bio, social accounts, etc.

yeah
