### ISSUE TITLE
💡feat: Add custom 404 page

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#202]
- We need to add a custom 404 error page. 
- When users type the wrong query it will show a custom 404 page
- In the 404 error page there will be a home button to return home page

**Comment by Saurav-Pant** [comment]
assign it to me I will work on it @priyankarpal

**Comment by Saurav-Pant** [comment]
how is this, is any problem let me know
https://user-images.githubusercontent.com/103263909/232397773-98ac7b40-8236-4f14-900b-ec69604ac3bf.mp4

**Comment by priyankarpal** [comment]
> how is this, is any problem let me know @priyankarpal https://user-images.githubusercontent.com/103263909/232397773-98ac7b40-8236-4f14-900b-ec69604ac3bf.mp4

Looks Good 🎉 just change the bg to `#000513`

**Comment by priyankarpal** [comment]
> in tailwind how do I add this color? or I will add a similar tailwind class for that like bg-gray-950.

bg-[#000513]

**Comment by Saurav-Pant** [comment]
what should I write the name of a component?

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
