### ISSUE TITLE
feat: Adding animation to the text on the home screen.

### ISSUE THREAD

**Issue by AdityaLahane-2003** [priyankarpal/ProjectsHut#2022]
### What feature?

Adding animation to the text on the home screen.

### Add screenshots

![1](https://github.com/priyankarpal/ProjectsHut/assets/108022893/c26d70b3-724a-4c9f-9d66-d97a05559541)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@AdityaLahane-2003 I think it's better to keep things simple, especially since we've already included animations
