### ISSUE TITLE
feat: Add PWA (Progressive web app) in ProjectsHut

### ISSUE THREAD

**Issue by SubhamB2003** [priyankarpal/ProjectsHut#2028]
### What feature?

Hey, I want to add the PWA to this site so it's also installable.
If you need this feature then can you please assign it to me?

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/94003231/cd5f52a6-885d-49cc-8c53-d354ae2cec5e)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah @SubhamB2003  we can do this assigned to you
