### ISSUE TITLE
chore: project addition by Subham

### ISSUE THREAD

**Issue by SubhamB2003** [priyankarpal/ProjectsHut#2029]
### Add a new project to the list

I want to add my react firebase email password and Google authentication project.
Can I add?

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
could you share your progress on this issue?
