### ISSUE TITLE
chore: project addition by Subham

### ISSUE THREAD

**Issue by SubhamB2003** [priyankarpal/ProjectsHut#2030]
### Add a new project to the list

Hey, I want to my Add Tic Tac Toe project and Url to Qr code generator project.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@SubhamB2003 please make sure that we are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)
