### ISSUE TITLE
chore: project addition by Deepanshu

### ISSUE THREAD

**Issue by Deepanshu0703** [priyankarpal/ProjectsHut#2034]
### Add a new project to the list

I want to add a college canteen website made using html css javascript and php.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@Deepanshu0703 please make sure that we are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by priyankarpal** [comment]
could you share your progress on this issue?
