### ISSUE TITLE
Front End IDE

### ISSUE THREAD

**Issue by piyushkhurana2019** [priyankarpal/ProjectsHut#2035]
### Add a new project to the list

It is a Front end code IDE which have colour syntax, error detection and many more features, it supports HTML, CSS, JS codes and displays there outputs in the window below
tech stack used:- React, HTML, CSS, JS

<img width="1440" alt="Screenshot 2023-08-06 at 6 47 13 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/96003210/4af72881-7a2e-424b-974e-c3fd6ecab718">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@piyushkhurana2019 I think you can add projects in a single PR you don't need to create 7 times issues for 7 projects. Also, if you're a GSSoC contributor we are not providing any labels for project additions as they are not associated with solving any issues.( according to gssoc23 rules)

**Comment by piyushkhurana2019** [comment]
Sure,
if i will add my projects, my score won't increase?

**Comment by priyankarpal** [comment]
could you share your progress on this issue?
