### ISSUE TITLE
feat: [STEP1] Use framer-motion in server components

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2045]
### What feature?

# Leveraging Next.js 13 App Router for Enhanced SEO and Page Load Speed

## Issue:
I've observed that a significant portion of our components are currently designed for client-side rendering. Given the recent integration of Next.js 13's App Router, I propose a beneficial shift towards utilizing its new capabilities. By transitioning more components into server components, we can potentially achieve improved SEO performance and faster page loading times.

## Proposal:
To ensure a seamless transition, I'm suggesting a step-by-step approach. Currently, our components leveraging Framer Motion are categorized as client components. However, I believe it's worth exploring the possibility of incorporating Framer Motion within server components. This adjustment could further optimize our application's rendering process and contribute to our broader goal of enhancing user experience.

Let's collaborate on this initiative, starting with the migration of Framer Motion-dependent components into the realm of server components. This incremental approach will allow us to evaluate the impact on performance, SEO, and overall user satisfaction, while maintaining control over the scope of changes.

I'm excited about the potential of this enhancement and look forward to discussing the feasibility and implementation details with the team. Your thoughts and feedback on this proposal would be greatly appreciated.

Thank you,
[Your Name]

### Add screenshots

.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure
