### ISSUE TITLE
docs: Typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Sriparno08** [priyankarpal/ProjectsHut#2047]
### what's wrong with the documentation?

In the below sentence, 'go ahead' is wrongly written as 'do ahead'.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/89148144/3e5f132b-1507-47d0-a732-3c68d068a7e9)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
