### ISSUE TITLE
[Refactor] Update "link" to "github_url" in JSON file and Correct False URL

### ISSUE THREAD

**Issue by s2sharpit** [priyankarpal/ProjectsHut#2049]
### File Name

DB/projects.json

### Reason for Refactoring the Code

In the current JSON file structure, there is a key named "link" that is being used to store GitHub repository URLs. It would be more intuitive and consistent to use the key name "github_url" instead.

Additionally, there is an incorrect URL stored under the "github_url" key for a specific entry in the JSON file. This URL needs to be corrected to ensure accurate and functional links.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
