### ISSUE TITLE
[style]:  Add stylish Scrollbar

### ISSUE THREAD

**Issue by piyushkhurana2019** [priyankarpal/ProjectsHut#2059]
### What's the style idea?

The website UI is very beautiful, just there is one thing which can enhance its beauty to a great extent that is scroll bar.
I want to add a stylish scroll bar to the website so that it looks more eye catching to the users

<img width="1424" alt="Screenshot 2023-08-10 at 6 49 51 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/96003210/c97fea6b-14d2-4988-8bbb-2b8c9e4cae06">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it's not necessary

**Comment by piyushkhurana2019** [comment]
Sure Sir, is there anything else that i can fix or contribute?

**Comment by priyankarpal** [comment]
> Sure Sir, is there anything else that i can fix or contribute?

GSSoC has ended. If you still want to contribute please wait few days we will create issues or you can create issues if you find any bugs or want to add new feature that will help this project.
