### ISSUE TITLE
feat: Automatic setup the workspace in codespaces 

### ISSUE THREAD

**Issue by PriyansuMaurya** [priyankarpal/ProjectsHut#2060]
### What feature?

I would love to add `.devcontainer/devcontainer.json`

- A `devcontainer.json` file can **install tools** and **runtimes**, and perform **other setup tasks** that the project requires.
- It installs **all the dependencies** and **runs the project automatically**, allowing the developer to **concentrate on coding**.
- A `devcontainer.json` file can be used to configure the development container for both codespaces and local development using Visual Studio Code.

### Add screenshots

You can try how it works by creating a codespace on the **main** branch in this repository.

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/e6a0289a-420d-4e07-8619-fb9dffc56f82)

Here is the link to the repo :https://github.com/PriyansuMaurya/Rick-and-Morty-App

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PriyansuMaurya** [comment]
@priyankarpal , do you have any idea of this error?

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/1841d158-5450-45c7-9a00-b977ac61f047)

**Comment by priyankarpal** [comment]
currently no. Please check the link that is mentioned

**Comment by PriyansuMaurya** [comment]
I have checked, but I am not understanding what the issue is.

This problem persists in all the development environments irrespective of the operating system.

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/b3f04321-20f9-40d2-96da-53a8d36a7701)


When I replace `npm dev` with `pnpm run build` and `pnpm run start`, everything works as expected. For now, I would say let's keep it this way. In the future, we would make changes if we find a solution.
