### ISSUE TITLE
[style]: Adding type writer effect

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2075]
### What's the style idea?

we can add an type writer effect on the search for cools projects text on projects page

### Add screenshots

<img width="785" alt="Screenshot 2023-08-18 at 7 36 07 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/912e5a77-0d5f-468b-882b-67067c95c35b">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it's unwanted
