### ISSUE TITLE
feat:Addition of Tailwind css as an filter would be nice

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2076]
### What feature?

I have been searching for projects that use Tailwind CSS, but it has been a hassle. Perhaps we should add a filter for this and more if you have any ideas.

### Add screenshots

<img width="481" alt="Screenshot 2023-08-18 at 7 56 49 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/1b5ac04f-2cee-46bc-a115-cbc8d0b1eec8">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure assigned
