### ISSUE TITLE
feat:Addition of link of user github account will be great 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2077]
### What feature?

As per the UX we should do this add an link thats redirects to the users github account 

### Add screenshots

<img width="385" alt="Screenshot 2023-08-18 at 8 00 41 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/d776a243-2709-45a9-93da-4265759dc6ab">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have user's page where we have added github link so I think we don't need to add here.
