### ISSUE TITLE
feat: Addtion of links to the official pages / documents of the tech stack 

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2078]
### What feature?

The feature will assist users in redirecting to the official documentation. This functionality can help new users learn and understand the meaning of the tech stack using the official documentation.

### Add screenshots

<img width="478" alt="Screenshot 2023-08-18 at 8 06 33 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/109215419/53868822-95c3-4b32-8c3d-eaf7a5d7eb2c">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
it's unwanted
