### ISSUE TITLE
[style]: Fix Search Bar in Projects Page

### ISSUE THREAD

**Issue by freedompraise** [priyankarpal/ProjectsHut#2090]
### What's the style idea?

If a user is scrolling through the projects, and decides to rather search, he has to manually scroll back up to be able to search. 
I suggest making the search bar fixed to make things easier

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [x] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
if we do this it will change the UI

**Comment by freedompraise** [comment]
Yeah, I just noticed that, but I think it shouldn't be entirely ruled out.
For example, and icon that toggles the search bar could be put somewhere further upwards, like the Navbar
