### ISSUE TITLE
docs: Typo in Issue Template

### ISSUE THREAD

**Issue by freedompraise** [priyankarpal/ProjectsHut#2091]
### what's wrong with the documentation?

The tag for the option of selecting a `Style Changing Request` issue type wrongly reads
"Suggest a Style designs", rather than "Suggest a Style design".

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/70984186/59aa640c-929e-4d1e-9544-8bc78c1d3c19)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [ ] I want to work on this issue

**Comment by priyankarpal** [comment]
remove the text `Suggest a style designs`

**Comment by freedompraise** [comment]
> remove the text `Suggest a style designs`

Yeah, I want to rather replace it with `Suggest a style design`
