### ISSUE TITLE
feat: adding step by step video process of making an pull request in contrubution.md or on the website

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2094]
### What feature?

There are many beginners who find it very difficult to pull, push, and clone, and we need to create a proper video or something on the demonstrate of that will help the newbies

### Add screenshots

just an suggestion no ss

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yup we can do this too. 👏🏻 we need to add the video to the contributing guide. assigned to you

**Comment by Sahilll15** [comment]
cool

**Comment by Sahilll15** [comment]
@priyankarpal, should I create an issue for adding new projects? It will help me demonstrate properly.

**Comment by priyankarpal** [comment]
> @priyankarpal, should I create an issue for adding new projects? It will help me demonstrate properly.

yeah sure
