### ISSUE TITLE
Redesign the heading

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#21]
### Just need to redesign the heading 

![image](https://user-images.githubusercontent.com/88102392/219881365-fcdbc97d-1db0-4052-8de1-c2274da792cb.png)

**Comment by ujjawaltyagii** [comment]
is it OK if we add some changes in style of sub-heading too along with heading to make it look good overall ??

**Comment by priyankarpal** [comment]
> is it OK if we add some changes in style of sub-heading too along with heading to make it look good overall ??

yeah, you can work on it &  don't forget to add a screenshot.

**Comment by Vijaykv5** [comment]
Could you assign this issue to me?

**Comment by priyankarpal** [comment]
> Could you assign this issue to me?

Work on it
