### ISSUE TITLE
feat: Loading projects should be made optional to some extend

### ISSUE THREAD

**Issue by xmayukx** [priyankarpal/ProjectsHut#2113]
### What feature?

I think the project route should be modified with a `Load-more` option where 10-20 projects will be fetched at each request, or we can implement pagination.

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/89103181/60bbe32a-cfca-4e76-b786-b033b15e934d

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@xmayukx we have to add a `load more` button. Previously we had pagination

**Comment by thevinitgupta** [comment]
I would love to work on this.

**Comment by priyankarpal** [comment]
@xmayukx Can you update me on the progress of this particular issue?

**Comment by xmayukx** [comment]
I'm gonna create a PR by tomorrow
