### ISSUE TITLE
feat: add angular to techStack

### ISSUE THREAD

**Issue by lorenzomiscoli** [priyankarpal/ProjectsHut#2116]
### What feature?

Right now you cannot filter for angular but there's at least 1 project done with it so it makes sense to be able to filter for Angular.

### Add screenshots

![angular-tech-stack](https://github.com/priyankarpal/ProjectsHut/assets/65784008/d7b17094-be05-4cb1-b2e2-565e678b96f5)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
