### ISSUE TITLE
🐞Bug: <Heading Font size and line height >

### ISSUE THREAD

**Issue by jayk-gupta** [priyankarpal/ProjectsHut#212]
**Describe the bug**
Show your project to the world heading line height and font size at md and lg screens needs to be fixed.

**Comment by Ahtaxam** [comment]
can i work on this issue? That would be my first contribution in this project.

**Comment by priyankarpal** [comment]
> can i work on this issue? That would be my first contribution in this project.

@jayk-gupta created the PR. If you want to contribute your first code to this repo you can add your projects here. Check the documentation for more information https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md

**Comment by Ahtaxam** [comment]
@priyankarpal Contributed new Project and Open PR
