### ISSUE TITLE
Bug: In that project page if you haven't selected any filter still there is that clear filter button

### ISSUE THREAD

**Issue by Monilprajapati** [priyankarpal/ProjectsHut#2125]
### What happened?

There is one filter function in project page but it should work like whenever we add some filters then and then it needs to show a clear filter button but here it is a static button like whether there is a filter or not.

I can solve this issue and would love to contribute in your project.

### Add screenshots

Issue Preview: Filter section :  clear

![image](https://github.com/priyankarpal/ProjectsHut/assets/99136041/1c634e92-5e03-42be-a2c0-2ada021e4d01)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
good spot @Monilprajapati 👏🏻

**Comment by Monilprajapati** [comment]
> good spot @Monilprajapati 👏🏻

I have done with the Issue but I am facing an issue in commit phase as I am new to nextJs and this thing commitlint. It shows me this error what should i do ?
```
 PS C:\Users\Monil Prajapati\Desktop\OS\ProjectsHut> git commit -m "Issue2125"

> next-migrate@0.1.0 commitlint C:\Users\Monil Prajapati\Desktop\OS\ProjectsHut
> commitlint --edit ".git/COMMIT_EDITMSG"

⧗   input: Issue2125
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

 ELIFECYCLE  Command failed with exit code 1.
husky - commit-msg hook exited with code 1 (error) 
```

**Comment by Monilprajapati** [comment]
Yeah @priyankarpal I have done with this Issue [PR : #2126 ] and got to learn about commitlint. 🤝
