### ISSUE TITLE
[style]: change the twitter icon to X

### ISSUE THREAD

**Issue by Sahilll15** [priyankarpal/ProjectsHut#2127]
### What's the style idea?

As Twitter has updated their logo i guess we should do it too

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned
