### ISSUE TITLE
feat:Adding an hover Animation effect

### ISSUE THREAD

**Issue by Vijaykv5** [priyankarpal/ProjectsHut#2159]
### What feature?

What about adding an hover effect on the Project card 

### Add screenshots

<img width="1398" alt="Screenshot 2023-10-01 at 12 39 38 AM" src="https://github.com/priyankarpal/ProjectsHut/assets/94985341/bb551ebd-6026-4a4d-bff9-3cb0cfc1645d">

When user **hovers** on the respective cards, adding an animation like

>  pop out

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think this simple border hover effect is looking good.

**Comment by Vijaykv5** [comment]
Okayy
