### ISSUE TITLE
🐞Bug: product card overflow due to excess tech items

### ISSUE THREAD

**Issue by SteveSayantan** [priyankarpal/ProjectsHut#216]
**Describe the bug**
Too many items in the tech-stack are causing overflow of product card.

**Expected behavior**
We should only display the top three technologies used, instead of displaying all of those for a particular project.

**Screenshots**
![product-card-overflow](https://user-images.githubusercontent.com/92118155/233614039-faed1e6c-aab9-4b5f-8da7-4927bb3591de.JPG)

**Comment by priyankarpal** [comment]
> **Describe the bug** Too many items in the tech-stack are causing overflow of product card.
> 
> **Expected behavior** We should only display the top three technologies used, instead of displaying all of those for a particular project.
> 
> **Screenshots** ![product-card-overflow](https://user-images.githubusercontent.com/92118155/233614039-faed1e6c-aab9-4b5f-8da7-4927bb3591de.JPG)

thank you for opening the issue. I fixed this problem already you can check. if there any problem you can tell us.
![image](https://user-images.githubusercontent.com/88102392/233639871-6de263d1-924c-4124-91b5-71d724866e96.png)

**Comment by SteveSayantan** [comment]
This is fine, but there should be a limit on the number of tech-items...What do you think?

**Comment by priyankarpal** [comment]
> This is fine, but there should be a limit on the number of tech-items...What do you think?

yes, I'm also thinking.

**Comment by SteveSayantan** [comment]
We can allow only the first three items, and for the rest of the items we can show `+2` like this...

**Comment by priyankarpal** [comment]
> We can allow only the first three items, and for the rest of the items we can show `+2` like this...

okk

**Comment by priyankarpal** [comment]
assigning to you

**Comment by SteveSayantan** [comment]
Take a look at this, lemme know if any changes are necessary . 
![maxTechItemsImplemented](https://user-images.githubusercontent.com/92118155/234880060-0430925b-3345-47a5-8d68-961a78a641bc.JPG)

**Comment by priyankarpal** [comment]
ok looks good. 

is it clickable?

**Comment by SteveSayantan** [comment]
> ok looks good.
> 
> is it clickable?

No, it isn't. But in that case, we shall have the same issue of so many tech items in the card.

**Comment by priyankarpal** [comment]
ok just create a PR I will check it soon

**Comment by SteveSayantan** [comment]
> ok just create a PR I will check it soon

Here it is
