### ISSUE TITLE
feat: it's not mobile responsive 

### ISSUE THREAD

**Issue by Ankitmohanty2** [priyankarpal/ProjectsHut#2169]
### What feature?

I want to contribute through hacktoberfest23 will u assign me

### Add screenshots

notes_img

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
please elaborate on your issue with responsiveness & this project is not in hacktoberfest
