### ISSUE TITLE
feat: Add sort by name feature for projects

### ISSUE THREAD

**Issue by singodiyashubham87** [priyankarpal/projectshut#2174]
### What feature?

Currently, there is no option for sorting the projects in alphabetical order if the user wants to.
I want to incorporate this functionality in the application.

Kindly assign me this issue for hacktoberfest'23

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/93720428/c0e74e37-34ed-4ef8-ba53-35914ee7e5ce)
![image](https://github.com/priyankarpal/ProjectsHut/assets/93720428/adf545f5-e8f7-448e-9f65-ca36f164a666)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
there is already a sorting feature why do we need to add alphabetical sorting? also, the 

https://github.com/priyankarpal/ProjectsHut/assets/88102392/a53dc5de-30e9-4fc1-addb-df810bbc0f3c

project is not under hacktoberfest.

**Comment by singodiyashubham87** [comment]
> there is already a sorting feature why do we need to add alphabetical sorting? also, the project is not under hacktoberfest.
> 
>  2023-10-08_08-57-19.mp4

Okay Got it..

By the way, I was thinking of adding labels to project details
Like here is written HTML, CSS, JS; It will be better if before all this we add a label 'Tech Stack', Same for Project Title and Description; It will make the UX better.
![image](https://github.com/priyankarpal/ProjectsHut/assets/93720428/dea2ceb3-26b5-48f7-b1f4-eb7d1340c255)

**Comment by priyankarpal** [comment]
> > there is already a sorting feature why do we need to add alphabetical sorting? also, the project is not under hacktoberfest.
> > 2023-10-08_08-57-19.mp4
> 
> Okay Got it..
> 
> By the way, I was thinking of adding labels to project details Like here is written HTML, CSS, JS; It will be better if before all this we add a label 'Tech Stack', Same for Project Title and Description; It will make the UX better. ![image](https://user-images.githubusercontent.com/93720428/273431203-dea2ceb3-26b5-48f7-b1f4-eb7d1340c255.png)

yeah we can do

**Comment by singodiyashubham87** [comment]
> > > there is already a sorting feature why do we need to add alphabetical sorting? also, the project is not under hacktoberfest.
> > > 2023-10-08_08-57-19.mp4
> > 
> > 
> > Okay Got it..
> > By the way, I was thinking of adding labels to project details Like here is written HTML, CSS, JS; It will be better if before all this we add a label 'Tech Stack', Same for Project Title and Description; It will make the UX better. ![image](https://user-images.githubusercontent.com/93720428/273431203-dea2ceb3-26b5-48f7-b1f4-eb7d1340c255.png)
> 
> yeah we can do

Kindly assign me this issue then.

**Comment by priyankarpal** [comment]
hello @singodiyashubham87 now you can work your issues
