### ISSUE TITLE
feat: Add load more button in the projects section

### ISSUE THREAD

**Issue by singodiyashubham87** [priyankarpal/projectshut#2175]
### What feature?

If we scroll down in the projects page then the projects keep on loading and new projects are refreshed every time hence I'm not able to see the footer part of the application.

I want to fix this by adding a load more button to the web app so that whenever the user clicks on the load more button only more projects will be shown.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/93720428/19ec7f6a-f346-4fe5-865b-8fb94eda3fc9)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
yeah! we can do this. assigned
