### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#218]
It will be more attractive if we give contributors a box and also adding a arrow beside it..

![Screenshot from 2023-04-21 18-21-29](https://user-images.githubusercontent.com/108119109/233641882-92506a4e-f3e5-405d-9254-4021f1bd7eed.png)

**Comment by Bharadwajshivam28** [comment]
ya sharing now give me 10 mins

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-21 18-51-12](https://user-images.githubusercontent.com/108119109/233647123-18b763dc-9730-4178-a4e3-83b4c1927447.png)
![Screenshot from 2023-04-21 18-51-18](https://user-images.githubusercontent.com/108119109/233647134-90544d81-a298-4128-9582-0e62c5f75551.png)

**Comment by priyankarpal** [comment]
> ![Screenshot from 2023-04-21 18-51-12](https://user-images.githubusercontent.com/108119109/233647123-18b763dc-9730-4178-a4e3-83b4c1927447.png) ![Screenshot from 2023-04-21 18-51-18](https://user-images.githubusercontent.com/108119109/233647134-90544d81-a298-4128-9582-0e62c5f75551.png)

first one

**Comment by Bharadwajshivam28** [comment]
okay
