### ISSUE TITLE
chore: project addition by 

### ISSUE THREAD

**Issue by Sakhi29** [priyankarpal/ProjectsHut#2186]
### Add a new project to the list

I want to add my projects

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Thank you for your contributions! We appreciate your efforts and value your support. Congratulations on a job well done! ❤️🎉
