### ISSUE TITLE
feat: Create an about us page

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#220]
We can build a about page. The About page will contain information about ProjectsHut, including the project's history, goals, and features.

**Comment by priyankarpal** [comment]
> We can build a about page. The About page will contain information about ProjectsHut, including the project's history, goals, and features.

great idea. +1 assigning to you

**Comment by Bharadwajshivam28** [comment]
thanks

**Comment by Bharadwajshivam28** [comment]
Hello @priyankarpal I have created a About Page and i have kept it as simple as like it have the details of Projects but it is very simple..

![Screenshot from 2023-04-24 00-26-46](https://user-images.githubusercontent.com/108119109/233859556-ef45c642-bc45-4688-9487-20cd83081a8f.png)

**Comment by Bharadwajshivam28** [comment]
I will make the footer down

**Comment by priyankarpal** [comment]
add texts to the center

**Comment by Bharadwajshivam28** [comment]
> add texts to the center

Okay 👍 any more changes?

**Comment by priyankarpal** [comment]
> > add texts to the center
> 
> Okay +1 any more changes?

create a PR I will check

**Comment by Bharadwajshivam28** [comment]
> > > add texts to the center
> > 
> > Okay +1 any more changes?
> 
> create a PR I will check 

Okay I will create by evening currently I am in class

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-24 19-53-06](https://user-images.githubusercontent.com/108119109/234026958-f9ff47fa-2661-48ef-be2b-c502c74e8872.png)

Suggest me one thing that in this ScreenShot we love ProjectsHut is not looking good in about page we can move it in the footer... What say? If in footer then where it will look good in footer @priyankarpal

**Comment by priyankarpal** [comment]
try to change to footer text `proudly open source`

**Comment by priyankarpal** [comment]
> can you drop some good resource which can help in creating about page for mobile view

don't need to do it just add the link & it will automatically add

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-25 22-05-53](https://user-images.githubusercontent.com/108119109/234345471-2ca6f0d8-8c00-4470-872f-c30243d183e5.png)
![Screenshot from 2023-04-25 22-06-30](https://user-images.githubusercontent.com/108119109/234345484-5d0194a6-c731-4822-9fcb-68698f968459.png)

@priyankarpal These are 2 ss one is with more emoji and other one is of less emoji which is more good??

**Comment by priyankarpal** [comment]
Use 2nd ss & use left align for text but middle position

**Comment by Bharadwajshivam28** [comment]
okay got it

**Comment by Bharadwajshivam28** [comment]
@priyankarpal facing issue while doing it

![Screenshot from 2023-04-25 22-23-12](https://user-images.githubusercontent.com/108119109/234348449-1b95da14-4487-4563-b962-63fd6feb7cb7.png)

I am using this code:

<div class="flex justify-start items-center">
  <p class="text-left mx-auto">Text here</p>
</div>

**Comment by priyankarpal** [comment]
take your time & build it. It's not urgent. 🥲💀

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by priyankarpal** [comment]
The demo about page should be like this. Add image to the right side


![image](https://user-images.githubusercontent.com/88102392/234355760-6920ff5f-05dd-4764-9dee-c525d18402e3.png)

**Comment by Bharadwajshivam28** [comment]
okay which image to add???

**Comment by priyankarpal** [comment]
> okay which image to add???

you can find coding images on Unsplash

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
> The demo about page should be like this. Add image to the right side
> 
> ![image](https://user-images.githubusercontent.com/88102392/234355760-6920ff5f-05dd-4764-9dee-c525d18402e3.png)

all the text in about should be like this same correct??

**Comment by priyankarpal** [comment]
> > The demo about page should be like this. Add image to the right side
> > ![image](https://user-images.githubusercontent.com/88102392/234355760-6920ff5f-05dd-4764-9dee-c525d18402e3.png)
> 
> all the text in about should be like this same correct??

I just gave you an idea.

**Comment by Bharadwajshivam28** [comment]
okay i will work on it

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-26 00-15-15](https://user-images.githubusercontent.com/108119109/234373723-21cfd61c-9c13-4616-834e-e1869dbcc978.png)

@priyankarpal I am thinking to end our about page like this .. Aligning text with a coding image this is unique style as in our project this is will first unique design

**Comment by priyankarpal** [comment]
> ![Screenshot from 2023-04-26 00-15-15](https://user-images.githubusercontent.com/108119109/234373723-21cfd61c-9c13-4616-834e-e1869dbcc978.png)
> 
> @priyankarpal I am thinking to end our about page like this .. Aligning text with a coding image this is unique style as in our project this is will first unique design

show the full design

**Comment by Bharadwajshivam28** [comment]
> > ![Screenshot from 2023-04-26 00-15-15](https://user-images.githubusercontent.com/108119109/234373723-21cfd61c-9c13-4616-834e-e1869dbcc978.png)
> > 
> > @priyankarpal I am thinking to end our about page like this .. Aligning text with a coding image this is unique style as in our project this is will first unique design
> 
> show the full design

Okay I will share it by tomorrow currently I am suffering from fever so taking rest

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-26 17-20-05](https://user-images.githubusercontent.com/108119109/234566383-0bf8832e-add2-4076-8790-163317d4980b.png)

@priyankarpal This design is unique and good looking also... What say?

**Comment by priyankarpal** [comment]
> ![Screenshot from 2023-04-26 17-20-05](https://user-images.githubusercontent.com/108119109/234566383-0bf8832e-add2-4076-8790-163317d4980b.png)
> 
> @priyankarpal This design is unique and good looking also... What say?

it's looking overwhelming. I previously gave you a sample design idea to try to make it like that.

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
@priyankarpal  I tried designs but none of them was so good like the previous one i shared.. That one was more good

**Comment by priyankarpal** [comment]
> @priyankarpal I tried designs but none of them was so good like the previous one i shared.. That one was more good

I will work on it soon

**Comment by Bharadwajshivam28** [comment]
> > @priyankarpal I tried designs but none of them was so good like the previous one i shared.. That one was more good
> 
> I will work on it soon 

Okay 👍
