### ISSUE TITLE
chore: project addition by Ayan-Joshi

### ISSUE THREAD

**Issue by ayan-joshi** [priyankarpal/ProjectsHut#2211]
### Add a new project to the list

I want to add PING PONG multiplayer game , 
Tech stacks used are javascript  , html and css

Assign it to me @priy

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by ayan-joshi** [comment]
@priyankarpal if I want to add a new project , I have to add in this issue only ?

**Comment by priyankarpal** [comment]
> @priyankarpal if I want to add a new project , I have to add in this issue only ?

yeah.

**Comment by ayan-joshi** [comment]
> > @priyankarpal if I want to add a new project , I have to add in this issue only ?
> 
> yeah.

So I'm adding two projects
