### ISSUE TITLE
chore: project addition by Ayan-Joshi

### ISSUE THREAD

**Issue by ayan-joshi** [priyankarpal/ProjectsHut#2212]
### Add a new project to the list

I want to add a new project Sorting Visualizer , 
Assign me this issue so I can start my work @priyankarpal 

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
duplicate of #2211
