### ISSUE TITLE
💡feat: create a navbar

### ISSUE THREAD

**Issue by HarshPanchal26** [priyankarpal/ProjectsHut#222]
I just cloned a repo for ProjectHut  and found it great  , I have a one thought that , If we can add a navbar which contains  various pages of application for redirect to one form another would be grate .

  If I am on right way we will can make a navbar for 
  1 . Project Page 
  2 . ContributorsPage
  3 . Add your project guide
  4. Would about us page 
  
  And If we will add further pages , It will easier to maintain at that time too . 
  
  I am would like to do it , Can you assign it to me ?

**Comment by priyankarpal** [comment]
> ```
> I just cloned a repo for ProjectHut  and found it great  , I have a one thought that , If we can add a navbar which contains  various pages of application for redirect to one form another would be grate .
> ```
> 
> If I am on right way we will can make a navbar for 1 . Project Page 2 . ContributorsPage 3 . Add your project guide 4. Would about us page
> 
> And If we will add further pages , It will easier to maintain at that time too .
> 
> I am would like to do it , Can you assign it to me ?

yes. I'm also thinking about this feature. 
You can work on it 🤝

**Comment by HarshPanchal26** [comment]
Ok ,I will work on it now.

**Comment by HarshPanchal26** [comment]
Is this ok If I used of material UI for  fixing some issues ?

**Comment by priyankarpal** [comment]
> Is this ok If I used of material UI for fixing some issues ?

ok no problem.

**Comment by HarshPanchal26** [comment]
I do it in this way 

![Screenshot (200)](https://user-images.githubusercontent.com/95937722/233773017-e31de62e-abc7-4c60-b894-388643a48f66.png)


![Screenshot (201)](https://user-images.githubusercontent.com/95937722/233773029-bfab5a1a-7aae-4da9-8778-1cdae666b3cf.png)


Is it looking fine ?

**Comment by priyankarpal** [comment]
looks good. just share responsive mode.

**Comment by HarshPanchal26** [comment]
Ya sure . 

Here it is 
![Screenshot (203)](https://user-images.githubusercontent.com/95937722/233774959-842166ce-a6f0-4b57-8031-897f9d8aafa8.png

**Comment by priyankarpal** [comment]
> Ya sure .
> 
> Here it is ![Screenshot (203)](https://user-images.githubusercontent.com/95937722/233774959-842166ce-a6f0-4b57-8031-897f9d8aafa8.png

ok but we can add drop-down menu too

**Comment by HarshPanchal26** [comment]
Working on it . 

And I need one help , I got one error while commit time , that 
"Husky pre-commit fails with code 1 (error)" 

can you help me with this ?

**Comment by priyankarpal** [comment]
> Working on it .
> 
> And I need one help , I got one error while commit time , that "Husky pre-commit fails with code 1 (error)"
> 
> can you help me with this ?

send me the screenshots

**Comment by HarshPanchal26** [comment]
I think it is because of commit-convention in eslint file .


Here is screen short 

![Screenshot (204)](https://user-images.githubusercontent.com/95937722/233775921-345f3dac-a0d2-4c6e-bf48-4ded5941d385.png)

**Comment by priyankarpal** [comment]
just format the code using `pnpm format`. Whenever you face this same problem use this command.

**Comment by HarshPanchal26** [comment]
Did this for Mobile Screen  and small size Screen 

![Screenshot (205)](https://user-images.githubusercontent.com/95937722/233780817-d1f9f7f1-83b1-4381-8ef9-370730458efc.png)
![Screenshot (206)](https://user-images.githubusercontent.com/95937722/233780820-4fb61e37-51ee-4029-b2cd-9ac1338df9fb.png)

**Comment by priyankarpal** [comment]
cool

**Comment by HarshPanchal26** [comment]
Ok , Anything else you want to add  ?

**Comment by priyankarpal** [comment]
> Ok , Anything else you want to add ?

is there any `X` button for closing?

**Comment by HarshPanchal26** [comment]
When you click outside it or any of the option it close itself .   But If u want we can add it

**Comment by priyankarpal** [comment]
> When you click outside it or any of the option it close itself . But If u want we can add it

ok. I would recommend you to add this.

**Comment by HarshPanchal26** [comment]
![Screenshot (207)](https://user-images.githubusercontent.com/95937722/233788721-926cc543-9f30-4545-a9b1-51f21a84e323.png)

Now ?

**Comment by priyankarpal** [comment]
> ![Screenshot (207)](https://user-images.githubusercontent.com/95937722/233788721-926cc543-9f30-4545-a9b1-51f21a84e323.png)
> 
> Now ?

cool  Create  a PR

**Comment by HarshPanchal26** [comment]
Just made it . Check it and let me know if there is any issue .

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
