### ISSUE TITLE
Adding the Super Mario Game to this Project

### ISSUE THREAD

**Issue by Sch476** [priyankarpal/projectshut#2223]
### Add a new project to the list

I have a js project of the super mario game and I want to add it to this repo. 

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
hello @Sch476 any updates?
