### ISSUE TITLE
docs: add hacktober fest to readme

### ISSUE THREAD

**Issue by barkhaaroraa** [priyankarpal/ProjectsHut#2224]
### what's wrong with the documentation?

Saw that this repo was a part of gssoc, since it’s also a part of hacktober fest, I’d like to add that to the readme

### Add screenshots

![IMG_2222](https://github.com/priyankarpal/ProjectsHut/assets/115429121/24579c7b-5c24-4d8c-9004-3e42c099d22c)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@barkhaaroraa this project is not the part of hacktoberfest so we don't need to add
