### ISSUE TITLE
💡feat:  add Search Functionality

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#223]
**Feature.**
I wanted to suggest that we add a search functionality to our  project. This would allow users to easily search for and find specific Project  within the projects making it more user-friendly and convenient. 

**Solution**
We can make Navbar of used technologies in projects if someone want to see project of a specific technology. Just Click on It and below he can see related Projects. 

i would like to do it. can you assign it tome?

**ScreenShoot**
![White and Yellow Minimalist Pixalated Motivational Quote Phone Wallpaper](https://user-images.githubusercontent.com/64573767/233770645-c1b1509f-6e31-4e00-aa40-e5755e8c9c8e.png)

**Comment by priyankarpal** [comment]
you can work on it.

**Comment by Ahtaxam** [comment]
Ok i will
