### ISSUE TITLE
chore: project addition by blindaks

### ISSUE THREAD

**Issue by blindaks** [priyankarpal/projectshut#2236]
### Add a new project to the list

URL Shortener using HTML, CSS, JavaScript.

![Screenshot (185)](https://github.com/priyankarpal/ProjectsHut/assets/128223364/ca77c8ba-d82e-43ae-8dfd-455c11761520)
![Screenshot (186)](https://github.com/priyankarpal/ProjectsHut/assets/128223364/1d0ccaae-0a38-4ee1-a0cc-afcb5026a13e)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
