### ISSUE TITLE
scroll to the top💡

### ISSUE THREAD

**Issue by Surya-Teja-Sankuri** [priyankarpal/ProjectsHut#224]
when going through different pages of projects. When clicked on 1st or 2nd or 3rd page, the page should scroll to the top to go through the projects. This way it gives good look to the website.
And clicking on the **add your project** button the page goes directly to the down this makes user to scroll to the top.

**Comment by priyankarpal** [comment]
> when going through different pages of projects. When clicked on 1st or 2nd or 3rd page, the page should scroll to the top to go through the projects. This way it gives good look to the website. And clicking on the **add your project** button the page goes directly to the down this makes user to scroll to the top.

could you share a demo?

**Comment by Surya-Teja-Sankuri** [comment]
> > when going through different pages of projects. When clicked on 1st or 2nd or 3rd page, the page should scroll to the top to go through the projects. This way it gives good look to the website. And clicking on the **add your project** button the page goes directly to the down this makes user to scroll to the top.
> 
> could you share a demo?

https://user-images.githubusercontent.com/117016540/233785399-5b9d7b01-f6b4-4632-8940-bb26031392d8.mp4

In this video you can see, clicking on **add your project** button loads the page directly to down.

**Comment by priyankarpal** [comment]
> > > when going through different pages of projects. When clicked on 1st or 2nd or 3rd page, the page should scroll to the top to go through the projects. This way it gives good look to the website. And clicking on the **add your project** button the page goes directly to the down this makes user to scroll to the top.
> > 
> > 
> > could you share a demo?
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4 
> In this video you can see, clicking on **add your project** button loads the page directly to down.

yeah +1. assigning to you

**Comment by Surya-Teja-Sankuri** [comment]
> > > > when going through different pages of projects. When clicked on 1st or 2nd or 3rd page, the page should scroll to the top to go through the projects. This way it gives good look to the website. And clicking on the **add your project** button the page goes directly to the down this makes user to scroll to the top.
> > > 
> > > 
> > > could you share a demo?
> > 
> > 
> > Untitled.video.-.Made.with.Clipchamp.mp4
> > In this video you can see, clicking on **add your project** button loads the page directly to down.
> 
> yeah +1. assigning to you

Ok. I will be working on it.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
