### ISSUE TITLE
chore: addition of the one project

### ISSUE THREAD

**Issue by abhay-raj19** [priyankarpal/projectshut#2250]
### What feature?

a simple MERN tech stack based project 

### Add screenshots

will add into the given file system

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?

**Comment by abhay-raj19** [comment]
i had not started working on this issue
