### ISSUE TITLE
chore: remove share on twitter button & add Twitter logo 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#226]
- just need to remove the `share on Twitter button` from the footer & make credit text to center 

![image](https://user-images.githubusercontent.com/88102392/233784904-16c10e51-25e2-4641-9c28-8c362cf800b4.png)

**Comment by Bharadwajshivam28** [comment]
@priyankarpal  I want to work on this please assign me

**Comment by Bharadwajshivam28** [comment]
we have to move the complete footer text in center

**Comment by priyankarpal** [comment]
> we have to move the complete footer text in center

yes

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
@priyankarpal  can you help me that while moving text in center the text gets seprated away far away.....

**Comment by priyankarpal** [comment]
> @priyankarpal can you help me that while moving text in center the text gets seprated away far away.....

share the demo

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-04-22 19-03-50](https://user-images.githubusercontent.com/108119109/233788201-8be2f5af-e0e2-4945-97ed-938a5b01a39d.png)

Currently this is in footer like when i am making all these in center then words get spread

**Comment by priyankarpal** [comment]
> ![Screenshot from 2023-04-22 19-03-50](https://user-images.githubusercontent.com/108119109/233788201-8be2f5af-e0e2-4945-97ed-938a5b01a39d.png)
> 
> Currently this is in footer like when i am making all these in center then words get spread

ok

**Comment by Bharadwajshivam28** [comment]
this is also in center if we will move them more in center then this looks not more good

**Comment by priyankarpal** [comment]
> this is also in center if we will move them more in center then this looks not more good

create a PR

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
close this issue @priyankarpal as it has been completed by me
