### ISSUE TITLE
Team section

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#227]
We can add a team section in the navbar. That will consists of team of the project including its photo and social media handle links..

**Comment by Bharadwajshivam28** [comment]
we can add this in the navbar

**Comment by priyankarpal** [comment]
> We can add a team section in the navbar. That will consists of team of the project including its photo and social media handle links..

we already have a contributors page. where we show all contributors list.

**Comment by Bharadwajshivam28** [comment]
okay
