### ISSUE TITLE
add discord server link 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#228]
Add discord server link to the Navbar & Footer also 

server link https://discord.gg/9qnF5esp

**Comment by Bharadwajshivam28** [comment]
@priyankarpal I want to work on this issue

**Comment by Bharadwajshivam28** [comment]
I have added the discord button in the navbar but i am not able to understand like why we need to add it also in the footer. As all the links of social handle are in the navbar

![Screenshot from 2023-04-22 19-53-31](https://user-images.githubusercontent.com/108119109/233790551-fc252392-dc73-49e0-ab6d-c5dd78405fb1.png)

**Comment by Bharadwajshivam28** [comment]
I have added the discord button in the navbar but i am not able to understand like why we need to add it also in the footer. As all the links of social handle are in the navbar

![Screenshot from 2023-04-22 19-53-31](https://user-images.githubusercontent.com/108119109/233790617-b1cfb4ff-9ac4-4e59-84b5-2851df0a0e68.png)

**Comment by priyankarpal** [comment]
ok so create a PR

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
