### ISSUE TITLE
docs: make it easier to launch the project

### ISSUE THREAD

**Issue by EstebanBAR0N** [priyankarpal/projectshut#2326]
### what's wrong with the documentation?

The aim is to make it easier to launch the project by updating the README.md file with a "Run project locally" section.

### Add screenshots

Here is an overview of the documentation updated with this new section: 

<img width="768" alt="Screenshot 2023-11-21 at 15 42 56" src="https://github.com/priyankarpal/projectshut/assets/94709417/f3fc5730-4743-4290-974e-1bc53f75b78c">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
already mentioned in https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md

**Comment by EstebanBAR0N** [comment]
@priyankarpal I think you've misunderstood what I'm proposing. I'm just proposing documentation to simplify how to launch the project locally. It's not about helping to add a new project.
