### ISSUE TITLE
feat: redesign footer section

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#235]
We can give our project a good Footer which will be not much fancy it will be attractive and responsive @priyankarpal

**Comment by priyankarpal** [comment]
share a demo

**Comment by Bharadwajshivam28** [comment]
wait dropping a sample

**Comment by Bharadwajshivam28** [comment]
These are some sample we can give our details in the footer section and it will be really good as a project is more good with a responsive footer


![Screenshot from 2023-04-23 00-02-01](https://user-images.githubusercontent.com/108119109/233801034-d1174b1a-1cd3-4b93-8c03-dde2277773ea.png)
![Screenshot from 2023-04-23 00-03-23](https://user-images.githubusercontent.com/108119109/233801041-02a0efe2-f29f-488b-9251-1945a5fde7c0.png)
![Screenshot from 2023-04-23 00-04-16](https://user-images.githubusercontent.com/108119109/233801043-ffbd162a-b172-4239-90a1-ade4924ff71b.png)
![Screenshot from 2023-04-23 00-04-52](https://user-images.githubusercontent.com/108119109/233801045-177858db-8ad9-4403-a4c0-e53ee087f946.png)

**Comment by priyankarpal** [comment]
I'm also thinking about this design wby?


![image](https://user-images.githubusercontent.com/88102392/233801165-a77f4473-9e44-4024-b26b-f659196aaa8f.png)

**Comment by Bharadwajshivam28** [comment]
ya we can go on this

**Comment by Bharadwajshivam28** [comment]
it will be more clean and good

**Comment by priyankarpal** [comment]
ok then just change the text. Also github & discord links too

**Comment by Bharadwajshivam28** [comment]
ya thanks

**Comment by Bharadwajshivam28** [comment]
we have to add github and discord link in the footer right?

**Comment by Bharadwajshivam28** [comment]
@priyankarpal Why am i facing this issue after doing pnpm install/i and running it by pnpm run dev i get a blank screen although my code is correct and also setup is correct

![Screenshot from 2023-04-23 18-33-15](https://user-images.githubusercontent.com/108119109/233841686-09ebb92b-4198-422a-bf2a-f39dca42a1e7.png)

**Comment by priyankarpal** [comment]
> @priyankarpal Why am i facing this issue after doing pnpm install/i and running it by pnpm run dev i get a blank screen although my code is correct and also setup is correct
> 
> ![Screenshot from 2023-04-23 18-33-15](https://user-images.githubusercontent.com/108119109/233841686-09ebb92b-4198-422a-bf2a-f39dca42a1e7.png)

share your console screenshots

**Comment by Bharadwajshivam28** [comment]
> > @priyankarpal Why am i facing this issue after doing pnpm install/i and running it by pnpm run dev i get a blank screen although my code is correct and also setup is correct
> > 
> > ![Screenshot from 2023-04-23 18-33-15](https://user-images.githubusercontent.com/108119109/233841686-09ebb92b-4198-422a-bf2a-f39dca42a1e7.png)
> 
> share your console screenshots

Okay I will share

**Comment by priyankarpal** [comment]
> ![Screenshot from 2023-04-24 22-17-52](https://user-images.githubusercontent.com/108119109/234063244-91f3efbf-7685-4e09-892f-a2c698aaf9cb.png)
> 
> @priyankarpal This is my console when i create the footer and then i get a blank screen

import discord icon

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
what should be the exact line to import

**Comment by priyankarpal** [comment]
> import { FaDiscord, FaGithub } from "react-icons/fa"

import { FaDiscord, FaGithub } from "react-icons/fa"

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
