### ISSUE TITLE
docs: Few points lack periods

### ISSUE THREAD

**Issue by nepalivai** [priyankarpal/projectshut#2354]
### what's wrong with the documentation?

In the contribution.md, many points lack period at the end of sentance.

### Add screenshots

<img width="793" alt="image" src="https://github.com/priyankarpal/projectshut/assets/108126089/a679831a-f30e-4b38-832c-58ca54662d70">

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
I think it is unnecessary
