### ISSUE TITLE
📙 docs: add material ui tech stack 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#236]
In the README.md file, we need to add a **Material UI** badge with a website link & description.

![image](https://user-images.githubusercontent.com/88102392/233800937-5e0f1e56-00ff-4f4a-97f9-d411900aa6f8.png)

**Comment by Bharadwajshivam28** [comment]
assign me i want to work on this @priyankarpal

**Comment by Bharadwajshivam28** [comment]
@priyankarpal can you elaborate this issue please

**Comment by priyankarpal** [comment]
We need to add a badge of material UI like others tech stack badges

**Comment by Bharadwajshivam28** [comment]
not got it

**Comment by priyankarpal** [comment]
we need to add a badge like these of material ui

![image](https://user-images.githubusercontent.com/88102392/235332877-69aca888-7b30-4d0c-b893-91c1222b2340.png)

**Comment by Bharadwajshivam28** [comment]
okay it will be done @priyankarpal

**Comment by priyankarpal** [comment]
It appears that you may not be able to resolve this issue. Therefore, I'm unassigning you from it. It's worth noting that this issue has been open for two weeks

**Comment by Ahtaxam** [comment]
@priyankarpal assign it to me. i would like to work on it.

**Comment by priyankarpal** [comment]
> @priyankarpal assign it to me. i would like to work on it.

assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
