### ISSUE TITLE
🐞Bug: Fix browse projects button on mobile view

### ISSUE THREAD

**Issue by Deva-1903** [priyankarpal/ProjectsHut#238]
**Describe the bug**
The image of the monitor is overlaying on the button

**To Reproduce**
Set Screen size to mobile view

**Screenshots**

![Screenshot (312)](https://user-images.githubusercontent.com/97371915/233821803-8b87c21e-11a4-4583-af15-0145b2e3175e.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]

**Comment by priyankarpal** [comment]
do you want to work on this issue?

**Comment by Deva-1903** [comment]
Yeah!

**Comment by priyankarpal** [comment]
> Yeah!

assigned
