### ISSUE TITLE
Have to create a LOGO

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#24]

**Comment by ujjawaltyagii** [comment]
- I already kinda new it so I already had  a design created for ProjectsHut (it includes redesigning of heading and a little modification to sub-heading too) + logo
- will create PR in few hours hopefully you will like the complete design !

**Comment by priyankarpal** [comment]
> * I already kinda new it so I already had  a design created for ProjectsHut (it includes redesigning of heading and a little modification to sub-heading too) + logo
> * will create PR in few hours hopefully you will like the complete design !

Can you share the final logo?

**Comment by ujjawaltyagii** [comment]
have already created a PR for this 
![image](https://user-images.githubusercontent.com/115401171/220167972-58de90a8-bf7c-4253-949b-a6b404b2050d.png)

![image](https://user-images.githubusercontent.com/115401171/220168060-2897b8fd-6dad-484a-a989-2e69814672a2.png)

**Comment by priyankarpal** [comment]
hey, @ujjawaltyagii I'm thinking that the logo should be changed. Such as add coding related logos.

**Comment by ujjawaltyagii** [comment]
ok !! will remove this for now

**Comment by priyankarpal** [comment]
> ok !! will remove this for now

One more suggestion for you please change the font style I think it would be great. If you need any help you can ask me on [Twitter](https://twitter.com/priyankarpal)

**Comment by Vijaykv5** [comment]
Hey , Can you assign this issue to me

**Comment by priyankarpal** [comment]
@ujjawaltyagii would you like to work on this issue?
