### ISSUE TITLE
chore: project addition by JuanPabloDiaz

### ISSUE THREAD

**Issue by JuanPabloDiaz** [priyankarpal/projectshut#2413]
### Add a new project to the list

Add multiple projects such as:
- [FreeCodeCamp collection](https://github.com/JuanPabloDiaz/freecodecamp)
- [jpShop](https://github.com/JuanPabloDiaz/jpShop) - e-Commerce that consumes an API to fetch products
- [Vid-Box](https://github.com/JuanPabloDiaz/youtube) - Youtube Clone
- [Dev Memes](https://github.com/JuanPabloDiaz/devMemes-RapidAPI)
- [Self Hosting - Pi Server](https://github.com/JuanPabloDiaz/SelfHosting-PiServer)
- [Pinterest](https://github.com/juanPabloDiaz/pinterest) clone
- [Landing Page](https://github.com/juanPabloDiaz/brothers-landingPage)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
assigned to you
