### ISSUE TITLE
Fix a typo in the content displayed on the website

### ISSUE THREAD

**Issue by Ishpreet01** [priyankarpal/projectshut#2416]
@priyankarpal There is a typo in the content displayed on your website. I would like to contribute by fixing it. I am new to open source so this will be a valuable addition from my side.

**Comment by priyankarpal** [comment]
Could you please share the screenshot where you found the typo? @Ishpreet01

**Comment by Ishpreet01** [comment]
@priyankarpal This is the screenshot of the typo:
(The spelling of the Tic-Tac-Toe project in the heading is wrong.)
![image](https://github.com/priyankarpal/projectshut/assets/122776900/f235a2e6-1230-41fa-a76d-89a6f90574d4)

**Comment by priyankarpal** [comment]
> @priyankarpal This is the screenshot of the typo: (The spelling of the Tic-Tac-Toe project in the heading is wrong.) ![image](https://private-user-images.githubusercontent.com/122776900/303932291-f235a2e6-1230-41fa-a76d-89a6f90574d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDg2NzcsIm5iZiI6MTcwNzcwODM3NywicGF0aCI6Ii8xMjI3NzY5MDAvMzAzOTMyMjkxLWYyMzVhMmU2LTEyMzAtNDFmYS1hNzZkLTg5YTZmOTA1NzRkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwMzI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjE2OGI1YWUzNTFiMTg2MmJlZGNhM2Y4MWI5NmQzYzYwYzBmMTkxMzBhZTIwMzQ1YzcwY2RjNWVkODJjYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KZOc3K1XuQNb3SAoNcvKfwI912PKQp4fSIVMYHMHPBU)

sure go ahead

**Comment by Ishpreet01** [comment]
@priyankarpal Thanks for assigning.

**Comment by Ishpreet01** [comment]
@priyankarpal I have made the required changes and created a PR. Please review it.
