### ISSUE TITLE
🐞Bug: Fix the image on moblie view 

### ISSUE THREAD

**Issue by Deva-1903** [priyankarpal/ProjectsHut#242]
**Describe the bug**
Fix the image shown in the screenshot on mobile view 

**To Reproduce**
Set Screen size to mobile view

**Screenshots**

![Screenshot (314)](https://user-images.githubusercontent.com/97371915/233827433-28e819f4-4af3-425b-a350-07af0d2cdd6b.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]

**Comment by Deva-1903** [comment]
is this ok for mobile view? @priyankarpal 

![Screenshot (315)](https://user-images.githubusercontent.com/97371915/233827846-66885c83-e046-44a1-bb8d-ac3d534509f9.png)

**Comment by priyankarpal** [comment]
> is this ok for mobile view? @priyankarpal
> 
> ![Screenshot (315)](https://user-images.githubusercontent.com/97371915/233827846-66885c83-e046-44a1-bb8d-ac3d534509f9.png)

cool

**Comment by priyankarpal** [comment]
assigned to you
