### ISSUE TITLE
feat: Light mode

### ISSUE THREAD

**Issue by Bashamega** [priyankarpal/projectshut#2502]
### What feature?

Hello:)
My idea is to add a light mode theme for the site.
And add the toggle light mode button.
Some users who prefer light mode will benefit from it

### Add screenshots

None

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
The project's theme is designed for the black mode :)
