### ISSUE TITLE
[Refactor] You can't reach or read the footer due to the implementation of infinite scroll just above it in project page.

### ISSUE THREAD

**Issue by Adeesh-bode** [priyankarpal/projectshut#2503]
### File Name

components/projects/Projects.tsx

### Reason for Refactoring the Code

The reason for refactoring is to fix the issue with the infinite scroll that prevents users from accessing the footer. We can adjust the scroll behavior to ensure the footer remains accessible. This could involve implementing a threshold for the scroll or a pause in the loading of new content when nearing the footer. These changes can improve usability without disrupting existing functionality.

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure, go ahead!

**Comment by mrvivekthumar** [comment]
i want to work on this issue

**Comment by mrvivekthumar** [comment]
Also i have figured out how to solve this but the problem with this after reaching the threshold value some project is not loaded . its create bad effect on ui and i dont how handle that .    [
![image](https://github.com/priyankarpal/projectshut/assets/121384293/ae2ef85f-fc02-4cb3-bd23-da9a130412d4)
](url)

**Comment by priyankarpal** [comment]
> i want to work on this issue

currently, I assigned to someone

**Comment by priyankarpal** [comment]
.

**Comment by Adeesh-bode** [comment]
I have raised pr , please check
