### ISSUE TITLE
feat: Add dark/light mode

### ISSUE THREAD

**Issue by Saurav-Pant** [priyankarpal/ProjectsHut#251]
As a user, I want to be able to switch between light and dark themes on the website/app, so that I can choose the one that is easier on my eyes or fits my preferences.

To implement this feature, we will need to add a button or switch somewhere on the page that the user can click or tap to toggle the theme. When the user switches the theme, we will need to update the CSS styles accordingly to apply the appropriate colors, fonts, and other design elements.

In addition, we should consider storing the user's preference for the theme in a cookie or local storage, so that it persists across page reloads and sessions.

Adding this functionality can improve the user experience and make the website/app more accessible and customizable for users.

**Comment by priyankarpal** [comment]
dark & light mode features?

**Comment by Saurav-Pant** [comment]
Yes, yesterday I got many errors but today I made changes,here is the PR #252
