### ISSUE TITLE
💡feat: implement Add Project route

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#257]
I wanted to suggest that we should a Add Project button on Navbar. This will allow users  to  add their projects directly  to platform. 

I think we should use **json-server** (a fake Rest api to store data) or implement backend in Node, MongoDB. so,  our data will also be safe, secure and on cloud. By doing this we can easily achieve this.

**ScreenShoot**
![Screenshot from 2023-04-24 10-07-32](https://user-images.githubusercontent.com/64573767/233904722-a709ebe3-5dac-4cc4-a01b-7fb8fc53d2ff.png)

**Comment by priyankarpal** [comment]
> 

yes, we will do it when we will add the backend here.

**Comment by Ahtaxam** [comment]
ok. so, when we will start implement backend here. any idea, if it early i think i start working. what you think or suggest ?

**Comment by priyankarpal** [comment]
> ok. so, when we will start implement backend here. any idea, if it early i think i start working. what you think or suggest ?

TBH I don't have any knowledge of the backend. I don't know when we will implement but soon we will do it.

**Comment by Ahtaxam** [comment]
then, i think we should close this issue

**Comment by priyankarpal** [comment]
> then, i think we should close this issue

ok
