### ISSUE TITLE
Bug: Inconsistent height of Filters box when filters are applied under Projects page 

### ISSUE THREAD

**Issue by Absis98** [priyankarpal/projectshut#2595]
### What happened?

**Issue**
When we go to Projects page, and open Filters panel, we see multiple pre-defined filters that can be applied by directly clicking on them. 
But I observed a pattern that when we select filter from 2nd or 3rd row of filters, the height of panel changes which results in an inconsistent and not so good User experience.

**Expected Behavior**
Height of panel should not change and stay consistent after user interacts with it.

### Add screenshots

Normal view:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/083c6a35-fd98-47e2-9420-ae17a25fd407">

view when a filter is selected:
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/902cfb15-f9ce-4262-9875-56dae19a3353">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure. assigned to you

**Comment by priyankarpal** [comment]
any updates @Absis98
