### ISSUE TITLE
Using tailwind config theme instead of static colors in project

### ISSUE THREAD

**Issue by Rksingh620** [priyankarpal/ProjectsHut#26]
The project is using tailwind but all the colours in the source code are statically typed. We could use tailwind config to extend these colours which can be helpful in switching theme colours if need in future.

**Comment by priyankarpal** [comment]
> 

Yes. I thought. You can work on it.

**Comment by Rksingh620** [comment]
Okay, I'll start working on it.

**Comment by Rksingh620** [comment]
you can assign it to me.

**Comment by priyankarpal** [comment]
> you can assign it to me.

Ok, work on it. It would be great.
