### ISSUE TITLE
💡 Individual Page for Users to show their Projects

### ISSUE THREAD

**Issue by HarshPanchal26** [priyankarpal/ProjectsHut#260]
I have an idea , If somehow we can mange to make a page for each and every creator, who are listed their projects to ProjectsHut , will
be amazing and helpful thing , We can do it by using unique GitHub Username (Just like EddiHub)  in URL .
(Ex . ProjectsHut/Project/<username>)

What you think , If you would find it useful to , I want to work on it ,Assign me for this .

**Comment by priyankarpal** [comment]
Yes. Good idea 💡. 

When user will click on the projects card a popup will be open where we can show their total projects. 

What do you think?

**Comment by HarshPanchal26** [comment]
Yes good idea , or we can add a Button in card named as "More Projects" or with any other name , which will redirect user to the page which is dedicated only for specific user , which contains all the projects and other stuff .

**Comment by priyankarpal** [comment]
> Yes good idea , or we can add a Button in card named as "More Projects" or with any other name , which will redirect user to the page which is dedicated only for specific user , which contains all the projects and other stuff .

assigned to you

**Comment by priyankarpal** [comment]
also share a demo

**Comment by HarshPanchal26** [comment]
Give me some time ,I will update you soon .

**Comment by HarshPanchal26** [comment]
was not well , So Stared working on it from now , update you soon .

**Comment by priyankarpal** [comment]
> was not well , So Stared working on it from now , update you soon .

ok no issue

**Comment by HarshPanchal26** [comment]
Hey , I am thinking about to store data in a below way , because I am thinking to make a button called "More " which redirect user to the page which is dedicated for that user only , which show case his/her all work , which user wants to show to community .

way of data Collection 
 {
    "gh-username": "HarshPanchal26",
    "listOfProjects" : [
      {
        "link": "https://github.com/HarshPanchal26/chatRoom",
       "title": "Chat App",
       "description": "A chat Application for let you connect with your close one",
      "tech": ["React", "Expressjs", "MongoDB", "NodeJs"]
      },
     {   // secoend project 

    }, 
   {  // Third Project  //, }

  
    
    ]
   
  }


What you think ?

**Comment by HarshPanchal26** [comment]
Check this once 

![Screenshot (209)](https://user-images.githubusercontent.com/95937722/235133561-a40b4c30-e902-46ad-a237-de059540401f.png)


After Clicking on "More" button 

![Screenshot (208)](https://user-images.githubusercontent.com/95937722/235133624-611a5e92-fe5a-4423-a099-85771aef6f25.png)

Mobile UI 

![Screenshot (210)](https://user-images.githubusercontent.com/95937722/235133667-9daae7ae-7b6b-4f50-8e24-6571629a9518.png)


Is it look cool ?

**Comment by priyankarpal** [comment]
Awesome 😎

what if we add profile sidebar to the left side?

**Comment by HarshPanchal26** [comment]
You want it left side ? 

And ya if we want to display more projects for individual user , we need to change the way we are storing data in json file ,

as I mention in above comments 


{
"gh-username": "HarshPanchal26",
"listOfProjects" : [
{
"link": "https://github.com/HarshPanchal26/chatRoom",
"title": "Chat App",
"description": "A chat Application for let you connect with your close one",
"tech": ["React", "Expressjs", "MongoDB", "NodeJs"]
},
{ // secoend project

}, 
{ // Third Project //, }

]


It will help us for containing more projects for one user , and we also can add Social media handles of user , by taking it in object .


What's  your thought on this ?

**Comment by priyankarpal** [comment]
Awesome 😎

what if we add profile sidebar to the left side? 

 Yes. Just change the profile card to the left side

**Comment by priyankarpal** [comment]
> You want it left side ? 
> 
> And ya if we want to display more projects for individual user , we need to change the way we are storing data in json file ,
> 
> as I mention in above comments 
> 
> 
> {
> "gh-username": "HarshPanchal26",
> "listOfProjects" : [
> {
> "link": "https://github.com/HarshPanchal26/chatRoom",
> "title": "Chat App",
> "description": "A chat Application for let you connect with your close one",
> "tech": ["React", "Expressjs", "MongoDB", "NodeJs"]
> },
> { // secoend project
> 
> }, 
> { // Third Project //, }
> 
> ]
> 
> 
> It will help us for containing more projects for one user , and we also can add Social media handles of user , by taking it in object .
> 
> 
> What's  your thought on this ?

Yeah we need to change the json code.

And just change the profile card to the left side

**Comment by HarshPanchal26** [comment]
![Screenshot (211)](https://user-images.githubusercontent.com/95937722/235286314-ce93e8b1-399e-42fd-8e32-da049c4f462d.png)
![Screenshot (212)](https://user-images.githubusercontent.com/95937722/235286317-c2a552f8-4e8b-4f59-8702-987e7d636350.png)

Profile is now at the left side ,

**Comment by priyankarpal** [comment]
> ![Screenshot (211)](https://user-images.githubusercontent.com/95937722/235286314-ce93e8b1-399e-42fd-8e32-da049c4f462d.png)
> ![Screenshot (212)](https://user-images.githubusercontent.com/95937722/235286317-c2a552f8-4e8b-4f59-8702-987e7d636350.png)
> 
> Profile is now at the left side , 
> 

Ok 👌

**Comment by HarshPanchal26** [comment]
Now what about  JSON DATA , We need to change it , and as well as documentation for it , What do you think ?

**Comment by priyankarpal** [comment]
> Now what about  JSON DATA , We need to change it , and as well as documentation for it , What do you think ?

Yes.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
