### ISSUE TITLE
feat: search projects by owner's name

### ISSUE THREAD

**Issue by TzivyaFireman** [priyankarpal/projectshut#2607]
### What feature?

Currently, projects can only be searched by their name. 
It would be helpful to add the option to search by the project owner's name as well. 
This would make it easier to find projects based on the creator.

### Add screenshots

![image](https://github.com/user-attachments/assets/33474670-175d-4ce8-bee9-951e6aeb369b)

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
sure we can do this assigned to you

**Comment by TzivyaFireman** [comment]
Upon reviewing the code, I realized that this feature already exists,
 and I simply hadn't noticed it.
  Therefore, I am closing this issue. 
  
![image](https://github.com/user-attachments/assets/e64200c9-2d43-4588-978d-b572437e3741)
