### ISSUE TITLE
🐞Bug: Text is not visible

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#267]
Text **Built for Collaboration** is not visible on both dark and light theme. Also change footer background color to dark in dark mode.
**Note**: Open to work on this issue

**Screenshots**
![Screenshot from 2023-04-25 09-27-52](https://user-images.githubusercontent.com/64573767/234174911-ed0a33f4-932d-458c-8c10-93b076caa013.png)

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
