### ISSUE TITLE
🐞Bug: Icons in the header not aligned

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [priyankarpal/ProjectsHut#269]
**Describe the bug**
Icons are not aligned in the header.

**Expected behavior**
Icons should be aligned.

**Screenshots**
<img width="1674" alt="Screenshot 2023-04-25 at 12 09 53 PM" src="https://user-images.githubusercontent.com/88369802/234201371-30fc588c-a54c-4dc6-85d3-05e25ae3d53d.png">

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @priyankarpal, Can you assign this issue to me?

**Comment by priyankarpal** [comment]
> Hi @priyankarpal, Can you assign this issue to me?

done

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
