### ISSUE TITLE
🐞Bug: Center "Under MIT License" word in mobile view

### ISSUE THREAD

**Issue by Deva-1903** [priyankarpal/ProjectsHut#271]
**Describe the bug**
Center "**Under MIT License**" word in mobile view

**Expected behavior**
It needs to be in the center of the page

**Screenshots**

![Screenshot (316)](https://user-images.githubusercontent.com/97371915/234213833-2461daca-8c7d-468d-9563-50a33d425a22.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @Deva-1903, Are you working on this issue?

**Comment by Deva-1903** [comment]
No, you can work on it @Syed-Ali-Abbas-Zaidi

**Comment by Deva-1903** [comment]
Yes @Syed-Ali-Abbas-Zaidi

**Comment by priyankarpal** [comment]
assigned to you @Deva-1903
