### ISSUE TITLE
🐞Bug: Splash screen text color issue

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [priyankarpal/ProjectsHut#272]
**Describe the bug**
When we are in light theme the loading state (Splash Screen) has both the background and text color set to white.

**To Reproduce**

1. Go to ['ProjectsHut'](https://projectshut.vercel.app/)
2. Refresh the page
3. See error

**Expected behavior**
If we are in the light theme the text color of SplashScreen should be black.

**Screenshots**
<img width="1680" alt="Screenshot 2023-04-25 at 1 06 41 PM" src="https://user-images.githubusercontent.com/88369802/234216180-f1b9e151-57e4-4ba5-aa0a-4bb50f440482.png">

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @priyankarpal, Please assign this issue to me.

**Comment by Deva-1903** [comment]
You can start to work on it. @Syed-Ali-Abbas-Zaidi

**Comment by priyankarpal** [comment]
> You can start to work on it. @Syed-Ali-Abbas-Zaidi

great collaboration ❤️

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
