### ISSUE TITLE
🐞Bug: Sidebar not appearing for certain width

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [priyankarpal/ProjectsHut#281]
**Describe the bug**
The hamburger icon appears on the navbar at `767px` but if we click on it sidebar does not get displayed.

**To Reproduce**

1. Go to '[ProjectsHut](https://projectshut.vercel.app/)'
2. Reduce the screen width to `767px`
3. Click on the hamburger icon
4. See the error

**Expected behavior**
The sidebar should start appearing from `767px`.

**Screenshots**

https://user-images.githubusercontent.com/88369802/234555883-27a5e837-8e24-420d-be8a-d23de7d5420a.mov

**Comment by priyankarpal** [comment]
> Hi @priyankarpal, Assign this to me.

sure

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
