### ISSUE TITLE
 🗣 Translate: New Language french

### ISSUE THREAD

**Issue by NaimCode** [priyankarpal/ProjectsHut#283]
I wand to translate to french

**Comment by priyankarpal** [comment]
> I wand to translate to french

assigned to you

**Comment by meanwhile7** [comment]
these issue has been opened for 4 days and no development or any message  from the assigned person . can i take these issue instead if @NaimCode is not working on it anymore

**Comment by priyankarpal** [comment]
@NaimCode are you working on it?

**Comment by meanwhile7** [comment]
i would like to work on it as no development seems to be made by the assigned person for 4 days

**Comment by NaimCode** [comment]
Im working on, i will make a PR today.

**Comment by priyankarpal** [comment]
> Im working on, i will make a PR today.

cool

**Comment by meanwhile7** [comment]
> Im working on, i will make a PR today.

oh that's good

**Comment by NaimCode** [comment]
@priyankarpal do you have an idea how to change my github account's language?

**Comment by priyankarpal** [comment]
go to settings > scroll down > change 


https://github.com/settings/profile


![Screenshot from 2023-04-30 18-47-01](https://user-images.githubusercontent.com/88102392/235354933-0d909582-e4a0-4a62-bf49-1fb03cdeb326.png)

**Comment by meanwhile7** [comment]
as the French translation has been merged @priyankarpal you should close these issue
