### ISSUE TITLE
[Feat]: Add quality check github action

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [priyankarpal/ProjectsHut#304]
### What feature?

We should add a Quality Check GitHub action, which will ensure that `pnpm format` is passing. Because recently there are PRs that are getting merged in `main` with formatting issues. (I have shared screenshots with such instances where `pnpm format` is failing on the latest pull of the `main` branch)

### Add screenshots

<img width="704" alt="Screenshot 2023-04-28 at 11 58 02 PM" src="https://user-images.githubusercontent.com/88369802/235232495-245b25df-5905-4d8e-8b99-4f706eda2b1c.png">

<img width="1229" alt="Screenshot 2023-04-29 at 12 06 53 AM" src="https://user-images.githubusercontent.com/88369802/235232517-19bbd25d-a603-4d3d-adcb-b630f0f7488a.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
Hi @priyankarpal, What do you think about this? Should I start working on this?

**Comment by priyankarpal** [comment]
what if we add `pnpm format` to the `.husky` folder?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
@priyankarpal, I tried that but the issue is husky executes on commit. So if we add `pnpm format` to husky folder, it will format the files but they will remain unstaged and a newbie could still push the unformatted code because the commit will be created. (Attached demo)


https://user-images.githubusercontent.com/88369802/235286159-afcad5a6-fcaf-4c48-8a70-a19e58cdaa7d.mp4

**Comment by priyankarpal** [comment]
Ok then add gh action

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
