### ISSUE TITLE
[Bug]: Only single project on listing page

### ISSUE THREAD

**Issue by Syed-Ali-Abbas-Zaidi** [priyankarpal/ProjectsHut#309]
### What happened?

If a user has added more than 1 project on ProjectsHut the project listing page still only shows 1 project. It should render all the uploaded projects by that user.

### Add screenshots

Add screenshots
<img width="1676" alt="Screenshot 2023-04-29 at 6 26 35 PM" src="https://user-images.githubusercontent.com/88369802/235305462-896dac9f-b353-4577-8cb5-ffe290c13554.png">
<img width="1669" alt="Screenshot 2023-04-29 at 6 26 45 PM" src="https://user-images.githubusercontent.com/88369802/235305476-2dbdd343-c473-469d-88df-cd97394a6dad.png">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes. currently it's now under construction
