### ISSUE TITLE
[Docs]: Translate to Japanese 

### ISSUE THREAD

**Issue by meanwhile7** [priyankarpal/ProjectsHut#310]
### in which language do you want to translate?

I want to translate documentation to Japanese 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
whenever you create a PR/issue try to add a good & clear title

**Comment by meanwhile7** [comment]
Ok I will take care of it
