### ISSUE TITLE
[Docs]: we need to mention few points

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#313]
## We need to add a few points such as
- whenever you create a PR/issue please add a good title & description
-  add good commit messages
-  add screenshots if needed

## where to mention?
- need to add README.md
- contributing.md file 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bharadwajshivam28** [comment]
@priyankarpal can i work on it

**Comment by priyankarpal** [comment]
I'm working in this issue

**Comment by Bharadwajshivam28** [comment]
okay
