### ISSUE TITLE
Translate docs to Malayalam language 

### ISSUE THREAD

**Issue by E-fais** [priyankarpal/ProjectsHut#319]
I would like  to translate documentation to Malayalam language.

**Comment by priyankarpal** [comment]
could you add a clear title? it will help others to understand the issue. @E-fais

**Comment by E-fais** [comment]
> could you add a clear title? it will help others to understand the issue. @E-fais

Done, i would like to improve documentation. I can translate docs to Malaylam language.

**Comment by priyankarpal** [comment]
Amazing you can work on it

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @E-fais

**Comment by priyankarpal** [comment]
It appears that you may not be able to resolve this issue. Therefore, I'm unassigning you from it. It's worth noting that this issue has been open for a few weeks

**Comment by vishnuhari17** [comment]
I think i can translate the docs to malayalam. Is someone currently working on it?

**Comment by priyankarpal** [comment]
> I think i can translate the docs to malayalam. Is someone currently working on it?

no one is working. I'm assigning to you

**Comment by vishnuhari17** [comment]
@priyankarpal I have opened a PR...is there anything more to do in it? #374

**Comment by priyankarpal** [comment]
cool just add the issue number to the PR description @vishnuhari17

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
