### ISSUE TITLE
[Feat]: Include live link in json

### ISSUE THREAD

**Issue by ManishBisht777** [priyankarpal/ProjectsHut#321]
### What feature?

I have an idea that we can include live link in the JSON as well so that other people can view projects directly from site without going to github

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, I agree with you also we're working on a new feature.  

- so you can add this feature thereafter releasing the current feature. 

- also, some projects don't have any live links.

**Comment by ManishBisht777** [comment]
> 

mmm isn't projects without a live link are good for nothing? i mean no one will be looking at GitHub code and running it on his system.

**Comment by priyankarpal** [comment]
> > 
> 
> mmm isn't projects without a live link are good for nothing? i mean no one will be looking at GitHub code and running it on his system.

I agree with your idea. just add the feature after releasing the new one if we add it now we need to change some codes.

**Comment by priyankarpal** [comment]
@ManishBisht777 you can work on it.

**Comment by balaji-sivasakthi** [comment]
@ManishBisht777 

> If you need any help, I could assist you

**Comment by priyankarpal** [comment]
I will ping here soon. for now I'm holding this issue

**Comment by priyankarpal** [comment]
we're thinking to improve to redesign the card & adding new features such as analytics etc.  so now I'm closing this issue.
