### ISSUE TITLE
[Feat]:  Adding a button which switches to diffrent languages

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#323]
### What feature?

I have an idea that we can create a button where user can switch to different languages.. Like if the current page is in english and when user will  click on hindi then he/she can view the page in hindi.. Same with other languages like french, korean, chinese and more

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
are you want to work on this issue?

**Comment by Bharadwajshivam28** [comment]
yes i want to work on this

**Comment by priyankarpal** [comment]
It appears that you may not be able to resolve this issue. Therefore, I'm unassigning you from it. It's worth noting that this issue has been open for a few weeks

**Comment by gkprasanth** [comment]
Hi @priyankarpal  can I work on this issue?

**Comment by Naincy04** [comment]
Hello,I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by gkprasanth** [comment]
> > Hi @priyankarpal can I work on this issue?
> 
> yeah sure. Assigning to you

Thank You @priyankarpal for assigning me this issue. I will start working on this.

**Comment by gkprasanth** [comment]
@priyankarpal Am I allowed to use an external library for translating website's content? If yes I would like to use i18next library and add languages related objects in the translate directory.

**Comment by priyankarpal** [comment]
> @priyankarpal Am I allowed to use an external library for translating website's content? If yes I would like to use i18next library and add languages related objects in the translate directory.

yeah, you can work on it.

**Comment by PayalPadmalyaPrusty** [comment]
@priyankarpal  I want to contribute.Please assign me

**Comment by gkprasanth** [comment]
@priyankarpal I've finished integrating support for three languages. Is adding for the seven languages already available in the translations sufficient, or do I need to add other languages?

**Comment by gkprasanth** [comment]
> > @priyankarpal I've finished integrating support for three languages. Is adding for the seven languages already available in the translations sufficient, or do I need to add other languages too?
> 
> which languages have you added? also, share demo

English, German and French. Demo in the sense should I share screenshots?

**Comment by priyankarpal** [comment]
> > > @priyankarpal I've finished integrating support for three languages. Is adding for the seven languages already available in the translations sufficient, or do I need to add other languages too?
> > 
> > 
> > which languages have you added? also, share demo
> 
> English, German and French. Demo in the sense should I share screenshots?

yeah. you can add Hindi as well

**Comment by gkprasanth** [comment]
> > > > @priyankarpal I've finished integrating support for three languages. Is adding for the seven languages already available in the translations sufficient, or do I need to add other languages too?
> > > 
> > > 
> > > which languages have you added? also, share demo
> > 
> > English, German and French. Demo in the sense should I share screenshots?
> 
> yeah. you can add Hindi as well

Yup I will add Hindi ass well.

**Comment by gkprasanth** [comment]
@priyankarpal I have added Hindi ass well. What other languages do you want me to include?

**Comment by gkprasanth** [comment]
> > @priyankarpal I have added Hindi ass well. What other languages do you want me to include?
> 
> that's ok for now. also, make sure to update your branch

Yup I will make a pr from my branch.

**Comment by priyankarpal** [comment]
ig currently we don't need this feature right now so I'm closing this issue
