### ISSUE TITLE
Footer: Add social links to footer

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#33]
### Add social links to the footer section

![image](https://user-images.githubusercontent.com/88102392/220430072-3e19f5af-a8ba-4fca-97b0-1d44b80dadb4.png)

**Comment by danchan020** [comment]
can you assign me this issue? what are the links you would like me to add?

**Comment by Vijaykv5** [comment]
Please assign me the task

**Comment by priyankarpal** [comment]
sorry @Vijaykv5 for this @danchan020 said that first. @danchan020 you can work on it.

**Comment by danchan020** [comment]
@priyankarpal got it, what are the links that you want me to add?

**Comment by priyankarpal** [comment]
Twitter, GitHub 

https://twitter.com/Priyankarpal
https://github.com/priyankarpal/ProjectsHut

**Comment by danchan020** [comment]
Done, sent pr!
