### ISSUE TITLE
[Docs]: update docs according to the `contributing.md` file

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#333]
### what's wrong in the documentation?

- Update the documentation according to the `contributing. md` file. 

### Add screenshots

![image](https://user-images.githubusercontent.com/88102392/235684895-aab1754a-3cb6-452f-965e-db0433e3f823.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bharadwajshivam28** [comment]
@priyankarpal I want to work on this

**Comment by SurajPratap10** [comment]
@priyankarpal If it's free then you can assign it to me

**Comment by priyankarpal** [comment]
@Bharadwajshivam28 are you working on it?

**Comment by Bharadwajshivam28** [comment]
no

**Comment by priyankarpal** [comment]
> no

If you find yourself unable to work on a specific issue, kindly inform the community as it will facilitate other members to collaborate and work towards resolving the issue.

**Comment by priyankarpal** [comment]
assigned to you @SurajPratap10

**Comment by priyankarpal** [comment]
It appears that you may not be able to resolve this issue. Therefore, I'm unassigning you from it. It's worth noting that this issue has been open for a few weeks

**Comment by Ahtaxam** [comment]
@priyankarpal I want to work on this issue. can you explain to me a  little bit more?

**Comment by prathamkumarjha** [comment]
i think for this isssue i am suppossed to enhance the documentation by updating the documentation and add screenshots for each step which would be helpful for new contributors may i ask you to assign this issue to me as i can work on it

**Comment by Geeta259** [comment]
I would like to contribute on this issue if it's issue still not resolved then you can assign this issue to me!
Hope you will consider me! @priyankarpal

**Comment by priyankarpal** [comment]
> @priyankarpal I want to work on this issue. can you explain to me a little bit more?

assigned to you. @Ahtaxam.

## What to do? 
- we need to update the docs according to the `contribution. md` file. 
- in that https://projectshut.vercel.app/AddYourProjectsGuide page some points are missing so we need to add these.

**Comment by Ahtaxam** [comment]
@priyankarpal Thanks. I got it just by looking at contribution. md file update  AddYourProject react  component?

**Comment by priyankarpal** [comment]
> @priyankarpal Thanks. I got it just by looking at contribution. md file update AddYourProject react component?

yes

**Comment by PoulasthaMukherjee** [comment]
@priyankarpal May I work on this as well?

**Comment by Ahtaxam** [comment]
@priyankarpal Please take a look. is it ok?

![Screenshot from 2023-05-21 13-59-13](https://github.com/priyankarpal/ProjectsHut/assets/64573767/f8c4a631-ee4d-43cd-af9f-9d0f5b54e130)

**Comment by priyankarpal** [comment]
@Ahtaxam make sure to add screenshots.

**Comment by Ahtaxam** [comment]
of which step i should add screen shots because these steps are just to follow on terminal  by looking at docs.

**Comment by priyankarpal** [comment]
> of which step i should add screen shots because these steps are just to follow on terminal by looking at docs.

I guess we have added screenshots to the contributing.md file also, add whole content to the doc page from contributing.md file

**Comment by Ahtaxam** [comment]
> > of which step i should add screen shots because these steps are just to follow on terminal by looking at docs.
> 
> I guess we have added screenshots to the contributing.md file also, add whole content to the doc page from contributing.md file

There are screenShoots of those steps who a user will performed on GitHub, not for those when he setup project locally.

**Comment by priyankarpal** [comment]
> > > of which step i should add screen shots because these steps are just to follow on terminal by looking at docs.
> > 
> > 
> > I guess we have added screenshots to the contributing.md file also, add whole content to the doc page from contributing.md file
> 
> There are screenShoots of those steps who a user will performed on GitHub, not for those when he setup project locally.

yeah add those

**Comment by Ahtaxam** [comment]
> > > > of which step i should add screen shots because these steps are just to follow on terminal by looking at docs.
> > > 
> > > 
> > > I guess we have added screenshots to the contributing.md file also, add whole content to the doc page from contributing.md file
> > 
> > 
> > There are screenShoots of those steps who a user will performed on GitHub, not for those when he setup project locally.
> 
> yeah add those

@priyankarpal Those screenshoots were priorly added. now i just follow contributing.md file and update there was no screenshoots for that steps. Now should i open PR.

**Comment by priyankarpal** [comment]
> > > > > of which step i should add screen shots because these steps are just to follow on terminal by looking at docs.
> > > > 
> > > > 
> > > > I guess we have added screenshots to the contributing.md file also, add whole content to the doc page from contributing.md file
> > > 
> > > 
> > > There are screenShoots of those steps who a user will performed on GitHub, not for those when he setup project locally.
> > 
> > 
> > yeah add those
> 
> @priyankarpal Those screenshoots were priorly added. now i just follow contributing.md file and update there was no screenshoots for that steps. Now should i open PR.

ok open a PR & if there are anything changes required I will request you

**Comment by Ahtaxam** [comment]
open PR.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
