### ISSUE TITLE
[Feat]: remove cards animation

### ISSUE THREAD

**Issue by dheerajmw** [priyankarpal/ProjectsHut#334]
### What feature?

Adding link to 'more' on the whole project card can improve user experience. Hover effect on card make it feel like a button but having no action on clicking over it triggers disappointment. 

### Add screenshots

![Screenshot 2023-05-02 at 10 21 38 PM](https://user-images.githubusercontent.com/112400361/235735434-0965e48c-6b9a-4b18-bf62-0bb8a382841c.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we need to remove cards animation.

**Comment by dheerajmw** [comment]
> we need to remove cards animation.

I want to work on that. Please assign me the issue.

**Comment by dheerajmw** [comment]
> > > we need to remove cards animation.
> > 
> > 
> > I want to work on that. Please assign me the issue.
> 
> assigned to you

I've made changes and pushed it to my forked repo, what I have to do next.

**Comment by priyankarpal** [comment]
> > > > we need to remove cards animation.
> > > 
> > > 
> > > I want to work on that. Please assign me the issue.
> > 
> > 
> > assigned to you
> 
> I've made changes and pushed it to my forked repo, what I have to do next.

have you created a PR?
