### ISSUE TITLE
[Docs]: update translation_guide.md file

### ISSUE THREAD

**Issue by meanwhile7** [priyankarpal/ProjectsHut#338]
### what's wrong in the documentation?

We need to add some description about updating the available language list when translating the doc in a new language 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
