### ISSUE TITLE
[Docs]: update Translation Guide 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/projectshut#341]
### what's wrong in the documentation?

We need to update the translation guide.

## Need to change

- remove `yarn` & add `pnpm` also remember to follow the `contributing.md` file
- add fork image
- remove unwanted texts etc.

## Image 1

![image](https://user-images.githubusercontent.com/88102392/235755606-ac4414f8-41ca-4bc9-87ff-cfde424e2c69.png)

## Image 2

![image](https://user-images.githubusercontent.com/88102392/235755670-6b980548-b24b-4128-a092-2e4792fbcf99.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Younus-Saberi** [comment]
Hi @priyankarpal , Could you assign the issue to me to work on **further**

**Comment by priyankarpal** [comment]
Sure work on it

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
