### ISSUE TITLE
[Feat]: add multiple projects feature 

### ISSUE THREAD

**Issue by HarshPanchal26** [priyankarpal/ProjectsHut#345]
### What feature?

I have an idea , About updating  our Database file in below way , So we can add multiple projects for single user , and display all of them in a dedicated user page , which we created in previous Issue .

  {
    gh_username: 'priyankarpal',
    social_media: {
      linkdIn: '',
      twitter: '',
      hashNode: '',
      YouTube: '',
      GitHub: 'https://github.com/priyankarpal/TheaTheme'
    },
    Projects: [ 
     {
       name : ' ',
      discription  : ' ',
      teckStack : null,
      GitHub Link :  ' '
     }
     ]
  },
  
  
  What's Your thought on this .

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
