### ISSUE TITLE
[Bug]: Dark theme toggle button not showing instead there is an emoji there

### ISSUE THREAD

**Issue by shubhsharma19** [priyankarpal/ProjectsHut#348]
### What happened?

Here you can see the switch to change theme is missing instead there is an emojie. 

Once the theme is changed to dark, it shows a box.

I have attached screenshots.

### Add screenshots

![Theme issue with ProjectsHut](https://user-images.githubusercontent.com/69891912/236666685-f013697b-de4c-4ca4-b529-a42a7135e762.png)
![Theme issue with ProjectsHut Dark](https://user-images.githubusercontent.com/69891912/236666690-00c4157b-0ac1-4807-a7e7-d9439090eac5.png)

### What browsers are you seeing the problem on?

Edge and Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ahtaxam** [comment]
I think both emojis for dark and light themes are different.in my point of view  looks good than Box. what you think @priyankarpal

**Comment by shubhsharma19** [comment]
> I think both emojis for dark and light themes are different.in my point of view  looks good than Box. what you think @priyankarpal 

There should be a moon and a sun kind of emojies right? 

☀️ And 🌒 like this. 

Instead there is some other emoji.

**Comment by priyankarpal** [comment]
but in my browser,  it's working well 😢 

https://user-images.githubusercontent.com/88102392/236718945-bffd9980-e033-4919-96fc-32796b599cad.mp4

**Comment by Ahtaxam** [comment]
> 

Yes there should be that will look better

**Comment by shubhsharma19** [comment]
> but in my browser, it's working well 😢
> 
>  2023-05-08_07-44-45.mp4

Saw that, Lets first see if someone else also has the same issue or not!

**Comment by RahulRana701** [comment]
hi @shubhsharma19  @priyankarpal It is working fine in my browser as well
<img width="748" alt="Screenshot 2023-05-10 121339" src="https://github.com/priyankarpal/ProjectsHut/assets/123585591/6b8ea05b-393d-4d52-8668-e91da587fbae">

**Comment by shubhsharma19** [comment]
> hi @shubhsharma19 @priyankarpal It is working fine in my browser as well <img alt="Screenshot 2023-05-10 121339" width="748" src="https://user-images.githubusercontent.com/123585591/237300717-6b8ea05b-393d-4d52-8668-e91da587fbae.png">

Then it should be an issue from my side! I will look into it.

**Comment by priyankarpal** [comment]
I think we should close this issue
