### ISSUE TITLE
[Test]: Footer component

### ISSUE THREAD

**Issue by AhorIsaac** [priyankarpal/ProjectsHut#358]
### What feature?

I would love to write tests for the footer component using vitest!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by AhorIsaac** [comment]
Thank you.
I'm working on it

**Comment by priyankarpal** [comment]
> /assign

When we have already assigned someone, kindly refrain from requesting a reassignment. @BHANUJATIN

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
