### ISSUE TITLE
[Feat]: Filter Animation with Framer Motion on Project Cards

### ISSUE THREAD

**Issue by Devansh-365** [priyankarpal/ProjectsHut#360]
### What feature?

Proposing to implement filter animation based on tags using Framer Motion on project cards for the following reasons:

1. Visual Enhancement: Engaging animations enhance project card visuals.
2. User-Friendly Filtering: Smooth transitions and fading improve user experience.
3. Interactive Experience: Interactive animations respond to user interactions.
4. Technological Advancement: Showcase proficiency with modern tools.
5. This enhancement will elevate visuals, improve user experience, and showcase technical expertise.

Available to discuss implementation details and collaborate on integrating Framer Motion animations.

Thank you for considering this feature request.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
agreed. btw could you show me some demo?

**Comment by Devansh-365** [comment]
Yeah sure there is an example I am planning to implement: 


https://github.com/priyankarpal/ProjectsHut/assets/83155844/91b47d07-3d9d-4bee-b310-584210789e78

**Comment by priyankarpal** [comment]
looks good. 

- we already have tag options now we need to add animations.

I'm assigning it to you.

**Comment by Devansh-365** [comment]
@priyankarpal  I notice that there is a bug with sorting I hope it's okay if I can resolve this bug. Already started working on it.

**Comment by priyankarpal** [comment]
> @priyankarpal I notice that there is a bug with sorting I hope it's okay if I can resolve this bug. Already started working on it.

check the issue #370

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @Devansh-365

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
