### ISSUE TITLE
Sign In With Google Functionality 

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#364]
### What feature?

What do you think about implementing "Sign in with Google" for this website?

Please assign this task to me. I will create the "Sign in with Google" functionality, allowing only those users who are logged in with Google to access the entire project list. It will track how many user are actually working for this open source project.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noobtuber20103152** [comment]
thank you I am working on it🥳

**Comment by priyankarpal** [comment]
Alright, we'll consider it at a later time. It's not necessary for us at the moment.

**Comment by priyankarpal** [comment]
> smiling_face_with_tear

we're not storing any data/showing any data so we think it's not necessary for us at this time.
