### ISSUE TITLE
[Bug]: URL structure should be lowercase

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#365]
### What happened?

I found a BUG 🐞

Using lowercase letters in URLs helps improve consistency, readability, and user-friendliness. It can also prevent potential issues that may arise from case sensitivity, such as broken links due to incorrect letter casing. Furthermore, lowercase URLs tend to be more compatible across different platforms, servers, and browsers.

While some web servers and systems might treat URLs as case-sensitive, it is advisable to stick with lowercase letters to ensure a consistent and accessible user experience.

The current URL for the project page is https://projectshut.vercel.app/ProjectsPage. It should be structured as https://projectshut.vercel.app/project-page.

Please assign this task to me

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by k-deepak04** [comment]
@noobtuber20103152 assign this to me
i would like to contribute on this issue

**Comment by pearlrathour** [comment]
I would like to contribute on this issue, assign this to me.

**Comment by priyankarpal** [comment]
> ### What happened?
> I found a BUG lady_beetle
> 
> Using lowercase letters in URLs helps improve consistency, readability, and user-friendliness. It can also prevent potential issues that may arise from case sensitivity, such as broken links due to incorrect letter casing. Furthermore, lowercase URLs tend to be more compatible across different platforms, servers, and browsers.
> 
> While some web servers and systems might treat URLs as case-sensitive, it is advisable to stick with lowercase letters to ensure a consistent and accessible user experience.
> 
> The current URL for the project page is https://projectshut.vercel.app/ProjectsPage. It should be structured as https://projectshut.vercel.app/project-page.
> 
> Please assign this task to me
> 
> ### Add screenshots
> Add screenshots
> 
> ### What browsers are you seeing the problem on?
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

I guess just we need to rename the filename.

Assigned to you @noobtuber20103152

**Comment by noobtuber20103152** [comment]
yes thank you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
