### ISSUE TITLE
[style]: Improve Project card style

### ISSUE THREAD

**Issue by AshutoshDash1999** [priyankarpal/ProjectsHut#368]
### What's the style idea?

We need to improve  the overall card styling like button design, border, etc

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/46455250/1643b4c0-e111-425e-a874-7eec0d80b30e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by swoyam2609** [comment]
@priyankarpal I would like to work on this issue, would you like to assign it to me ?

**Comment by AshutoshDash1999** [comment]
@priyankarpal should i wait for being assigned or directly work on it?

**Comment by i-am-SnehaChauhan** [comment]
Hi! I would like to contribute to this issue under the GSSoC'23. It seems interesting and aligned with my skills.

**Comment by pearlrathour** [comment]
I would like to work on this issue, would you please to assign it to me.

**Comment by priyankarpal** [comment]
> @priyankarpal should i wait for being assigned or directly work on it?

when you create an issue to any open-source projects wait for assigning & review after that you can create PR(if you got assigned)
