### ISSUE TITLE
[Bug]: Unsorted Projects When Selecting Tech Stacks

### ISSUE THREAD

**Issue by itsme-shivamkumar** [priyankarpal/ProjectsHut#370]
### What happened?

# Bug Description:
### When selecting the tech stacks on the platform, the projects are not being sorted, and no action is triggered. This issue prevents users from effectively filtering and finding projects based on their desired technologies.

# Steps To Reproduce
- Go to the project selection page.
- Click on the "Tech Stacks" dropdown menu.
- Notice that the projects are not sorted, and selecting a tech stack does not yield any results.

# Expected Behavior:
### The projects should be sorted when selecting a tech stack, allowing users to easily find projects that match their desired technologies.

# Actual Behavior:
### The projects are not sorted, and selecting a tech stack does not have any effect.

# Preview:

https://github.com/priyankarpal/ProjectsHut/assets/91745441/373f671f-4be6-4e7d-b916-b3b69354efea

# Possible Fix:
### To address this issue, the following steps can be taken:
- Capture the index of the selected tech stack.
- Iterate over all the projects and apply a string matching algorithm, such as regular expressions (regex), to match the tech stack with the projects.
- Sort the projects based on the matching results.
- Update the user interface to reflect the sorted projects.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsme-shivamkumar** [comment]
# Bug Fix Description:
The issue causing the projects to remain unsorted when selecting tech stacks has been resolved by me. 
## Here is a preview of the fix:

https://github.com/priyankarpal/ProjectsHut/assets/91745441/6aa620ec-8903-40cc-a77a-aa676b30d881

## Proposed Solution
#### To address the bug, the following steps were taken:
- Captured the index of the selected tech stack.
- Iterated over all the projects, implementing a string matching algorithm using regular expressions (regex).
- Sorted the projects based on the matching results.
- Updated the user interface to display the sorted projects correctly.

## Request for Review and Assistance:
I have successfully resolved this bug and would like to contribute the fix by submitting a pull request (PR). As this will be my first contribution to the project, I kindly request your assistance with the next steps.

Could you please guide me on the process for submitting a PR? Any additional information or specific requirements I need to be aware of would be greatly appreciated.

Thank you for your attention to this matter. I am excited to contribute further to the project's improvement and look forward to your guidance.

Please let me know if there is anything else I can assist you with.

**Comment by itsme-shivamkumar** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by priyankarpal** [comment]
@itsme-shivamkumar it's highly recommended that create PR after being assigned by Maintainers. 

For this time it's ok

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by itsme-shivamkumar** [comment]
> @itsme-shivamkumar it's highly recommended that create PR after being assigned by Maintainers. 
> 
> For this time it's ok  

Sure 😊, this was first time so I was a little confused but I will always follow this protocol from next time, thanks for merging my PR☺️❤️
