### ISSUE TITLE
[style]: Styling Changes for Navbar NavLinks

### ISSUE THREAD

**Issue by Amitavpanda** [priyankarpal/ProjectsHut#373]
### What's the style idea?

I'm excited to contribute to your open-source project and have identified an issue that I would like to work on.

In the current navbar implementation, the styling of the navlinks remains unchanged when interacting with them. I propose adding styling changes to the navlinks to provide better visual feedback to the users when hovering or selecting them.

**Expected Behavior:**

**Light Mode:**

- On hover: The text color should change to white (#FFFFFF), and the background color should change to black (#000000).
- On selection: The text color should remain white (#FFFFFF), and the background color should remain black (#000000).
- When not hovering or selected: The text color should be black (#000000), and the background color should be white (#FFFFFF).

**Dark Mode:**

- On hover: The text color should change to black (#000000), and the background color should change to white (#FFFFFF).
- On selection: The text color should remain black (#000000), and the background color should remain white (#FFFFFF).
- When not hovering or selected: The text color should be white (#FFFFFF), and the background color should be black (#000000).

**Implementation Steps:**

- Identify the CSS classes responsible for styling the NavLinks in the Navbar component.
- Add conditional CSS classes or inline styles to update the text color and background color based on the current mode (white or dark) and the hover/selection state.
- Implement the necessary  React logic to handle the hover and selection events and apply the appropriate styles.
- Test the changes thoroughly in both white and dark modes to ensure the desired styling behavior is achieved.

### Add screenshots

![Screenshot (90)](https://github.com/priyankarpal/ProjectsHut/assets/56599943/b7fe1d5e-4b24-4135-9bb0-928a90501b54)
![Screenshot (89)](https://github.com/priyankarpal/ProjectsHut/assets/56599943/fc708660-21a5-4c8b-99c8-4b7e7431aa39)
![Screenshot (88)](https://github.com/priyankarpal/ProjectsHut/assets/56599943/90248f1d-0f84-4466-b419-21baa2240b4b)

I will be changing this navlinks on hovering and selection.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amitavpanda** [comment]
Once this issue is assigned to me, I will begin working on implementing the proposed changes. I look forward to contributing to this project and improving the user experience of the Navbar NavLinks.

**Comment by Amitavpanda** [comment]
I would like to work on this under gssoc23, please assign me this.

**Comment by Naincy04** [comment]
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by Amitavpanda** [comment]
@priyankarpal can you assign me this task so that I can start contributing on it.

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> I'm excited to contribute to your open-source project and have identified an issue that I would like to work on.
> 
> In the current navbar implementation, the styling of the navlinks remains unchanged when interacting with them. I propose adding styling changes to the navlinks to provide better visual feedback to the users when hovering or selecting them.
> 
> **Expected Behavior:**
> 
> **Light Mode:**
> 
> * On hover: The text color should change to white (#FFFFFF), and the background color should change to black (#000000).
> * On selection: The text color should remain white (#FFFFFF), and the background color should remain black (#000000).
> * When not hovering or selected: The text color should be black (#000000), and the background color should be white (#FFFFFF).
> 
> **Dark Mode:**
> 
> * On hover: The text color should change to black (#000000), and the background color should change to white (#FFFFFF).
> * On selection: The text color should remain black (#000000), and the background color should remain white (#FFFFFF).
> * When not hovering or selected: The text color should be white (#FFFFFF), and the background color should be black (#000000).
> 
> **Implementation Steps:**
> 
> * Identify the CSS classes responsible for styling the NavLinks in the Navbar component.
> * Add conditional CSS classes or inline styles to update the text color and background color based on the current mode (white or dark) and the hover/selection state.
> * Implement the necessary  React logic to handle the hover and selection events and apply the appropriate styles.
> * Test the changes thoroughly in both white and dark modes to ensure the desired styling behavior is achieved.
> 
> ### Add screenshots
> ![Screenshot (90)](https://user-images.githubusercontent.com/56599943/239636975-b7fe1d5e-4b24-4135-9bb0-928a90501b54.png) ![Screenshot (89)](https://user-images.githubusercontent.com/56599943/239636989-fc708660-21a5-4c8b-99c8-4b7e7431aa39.png) ![Screenshot (88)](https://user-images.githubusercontent.com/56599943/239636995-90248f1d-0f84-4466-b419-21baa2240b4b.png)
> 
> I will be changing this navlinks on hovering and selection.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

agreed!


Assigned to you @Amitavpanda
