### ISSUE TITLE
[Feat]: Adding a light and dark mode switching button

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#376]
### What feature?

I have an idea to create a button on top right corner under the navbar to add a toggle switch for light/dark mode,it would look good with the projects color scheme

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I think a toggle button would be beter for the same,I would like to work on this issue under gssoc'23

**Comment by Naincy04** [comment]
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by pearlrathour** [comment]
I would like to work on this issue under. Can u please assign this issue to me?

**Comment by priyankarpal** [comment]
> I think a toggle button would be beter for the same,I would like to work on this issue under gssoc'23

assigned to you

**Comment by karthiknadar1204** [comment]
Thank you,will get working on it

**Comment by karthiknadar1204** [comment]
Have started work on the issue

**Comment by karthiknadar1204** [comment]
Does a button work for the dark light mode.tried implementing a capsule shaped button @priyankarpal

**Comment by karthiknadar1204** [comment]
yes in a. min

**Comment by karthiknadar1204** [comment]
<img width="228" alt="Screenshot 2023-05-22 at 3 13 45 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/4dce2185-7334-48e5-8ead-e9c51be2b79e">


works perfectly fine as well
<img width="1709" alt="Screenshot 2023-05-22 at 3 16 05 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/73612039-5685-41d6-a772-643276eefc7d">


<img width="1715" alt="Screenshot 2023-05-22 at 3 16 14 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/c818b3f3-1454-47e8-921a-dc3e0e0b72ff">

And sorry for the spam pr as well,i interpreted the conversation wrongly, i thought if i wrapped up the navbar issue before anyone pings it, i could merge the pr

Extremely sorry for that

**Comment by karthiknadar1204** [comment]
I was thinking of adding some additional hover effects as well to it

**Comment by karthiknadar1204** [comment]
can i push the changes to a new branch and create a pr?

**Comment by priyankarpal** [comment]
suggestions:  remove the navbar designs & add button like this 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/f25921f0-04b8-4d1f-8a34-65f9fe0ffa70)

**Comment by karthiknadar1204** [comment]
ok will do,i was working on the same branch so did not revert it and submit pr before day ends

**Comment by karthiknadar1204** [comment]
<img width="1769" alt="Screenshot 2023-05-22 at 3 39 55 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/bccae52c-1add-441f-aba7-5e271ae4549a">
<img width="1787" alt="Screenshot 2023-05-22 at 3 40 04 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/d319248d-ba38-497b-a845-937e141cae37">

How does this look @priyankarpal

**Comment by karthiknadar1204** [comment]
<img width="1779" alt="Screenshot 2023-05-22 at 3 43 00 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/1619ef7c-c2a8-479f-8db8-38d1efe03daf">

**Comment by karthiknadar1204** [comment]
Have to leave for a class now,will submit pr for review by 5:30pm is that fine @priyankarpal

**Comment by priyankarpal** [comment]
> will reinstate the github link to the left of the switch and submit pr for review on a different branch,fine?

add the github link to the left & it will be good if you create a new fresh PR. also make sure to update all branch

**Comment by priyankarpal** [comment]
> Have to leave for a class now,will submit pr for review by 5:30pm is that fine @priyankarpal

no issue

**Comment by karthiknadar1204** [comment]
yes

**Comment by priyankarpal** [comment]
> <img alt="Screenshot 2023-05-22 at 3 49 59 PM" width="1764" src="https://user-images.githubusercontent.com/95973644/239879781-ef50d200-105c-4196-a05d-ddea6821a3c9.png"> <img alt="Screenshot 2023-05-22 at 3 50 04 PM" width="1785" src="https://user-images.githubusercontent.com/95973644/239879809-de3de0b1-3cb3-48f0-acf5-5d32c3655b24.png">
> added the github link

awesome

**Comment by karthiknadar1204** [comment]
@priyankarpal submitted a pr for review

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
