### ISSUE TITLE
Add styling to Footer according to color pallette ( Now it looks plain )[Feat]: 

### ISSUE THREAD

**Issue by DurgaSanthosh** [priyankarpal/ProjectsHut#378]
### What feature?

Add styling to footer according to color palette. I'm in GSSOC'23".

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Naincy04** [comment]
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by priyankarpal** [comment]
could you share the demo? @DurgaSanthosh

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

Thank you for your understanding.
