### ISSUE TITLE
[style]: Redesign the contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#379]
### What's the style idea?

We need to improve  the contributors page,all the contributors iimages appear plane on the contributors page,how good would it be if we took the contributor info as a json file and convert it into a card with user details like their github account,twitter account,a small info,their portfolio and an image of the contributor

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Naincy04** [comment]
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by creator79** [comment]
@priyankarpal  I would like to work on this issue under GSSOC'23. Can u please assign this issue to me

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> We need to improve the contributors page,all the contributors iimages appear plane on the contributors page,how good would it be if we took the contributor info as a json file and convert it into a card with user details like their github account,twitter account,a small info,their portfolio and an image of the contributor
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

we are using github API to fetch the data. we can create a card for contributors. i guess we don't need social links they have their github link.
