### ISSUE TITLE
[Bug]:  dark theme icon is not visible

### ISSUE THREAD

**Issue by mandliyarajendra11** [priyankarpal/ProjectsHut#383]
### What happened?

I found a BUG 🐞

when we click  on dark mode icon look like this - [] (check ss )

and also light mode icon looking not good 

can you assign me this issue 

### Add screenshots

Add screenshots
**dark theme icon -** 
![Screenshot (88)](https://github.com/priyankarpal/ProjectsHut/assets/119125519/a100d764-38e8-4f0c-aafd-0c580bc49b58)

**light theme icon -** 
![Screenshot (89)](https://github.com/priyankarpal/ProjectsHut/assets/119125519/45d85eb6-f3a8-480d-ab6f-75051bf4e622)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mandliyarajendra11** [comment]
i want to work on this issue please assign me

**Comment by vikram-8290** [comment]
i would like to work on this under gssoc please assgin me this.

**Comment by Naincy04** [comment]
Hello, I would like to work on this issue under GSSOC'23. Can u please assign this issue to me?

**Comment by priyankarpal** [comment]
yes check the issue  #376 we will add a toggle button for that
