### ISSUE TITLE
[Bug]: Pagination is not working properly

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#388]
### What happened?

I found a BUG 🐞
If you go to the last page still the next button is showing.
If you go to the first page still the previous button is showing

i would like to work on this for gssoc 2023

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @suzy-g38

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
