### ISSUE TITLE
[Feat]: To add tooltips to the icons

### ISSUE THREAD

**Issue by kriti-002** [priyankarpal/ProjectsHut#389]
### What feature?

I have an idea!
We can add tooltip for the icons for Github and Dark Mode icon. As it doesn't signify what will happen on clicking those buttons.

### Add screenshots

Add screenshots
![Screenshot 2023-05-20 110752](https://github.com/priyankarpal/ProjectsHut/assets/66835642/c5e01e32-97fd-4841-98f6-ef5eff7d1ebe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kriti-002** [comment]
@priyankarpal please assign this issue to me.

**Comment by priyankarpal** [comment]
I guess it's not necessary there is only a GitHub icon even though everyone knows it.
