### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by An525ish** [priyankarpal/ProjectsHut#393]
### What happened?

I found a BUG 🐞All social media icons are redirecting to the github repo

 I would like to fix tht

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noobtuber20103152** [comment]
This is not an issue if you write same links  github link on every field of social media, it is obvious that it go to only github. This is work correctly, there is no bug.
Thank You!

**Comment by priyankarpal** [comment]
this is not a bug we added these when we are adding new features
