### ISSUE TITLE
[Feat]: Add search option 

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#400]
### What feature?

I have an idea 
If we add a search option that will easy for the users to search a particular project

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by suzy-g38** [comment]
> ### What feature?
> I have an idea If we add a search option that will easy for the users to search a particular project
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

i would like to work on it under gssoc2023

**Comment by balaji-sivasakthi** [comment]
Hey @suzy-g38 ,
Just wanted to give you a heads-up that I've completed the feature request you made it here. I've made the necessary changes and I have to create a pull request for your review.

Would you mind taking a look at the changes when you have a moment? I would greatly appreciate your feedback and any suggestions you might have.

Thanks in advance for your time and help!

**Comment by priyankarpal** [comment]
Assigned to you @suzy-g38

**Comment by noobtuber20103152** [comment]
@suzy-g38 are you working on this issue ? 
@priyankarpal I think she is not working on it , please assign it to me.

**Comment by priyankarpal** [comment]
> @suzy-g38 are you working on this issue? @priyankarpal I think she is not working on it, please assign it to me.

her one PR got merged & now she is working on it.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
