### ISSUE TITLE
Back to Project Page link

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#401]
### What feature?

I have an idea that on more detail page of user there should be a back to  project page that should take users back to projects. 
what do you think @priyankarpal .

**Note:** I would like to work on this issue under GSSOC'23.

### Add screenshots

![Screenshot from 2023-05-20 13-25-09](https://github.com/priyankarpal/ProjectsHut/assets/64573767/bd2a67a5-d76a-4a26-8bce-b1969678c2fc)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### What feature?
> I have an idea that on more detail page of user there should be a back to project page that should take users back to projects. what do you think @priyankarpal .
> 
> **Note:** I would like to work on this issue under GSSOC'23.
> 
> ### Add screenshots
> ![Screenshot from 2023-05-20 13-25-09](https://user-images.githubusercontent.com/64573767/239676860-bd2a67a5-d76a-4a26-8bce-b1969678c2fc.png)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

yes but where to add? could you share the demo?

**Comment by Ahtaxam** [comment]
What if we made Project heading a link. so when user will click on that, he'll navigate to project page.

what if we do like this projects > [name_of_project].
what you think. @priyankarpal 

![Screenshot from 2023-05-21 14-15-06](https://github.com/priyankarpal/ProjectsHut/assets/64573767/f59298ff-601f-4b66-a2c9-0d449d6e9077)

**Comment by priyankarpal** [comment]
> Then we can back button opposite side of **project** (right side of screen)

we can add the button to the top of left side of the profile card in profile page

**Comment by Ahtaxam** [comment]
Yes. that's also Great !

**Comment by Ahtaxam** [comment]
@priyankarpal should i start working on this ?

**Comment by priyankarpal** [comment]
> @priyankarpal should i start working on this?

please work on that BUG issue after that you can

**Comment by priyankarpal** [comment]
> > @priyankarpal should i start working on this?
> 
> please work on that BUG issue after that you can

you can work on this issue

**Comment by Ahtaxam** [comment]
@priyankarpal how is this ?

![Screenshot from 2023-05-22 23-12-52](https://github.com/priyankarpal/ProjectsHut/assets/64573767/5ae3fed2-a62e-4347-9b99-f5b5c61c2853)

After hover affect
![Screenshot from 2023-05-22 23-13-03](https://github.com/priyankarpal/ProjectsHut/assets/64573767/d0211c34-8309-4774-aa06-bda77ce87921)

**Comment by priyankarpal** [comment]
> @priyankarpal how is this ?
> 
> ![Screenshot from 2023-05-22 23-12-52](https://user-images.githubusercontent.com/64573767/239996578-5ae3fed2-a62e-4347-9b99-f5b5c61c2853.png)
> 
> After hover affect ![Screenshot from 2023-05-22 23-13-03](https://user-images.githubusercontent.com/64573767/239996781-d0211c34-8309-4774-aa06-bda77ce87921.png)

ok

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
