### ISSUE TITLE
Improving contribution.md file📄

### ISSUE THREAD

**Issue by kinshukgoel4** [priyankarpal/ProjectsHut#402]
### what's wrong in the documentation?

We need to improve contribution steps in [contribution.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) and I have a few steps which can improve the readability of it. 
Please assign me this task

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kinshukgoel4** [comment]
hey @priyankarpal can you assign this issue to me with appropriate labels

**Comment by priyankarpal** [comment]
> ### what's wrong in the documentation?
> We need to improve contribution steps in [contribution.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) and I have a few steps which can improve the readability of it. Please assign me this task
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

could you share the demo?

**Comment by kinshukgoel4** [comment]
Demo? Do u mean what changes can I make? Ya sure.
![image](https://github.com/priyankarpal/ProjectsHut/assets/98045941/0891a84c-91ed-4b3b-b46c-a81c4a855c50)
After making changes it will looks something like this

**Comment by priyankarpal** [comment]
I guess we already mentioned all steps. please check our contributing guide & if there is anything missing then we need to work on that. @kinshukgoel4

**Comment by kinshukgoel4** [comment]
Okay then i will submit the PR and you review the changes

**Comment by kinshukgoel4** [comment]
hey @priyankarpal please checkout the [PR](https://github.com/priyankarpal/ProjectsHut/pull/544) related to this issue. I am open to your feedback on my PR. 

>Note: Please do add gssoc'23 label to issue and PR

**Comment by priyankarpal** [comment]
> hey @priyankarpal please checkout the [PR](https://github.com/priyankarpal/ProjectsHut/pull/544) related to this issue. I am open to your feedback on my PR.
> 
> > Note: Please do add gssoc'23 label to issue and PR

really it's looking good.

**Comment by kinshukgoel4** [comment]
Hey, it was nice working on this issue with you.  Thanks for approving my PR. I am really looking at your project automation, can you giveaway tips as a project maintainer in regard to automation and GitHub actions. It will be helpful such that I can implement the necessary automation on my project
