### ISSUE TITLE
[Feat]: Creating search bar for contributer page

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#404]
### What feature?

It will make this website more attractive if a search system  present in the contributor page to search a specific user between thousands of contributors.

Please assign this task to me @priyankarpal 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by balaji-sivasakthi** [comment]
I would like to work on this feature under GSSOC'23.

**Comment by priyankarpal** [comment]
Duplicate of #400

**Comment by noobtuber20103152** [comment]
issue no #400 is for creating a search bar for project by my issue is to make a search bar for contributor page not project to find an user from thousand of users. @priyankarpal

**Comment by priyankarpal** [comment]
will it help us?
