### ISSUE TITLE
[Bug]: Sort functionality is not working in your projects page

### ISSUE THREAD

**Issue by crocmons** [priyankarpal/ProjectsHut#409]
### What happened?

Sort functionality is not working in your projects page

### Add screenshots

Add screenshots
![bug GSSOc23 project-2](https://github.com/priyankarpal/ProjectsHut/assets/106610322/3a2e3bd7-0fdc-408d-86af-a6c6361a9b4b)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crocmons** [comment]
I would like to work on this project. Please assign it to me! I have already worked on similar projects like this I just need to add more functionalities into it and it will be complete.

**Comment by harmeetsingh11** [comment]
Hi! I am a GSSoC Contributor and would like to work on this issue.
Please assign it to me.

**Comment by harmeetsingh11** [comment]
This issue is already opened in issue #385

**Comment by priyankarpal** [comment]
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/370 also, got fixed
