### ISSUE TITLE
[Docs]: Update how to add projects in contribution documentation

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#410]
### what's wrong in the documentation?

The current documentation structure follows this format:

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/f9e4a6fb-4ad5-4c77-86e2-3710bf2c8b84)

Whereas the way to add your project is :

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/07c70c16-0ae7-4eb9-80b4-bd8821f5cecf)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
