### ISSUE TITLE
[style]: Redesign the Contributor Profile Page

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#411]
### What's the style idea?

Currently, the page design just shows the projects and contributors' other social handles:

![image](https://github.com/priyankarpal/ProjectsHut/assets/62666287/87cb495e-1539-4e6b-ad15-85891804fb7a)

We can add the total number of contributions to the ProjectsHut, and the total number of projects, and redesign the existing card by changing some styles.

I would like to work on it under gssoc23.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by sonustar** [comment]
i would like to contribute in it 
please assign me

**Comment by balaji-sivasakthi** [comment]
@suzy-g38 if you need any help?

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> Currently, the page design just shows the projects and contributors' other social handles:
> 
> ![image](https://user-images.githubusercontent.com/62666287/239684431-87cb495e-1539-4e6b-ad15-85891804fb7a.png)
> 
> We can add the total number of contributions to the ProjectsHut, and the total number of projects, and redesign the existing card by changing some styles.
> 
> I would like to work on it under gssoc23.
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

assigned to @suzy-g38
