### ISSUE TITLE
data: project addition by Akshatchaube01

### ISSUE THREAD

**Issue by Akshatchaube01** [priyankarpal/ProjectsHut#412]
I would like to add my open source project in it.

**Comment by priyankarpal** [comment]
> I would like to add my open source project in it.

assigned to you.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by priyankarpal** [comment]
> I would like to contribute to this issue as a part of @GSSOC'23 Please assign it to me. Thank you.

you can check another issue

**Comment by priyankarpal** [comment]
@Akshatchaube01 is it for GSSoC'23?

**Comment by Akshatchaube01** [comment]
yeah ..

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
