### ISSUE TITLE
[style]:  Home page Images are not Responsive in mobile device

### ISSUE THREAD

**Issue by crocmons** [priyankarpal/ProjectsHut#417]
### What's the style idea?

We need to improve the Home page Grid Images because that is not Responsive in mobile device.

### Add screenshots

Add screenshots
![bug -2 project-2](https://github.com/priyankarpal/ProjectsHut/assets/106610322/008c7ef4-79a0-4f8d-8035-b83163eb3c51)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crocmons** [comment]
I would like to work on this project. Please assign it to me!

**Comment by Rishi2602** [comment]
I would like to contribute to this project as a GSSoC'23 contributor. Assign it to me.

**Comment by priyankarpal** [comment]
assigned to you @crocmons

**Comment by crocmons** [comment]
> assigned to you @crocmons

thank you , I will do that..

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
