### ISSUE TITLE
data: add more projects

### ISSUE THREAD

**Issue by Atharva-3000** [priyankarpal/ProjectsHut#420]
### What feature?

I have an idea to add more projects with wider tech stacks, like MERN and some with typescript.
Please allow me to add some more projects to the projects.json.
(Part of GSSOC23)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
do you want to add your projects?

**Comment by Atharva-3000** [comment]
> do you want to add your projects?

**Yes**, I would love to, also I can **translate the docs to Hindi**

**Comment by priyankarpal** [comment]
> > do you want to add your projects?
> 
> **Yes**, I would love to add some projects. Also, when **clicking on check documentation for adding projects via the website**, it gives a **404 error,** I would also like to change that so that the **user gets redirected to the repo**. Can I raise a new issue for that if it doesn't exist?

you can add projects here. & next issue someone is working https://github.com/priyankarpal/ProjectsHut/issues/484

**Comment by Atharva-3000** [comment]
Ok, working on it

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
