### ISSUE TITLE
[Feat]: i have more project ideas 

### ISSUE THREAD

**Issue by warisamir** [priyankarpal/ProjectsHut#421]
### What feature?

I have an more project to add on this repo
![image](https://github.com/priyankarpal/ProjectsHut/assets/77074869/c01b0505-9043-4f19-b745-831bd7a69160)

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/77074869/08e54ca6-fe8b-477a-bb2e-f671961632b5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by warisamir** [comment]
it this pr accepted or not and it will be counted

**Comment by priyankarpal** [comment]
> it this pr accepted or not and it will be counted

you just merged your PR in your forked repo. Please check the docs for more info & make sure to add a good title & description

**Comment by priyankarpal** [comment]
> it this pr accepted or not and it will be counted

no

**Comment by priyankarpal** [comment]
ig it's completed
