### ISSUE TITLE
Hover effect on homepage images [style]: 

### ISSUE THREAD

**Issue by HimanshuNarware** [priyankarpal/ProjectsHut#424]
### What's the style idea?

We need to improve  home page images does not have any hover effect
please assign me this issue so i can work on this issue

### Add screenshots

Add screenshots
![ph hover](https://github.com/priyankarpal/ProjectsHut/assets/83147410/43891c61-195a-4cff-90bc-ebbf6d3f9366)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I guess it's not needed. in future if we want to add I will ping here

**Comment by HimanshuNarware** [comment]
ok but I already resolve this feature on my device

**Comment by HimanshuNarware** [comment]
so If you can again open this issue it's beneficial for me
