### ISSUE TITLE
Hover effect on project list box [style]: 

### ISSUE THREAD

**Issue by HimanshuNarware** [priyankarpal/ProjectsHut#425]
### What's the style idea?

We need to improve The project list box does not have  any hover effect on it
kindly assign me this  issue

### Add screenshots

Add screenshots
![project hover](https://github.com/priyankarpal/ProjectsHut/assets/83147410/7c181439-0fda-4087-a355-36be75bb69f3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Duplicate of  #368
