### ISSUE TITLE
[style]: making the website responsive and making overall ui better

### ISSUE THREAD

**Issue by 5h0ov** [priyankarpal/ProjectsHut#426]
### What's the style idea?

i can make the website fit the resolution of the device. I can also make the header and footer better with a background.

I would love to contribute in this project!

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share where are you facing the issue? @5h0ov

**Comment by 5h0ov** [comment]
for lower resolutions the right side images are getting cut out. The images to the right of Share your projects.

**Comment by priyankarpal** [comment]
> for lower resolutions the right side images are getting cut out. The images to the right of Share your projects.
plz Share screenshots
