### ISSUE TITLE
[Bug]: Console.log printing which is of no use to user 

### ISSUE THREAD

**Issue by Shubham185y** [priyankarpal/ProjectsHut#427]
### What happened?

I found a BUG 🐞
i can work on this please assign to me
![image](https://github.com/priyankarpal/ProjectsHut/assets/100077254/325f6b13-67d5-4380-a174-5af8f146fff2)

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/100077254/42c53c87-db80-4746-9595-8345a0022b6f)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shubham185y** [comment]
assign this to me I will solve this ASAP!

**Comment by akkshayTandon** [comment]
I think you opened this issue on the wrong project. The QuickLearn repository is here: [https://github.com/DSC-JSS-NOIDA/QuickLearn](url)

**Comment by Shubham185y** [comment]
Really sorry for that there are so many tabs open i confused it was not intentional
