### ISSUE TITLE
[Docs]: add hindi translation the project

### ISSUE THREAD

**Issue by akkshayTandon** [priyankarpal/ProjectsHut#429]
### in which language do you want to translate?

I want to translate documentation to HINDI.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akkshayTandon** [comment]
please assign me this issue.
"I'm in GSSOC'23"

**Comment by priyankarpal** [comment]
assigned to you @akkshayTandon

**Comment by PayalPadmalyaPrusty** [comment]
@priyankarpal I want to contribute.Please assign me

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
