### ISSUE TITLE
Changing logo and button styles

### ISSUE THREAD

**Issue by RAKESHKUMARSM** [priyankarpal/ProjectsHut#43]
**Change1**

- Replacing a logo 

**Change2**

- Changing the button styles in order to enhance the page looks

**Comment by priyankarpal** [comment]
> **Change1**
> 
> * Replacing a logo
> 
> **Change2**
> 
> * Changing the button styles in order to enhance the page looks

You can work on it, and assign it to you.

**Comment by priyankarpal** [comment]
I'm closing this issue.
