### ISSUE TITLE
[Feat]: 2 features to be added

### ISSUE THREAD

**Issue by namanrox** [priyankarpal/ProjectsHut#431]
### What feature?

I have an idea regarding loading of website on getting scrolled down by the user. Moreover, animated loading of website is good, if it takes time to load.

I am a contributor for GSSoC '23 and would love to contribute on your project.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### What feature?
> I have an idea regarding loading of website on getting scrolled down by the user. Moreover, animated loading of website is good, if it takes time to load.
> 
> I am a contributor for GSSoC '23 and would love to contribute on your project.
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

could you share the demo & change the title

**Comment by Ritikkumar03** [comment]
I want to work on this.
I'm a contributor for GSSoC '23, kindly assign this issue to me.

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 


Thank you for your understanding.
