### ISSUE TITLE
[Docs]: Translate ProjectsHut's docs to Turkish

### ISSUE THREAD

**Issue by mhdamaan79** [priyankarpal/ProjectsHut#433]
### in which language do you want to translate?

👋 I want to translate documentation to Turkish. **I'm in GSSOC'23**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @mhdamaan79

**Comment by mohammad-ayan-008** [comment]
Can you assign me The task @priyankarpal

**Comment by mhdamaan79** [comment]
I'm working on this issue. You can search for other issues or create one. @mohammad-ayan-008

**Comment by mhdamaan79** [comment]
🚀 Just raised the PR (#464). Would greatly appreciate your review. Thank you for your attention. @priyankarpal

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
