### ISSUE TITLE
[style]: Redesign Dark mode and Add Your Projects page

### ISSUE THREAD

**Issue by mainaak03** [priyankarpal/ProjectsHut#434]
### What's the style idea?

The dark mode currently looks to flat and dark and it needs more styling and contrast. Also the layout of the Docs page needs to be improved. A footer will also be needed to improve the look of the website.

I am a GSSOC contributor and would love to contribute to this project if I get the opportunity.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before https://github.com/priyankarpal/ProjectsHut/issues/376. We kindly request you to review the existing issues and, if necessary, create a new one accordingly.
