### ISSUE TITLE
[style]: Improving Navbar 

### ISSUE THREAD

**Issue by Tanusingh02** [priyankarpal/ProjectsHut#435]
### What's the style idea?

We need to improve the navigation section as it looks very simple and we can improve some features of nav bar like adding seach bar.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by sonustar** [comment]
can i also improve by contributing the navbar

**Comment by amrit2611** [comment]
Hey @Tanusingh02 !
I would love to work on this issue.
Kindly assign me this issue under the GSSOC '23

**Comment by Parth-2609** [comment]
Hey @Tanusingh02 
I would like to help you in improving the nav bar.
As you said we can add the search bar and even change some themes either by using Material UI or CSS.
Please assign me this issue under GSSOC '23 whenever it's possible.

**Comment by yuvraj6446** [comment]
- Hey We can improve the navbar by implementing the hover effect , (scaling over hovering and light outline). 
- We can also change the color item once it is clicked. 
- We can change the light/dark emoji to an more relatable icon.
- We can implement an bottom border for navbar to separate it from the rest of the page.
- Kindly assign me this task.

**Comment by ShreyaDhiman24** [comment]
Hello! 
I'd be glad to contribute to this project.
Please give me this task as part of the GSSOC '23.

**Comment by kasturimandlik** [comment]
I would like to work on this issue under GSSOC'23.
We can change the navbar css (design) and enhance the user experience.
please assign me this issue

**Comment by iamFaizanArif** [comment]
Assign me!
