### ISSUE TITLE
[Bug]: A Bug when switched to Dark Mode

### ISSUE THREAD

**Issue by amrit2611** [priyankarpal/ProjectsHut#437]
### What happened?

I found a BUG 🐞

![20 05 2023_21 45 32_REC](https://github.com/priyankarpal/ProjectsHut/assets/81375472/663dcc95-e7af-4bc3-bdb9-afc50206ee8c)

would love to remove this bug
Kindly assign this to me under the GSSOC '23

**Comment by akuldeepj** [comment]
@amrit2611 Its running properly on the deployed website . 
could you provide how to replicate it
![image](https://github.com/priyankarpal/ProjectsHut/assets/97216956/5d3621cf-0528-4adb-ac0e-d60a4008d07f)
![image](https://github.com/priyankarpal/ProjectsHut/assets/97216956/11f2024d-7ad4-4304-9be6-49d185783e12)

**Comment by amrit2611** [comment]
@akuldeepj 
Kindly check in other browsers as well.
If it works just fine, I'll close this issue.

**Comment by akuldeepj** [comment]
Yup I checked it in chrome and firefox

**Comment by amrit2611** [comment]
> Yup I checked it in chrome and firefox

Okay
In that case I'll close this issue.
