### ISSUE TITLE
[Feat]: About us

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [priyankarpal/ProjectsHut#440]
### What feature?

I can create an about us section on the home page which clears the mission and vision of the project it would be better for users who are visiting first time in the website.

@priyankarpal, please assign this to me under GSSOC '23.

Thank You :)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I guess it's not necessary. We already added about of projectshut in readme
