### ISSUE TITLE
[style]: Improving button style

### ISSUE THREAD

**Issue by ShubhamMore6688** [priyankarpal/ProjectsHut#442]
### What's the style idea?

We need to improve  the button under the projects section that looks very simple and color used is very light. It is not properly visible.

### Add screenshots

Add screenshots
![Screenshot 2023-05-20 223123](https://github.com/priyankarpal/ProjectsHut/assets/94038708/6e3f1c34-0b42-4532-bcba-d0bf32e724aa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> We need to improve the button under the projects section that looks very simple and color used is very light. It is not properly visible.
> 
> ### Add screenshots
> Add screenshots ![Screenshot 2023-05-20 223123](https://user-images.githubusercontent.com/94038708/239700115-6e3f1c34-0b42-4532-bcba-d0bf32e724aa.png)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

yeah, we need to change the design. assigned to you.

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 


Thank you for your understanding.
