### ISSUE TITLE
[Feat]: featured projects section

### ISSUE THREAD

**Issue by Niharika2608** [priyankarpal/ProjectsHut#443]
### What feature?

 As a GSSOC'23 contributer I have an idea of adding more section down ,between the footer section and landing page. We can add blogs section and featured projects section. I am a Ui designer so I can create a better UI for blog and featured section . Please assign this issue to me

**Comment by priyankarpal** [comment]
could you add a good title?

also, currently, we don't have blogs so I think we don't need to add them & the last featured project section sounds good. can you share your design with us & after that, you can create an issue for only the featured projects section(if you want to work you can work)

**Comment by Niharika2608** [comment]
hey ! I've created design of feature project section check it out .
![feature project](https://github.com/priyankarpal/ProjectsHut/assets/101355205/414ea7e9-6fa2-4382-824a-fd03bfe24c7c)

**Comment by priyankarpal** [comment]
> hey ! I've created design of feature project section check it out . ![feature project](https://user-images.githubusercontent.com/101355205/239758914-414ea7e9-6fa2-4382-824a-fd03bfe24c7c.jpg)

looks good

**Comment by priyankarpal** [comment]
could you add a good title? @Niharika2608

**Comment by priyankarpal** [comment]
issue title

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/652939b8-b717-4631-bfe8-b7ad097b2a82)

**Comment by priyankarpal** [comment]
> title for what ? Also a slider will be provided through these left right icons . if this seems ok to you so i can start working on it ?

yeah sure

**Comment by priyankarpal** [comment]
@Niharika2608 could you share your progress on this issue?

**Comment by mohit-0007** [comment]
Hello @priyankarpal I'm a GSSOC contributor if no one is working on this issue you can assign this issue to me. I would love to work on this.

**Comment by priyankarpal** [comment]
@Niharika2608 could you share your progress on this issue?

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
