### ISSUE TITLE
[style]: Redesign a Logo 

### ISSUE THREAD

**Issue by Niharika2608** [priyankarpal/ProjectsHut#444]
### What's the style idea?

We need to improve an Logo . as it very simple , we can make it more attractive and elegant . I would like to do it , kindly assign this to me .

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> We need to improve an Logo . as it very simple , we can make it more attractive and elegant . I would like to do it , kindly assign this to me .
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [ ]  I agree to follow this project's Code of Conduct

yeah, we need to add a logo. could you share a demo with us?

**Comment by Niharika2608** [comment]
HEY! I've made some logo you can check and let me know the final one. [https://drive.google.com/file/d/14Wbavi7zSC5LxjtASubd3oTf5oUh4twt/view?usp=share_link](url)

**Comment by Niharika2608** [comment]
[drive link ](https://drive.google.com/file/d/14Wbavi7zSC5LxjtASubd3oTf5oUh4twt/view?usp=share_link) 
[Project.zip](https://github.com/priyankarpal/ProjectsHut/files/11525120/Project.zip)

**Comment by priyankarpal** [comment]
> Hey I've made some logo. Please Check and final one of them and let me know . [drive link ](https://drive.google.com/file/d/14Wbavi7zSC5LxjtASubd3oTf5oUh4twt/view?usp=share_link) [Project.zip](https://github.com/priyankarpal/ProjectsHut/files/11525120/Project.zip)

I checked but it's looking normal we need to improve

**Comment by priyankarpal** [comment]
ig it's looking good so I'm closing this issue

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/e840a0db-6cc7-46fd-b4bf-f7da2534f5fe)
