### ISSUE TITLE
[style]: Docs page issue in light mode

### ISSUE THREAD

**Issue by him-raw99** [priyankarpal/ProjectsHut#445]
### What's the style idea?

We need to improve the background of the docs page in light mode 

![image](https://github.com/priyankarpal/ProjectsHut/assets/97152850/9a9afdd8-c768-4b65-b34d-38e277f4a887)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

> These solid black lines make it hard to read the text and provide distraction 

I would like to contribute to this project by making this design subtle and soothing to eye
kindly assign me this issue as a GSSOC'23 contributor 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhairyaMajmudar** [comment]
please assign me this issue, I will solve it under GSSoC'23

**Comment by him-raw99** [comment]
I was hoping for you too assign this issue to me under GSSOC'23 @priyankarpal
