### ISSUE TITLE
[Docs]: rewrite the readme

### ISSUE THREAD

**Issue by poorvika11** [priyankarpal/ProjectsHut#449]
### in which language do you want to translate?

Documentaion of Project has less attractive README file. Technology used can be edited as it has lot of unusefull content. Also the readme file can have more details about project rather than having "How to Contribute instructions". These instructions can be provided in a separate file in a more elaborating way among other necessary files.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### in which language do you want to translate?
> Documentaion of Project has less attractive README file. Technology used can be edited as it has lot of unusefull content. Also the readme file can have more details about project rather than having "How to Contribute instructions". These instructions can be provided in a separate file in a more elaborating way among other necessary files.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

could you add a good title?

**Comment by poorvika11** [comment]
To the project or title to what?

**Comment by poorvika11** [comment]
It was by mistake, I have issued another issue, this was made by mistake and didn't know how to delete.
I want to update project's readme file as it is very de arranged.

**Comment by poorvika11** [comment]
Assign this task to me, I will rewrite the readme file.

**Comment by priyankarpal** [comment]
share your another issue number

**Comment by poorvika11** [comment]
Actually by mistake I had made two issue request of same problem. This is the main one issue#449. Assign #449 to me.

**Comment by priyankarpal** [comment]
> Actually by mistake I had made two issue request of same problem. This is the main one issue#449. Assign #449 to me.

share another issue number

**Comment by poorvika11** [comment]
#450

**Comment by priyankarpal** [comment]
assigned to you @poorvika11

**Comment by priyankarpal** [comment]
@poorvika11 could you share your progress on this issue?

**Comment by poorvika11** [comment]
Yes, mostly done. Just some changes required. PR against this issue will be generated by tomorrow surely.

**Comment by poorvika11** [comment]
@priyankarpal task done. You can review and merge it now

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
