### ISSUE TITLE
[Docs]:  Improvement and changes required

### ISSUE THREAD

**Issue by poorvika11** [priyankarpal/ProjectsHut#450]
### what's wrong in the documentation?

Documentaion of Project has less attractive README file. Technology used can be edited as it has lot of unusefull content. Also the readme file can have more details about project rather than having "How to Contribute instructions". These instructions can be provided in a separate file in a more elaborating way among other necessary files.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
don't create the same issue multiple times
