### ISSUE TITLE
[style]: Make dark mode toggle more accessible

### ISSUE THREAD

**Issue by sabhisharma-ise** [priyankarpal/ProjectsHut#452]
### What's the style idea?

Issue: The current dark mode toggle on the website is an emoji. This can be difficult to use for some users, such as those with visual impairments.

Solution: We propose to change the dark mode toggle to an actual switch. This will make it easier for all users to toggle dark mode.

Benefits: Changing the dark mode toggle to an actual switch will make the website more accessible to all users. This will help to improve the user experience and make the website more inclusive.

I hope this helps!

"I'm in GSSOC'23"

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/100849696/512aef32-bfe4-4d8b-9bca-70cadec2b916)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before https://github.com/priyankarpal/ProjectsHut/issues/376. We kindly request you review the existing issues and, if necessary, create a new one accordingly.
