### ISSUE TITLE
[Bug]: Dark mode is not working properly

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#453]
### What happened?

I found a BUG 🐞

When you click on dark mode and refresh the page for some fraction of a second the light mode is visible then the dark mode appears. However, it is not happening in light mode.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @suzy-g38
