### ISSUE TITLE
[style]: Redesign Docs Page

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [priyankarpal/ProjectsHut#456]
### What's the style idea?

Redesigning the Docs Page will be better so as to make it eye-catching.
I would like to redesign this !! 
Plz Assign me this Issue !!
I am a GSSOC'23 Contributor.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/333
