### ISSUE TITLE
[style]: improving home page buttons

### ISSUE THREAD

**Issue by poojaramnaney** [priyankarpal/ProjectsHut#458]
### What's the style idea?

We need to improve the buttons by adding hovering effect and make it more appealing to the users

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by poojaramnaney** [comment]
i have changed color to default color as it was previous

**Comment by priyankarpal** [comment]
show us a demo

**Comment by poojaramnaney** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/101456681/24e66e3b-3d17-4a49-882a-611e92f1fb49)
![image](https://github.com/priyankarpal/ProjectsHut/assets/101456681/2485c3a7-1eb2-4556-826d-9d6d0305d962)
![image](https://github.com/priyankarpal/ProjectsHut/assets/101456681/98b57d63-1ab5-4027-8f5c-4a76210f2854)

**Comment by priyankarpal** [comment]
pk push the changes

**Comment by poojaramnaney** [comment]
I have pushed the changes in the previous pr

**Comment by priyankarpal** [comment]
> I have pushed the changes in the previous pr

ok
