### ISSUE TITLE
data: project addition by sonustar

### ISSUE THREAD

**Issue by sonustar** [priyankarpal/ProjectsHut#462]
### Add a new project to the list

 I want to add a new project to the list 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Assigned to you @sonustar

**Comment by raju-kumar21** [comment]
I am a GSSoC'23 contributor. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by sonustar** [comment]
should I close this issue its done

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
