### ISSUE TITLE
data: project addition by vaibhav-xt

### ISSUE THREAD

**Issue by vaibhav-xt** [priyankarpal/ProjectsHut#463]
### Add a new project to the list

 I want to add a new project to the list on ProjectHut.

I like to add my Portfolio Project. 
![Screenshot (419)](https://github.com/priyankarpal/ProjectsHut/assets/90946899/4825afab-4218-460a-af70-218cbcc836a2)

This is my Frontend Developer portfolio made with HTML, CSS & JavaScript. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by vaibhav-xt** [comment]
Thanks to you for guiding me. ❤
