### ISSUE TITLE
[Feat]: Added Dynamic Copyright

### ISSUE THREAD

**Issue by rushabhpanbude** [priyankarpal/ProjectsHut#467]
### What feature?

I have an idea,
I can add  dynamic copyright in footer section which can auto update the current year.

### Add screenshots

![Capture](https://github.com/priyankarpal/ProjectsHut/assets/63780356/191ff2f0-e710-4057-9974-e447f619dee3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
