### ISSUE TITLE
Project Addition: React Quiz App

### ISSUE THREAD

**Issue by sshiwangi** [priyankarpal/ProjectsHut#468]
### Add a new project to the list

 I want to add a new project to the list. It is a Quiz Web App made with React and allows users to select an answer from a set of four possible answers and also calculates their score. 

![Screenshot 2023-05-20 111629](https://github.com/priyankarpal/ProjectsHut/assets/77545230/ef4f2859-88ce-47b9-a460-4064edec2e48)
![Screenshot 2023-05-20 111909](https://github.com/priyankarpal/ProjectsHut/assets/77545230/c7f73d8d-a10c-4b91-a990-b4170c9d11de)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Palakkgoyal** [comment]
Can you please assign this issue to me. I have a good understanding of both React and Tailwind.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
