### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hero-debug-cloud** [priyankarpal/ProjectsHut#470]
### What happened?

Home is not automatically selected at the starting of the website.
after selecting home section then it is selecting it and giving it borders.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/72332260/f0349cc9-ece1-4f6f-80a9-a95a32925aef)

![image](https://github.com/priyankarpal/ProjectsHut/assets/72332260/6d3a2710-8a62-4ecb-a7a0-dcf38d2ba272)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you add a good title?

**Comment by Hero-debug-cloud** [comment]
yeah, i want to work on this issue, please assign me under SSOC2023
