### ISSUE TITLE
DESUME | RESUME EDITOR FOR DEVELOPERS : React Project addition by itsme-shivamkumar

### ISSUE THREAD

**Issue by itsme-shivamkumar** [priyankarpal/ProjectsHut#471]
### Add a new project to the list

I want to add this project in the project list of ProjectsHut

# Desume Editor
## Features
- Google authentication for secure sign-in
- Editing of resumes using HTML and CSS directly in the app
- Ability to add styling like font size, letter spacing, font weight, color, and opacity
- Option to add elements using pure HTML code and inline style
- Option to delete any div in the HTML-based resume
- Responsive web mode for desktop screens
- Framer Motion library for animations
- jsPDF and html2canvas libraries for generating and downloading PDF resumes
- Installation
- To use Desume Editor, simply visit the website and sign in using your Google account.

## Usage
- Sign in with your Google account.
- Edit your resume using the text editor and styling options.
- Save your changes and download your resume in HTML or PDF format.
## Future Development
- Addition of layout customization and animation features
- Responsive design for mobile and tablet screens
- Technologies Used
## Desume Editor was built using the following technologies:
- React
- HTML
- CSS
- JavaScript
- Google authentication
- Framer Motion library
- jsPDF library
- html2canvas library

## Screenshots
![](https://github.com/itsme-shivamkumar/desume/blob/c4af297398cb71c8e452d1eb9ec1eebf96c30cd3/screenshots/p1.gif)
![](https://github.com/itsme-shivamkumar/desume/blob/c4af297398cb71c8e452d1eb9ec1eebf96c30cd3/screenshots/p2.gif)
![](https://github.com/itsme-shivamkumar/desume/blob/c4af297398cb71c8e452d1eb9ec1eebf96c30cd3/screenshots/p3.gif)
![](https://github.com/itsme-shivamkumar/desume/blob/c4af297398cb71c8e452d1eb9ec1eebf96c30cd3/screenshots/p4.gif)
## Contributing
This project was developed by a single developer [itsme-shivamkumar](https://github.com/itsme-shivamkumar), but contributions are always welcome. Please submit a pull request for any changes or fixes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
