### ISSUE TITLE
[Feat]: Adding Social Media Link in the Project Card

### ISSUE THREAD

**Issue by SagarNarsingani** [priyankarpal/ProjectsHut#473]
### What feature?

Basically, my idea is to give some more reference to the project owner, we can add a link on the profile image that is shown on the project card. User can provide link of any social media handle that he/she wants to show (only if he/she wants). This feature will give more credibility to the project owner and in case someone wants to contact the project owner then he/she can directly click on the link (instead of going in the repo -> user profile). It will add a little bit of convenience for the end users.

I am a **GSSoC'23 Contributor** and I am interested to contribute to this project, please review and assign me this issue if you find it valid.

### Add screenshots

Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/64188422/75d24eaf-0d48-4716-a5af-71b5de018b1d)

I am talking about the image in the top-right corner, I hope it makes sense.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we alreaddy have a profile page for users & where we have added our social media links

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/b66b3d11-349f-4785-b783-82da88334e67)
