### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by hrshtmlng** [priyankarpal/ProjectsHut#474]
### What feature?

I have an idea that we can add some animations on the buttons of navbar!!

### Add screenshots

Add screenshots
![Web capture_21-5-2023_123356_projectshut vercel app](https://github.com/priyankarpal/ProjectsHut/assets/101478591/7da56696-fdde-4d53-afbe-49e4dab76b8d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we improved the navbar 

https://github.com/priyankarpal/ProjectsHut/pull/623
