### ISSUE TITLE
[style]: Navbar improvements

### ISSUE THREAD

**Issue by faisalsaifii** [priyankarpal/ProjectsHut#475]
### What's the style idea?

We need to improve the navbar to have a sticky property so that it always stays there after scrolling through the page. Rounded edges and top margin would give it a modernised look.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/47176738/0166e576-4a1a-4734-862a-62ed17386006)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I guess the previous one is better.
