### ISSUE TITLE
data: project addition by abhinav_m22

### ISSUE THREAD

**Issue by abhinav-m22** [priyankarpal/ProjectsHut#476]
### Add a new project to the list

 I want to add a new project to the list 
The project is a Clone of Google Keep - a notes application built using ReactJS.

### Code of Conduct

- [.] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by raju-kumar21** [comment]
I am a GSSoC'23 contributor. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by abhinav-m22** [comment]
Added a PR - #520 
Please have a look.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
