### ISSUE TITLE
data: project addition by Lokesh Sangrame  

### ISSUE THREAD

**Issue by LokeshSangrame** [priyankarpal/ProjectsHut#479]
### Add a new project to the list

Introducing Algo Viewer, a captivating project by Me. Visit https://lokeshsangrame.github.io/Algo_Viewer/ to explore interactive visualizations of various algorithms. Gain a deeper understanding of their inner workings and embark on an algorithmic journey today!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @LokeshSangrame

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 


Thank you for your understanding.
