### ISSUE TITLE
[style]: Add hovering properties to the buttons and animation to text and images in the website

### ISSUE THREAD

**Issue by Arunjagan12** [priyankarpal/ProjectsHut#481]
### What's the style idea?

The idea is add respective hovering properties to the buttons and some animations to the images as it helps to enhance a better user experience and also helps user to easily navigate through the website. I am a **gssoc'23** contributor.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before https://github.com/priyankarpal/ProjectsHut/issues/458. We kindly request you review the existing issues and, if necessary, create a new one accordingly.
