### ISSUE TITLE
[style]: Make the navbar sticky and prominent

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#482]
### What's the style idea?

Make the navbar sticky so that it comes down with the user when they scroll down and also to make it more prominent looking we can make the background of the navbar blur and translucent,This would make the navbar look more alluring and attractive

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we assigned you in few issues so we're unable to assign you to this issue now. so you need to work on those issues first.

**Comment by karthiknadar1204** [comment]
Is it fine if i fix this issue by evening as the toggle switch might take some time to rewrite the logic with a switch @priyankarpal ,I think I can get it done pretty well

**Comment by karthiknadar1204** [comment]
Fine, have begun

**Comment by karthiknadar1204** [comment]
Done with box shadow and made the navbar sticky as well,will submit pr in a bit @priyankarpal with the ss

**Comment by vishnu9865** [comment]
@priyankarpal ,
Sir If you have any other ideas with regards to this issue to be implemented, please feel free to ask me.
I would be happy to do it for you regarding this issue. 😊👍🏽

**Comment by priyankarpal** [comment]
> @priyankarpal , Sir If you have any other ideas with regards to this issue to be implemented, please feel free to ask me. I would be happy to do it for you regarding this issue. blush👍🏽

share a ss for mobile view

**Comment by vishnu9865** [comment]
> > @priyankarpal , Sir If you have any other ideas with regards to this issue to be implemented, please feel free to ask me. I would be happy to do it for you regarding this issue. blush👍🏽
> 
> share a ss for mobile view

![projectshut vercel app_ (1)](https://github.com/priyankarpal/ProjectsHut/assets/91585213/97b456ae-be11-4a6c-b6f4-dac5ba5df639)

**Comment by priyankarpal** [comment]
> > > @priyankarpal , Sir If you have any other ideas with regards to this issue to be implemented, please feel free to ask me. I would be happy to do it for you regarding this issue. blush👍🏽
> > 
> > 
> > share a ss for mobile view
> 
> ![projectshut vercel app_ (1)](https://user-images.githubusercontent.com/91585213/239892746-97b456ae-be11-4a6c-b6f4-dac5ba5df639.png)

ok assigned to you @vishnu9865

**Comment by vishnu9865** [comment]
Thank you @priyankarpal for assigning this issue to me.
