### ISSUE TITLE
[Bug]: change pages URL

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#484]
### What happened?

Currently, we have added a new feature that is a lowercase URL on the site so we need to change URLs
## Where to change?
- change URLs for the mobile view according to the desktop view page URLs
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/6bbf867b-32d9-4a45-b7b4-4abe7a2fe8d8)
- change browse project url
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/b5d51da5-c6c7-4c76-bf49-407f9bf81b89)
- change and add your projects guide URL 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/9647f9d8-8d55-42b2-acfb-febcc86c572a)
- Change for docs
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/349af4a2-8384-4008-9090-495435aaffad)

### Correct URLs available for only desktop mode

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/47ad20b5-a7b7-445a-8178-778e6d361b86)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by narayan2111** [comment]
I would like to work on this issue.
Kindly assign this issue to me.

**Comment by priyankarpal** [comment]
> I would like to work on this issue. Kindly assign this issue to me.

assign to you

**Comment by raju-kumar21** [comment]
I am a GSSoC'23 contributor. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.

**Comment by priyankarpal** [comment]
> I am a GSSoC'23 contributor. I have all the skills required. Please assign me this issue, I want to work on this issue under the GSSoC'23.

don't do spam

**Comment by GyanPrakashRaj** [comment]
Hlw @priyankarpal Is this issue still open for PR?

**Comment by narayan2111** [comment]
> Hlw @priyankarpal Is this issue still open for PR?

I'm working on this bug and it is in process but don't why this issue is marked as close.

**Comment by priyankarpal** [comment]
> > Hlw @priyankarpal Is this issue still open for PR?
> 
> I'm working on this bug and it is in process but don't why this issue is marked as close.

some folks are creating duplicate issue so we need to mention this issue to their issue. don't worry about this.

**Comment by priyankarpal** [comment]
> Hlw @priyankarpal Is this issue still open for PR?

yeah

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @narayan2111

**Comment by Soulpurr** [comment]
Can you assign this issue to me if it's still open 
Under gssoc'23?

**Comment by narayan2111** [comment]
> could you share your progress on this issue? @narayan2111

Currently my semester exams are going on, if you don't mind, can I take more time than usual.

**Comment by priyankarpal** [comment]
> > could you share your progress on this issue? @narayan2111
> 
> Currently my semester exams are going on, if you don't mind, can I take more time than usual.

ok take your time if you're unable to work after certain time you can comment here

**Comment by narayan2111** [comment]
> > > could you share your progress on this issue? @narayan2111
> > 
> > 
> > Currently my semester exams are going on, if you don't mind, can I take more time than usual.
> 
> ok take your time if you're unable to work after certain time you can comment here

Thank you so much sir for your cooperation and continuous help.

**Comment by coder12git** [comment]
@priyankarpal Is this issue still open? I want to work on it.

**Comment by narayan2111** [comment]
@priyankarpal Thank you so much sir for your consideration, You can assign this issue to others as I will not be able to do as of now . I'm sorry for the inconvenience caused.

**Comment by coder12git** [comment]
Hey @priyankarpal I really want to work on this issue under GSSOC 2023. Please assign this to me!

**Comment by priyankarpal** [comment]
> Hey @priyankarpal I really want to work on this issue under GSSOC 2023. Please assign this to me!

assigned to you
