### ISSUE TITLE
data: project addition by Yash Kumar Shrivas

### ISSUE THREAD

**Issue by YashkShrivas4491** [priyankarpal/ProjectsHut#485]
### Add a new project to the list

I'm in GSSOC'23 

I want to add a new project to the list which is Weather Website link-https://yashkshrivas4491.github.io/WeatherWebApp/
* This project is about building a web application to show a weather forecast using weather API from external services Open weather map.
* Here you will be able to search for a specific location in the world and also it will automatically detect your current location in the beginning (for that you need to allow location) and will display all the important weather details. 

 # Features
Easily Fetch data from API.
Zero dependencies.
Background image changes according to the country's input.
It show humidity , wind , temperature.
if you enter wrong country's name than it show no data available.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to @YashkShrivas4491

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
