### ISSUE TITLE
[Docs]: Add How to Create Issue If You are in GSSOC'23 

### ISSUE THREAD

**Issue by suzy-g38** [priyankarpal/ProjectsHut#487]
### what's wrong in the documentation?

In the current format, there is no mention of how to create an issue for gssoc'23 participants. It will be really helpful  if we mention how to do that.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to @suzy-g38

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
