### ISSUE TITLE
Switch from HTML to React

### ISSUE THREAD

**Issue by RotrixLOL** [priyankarpal/ProjectsHut#49]
**Is your feature request related to a problem? Please describe.**
I would suggest to switch from HTML because the index.html file will be way too big in a future.

**Describe the solution you'd like**
So, I would switch to react, as you can create a component and then the people who want to put their projects only have to add a new component.

**Describe alternatives you've considered**
Even better would be to add that information to a json file and parse it.

**Comment by RotrixLOL** [comment]
If you like this improvement, I’ll love to work on it!

**Comment by priyankarpal** [comment]
yes, @RotrixLOL I also working on this point. You can work on it

**Comment by priyankarpal** [comment]
I thought it is getting heavy. I will add ReactJs after a few days. If you want to add you can create an PR

**Comment by RotrixLOL** [comment]
OK, I opened a PR. I migrated to react, parse projects from `src/projects.json` and changed tech to be represented as a tag.

**Comment by priyankarpal** [comment]
Merged your PR. Thanks for your awesome contribution. 🎉 ❤️
