### ISSUE TITLE
Text Color Change

### ISSUE THREAD

**Issue by Anshkaran7** [priyankarpal/ProjectsHut#490]
### What's the style idea?

When I hover over the navigation elements, both the background color and text color appear dark. I would like to change the text color to white as it would look much better.
Please assign me this issue under GSSOC 2023.

### Add screenshots

Add screenshots
![Screenshot 2023-05-21 023003](https://github.com/priyankarpal/ProjectsHut/assets/106963118/b7e4d116-bc44-4124-a5b0-3e3e4411d63e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before https://github.com/priyankarpal/ProjectsHut/issues/373. We kindly request you to review the existing issues and, if necessary, create a new one accordingly.
