### ISSUE TITLE
[Feat]: Seamless page transitions!!

### ISSUE THREAD

**Issue by SaiAbhinavGoud** [priyankarpal/ProjectsHut#492]
### What feature?

I'm in GSSOC'23

Seamless page transitions!!
Every time I switch pages, the transition is not seamless, and there aren't many transitions over the entire website. 

I have prior experience in web development I'd like to contribute to making the ProjectsHut website more seamless.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you add a demo?

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 


Thank you for your understanding.
