### ISSUE TITLE
[Bug]: Check Documentation 404 error.

### ISSUE THREAD

**Issue by Atharva-3000** [priyankarpal/ProjectsHut#493]
### What happened?

I found a BUG 🐞
While clicking on **Check Documentation** on the website, it gives a 404 error, rather than redirecting to this repo, I would like to fix this bug.

### Add screenshots

Add screenshots

![aa1](https://github.com/priyankarpal/ProjectsHut/assets/72994819/1d7db389-50e1-4943-a535-1840824091b3)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/484
