### ISSUE TITLE
[Feat]: Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [priyankarpal/ProjectsHut#495]
### What feature?

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes. we need to add this feature.

btw are you in GSSoC'23?

**Comment by M-A-N-I-K** [comment]
Yup i am in GSSOC'23 and assign me this task so that i can start working on it as soon as possible!

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
