### ISSUE TITLE
[style]: Add hover and active state transitions on gradient buttons.

### ISSUE THREAD

**Issue by curiousyuvi** [priyankarpal/ProjectsHut#496]
### What's the style idea?

I'm in GSSOC'23

I think if on hover over gradient buttons if there is a transition of the gradient sliding it would look good and more interactive,
and on active state that is when the button is clicked if there is a shrink transition it would also look good.

### Add screenshots

I'm referring to these gradient buttons
![Screenshot from 2023-05-21 16-44-39](https://github.com/priyankarpal/ProjectsHut/assets/58589519/1db10922-4451-4d55-b135-78126859d215)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by curiousyuvi** [comment]
I think something like this would look good.
![button-gradient-demo](https://github.com/priyankarpal/ProjectsHut/assets/58589519/11045153-8025-4662-8ae3-34bb8f67d9cd)

There is a gradient slide transition and scale transition on hover. If you think this looks good or suggest some other style, I can go ahead & create a PR, thanks😄.

**Comment by priyankarpal** [comment]
I think only scale is good. remove the gradient slide transition & create a PR

**Comment by curiousyuvi** [comment]
Ok, I also have one other idea, what if I add a translate x transition to the arrow on hover.
![ezgif com-video-to-gif (1)](https://github.com/priyankarpal/ProjectsHut/assets/58589519/e9c3f542-0c59-403a-8a87-c4ab6772574f)
What do you think about this?

**Comment by priyankarpal** [comment]
> Ok, I also have one other idea, what if I add a translate x transition to the arrow on hover. ![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/58589519/239889740-e9c3f542-0c59-403a-8a87-c4ab6772574f.gif) What do you think about this? or should I just go with the scale transition?

yeah I guess it will look better
