### ISSUE TITLE
data: project addition by urz-ahmed #141

### ISSUE THREAD

**Issue by urz-ahmed** [priyankarpal/ProjectsHut#497]
### Add a new project to the list

 I want to add a new project to the list which is social utopia
 It is made with React and Firebase.
 where user can login register and do some extra works like adding their content giving review to other contents like that.
 please Assign me this issue under gssoc'23
![Screenshot 2023-05-21 164724](https://github.com/priyankarpal/ProjectsHut/assets/106316083/1c57c83f-705e-49ec-8800-6c06e5ac67fe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by urz-ahmed** [comment]
Social Utopia Project Added #559
I have added my project please check it now and merge it.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
