### ISSUE TITLE
Yarn function is making problem in several cases [Docs]: 

### ISSUE THREAD

**Issue by Supriyo-I** [priyankarpal/ProjectsHut#498]
### what's wrong in the documentation?

We need to add I will try to add more detailed instruction for the user to use the repo

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you describe the issue a little bit? @Supriyo-I

**Comment by Supriyo-I** [comment]
Hii,
I am really sorry it was my falt it the code.
I was using node.js functions in the code but the project uses react.js it was an accident.
I will let you know if I find any new issues.
If you have any issues pending than please assign it to me.

I am extremely sorry for this inconvenience. 😢

**Comment by priyankarpal** [comment]
> Hii, I am really sorry it was my falt it the code. I was using node.js functions in the code but the project uses react.js it was an accident. I will let you know if I find any new issues. If you have any issues pending than please assign it to me.
> 
> I am extremely sorry for this inconvenience. cry

you can check issues labeled as "status: ready for dev"
