### ISSUE TITLE
data: project addition by jfmartinz

### ISSUE THREAD

**Issue by jfmartinz** [priyankarpal/ProjectsHut#500]
### Add a new project to the list

**I'm in GSSOC'23**. I want to add a new project to the list which is Etch a Sketch. I'd be happy to add this website to the website since I really work hard for this project and learned a lot JS concepts. Pls assign this to me :)

![image](https://github.com/priyankarpal/ProjectsHut/assets/129386460/c77f42a0-87fa-470f-811c-ed6c849cdb27)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
