### ISSUE TITLE
[Docs]: update README.md

### ISSUE THREAD

**Issue by SagarSharma2809** [priyankarpal/ProjectsHut#501]
### what's wrong in the documentation?

In line number 15 of the README.md file, the sentence structure is not making sense, This can create confusion for the reader trying to understand the project

![image](https://github.com/priyankarpal/ProjectsHut/assets/108415064/59716e18-9270-4ea5-8ae2-929266aec19d)

I can frame the sentence correctly by removing the full stop and adding coma with small letter w for "with"

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
