### ISSUE TITLE
data: project addition by [Arunjagan12]

### ISSUE THREAD

**Issue by Arunjagan12** [priyankarpal/ProjectsHut#502]
### Add a new project to the list

**I'm in gssoc'23**. I want to add my portfolio which I have developed using react, framer motion and three.js .The portfolio consists of my work experience, skills, projects, etc.. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
