### ISSUE TITLE
[style]: align footer text

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#504]
### What's the style idea?

We need to align the footer text for desktop & mobile views

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/83fc6828-1ecd-4b0a-9b7c-d455c08e896d)
![Screenshot from 2023-05-21 18-26-18](https://github.com/priyankarpal/ProjectsHut/assets/88102392/ca6e9893-f82b-4450-a8dd-1cf8b02bd0db)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rushabhpanbude** [comment]
You can assign this to me @priyankarpal

**Comment by priyankarpal** [comment]
> You can assign this to me @priyankarpal

I have assigned you another issue. now I can't assign you. so please work on that issue first

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, Please assign this footer styling to me if no one is currently working on it. I would also like to add some other page links in the footer.

assigned to you @ritik48

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
