### ISSUE TITLE
Weather app

### ISSUE THREAD

**Issue by Niladri2003** [priyankarpal/ProjectsHut#510]
### Add a new project to the list

 I want to add a new project to the list 
I have a fully functional weather app made with Html, Css and Js  which is also responsive.
I am adding website link
[Weather app](https://weather-app-ashy-eight.vercel.app/)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
