### ISSUE TITLE
data: project addition by Himanshu kumar

### ISSUE THREAD

**Issue by HIMANSHU00KUMAR** [priyankarpal/ProjectsHut#514]
### Add a new project to the list

I want to add a project created by me
which is a landing page of  a insurance company
Teckstack used - HTML, Tailwind css, React  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
