### ISSUE TITLE
[style]: Fixing Navbar styling for Small screens.

### ISSUE THREAD

**Issue by abhrajitray77** [priyankarpal/ProjectsHut#517]
### What's the style idea?

I'm in Gssoc'23.
We need to improve the navbar styling on small screens.
Specifically:

- Fixing the hover effect (colour and transition)
- Fixing the Margin (left)

### Add screenshots

Add screenshots
![Screenshot 2023-05-21 19-22-57](https://github.com/priyankarpal/ProjectsHut/assets/67530432/86f05a1e-7494-472c-ac75-17027add6578)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/373
