### ISSUE TITLE
Fix: update the contributing.md file

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#52]
### Need to fix the contributing.md file with proper screenshots. 

- Add how beginners can contribute without running code locally.
- Add how devs can run code locally step by step.

**Comment by Aathirajan** [comment]
Looking great!

**Comment by Aathirajan** [comment]
Is it up for grabs?

**Comment by priyankarpal** [comment]
> Is it up for grabs?

You can work on this issue.

**Comment by Aathirajan** [comment]
It seems like a good first issue, I'll look for other issues.

**Comment by priyankarpal** [comment]
> It seems like a good first issue, I'll look for other issues.

ok

**Comment by ChristianBega** [comment]
Hello, I'm new to open source contributions and I love the idea of this project. How can I start?

**Comment by priyankarpal** [comment]
> Hello, I'm new to open source contributions and I love the idea of this project. How can I start?

hi @ChristianBega currently you can start by adding your projects. You can check the [documentation](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md).
