### ISSUE TITLE
[Docs]: Add README badges

### ISSUE THREAD

**Issue by S-ishita** [priyankarpal/ProjectsHut#523]
### what's wrong in the documentation?

We need to add readme badges

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you elaborate this issue?

**Comment by S-ishita** [comment]
Similar to this 
![Uploading 239758946-e9947bc2-410f-4097-8557-93c55b807b62.png…]()

**Comment by priyankarpal** [comment]
we need to add one badge `open source is ❤️`  

assigned to you
