### ISSUE TITLE
[Feat]: create a documentation site for ProjectsHut

### ISSUE THREAD

**Issue by akkshayTandon** [priyankarpal/ProjectsHut#530]
### What feature?

As per the current structure we the we have some documentation for the project.
I want to suggest an idea where we can create a docs website for ProjectsHut.
### Pros
- improved UI for visitors to better understand the project
- improved UI for contributors to better understand the project for contributions
- can be developed as separate project and integrate/connect to main website later on
### Cons
- may take time
- may increase complexity as per further developments
### Example
- Project: https://codethesaur.us/
- docs: https://docs.codethesaur.us/

### Add screenshots

nil

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we already have a doc page i guess we don't need to separate website for docs
