### ISSUE TITLE
Add Navbar background on hover

### ISSUE THREAD

**Issue by EraKin575** [priyankarpal/ProjectsHut#532]
### What feature?

Adding background color on hover over Navbar elements

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/100225222/45fb354d-404f-423e-afbd-9ad8e1af191c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before https://github.com/priyankarpal/ProjectsHut/issues/373. We kindly request you to review the existing issues and, if necessary, create a new one accordingly.
