### ISSUE TITLE
[Feat]: Create a backend api for the project data to be updated and fetched

### ISSUE THREAD

**Issue by Kuldeep2001** [priyankarpal/ProjectsHut#533]
### What feature?

I want to create a Django backend and models so that we can get the projects with all their details using API request.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah also, we were thinking that we will add the backend API. & we will add it later
