### ISSUE TITLE
[Bug]: Inability to Sort Projects Based on Multiple Tech Stacks on ProjectsHut [ GSSoC23' ]

### ISSUE THREAD

**Issue by itsme-shivamkumar** [priyankarpal/ProjectsHut#535]
### The project sorting feature on ProjectsHut currently lacks the ability to sort projects based on multiple tech stacks simultaneously. This limitation hampers the user experience by restricting efficient filtering and identification of projects that align with specific technological requirements.

- Before Preview:
On ProjectsHut, the projects page serves as a hub for users to explore a variety of projects. Each project is associated with one or more tech stacks, indicating the technologies used in its development. However, the existing sorting feature on ProjectsHut only allows users to select one tech stack at a time, limiting their ability to discover projects that meet complex technological needs effectively.

https://github.com/priyankarpal/ProjectsHut/assets/91745441/5a786120-288c-40ac-8bc5-bb719d4a3e16

- After Preview:
After implementing the necessary changes, users will gain the capability to select multiple tech stacks for sorting projects on ProjectsHut. This enhancement will empower them to efficiently identify projects that combine various technologies, providing greater flexibility and precision in finding projects that align with their specific needs.

https://github.com/priyankarpal/ProjectsHut/assets/91745441/dd05042c-a5c1-4c40-bcdc-43f6c9892815

[Note: I have already worked on this, Kindly assign this issue to me so that I can fix this issue and allow me for further improvements]

### To Reproduce:

- Visit the ProjectsHut website.
- Navigate to the projects page.
- Observe the project sorting functionality, noting its limitation of selecting only one tech stack.

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
If someone wants to see only CSS-related projects they need to select only CSS they don't need to select multiple tags. 

 I guess it will cause confusion for users. in future, if we want to add this feature I will ping here.
