### ISSUE TITLE
Project addition by Abhay-raj19.

### ISSUE THREAD

**Issue by abhay-raj19** [priyankarpal/ProjectsHut#536]
## Add a new project to the list
I want to add a new project to the list. The name of the project is the Newsletter which is created using react,HTML,CSS,JS,etc.
Please assign me this issue.
Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhay-raj19** [comment]
I will be completing it as soon as possible.
Thankyou for assigning😊.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
