### ISSUE TITLE
[style]: Changing the css for the docs page

### ISSUE THREAD

**Issue by raghav1030** [priyankarpal/ProjectsHut#537]
### What's the style idea?

We need to improve the docs page as it seems difficult to read because of the background image or whatever is being inserted. Since it is a page that requires the user's attention to read so it should be clearer and easy to read.

I would like to work on it and this is regarding gssoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share a demo of problem?

**Comment by raghav1030** [comment]
![Screenshot 2023-05-21 231330](https://github.com/priyankarpal/ProjectsHut/assets/94848646/738ce788-d8ca-4e83-9296-deedf255862c)
Sure, here is the ss of the issue.

ps: The prev ss was put mistakenly. Sorry!

**Comment by priyankarpal** [comment]
> ![Screenshot 2023-05-21 231330](https://user-images.githubusercontent.com/94848646/239892209-738ce788-d8ca-4e83-9296-deedf255862c.jpg) Sure, here is the ss of the issue.

this is a SVG image

**Comment by raghav1030** [comment]
okay ? but whatever it is , it is not appearing correctly ig?

what do you think?

**Comment by priyankarpal** [comment]
I guess it's ok.
