### ISSUE TITLE
About fonts

### ISSUE THREAD

**Issue by bobbyy16** [priyankarpal/ProjectsHut#54]
This text color is not visible clearly in dark mode. I suggest to change the font color to white.
![Screenshot from 2023-03-06 09-39-44](https://user-images.githubusercontent.com/62874675/223017779-0cac7e7c-57ee-44e4-81a3-b16e5d3bb1ae.png)

**Comment by priyankarpal** [comment]
hi, @bobbyy16 ok ok. On my laptop, it's showing normal. But I think the white colour needs to add. You can work on this issue.

**Comment by bobbyy16** [comment]
sure! already working on it
