### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RoshanAnsy** [priyankarpal/ProjectsHut#540]
### What happened?

I am getting 404 errors on the small screen on the document page.[GSSoS 2023]
  

### Add screenshots

![Screenshot 2023-05-21 234143](https://github.com/priyankarpal/ProjectsHut/assets/91673102/0abf3daf-e226-4c87-b0aa-247e731debb5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/484

also don't do spam
