### ISSUE TITLE
CPI calculator react app: project addition by itsme-shivamkumar [ GSSOC'23 ]

### ISSUE THREAD

**Issue by itsme-shivamkumar** [priyankarpal/ProjectsHut#541]
### Add a new project to the list

 I want to add a new project to the list 

## Key Features:

- CPI Calculation: The app should include a calculation algorithm that takes into account the expected performance grades of each subject, the credit points of the previous semester, and the CPI to provide an accurate current CPI calculation.
- User-friendly Interface: The app should have a clean and modern user interface, making it easy for students to input their information and obtain their CPI quickly.
- Seamless Data Entry: The web app should allow students to enter their subject-specific information, such as the expected performance grades and credit points, in an intuitive manner.
- Missing Dataset Collaboration: As the initial dataset is incomplete, students should be encouraged to collaborate and help fill in the missing data to ensure accurate CPI calculations for all subjects, semesters, and branches.
- Feedback and Improvement: The app should encourage students to provide feedback on their experience using the web app, allowing for continuous improvement and addressing any usability issues.
## Benefits:

- Simplified CPI Calculation: With the WhatIsMyScore web app, NIT Raipur students can save time and effort by automatically calculating their CPI instead of performing the calculations manually.
- User-friendly Experience: The app's intuitive interface ensures that students can easily input their information and obtain their CPI without any confusion or complexity.
- Efficient Academic Planning: By having access to their current CPI, students can make informed decisions regarding their course selections and academic planning for future semesters.
- Collaborative Effort: Encouraging students to contribute to filling in the missing dataset fosters a sense of community and collective support among NIT Raipur students, resulting in a comprehensive and accurate tool for all.
- Continuous Improvement: By actively seeking feedback from users, the web app can be continuously improved to meet the evolving needs of NIT Raipur students, ensuring a seamless experience for all users.
Implementation Details:
- To implement this issue, the following steps should be considered:

- Develop the WhatIsMyScore web app using React JS, CSS, and jQuery for DOM manipulation to ensure a modern and user-friendly interface.
Implement the CPI calculation algorithm that considers expected performance grades, previous semester credit points, and CPI.
- Design an intuitive data entry system that allows students to input subject-specific information efficiently.
- Establish a collaboration mechanism for students to contribute and fill in the missing dataset, ensuring accuracy for all subjects, semesters, and branches.
- Collect user feedback and actively address any usability issues or suggestions for improvement to enhance the overall experience of the web app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
you don't need approval for `project addition` issue
