### ISSUE TITLE
GeoTrackerX vanilla javascript project addition by vaishalidewangan786 [GSSOC'23]

### ISSUE THREAD

**Issue by vaishalidewangan786** [priyankarpal/ProjectsHut#542]
## About The App

 - The app is a IP tracker with geo location.
 - It allows users to search the web with ease and convenience. 
 - The web application displays the location, city,time-zone, postal code, and region of the IP address that user enters.
 - The web application also displays information about the name, domain, ISP, proxy, VPN, and Tor of the IP address.
 - Users can also quickly re-search without having to return to the homepage to perform a new search.
 
## Technologies

 - The app was built using HTML, CSS, JavaScript.
 - Asynchronous programming is implemented through calling a Geolocation API by IPify. 
 - leaflet open-source JavaScript library is used to display map
 - CSS is used to style the layout and HTML elements. 
 - Javascript is used to give functionalty to the web.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
