### ISSUE TITLE
[style]: upgrading the boxes containing the data for projects

### ISSUE THREAD

**Issue by sanchitaa14** [priyankarpal/ProjectsHut#543]
### What's the style idea?

We need to improve the boxes and their style along with the background, the boxes are too close and leave the side spaces which looks a bit off, and it could also use some css upgradation to make it look more efficient.

### Add screenshots

Add screenshots
![Screenshot 2023-05-22 003430](https://github.com/priyankarpal/ProjectsHut/assets/118709611/8e2b13b2-4859-4f70-9068-0aec5d40430d)
the info box should look like this
![image](https://github.com/priyankarpal/ProjectsHut/assets/118709611/ce3bae6b-7b1a-4776-90e5-1c9fd8ef66c1)
and arranged like the boxes above with three in one row

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanchitaa14** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/118709611/2c3b5310-193e-4b5e-b2f3-93105d561d85)
like these short project info boxes are too plain, and can be updated. For example if you want someone to go to the site and open these projects, they will for sure be attracted by the catchy look of the info about it. Right now to be honest, it is a bit basic and just provides the info, I could edit the css, make it look more catchy to attract the attention of the viewers.

**Comment by sanchitaa14** [comment]
yes sure, by the way i am a part of gssoc'23

**Comment by priyankarpal** [comment]
hey @sanchitaa14  we are working on redesigning the card so now we can close this issue
