### ISSUE TITLE
data: project addition by Arnab Barua

### ISSUE THREAD

**Issue by Arnabhit** [priyankarpal/ProjectsHut#546]
### Add a new project to the list

 I want to add a new project to the list which is a netflix clone made from html and css for contributing in GSSOC'23 .Can you Please assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @Arnabhit

**Comment by Arnabhit** [comment]
@priyankarpal first of all I apologize for the delay as  my end sem practicals are going on that's why I am inactive right now but i will complete as soon as possible.

**Comment by priyankarpal** [comment]
> @priyankarpal first of all I apologize for the delay as  my end sem practicals are going on that's why I am inactive right now but i will complete as soon as possible.

i can feel your pain 🥲. it's a best practice, giving an update to Maintainers that you will be free after a few days 😊

**Comment by Arnabhit** [comment]
Thank you 😊
