### ISSUE TITLE
data: project addition by Hanshika Agarwal

### ISSUE THREAD

**Issue by hansi-2305** [priyankarpal/ProjectsHut#550]
### Add a new project to the list

 I want to add a new project to the list which is a travel website , it is a basically a guide which will give you a brief about the place you are willing to visit and benefits of the tour.
This project is made using html and css for contributing in GSSOC'23.
Please assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @hansi-2305

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.

**Comment by hansi-2305** [comment]
Please give me a chance.
please dont close this issue
