### ISSUE TITLE
data: project addition by junaid-arif-24

### ISSUE THREAD

**Issue by junaid-arif-24** [priyankarpal/ProjectsHut#551]
### Add a new project to the list

 I want to add a new project to the list of contributing in GSSoc'23  which is the real-time chat app using ReactJS which has features like online statuses, great design and functionality, icons telling you who read the message, image support, sound notifications, the ability to create multiple rooms, and much more...
Please Assign me this Issue.
Tech Stack:  CSS3 and ReactJS
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @junaid-arif-24

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
