### ISSUE TITLE
data: project addition by Abhinav kumar

### ISSUE THREAD

**Issue by Abhinavcode13** [priyankarpal/ProjectsHut#555]
### Add a new project to the list

 I want to add a new project to the list which is based on data science and python (movie recommender system) under Gssoc 23.

thanks and regards
Abhinav Kumar

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share your progress on this issue? @Abhinavcode13

**Comment by Abhinavcode13** [comment]
working on it @priyankarpal will create a pr soon

**Comment by Abhinavcode13** [comment]
where to add project , which file?

**Comment by Abhinavcode13** [comment]
@priyankarpal

**Comment by priyankarpal** [comment]
> where to add a project, and which file?

in the DB folder I already mentioned in the docs please check https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md

**Comment by Abhinavcode13** [comment]
so we basically have to deploy our project somewhere?

**Comment by priyankarpal** [comment]
> so we basically have to deploy our project somewhere?

I didn't understand.

**Comment by Abhinavcode13** [comment]
To provide the link of the project , we have to deploy it somewhere?

**Comment by Abhinavcode13** [comment]
hello @priyankarpal ?

**Comment by priyankarpal** [comment]
> hello @priyankarpal ?

you can add github repo url

**Comment by Abhinavcode13** [comment]
Cool @priyankarpal

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
