### ISSUE TITLE
data: project addition by Abhrajit Ray

### ISSUE THREAD

**Issue by abhrajitray77** [priyankarpal/ProjectsHut#557]
### Add a new project to the list

 I want to add a new project to the list based on a reactjs chrome extension that functions as a web clipper and a OpenAI gpt chat chatbot as well.
 
 I'm in Gssoc'23. Kindly assign me this issue.
 
 Tech Stack: Reactjs, Tailwind CSS, Typescript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
