### ISSUE TITLE
data: project addition by abhinav_m22

### ISSUE THREAD

**Issue by abhinav-m22** [priyankarpal/ProjectsHut#558]
### Add a new project to the list

 I want to add a new project to the list 
The project is a Google Chrome extension for adding Bookmarks of YouTube video timestamps.
Users can bookmark a video at particular timestamp and resume watching it later.

Please assign me the task under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
