### ISSUE TITLE
data: project addition by Sasi Vardhan A

### ISSUE THREAD

**Issue by SasiVardhan247** [priyankarpal/ProjectsHut#563]
### Add a new project to the list

 I want to add a new project to the list 
My Project is UserLocation. The UserLocation web app is useful in many real-world cases to locate the nearest available surrounding people. It's useful to locate Hospitals in case of emergency and also all the nearest places that can be located. This WebApp is built using JavaSpring Boot and Gradle.
Can you assign this to me.
I'm in gssoc'23.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
