### ISSUE TITLE
Add Animation on scroll[Feat]: 

### ISSUE THREAD

**Issue by Guli93** [priyankarpal/ProjectsHut#564]
### What feature?

I have an idea I can add some nice scroll animations.

please give me the opportunity by assigning this task to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you elaborate? where we need to add scroll?

**Comment by Guli93** [comment]
> could you elaborate? where do we need to add a scroll animations?

yeah sure!!

on home page if images and text will have animation when you scroll down it will make the UI more attractive.

**Comment by priyankarpal** [comment]
> > could you elaborate? where do we need to add a scroll animations?
> 
> yeah sure!!
> 
> on home page if images and text will have animation when you scroll down it will make the UI more attractive.

ok ok, could you share a demo? Are you planning to utilize Framer Motion??

**Comment by priyankarpal** [comment]
any updates? @Guli93

**Comment by priyankarpal** [comment]
> Hii @priyankarpal can you assign me this [Feat]: improve the card UI #906 since i have made a pr on issue #880 have a look when you are free Thanks

The #906 issue hasn't been ready yet.

**Comment by priyankarpal** [comment]
it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

Thank you for your understanding.
