### ISSUE TITLE
Hover effect on buttons [Bug]: 

### ISSUE THREAD

**Issue by Guli93** [priyankarpal/ProjectsHut#565]
### What happened?

I found a BUG 🐞There is no hover effect on home page button .

please assign this issue to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Duplicate of https://github.com/priyankarpal/ProjectsHut/issues/373
