### ISSUE TITLE
Languages buttons in smaller devices

### ISSUE THREAD

**Issue by shobhitexe** [priyankarpal/ProjectsHut#57]
![image](https://user-images.githubusercontent.com/29349136/223053277-8c033cf4-13e3-4794-9a5c-6712a3e54c07.png)

Somehow these buttons on mobile not looking good also the overflow 

lemme work in it 
plz assign this to me

**Comment by priyankarpal** [comment]
Thanks for creating this issue. You can work on this, Assign it to you.
