### ISSUE TITLE
data: project addition by kandepi bhavani

### ISSUE THREAD

**Issue by KandepiBhavani23** [priyankarpal/ProjectsHut#574]
### Add a new project to the list

 I want to add a new project to the list 

Features:

1. This app is similar to Swiggy which will be integrated using Swiggy's API.
2. Creating custom Shimmer UI component
3. Landing Page with Carousel and Restaurants List
4. Search for specific restaurant
5. Display the list of menu items of that particular restaurant
6. Shimmer effect to indicate when data is being loaded
7. Infinite scrolling for seamless loading of new data
8. Implement lazy loading/bundle chucking for fast loading of App.
9. Used react-redux for managing the state.
10. Add/Remove restaurants from the Cart.
11. Using Tailwind CSS for rapid development.

**Tech Stack** : React JS, Tailwind CSS, JavaScript, Redux-Toolkit

Please assign me this task under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by KandepiBhavani23** [comment]
Will complete this project in next 3 to 4 days

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
