### ISSUE TITLE
[style]: Elaborate more about ProjectHubs

### ISSUE THREAD

**Issue by akash19coder** [priyankarpal/ProjectsHut#576]
### What's the style idea?

We need to elaborate more about the ProjectHubs on the home page.
![projectHubs](https://github.com/priyankarpal/ProjectsHut/assets/72060440/9a8aa750-a949-45f4-bce4-0b17c036ca52)

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I guess we have to add this simple line so that users can understand easily & we also have README.md file where we mentioned about Projectshut.
