### ISSUE TITLE
Routing of page

### ISSUE THREAD

**Issue by shobhitexe** [priyankarpal/ProjectsHut#58]
![image](https://user-images.githubusercontent.com/29349136/223067356-40539fa4-7b3c-48b6-ac59-f7373a29add6.png)

Also instead of showing these cards here we should route them to different page 

lemme do if you want this 
assign it to me and ill assume it as green signal

**Comment by priyankarpal** [comment]
yes, great idea. Assign to you @shobhitexe

**Comment by priyankarpal** [comment]
Also, I think a separate page would be better such as projects, docs, etc.

**Comment by priyankarpal** [comment]
Done. 🎉
