### ISSUE TITLE
data: project addition by Khushi Shroff

### ISSUE THREAD

**Issue by Ks103** [priyankarpal/ProjectsHut#580]
### Add a new project to the list

 I want to add a new project to the list 
My project features:
- it is simple github username finder, where developers can access any user 
- it provides description of searched user as contributions, prs, issues raised etc.

I want you to please assign me this task so that I can start my work in contributing towards open source.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
