### ISSUE TITLE
data: project addition by Akkshay Tandon

### ISSUE THREAD

**Issue by akkshayTandon** [priyankarpal/ProjectsHut#581]
### Add a new project to the list

 Hi! I am in `GSSOC 23`. 

I want to add my Java Programs to the list, some main projects are:
- Tic-Tac-Toe
- Hangman Game
- To-Do list
- Dynamic Calculator
- Rock-Pape-Scissor
- 
Other than that there are also some miscellaneous programs for beginners to learn.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by akkshayTandon** [comment]
Can you please also add the `gssoc23` label?
