### ISSUE TITLE
TypeError: Detail of project is not showing

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#584]
### What happened?

I found a BUG 🐞. When we click on some project more button then APP UI broke, nothing displaying.
 I have added screenshoot.

### Add screenshots

![Screenshot from 2023-05-22 14-19-25](https://github.com/priyankarpal/ProjectsHut/assets/64573767/0fc9512c-8b71-4820-a16e-521fb732fd14)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
do you want to fix this issue?

**Comment by priyankarpal** [comment]
> Yes. surely

assigned to you

**Comment by priyankarpal** [comment]
ok so I fixed this bug you can work another issue that I have assigned to you
