### ISSUE TITLE
[style]: Automatically Selecting home icon at the starting of page

### ISSUE THREAD

**Issue by Hero-debug-cloud** [priyankarpal/ProjectsHut#587]
### What's the style idea?

We need to improve to select home icon automatically when loading the main page.

kindly assing me this issue.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/72332260/a4ab3730-02f9-4d2c-b78a-adda113f125f)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig it's not needed
