### ISSUE TITLE
data: project addition by Sambhav Kaushik

### ISSUE THREAD

**Issue by masterboy376** [priyankarpal/ProjectsHut#588]
### Add a new project to the list

I want to add a new project to the list. The name of the project is Card war game (an IOS application). Please assign me this issue. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
