### ISSUE TITLE
data: project addition by Aarya Chopkar

### ISSUE THREAD

**Issue by accodes21** [priyankarpal/ProjectsHut#590]
### Add a new project to the list

 I want to add a new project to the list based on ReactJS and YoutubeV3 API. It is a fully functional clone of Youtube
Tech Stack used: ReactJS, Youtube v3 API, CSS, React Router
I would to contribute under GSSOC'23
Please assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
