### ISSUE TITLE
data: project addition by 

### ISSUE THREAD

**Issue by Gurnav224** [priyankarpal/ProjectsHut#592]
### Add a new project to the list

 I want to add a new project to the list that tells  the user is birthday lucky or not 

[ ] feat  user will select   dob from the calender 
[ ] user will have to enter the lucky number 
[ ] Click the check button to check whether your birthday is lucky or not

![dob-select](https://github.com/priyankarpal/ProjectsHut/assets/72142482/5c490544-76db-4c46-86ba-bbafcb706413)

![number input](https://github.com/priyankarpal/ProjectsHut/assets/72142482/5536e18e-d1e1-4b4d-875a-8de2571fb8a0)

![check-btn](https://github.com/priyankarpal/ProjectsHut/assets/72142482/5d1b783e-d6b2-45e7-ac7e-4d7a67cceaa3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
