### ISSUE TITLE
[style]: The onclick effect of navitems are that great they need to be changed

### ISSUE THREAD

**Issue by Soulpurr** [priyankarpal/ProjectsHut#597]
### What's the style idea?

So the idea is to remove the onclick border effect of navitems and replace it with either hover or animate so that it will look better

### Add screenshots

![scrnli_22_05_2023_16-52-57](https://github.com/priyankarpal/ProjectsHut/assets/92094765/7d781168-9d6a-4ad4-bb53-a00f113d9eb2)

You can see here that after clicking navitems this type of border is comming 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before #373. We kindly request you review the existing issues and, if necessary, create a new one accordingly.
