### ISSUE TITLE
[Bug]: The documentation navitem returns a 404 not found in mobile

### ISSUE THREAD

**Issue by Soulpurr** [priyankarpal/ProjectsHut#598]
### What happened?

When using on mobile/smaller screens after clicking the documentation section it return a 404 not found page but it should show the docs page.
Pls assign this to under gssoc'23

### Add screenshots

Add screenshots
![Screenshot_2023-05-22-17-13-21-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/priyankarpal/ProjectsHut/assets/92094765/fcd12029-7a73-488f-a961-718fc4726545)
![Screenshot_2023-05-22-17-13-25-11_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/priyankarpal/ProjectsHut/assets/92094765/a21814eb-28fd-4143-8205-74bcc8f49914)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you to review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/484
