### ISSUE TITLE
[style]: change footer UI design

### ISSUE THREAD

**Issue by ShreyaDhiman24** [priyankarpal/ProjectsHut#601]
### What's the style idea?

By including abstract backgrounds,glassmorphism, etc. website design can be further enhanced. 
On this, I wish to work. Please assign me this work as part of GSSoC'23.

### Add screenshots

Add screenshots
![Screenshot from 2023-05-22 17-31-29](https://github.com/priyankarpal/ProjectsHut/assets/98320971/2de06bf0-da03-4acf-a392-1a2b349fcf1a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share the demo preview?

**Comment by ShreyaDhiman24** [comment]
Yeah Sure Sir! You can access the demo preview link here: 
https://drive.google.com/file/d/1oqU2-aiMYFC2tcDulyPuSjiIr5JsfswZ/view?usp=sharing

**Comment by priyankarpal** [comment]
we added new features please update your branch & I guess the present navbar design looks good(we have added transparency) and added a toggle button. if you want you can a dark footer bg for light mode 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/936575be-ed9e-4afa-80cb-2a51edfb0c55)

**Comment by ShreyaDhiman24** [comment]
okay

**Comment by ShreyaDhiman24** [comment]
Please, assign me this task

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
