### ISSUE TITLE
[style]:  Responsive Developer Profile

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#602]
### What's the style idea?

We need to improve  

In card when someone open the profile of developer
Its not responsive
The footer overlap the card

I will make it responsive for mobile view as well

Please assign me this issue
I Forget to add the correct ScreenShots in isssue #600 so I am creating this issue sorry for that.
I am in Gssoc'23

### Add screenshots

Add screenshots

Before

<img width="960" alt="2023-05-22 (10)" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/a1c88088-eee3-4564-8bd0-c1a89bf318ca">

After

<img width="960" alt="2023-05-22 (9)" src="https://github.com/priyankarpal/ProjectsHut/assets/101205226/238afdbc-f545-449b-9897-f104457be4e2">

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could add a good title so that we can discuss this issue?

**Comment by parasss19** [comment]
@priyankarpal  I changed the name of the issue to Responsive Developer Profile

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
