### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by Soulpurr** [priyankarpal/ProjectsHut#603]
### What feature?

I think when you hover on a particular project it should bounce a little bit ,so that it will look great  as you have seen in hulu.
It should kind of bounce and the text should become bold on hovering it.

Please assign this to me.

### Add screenshots

![scrnli_22_05_2023_17-21-55](https://github.com/priyankarpal/ProjectsHut/assets/92094765/fcabe58d-6333-489d-ae06-93168143c9a7)

It should be like this 
[scrnli_22_05_2023_17-27-44.webm](https://github.com/priyankarpal/ProjectsHut/assets/92094765/0dded7eb-9013-49e1-aee8-1ace42696c7d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
someone is working on improving card design feat https://github.com/priyankarpal/ProjectsHut/issues/368
