### ISSUE TITLE
[Docs]: Update timeline for an issue

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#607]
### what's wrong in the documentation?

Update the readme file with the time in which each issue needs to be completed in

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we need to add min 7 days for each issue.

assigned to you @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Will do
Thank you

**Comment by karthiknadar1204** [comment]
@priyankarpal Should i also add the pointer system like create a section in the girlscript summer of code section to point out the timeline and the pointer system.

**Comment by priyankarpal** [comment]
> @priyankarpal Should i also add the pointer system like create a section in the girlscript summer of code section to point out the timeline and the pointer system.

yeah sure

**Comment by karthiknadar1204** [comment]
@priyankarpal I have added the content to the readme but in the preview it is not placed, i tried breaking the line by adding two spaces at the end of each sentence but not working,any other method?

Editing Template
<img width="1336" alt="Screenshot 2023-05-23 at 1 55 13 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/eb5e903e-45da-423c-9019-75e3c4ca768c">

Preview of template
<img width="1383" alt="Screenshot 2023-05-23 at 1 56 35 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/95973644/7285c414-af04-46a4-bd3e-1da5576e6ed5">

**Comment by karthiknadar1204** [comment]
Want to start the points starting with - on a separate line

**Comment by priyankarpal** [comment]
push it I will check

**Comment by karthiknadar1204** [comment]
Subitted a pr @priyankarpal

**Comment by karthiknadar1204** [comment]
pr #661 it is

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
