### ISSUE TITLE
data: project addition by Tushar Minche

### ISSUE THREAD

**Issue by TusharMinche** [priyankarpal/ProjectsHut#608]
### Add a new project to the list

 I want to add a new project to the list 
The project is an Android application
The app called AR Watches. Project is based on Augmented reality Tech. It is basically E-commers application for watches. So I want to list my project in ProjectsHut. Also I'm in GSSOC'23.
PS: It just a project not any platform to sell watches.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
