### ISSUE TITLE
data: project addition by  Abishek Upadhyay

### ISSUE THREAD

**Issue by Google-Ka-Dinosaur** [priyankarpal/ProjectsHut#612]
### Add a new project to the list

 I want to add a new project to the list  which is known as DePay, it is a blockchain based money lending app using tech-stacks like solidity, next js etc. It is not an individual project of mine but has been made alongside my teammates.

![Screenshot (176)](https://github.com/priyankarpal/ProjectsHut/assets/98577878/498ac9c9-9fb4-4819-b5c6-dfcff52d8412)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
