### ISSUE TITLE
data: project addition by Pooja Ramnaney

### ISSUE THREAD

**Issue by poojaramnaney** [priyankarpal/ProjectsHut#614]
### Add a new project to the list

 I want to add a new project to the list which is an online food-ordering web app
The project is a Web application
The project is called Cosmic Cravings.
Developed a food ordering app designed on a Mars-based theme.
So I want to list my project in ProjectsHut. 
Also, I'm in GSSOC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
After your previous pull request (PR) has been merged, proceed to create a new PR.

**Comment by poojaramnaney** [comment]
I have raised a PR regarding issue this issue PR #831

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
