### ISSUE TITLE
[style]: Responsive Homepage

### ISSUE THREAD

**Issue by wisdom-egba** [priyankarpal/ProjectsHut#616]
### What's the style idea?

We need to improve on the homepage in tablet view to make it responsive

### Add screenshots

![tablet view](https://github.com/priyankarpal/ProjectsHut/assets/99222194/4ef9817a-5b31-418e-9287-b643d169bafe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
> ### What's the style idea?
> We need to improve on the homepage in tablet view to make it responsive
> 
> ### Add screenshots
> ![tablet view](https://user-images.githubusercontent.com/99222194/239935763-4ef9817a-5b31-418e-9287-b643d169bafe.jpg)
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Please update your branch

**Comment by SAGARGAUD01** [comment]
Hello , dear admin assign me this one for smashing this issue.
