### ISSUE TITLE
data: project addition by Baibhav Tiwari

### ISSUE THREAD

**Issue by BaibhavTiwari** [priyankarpal/ProjectsHut#620]
### Add a new project to the list

  **I want to add a new project to the list** 

 `project :` Summarizer 
 `description :` Summarizer is a web application built with React and Redux that utilizes the article-extractor-and-summarizer Rapid API to summarize articles and blog posts. The application allows users to enter a URL for an article or blog post and get a summary of the content.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by BaibhavTiwari** [comment]
hey @priyankarpal , I can see my PR is merged but I'm unable to see my project on ProjectsHut.

**Comment by priyankarpal** [comment]
Why?

**Comment by priyankarpal** [comment]
https://projectshut.vercel.app/projects/baibhavtiwari

**Comment by BaibhavTiwari** [comment]
Thanks , Sorry for the trouble was unable to find the project on NodeJS Tag. 🥹

> https://projectshut.vercel.app/projects/baibhavtiwari
