### ISSUE TITLE
[Bug]: Bug in Navbar

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#621]
### What happened?

The NavLink component does not take activeStyle prop. It should be changed to style.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/75559082/9dfb7eed-d92c-45fc-9256-d99bde794509)

### What browsers are you seeing the problem on?

Chrome, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I guess got fixed 
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/b78c35fa-c9d9-4b57-9858-ac2f996d02b6)

**Comment by kailashchoudhary11** [comment]
> I guess got fixed ![image](https://user-images.githubusercontent.com/88102392/239955579-b78c35fa-c9d9-4b57-9858-ac2f996d02b6.png)

But the NavLink component does not take `activestyle` as a prop. Here is the documentation [NavLink](https://reactrouter.com/en/main/components/nav-link)

**Comment by priyankarpal** [comment]
> > I guess got fixed ![image](https://user-images.githubusercontent.com/88102392/239955579-b78c35fa-c9d9-4b57-9858-ac2f996d02b6.png)
> 
> But the NavLink component does not take `activestyle` as a prop. Here is the documentation [NavLink](https://reactrouter.com/en/main/components/nav-link)

ok ok assigned to you
