### ISSUE TITLE
data: project addition by narayan2111

### ISSUE THREAD

**Issue by narayan2111** [priyankarpal/ProjectsHut#624]
### Add a new project to the list

I want to add a new project to the list based on a responsive Front-end design

I'm in Gssoc'23. Kindly assign me this issue.

Tech Stack: Html, CSS, Javascript.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by narayan2111** [comment]
> Completed. Thanks for your contributions tada heart

Thank you so much sir for your guidance and continuous support.
