### ISSUE TITLE
[style]: Images in the hero section is not responsive for low screen devices(I'm in GSSOC'23)

### ISSUE THREAD

**Issue by piyush-mahajan** [priyankarpal/ProjectsHut#625]
### What's the style idea?

We need to improve the styling of the main header section so it will become responsive👌

### Add screenshots

Add screenshots
![gssoc_1](https://github.com/priyankarpal/ProjectsHut/assets/98900169/e02bdbd8-4476-468f-ac50-35c8e2e6d25c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we have do fix it.
assigned to you.

**Comment by piyush-mahajan** [comment]
can you assign it to me? so i can start working on it🙂

**Comment by priyankarpal** [comment]
> can you assign it to me? so i can start working on itslightly_smiling_face

oh! yeah forgot to assigned 😢

**Comment by coder12git** [comment]
@priyankarpal What's the status of this issue? If it's still open then I want to work on this.

**Comment by priyankarpal** [comment]
hey, @piyush-mahajan can you share your progress?

**Comment by piyush-mahajan** [comment]
Hi @priyankarpal i have designed it and write some lines of code but due to my exam it is taking time.

**Comment by piyush-mahajan** [comment]
Hi @priyankarpal i have designed it and write some lines of code but due to my exam it is taking time.

**Comment by priyankarpal** [comment]
Based on the guidelines of **GSSoC'23**, it appears that this particular issue has not been resolved within the past few days. As it involves a simple pull request, we would like to kindly inform you that we will be closing this issue. 

If you still wish to work on this project, we encourage you to create a new issue and submit a pull request accordingly. Please ensure to review the [contributing guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md) 

Thank you for your understanding.
