### ISSUE TITLE
data: project addition by Monishka8303

### ISSUE THREAD

**Issue by Monishka8303** [priyankarpal/ProjectsHut#626]
### Add a new project to the list

 I want to add a new project to the list which is a clone of the discord website.

I'm in GSSoC'23. Kindly assign me this issue.

Tech Stack: HTML5, TailwindCSS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
