### ISSUE TITLE
[Bug]: Navbar hover effect

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#629]
### What happened?

I found a BUG 🐞

please assign this issue to me 

### Add screenshots

Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/101205226/b91c3f8a-1a2b-4826-905b-d494d4823da6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> > Hi @priyankarpal i worked on my issue #629 for more than 2 hours as it was my first issue and i have complete it. It was assigned to me but someone else fixed it already . It was not a good practice.
> 
> yeah, we need to check it carefully sorry for that.

there were lots of issue related to navbar ig

**Comment by parasss19** [comment]
> > > Hi @priyankarpal i worked on my issue #629 for more than 2 hours as it was my first issue and i have complete it. It was assigned to me but someone else fixed it already . It was not a good practice.
> > 
> > 
> > yeah, we need to check it carefully sorry for that.
> 
> there were lots of issue related to navbar ig

but i  put lot of time over it

**Comment by priyankarpal** [comment]
> > > > Hi @priyankarpal i worked on my issue #629 for more than 2 hours as it was my first issue and i have complete it. It was assigned to me but someone else fixed it already . It was not a good practice.
> > > 
> > > 
> > > yeah, we need to check it carefully sorry for that.
> > 
> > 
> > there were lots of issue related to navbar ig
> 
> but i put lot of time over it

I can understand. so I'm closing this issue & you can work on other issue
