### ISSUE TITLE
data: project addition by Ishpreet Kaur

### ISSUE THREAD

**Issue by Ishpreet-Kaur-Bedi** [priyankarpal/ProjectsHut#631]
### Add a new project to the list

 I want to add a new project to the list  named Password Manager, which uses node RSA for saving the passwords

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by priyankarpal** [comment]
> Can u assign me this issue

I've assigned you already 2 days ago. You can create PR.

**Comment by priyankarpal** [comment]
> can u assign me this issue

you can create an issue for your project addition

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by priyankarpal** [comment]
> can u assign me this issue

it's only for projects addition by the user if you want to add your projects then you can create an issue & I will assign you
