### ISSUE TITLE
[Feat]: Improve the responsiveness of the home page 

### ISSUE THREAD

**Issue by mohammadshaad** [priyankarpal/ProjectsHut#635]
## I have an idea to improve the UI of the home page by aligning the two buttons below each other. This would make the design more visually appealing and consistent across all screen sizes.

Currently, the buttons are aligned side-by-side on wide screens, but this creates a lot of empty space on mobile screens. By aligning the buttons below each other, we can make better use of the available space and create a more user-friendly experience.

I am willing to work on this issue, so please assign it to me. I am confident that I can make the necessary changes to improve the UI of the home page.

### Add screenshots

<img width="334" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/89409389/746e741a-ece2-460e-a4d6-cfa4009ff9d6">

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share a preview?

**Comment by ritik48** [comment]
hey @priyankarpal ,
this is what I would like to do in small screen

![project shut flexcol](https://github.com/priyankarpal/ProjectsHut/assets/84488726/1a35e7bf-86e5-47e3-87d0-a685ba68ccde)

Please assign it to me under GSSoC'23

**Comment by priyankarpal** [comment]
assigned to you @ritik48 also, please make the buttons size same

**Comment by ritik48** [comment]
@priyankarpal the button size is perfect, its just both have different amount of content

**Comment by priyankarpal** [comment]
> @priyankarpal the button size is perfect, its just both have different amount of content

yeah but if we make the same size button it will be good

**Comment by ritik48** [comment]
@priyankarpal this is how it will look if the button sizes are same but i think the above screenshot is much better
![project shut possibel](https://github.com/priyankarpal/ProjectsHut/assets/84488726/f419befb-e8b2-424c-a6de-bbf73d0001aa)

**Comment by ritik48** [comment]
@priyankarpal as per what you say, I will make pr

**Comment by priyankarpal** [comment]
> hey @priyankarpal , this is what I would like to do in small screen
> 
> ![project shut flexcol](https://user-images.githubusercontent.com/84488726/241560812-1a35e7bf-86e5-47e3-87d0-a685ba68ccde.png)
> 
> Please assign it to me under GSSoC'23

then create PR if we need to change anything we will do later

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
