### ISSUE TITLE
[style]: Adding hover effect to the socials

### ISSUE THREAD

**Issue by Akanksha-202** [priyankarpal/ProjectsHut#638]
### What's the style idea?

No hover effect on the social links of the users.
It'll beautify the site further.
Thinking to add the main colour {shade of violet} as the hover colour.

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/100708686/cca17d3f-70dd-4470-81f5-a1ed8e76f335)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah sounds good. 

we need to add a hover effect like this for social media links & navbar github links also


https://github.com/priyankarpal/ProjectsHut/assets/88102392/7c6d183e-e3c3-47ab-a76d-c6a756aadc98

do you want to work on this issue? & are you in GSSoC'23? @Akanksha-202

**Comment by Akanksha-202** [comment]
Yeah! 
I would rally like to work over this and yes under the GSSoC'23 label :)

**Comment by priyankarpal** [comment]
> Yeah! I would rally like to work over this and yes under the GSSoC'23 label :)

assigned to you.

**Comment by Himanshi1207** [comment]
Can i work on this issue please?

**Comment by villAsh** [comment]
can i work on this please?

**Comment by priyankarpal** [comment]
> can i work on this please?

I have already assigned someone for the task, so I kindly request you not inquire about further assignments here.

**Comment by Akanksha-202** [comment]
Hey @priyankarpal !
I have made the PR, kindly review it :)

**Comment by Akanksha-202** [comment]
Pleasure!
Thankyou for letting me know the importance of docs inside a code :)
