### ISSUE TITLE
FIX: code correction - directly push to original repo in "contributing.md"

### ISSUE THREAD

**Issue by ydv-ankit** [priyankarpal/ProjectsHut#64]
hey,
there is an error in contributing.md as code says to directly push changes to original repo which can become trouble for new contributors.

![error](https://user-images.githubusercontent.com/85311495/223366256-8c45c232-4e05-48f2-b5e6-33390e0ad360.png)

**Comment by priyankarpal** [comment]
is it not ok?

**Comment by priyankarpal** [comment]
Fix this

**Comment by priyankarpal** [comment]
@ydv-ankit but this command will allow you to fetch the latest changes from the main repository and merge them into your local branch.

**Comment by ydv-ankit** [comment]
got it. thanks
