### ISSUE TITLE
[Feat]: Add a slider

### ISSUE THREAD

**Issue by LizzyKate** [priyankarpal/ProjectsHut#642]
### What feature?

Add a slider to the home page displaying some of the projects made by contributors. Assing me to this issue. I'm in GSOC 

### Add screenshots

Add screenshots
<img width="1440" alt="Screenshot 2023-05-22 at 22 40 56" src="https://github.com/priyankarpal/ProjectsHut/assets/51890955/2c49d6b9-6e05-4aab-858e-5f16f06e86e9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### What feature?
> Add a slider to the home page displaying some of the projects made by contributors. Assing me to this issue. I'm in GSOC
> 
> ### Add screenshots
> Add screenshots <img alt="Screenshot 2023-05-22 at 22 40 56" width="1440" src="https://user-images.githubusercontent.com/51890955/240049941-2c49d6b9-6e05-4aab-858e-5f16f06e86e9.png">
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

it seems like this issue has already been raised before. We kindly request you to review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/443
