### ISSUE TITLE
[Feat]: Refactor the Navbar to avoid repetition of code.

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#645]
### What feature?

In the Navbar component too much of code is repeated. For example, the NavLinks. All of them contains the same classNames and other things. We can create an Array of the links and turn that array into NavLinks using map method instead of just copy pasting the whole code of NavLink for different links.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
sounds good. here in the project, we need to refactor lots of code.

**Comment by priyankarpal** [comment]
assigned to you. ig it will be better if we show data using array
