### ISSUE TITLE
data: project addition by Shivam Katare

### ISSUE THREAD

**Issue by Shivam-Katare** [priyankarpal/ProjectsHut#646]
### Add a new project to the list

 I want to add a new project to the list which is a gradient generator user can generate the gradient colors, modify those colors, get the random colors suggestions, and then, will able to copy its CSS code.

- I'm in GSSoC'23. Kindly assign me this issue.

- Tech Stack: HTML5, CSS3, JavaScript
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
