### ISSUE TITLE
[Bug]: Broken Link

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#650]
### What happened?

The `Check documentation` link is broken on the projects page.
It should redirect to `/docs` instead of `/AddYourProjectsGuide`

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. #484
