### ISSUE TITLE
data: project addition by Niladri2003

### ISSUE THREAD

**Issue by Niladri2003** [priyankarpal/ProjectsHut#653]
### Add a new project to the list

I want to add a new project to the list 
Yeah I have cool responsive landing page for a educational platform 

Here is the website link
[Eduhub](https://eduhub-1tyq.vercel.app/)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
