### ISSUE TITLE
[style]: Adding a dark theme icon for better than the previous 

### ISSUE THREAD

**Issue by arjun26122002** [priyankarpal/ProjectsHut#655]
### What's the style idea?

We need to improve  the dark theme section , i want to add a icon of dark theme , so the site look nice 

i am under the Gssoc'23 contributor , can you assign me for this work .

### Add screenshots

Add screenshots
![image](https://github.com/priyankarpal/ProjectsHut/assets/88227330/13b9c011-014f-4738-ad8d-9d94318e7d97)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you to review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/422
