### ISSUE TITLE
[style]: Change hover style of technologies on Project page

### ISSUE THREAD

**Issue by ks20soni** [priyankarpal/ProjectsHut#660]
### What's the style idea?

We need to improve the hover style to emphasize more on the tech list compared to the above line.

### Add screenshots

Add screenshots
<img width="847" alt="Screenshot 2023-05-23 at 2 33 41 PM" src="https://github.com/priyankarpal/ProjectsHut/assets/78134776/b7bb6902-4a41-4d1f-8ea4-d05b5e811da2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/442
