### ISSUE TITLE
[Feat]: The navigation bar should remain sticky while scrolling to enhance the user experience "I'm in GSSOC'23"

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#662]
### What feature?

The navigation bar should remain sticky while scrolling to enhance the user experience. For instance, if I am at the footer and need to navigate to another page, I shouldn't be forced to return to the top of the home page before accessing other routes.

### Add screenshots

Add screenshots
![Screenshot (79)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/a9bfefe1-e974-4d38-aaad-d8df16495cbe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
please fetch upstream we added new features

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/64659e04-0718-4b32-a02f-5aff808cad09)

**Comment by jibola2588** [comment]
The changes already exist in the fetched upstream,

**Comment by priyankarpal** [comment]
> The changes already exist in the fetched upstream,

ok closing this issue
