### ISSUE TITLE
[style]: Work on the Projects page to make it look more engaging

### ISSUE THREAD

**Issue by karthiknadar1204** [priyankarpal/ProjectsHut#664]
### What's the style idea?

Overall the website has a good color scheme with some good transitions and effects but when user navigates to the projects page, it somehow feels disappointing due to the smaller size of the tabs.

Proposed solution:
Make the individual cards of the projects more appealing by increasing their overall size, following that we can make the image of the project owner more big and prominent along with the project name. We can make the buttons on the cards more engaging by adding additional hover effect to them, right now the arrow movement on hovering looks good but additional scaling on the button might look more beautiful.

Also one of the things i would like to add was when the user clicks on the projects section on the navbar, instead of making the entire page directly appear, we could add some ease in animations on the cards and they appear slowly from the side.

Also thought of adding some box-shadow to the cards to make them look even better

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes, we need to focus on the projects page currently we are adding a few features like a search bar, and animation for the projects card after completing those features you can work on this issue.

Search Feature: https://github.com/priyankarpal/ProjectsHut/issues/400

Animation: https://github.com/priyankarpal/ProjectsHut/issues/360

so for now we are holding this issue.

**Comment by priyankarpal** [comment]
ok so we already have separate profile pages for each user
