### ISSUE TITLE
[style]: Developer profile card width

### ISSUE THREAD

**Issue by Sanchitbajaj02** [priyankarpal/ProjectsHut#665]
### What's the style idea?

While scrolling through the website, I came across this styling issue on mobile screens, the card which shows developer infos are going out of the edge. The bug is related to the width of the card.

Please assign me this issue so that I can solve this styling bug. Also, I'm in GSSoC'23.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/05767d5b-3f23-4eb4-8042-2a1d8cc73027)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes. I also, faced this issue. 

assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
