### ISSUE TITLE
[style]: Navigation Menu in Mobile should be centralised and on hovering should cover full width of navigation window

### ISSUE THREAD

**Issue by Gurmeet-Singh657** [priyankarpal/ProjectsHut#666]
### What's the style idea?

Hey , I want to improve Navigation Menu in Mobile page so that It can be centralised and on hovering it should cover full width.
Plz assign me this issue as a GSSOC'23 Contributor.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share a demo?

**Comment by Gurmeet-Singh657** [comment]
Sure 
Like You can see here on hovering it's showing small box . Also, it's not centralised.
![image](https://github.com/priyankarpal/ProjectsHut/assets/83361657/4e11a946-17fc-4c25-a425-a6cc407e4808)

Lemme show you my website
![image](https://github.com/priyankarpal/ProjectsHut/assets/83361657/fdf9289a-559f-4fad-aff1-fa8c451eed45)

**Comment by priyankarpal** [comment]
ok assigned to you.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
