### ISSUE TITLE
Readme Update[Docs]: 

### ISSUE THREAD

**Issue by shraddha761** [priyankarpal/ProjectsHut#667]
### what's wrong in the documentation?

We need to add badges to the Readme which makes it more attractive

### Add screenshots

Add screenshots
![Screenshot 2023-05-21 160801](https://github.com/priyankarpal/ProjectsHut/assets/106100728/9acf897f-ca22-4dce-8ae3-da1b8acbb9fb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
We currently added a few badges, and the addition of more might compromise the visual appeal.

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/eeef934e-e3e1-4a3f-843c-424fd0a421ed)
