### ISSUE TITLE
[style]: Improve Pagination Style

### ISSUE THREAD

**Issue by AkanshaMundel** [priyankarpal/ProjectsHut#668]
### What's the style idea?

I would like to suggest improvements in the pagination style to better accommodate a larger number of projects without occupying excessive space in the user interface (UI). Additionally, in the mobile view, the current pagination layout causes the pagination elements to span multiple lines, which negatively impacts UI. To address this, I propose changing the style to utilize arrow or button formats instead of displaying all numbers in between.

I am eager to contribute to this issue and would appreciate being assigned this task under GSSOC'23.

I would like to contribute in this . Please assign this issue to me under GSSOC'23.

### Add screenshots

Currently 
<img width="380" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/78690652/6c77d8d6-68c4-4b79-bd51-b3d97b917243">

we can add any of this 
<img width="922" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/78690652/92d279e2-a9e3-4735-93eb-c47f80ba3398">
or 
<img width="325" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/78690652/ea66fe1e-036a-46a9-952c-c7f945fd2e19">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes, we need to improve this one. 

ig it will look good just add `...` & add `>`, `<`

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/13145272-e85d-4fca-94c3-9b7b47ab7764)

assigned to you
