### ISSUE TITLE
[Docs]: change docs page content & show code snippet

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#669]
### what's wrong in the documentation?

We need to update the docs page sample code according to the `contributing.md`

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/3f9af3bc-cda3-47a8-b9d1-0448ed6e996d)

also, after updating the code snippet we need to show it as a code snippet like this 

![ray-so-export](https://github.com/priyankarpal/ProjectsHut/assets/88102392/9b699aae-8270-48bc-a14f-8fadb4c81df6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pushkar-2804** [comment]
I would love to work on this. 
Please assign me under GSSOC'23
Thanks

**Comment by priyankarpal** [comment]
> I just wanted to clarify that I have to update the projects.json file in this format `_{ "gh-username": "YOUR-GITHUB-USERNAME", "link": "LINK-TO-GITHUB-OR-DEMO", "title": "PROJECT-TITLE", "description": "PROJECT-DESCRIPTION", "tech": ["some tech 1", "some tech 2", "etc"] }_ `for each object ? @priyankarpal

just update according to the contributing guide

**Comment by priyankarpal** [comment]
> <img alt="image" width="669" src="https://user-images.githubusercontent.com/104600849/240605033-77765c13-2696-40fa-a826-26eae037458d.png">
> Hey @priyankarpal , Here is the snippet of the updated `projects.json` file. Does this meet your requirement? if not please tell me the corrections.

wait let me tell you

**Comment by priyankarpal** [comment]
just add a line that " if you want to add your projects you need to follow this format" & add this sample code 

```
{
  "github_username": "YOUR_GITHUB_USERNAME",
  "Social_media": {
    "gitHub": "YOUR_GITHUB_ACCOUNT_LINK",
    "LinkedIn": "YOUR_LINKEDIN_ACCOUNT_LINK",
    "Instagram": "YOUR_INSTAGRAM_ACCOUNT_LINK",
    "YouTube": "YOUR_YOUTUBE_ACCOUNT_LINK",
    "Twitter": "YOUR_TWITTER_ACCOUNT_LINK"
  },
  "Projects": [
    {
      "link": "PROJECT_LINK",
      "title": "PROJECT_NAME",
      "description": "PROJECT_DESCRIPTION",
      "tech": ["tech1", "tech2"]
    },
    {
      "link": "PROJECT_LINK",
      "title": "PROJECT_NAME",
      "description": "PROJECT_DESCRIPTION",
      "tech": ["tech1", "tech2"]
    }
  ]
}
```

**Comment by pushkar-2804** [comment]
By docs you mean README.MD ? @priyankarpal 
<img width="462" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/104600849/fde2fc88-033a-408e-adc3-f31029c2676d">

**Comment by priyankarpal** [comment]
> By docs you mean README.MD ? @priyankarpal <img alt="image" width="462" src="https://user-images.githubusercontent.com/104600849/240902247-fde2fc88-033a-408e-adc3-f31029c2676d.png">

nope on the website docs page, we need to show the sample code 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/d36e6478-737b-48a7-a994-1707617962be)

**Comment by pushkar-2804** [comment]
@priyankarpal 
<img width="960" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/104600849/d74ad3c9-1cb0-43d2-9cf6-61ff9541710a">

**Comment by harmeetsingh11** [comment]
Hi, is the issue resolved?

**Comment by priyankarpal** [comment]
> @priyankarpal <img alt="image" width="960" src="https://user-images.githubusercontent.com/104600849/240918345-d74ad3c9-1cb0-43d2-9cf6-61ff9541710a.png">

no, we need to show code snippets. now it's looking like text

**Comment by pushkar-2804** [comment]
@priyankarpal I hope this is what you were looking for.
<img width="723" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/104600849/545f13e9-9a1a-4a53-9dc8-50b8a98c4e6b">

**Comment by harmeetsingh11** [comment]
If the issue is not resolved, assign me I can try it out.

**Comment by priyankarpal** [comment]
> @priyankarpal I hope this is what you were looking for. <img alt="image" width="723" src="https://user-images.githubusercontent.com/104600849/240988882-545f13e9-9a1a-4a53-9dc8-50b8a98c4e6b.png">

yeah

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
