### ISSUE TITLE
[Feat]: Automate Add Project feature.

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#672]
### What feature?

We can create a form where the users can upload details related to their project and add the project when the user submits the form. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> ### What feature?
> We can create a form where the users can upload details related to their project and add the project when the user submits the form.
> 
> ### Add screenshots
> Add screenshots
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

yes we also thought of implementing later using the backend.
