### ISSUE TITLE
[Bug] the incorrect usage of process.env.GITHUB_TOKEN: 

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#674]
### What happened?

I found a BUG 🐞

### Add screenshots

![Screenshot (81)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/07bd6778-955c-4a72-ad3c-76ba2e2ccb49)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jibola2588** [comment]
before it was like this Authorization: ` ${process.env.GITHUB_TOKEN}`, and it was changed to  Authorization: `Bearer ${process.env.GITHUB_TOKEN}`.
contributors.map((contributor) => (  ... ) then changed to  contributors?.map((contributor) => (...)

**Comment by priyankarpal** [comment]
are you in GSSoC?

**Comment by jibola2588** [comment]
yes
I'm in  GSSOC'23.

**Comment by jibola2588** [comment]
Thanks
