### ISSUE TITLE
[Docs]:  I want to add a translation  (tagalog)

### ISSUE THREAD

**Issue by jfmartinz** [priyankarpal/ProjectsHut#675]
### in which language do you want to translate?

I want to translate documentation to **tagalog** (philippines foreign language)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by jfmartinz** [comment]
> assigned to you

 I have 1 clarification after translating it into tagalog should i add also the link path to the tagalog version to contribution.md?
like this: 
![image](https://github.com/priyankarpal/ProjectsHut/assets/129386460/5d61861b-ce7f-4ed5-ab47-7a68cd1befd6)

**Comment by priyankarpal** [comment]
> > assigned to you
> 
> I have 1 clarification after translating it into tagalog should i add also the link path to the tagalog version to contribution.md? like this: ![image](https://user-images.githubusercontent.com/129386460/240282117-5d61861b-ce7f-4ed5-ab47-7a68cd1befd6.png)

yes you  need to update you8r language to doc pages

**Comment by jfmartinz** [comment]
thank you!!

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
