### ISSUE TITLE
[Feat]: Addition of more lang to src folder 

### ISSUE THREAD

**Issue by Abhinavcode13** [priyankarpal/ProjectsHut#677]
### What feature?

I have an idea that we have for now just 7-8 languages , I will add more language to it which makes the interaction of people from the countries too.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
please assign this issue to me @priyankarpal under gssoc 23

**Comment by Abhinavcode13** [comment]
approx 10-12 more @priyankarpal

**Comment by priyankarpal** [comment]
done

**Comment by Abhinavcode13** [comment]
can it be level 2 @priyankarpal ?

**Comment by priyankarpal** [comment]
it's related to changing documentation. You can check our README.md file for GSSoC'23 guidelines.

**Comment by Abhinavcode13** [comment]
cool no issues @priyankarpal

**Comment by Abhinavcode13** [comment]
5 languages would work ? @priyankarpal

**Comment by priyankarpal** [comment]
> 5 languages would work ? @priyankarpal

ok
