### ISSUE TITLE
[style]: Update Navbar and add animations to the links

### ISSUE THREAD

**Issue by KashiwalHarsh** [priyankarpal/ProjectsHut#678]
### What's the style idea?

We need to improve the header of the website as everything is too close also 
The links need smooth animations to improve the UI experience

Please assign me this issue under GSSOC

### Add screenshots

<img width="681" alt="Screenshot 2023-05-23 193343" src="https://github.com/priyankarpal/ProjectsHut/assets/77677724/008d1c75-5a23-43de-9ba4-4ed245851794">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ok 
assigned to you

**Comment by priyankarpal** [comment]
> Ok then i'll be only working on animation

yes

**Comment by KashiwalHarsh** [comment]
Hii @priyankarpal 
I have made my changes but I cant find .env.example to add access token can you help me through it

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
