### ISSUE TITLE
[Bug]: Bug in Navbar

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#681]
### What happened?

On the input tag in navbar we are passing the `checked` prop but we aren't passing the `onChange` prop.
Whenever `checked` or `value` prop is passed to the input tag, the `onChange` prop must be passed.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kailashchoudhary11** [comment]
Hey @priyankarpal Can you assign it to me?

**Comment by priyankarpal** [comment]
how to find this bug? @kailashchoudhary11

**Comment by kailashchoudhary11** [comment]
You can check in on official [react](https://react.dev/reference/react-dom/components/input) documentation.
```
You can [make an input controlled](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable) by passing one of these props:

[checked](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#checked): A boolean. For a checkbox input or a radio button, controls whether it is selected.
[value](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#value): A string. For a text input, controls its text. (For a radio button, specifies its form data.)
When you pass either of them, you must also pass an onChange handler that updates the passed value.
```

**Comment by priyankarpal** [comment]
> You can check in on official [react](https://react.dev/reference/react-dom/components/input) documentation.
> 
> You can [make an input controlled](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable) by passing one of these props:
> 
> [checked](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#checked): A boolean. For a checkbox input or a radio button, controls whether it is selected. [value](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#value): A string. For a text input, controls its text. (For a radio button, specifies its form data.) When you pass either of them, you must also pass an onChange handler that updates the passed value.

ok ok
