### ISSUE TITLE
data: project addition by kunal kashyap

### ISSUE THREAD

**Issue by kunalkashyap-1** [priyankarpal/ProjectsHut#682]
### Add a new project to the list

I want to add a new project to the list
Yeah I have news API/RSS parser.
I'm in GSSOC'23

Here are the links:-
[Github](https://github.com/kunalkashyap-1/RSS_feed_parser-scraper)
[Docs](https://feedparsify.netlify.com/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
