### ISSUE TITLE
[Bug]: Bug in project.json file 

### ISSUE THREAD

**Issue by KawishAli6578** [priyankarpal/projectshut#684]
### What happened?

as you can see that in our contibuting.md file that is how we should be writing our teck 
![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/f8a0c402-a650-4390-b3d7-83456364e84f)
but in project.json we writing in this way 
![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/4b2535b5-c6bd-490a-bda9-1b83360ad49d)
need to fix this which will cause problem in filtering this project 
![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/60f12264-a7a0-4d26-91af-c978732c5925)

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we need to fix all json code-related bugs. 
Assigned to you

**Comment by Sumit-pd** [comment]
hey @priyankarpal can you tell me the discord server of this project!

**Comment by priyankarpal** [comment]
> Hey @priyankarpal, I want to know if there are any more bugs in JSON files. Additionally, I noticed that some tech names, like "Material UI" etc have a space between them. Should there be a no gap between the words, like "MaterialUI"? We can update the readme file to ensure consistency in naming conventions.

if you find any bugs in json file you can fix them & if you fix readme then make sure to add a different commit.

**Comment by priyankarpal** [comment]
> hey @priyankarpal can you tell me the discord server of this project?

for projectshut, there is no Discord but if you're a GSSoC'23 contributor ig you have joined their Discord server & you can find our project.

**Comment by priyankarpal** [comment]
> @priyankarpal sorry I was taking about contributing.md file I am not sure how to add a professional commit but this is what i did in contributing.md
> 
> ![image](https://user-images.githubusercontent.com/95257675/240547910-2fbf30de-18ab-4a71-a8a7-04e2f33f679e.png)

yes you can do it

**Comment by priyankarpal** [comment]
Thanks for your contributions 🎉 ❤️
