### ISSUE TITLE
[Feat]: we can add dynamic tech sorting

### ISSUE THREAD

**Issue by KawishAli6578** [priyankarpal/ProjectsHut#686]
### What feature?

So write now we are using only 7 teck which are hard coded on base we are sorting but should not we use 
all the tech available in project.json file so it will be more specific to anyone according to their need 
we can merge all the tech in one array and them map that array

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
so, we will add a search option on the projectspage & we will give suggestions there. 

https://github.com/priyankarpal/ProjectsHut/issues/400
