### ISSUE TITLE
Introducing some parameters or checks to get your project listed 

### ISSUE THREAD

**Issue by vedprakashnautiyal** [priyankarpal/ProjectsHut#69]
I think anyone being able to list their projects is little lenient.....Cause I saw some projects that have nothing but readme......

Wht are your thoughts about this or did I made a mistake while reviewing your project

**Comment by priyankarpal** [comment]
> I think anyone being able to list their projects is little lenient.....Cause I saw some projects that have nothing but readme......
> 
> Wht are your thoughts about this or did I made a mistake while reviewing your project

Yes. I also saw two same projects. If you want to change you can work.

**Comment by vedprakashnautiyal** [comment]
Give me this week to figure out what can we do, before I ask you to assign it to me....

**Comment by priyankarpal** [comment]
> Give me this week to figure out what can we do, before I ask you to assign it to me...

Yeah sure, you can work.
