### ISSUE TITLE
[Bug]: Issue regarding project display

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#693]
### What happened?

When you click on any button in projects page for example you click on NEXTJS. I show you all project related to NEXTJS but after it there is no way to seel all the project together , you need to reload all the project again in pagination form.

before choose filter
![image](https://github.com/priyankarpal/ProjectsHut/assets/81584747/09798ba0-0d81-4be8-80db-fa920517d7b3)
after choose filter
![image](https://github.com/priyankarpal/ProjectsHut/assets/81584747/9683e516-3723-42bd-9506-3df0c1e3ea01)

you need to reload again to see pagination 
after reload
![image](https://github.com/priyankarpal/ProjectsHut/assets/81584747/a974a85f-0ab3-4f24-bfbc-cae2625e885c)

There should be a button 'All'. which display all the projects in pagination form

Please assign it to me @priyankarpal 

I am a GSSoC 2023 contributor.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig there is no problem could you check one more time?? 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/10e24335-a0ab-44e9-801b-23e21712da75

**Comment by noobtuber20103152** [comment]
If you click on same button again then it is wokring correctly. But this not a goo user experience, these should be a button 'All' to display all the projects. For better user experience. Otherwise erything is fine, you can close this issue if you don't want to all a button for all projects.

Thank You !

**Comment by priyankarpal** [comment]
> If you click on same button again then it is wokring correctly. But this not a goo user experience, these should be a button 'All' to display all the projects. For better user experience. Otherwise erything is fine, you can close this issue if you don't want to all a button for all projects.
> 
> Thank You !

ig it's not needed.
