### ISSUE TITLE
data: project addition by coderhersh

### ISSUE THREAD

**Issue by coderhersh** [priyankarpal/ProjectsHut#695]
### Add a new project to the list

I want to add a new project to the list.
I'm in GSSoC23.
I want to add a machine learning project regarding Credit Card Fraud Detection.
Here is the project repo: [https://github.com/coderhersh/Credit-Card-Fraud-Detection](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
