### ISSUE TITLE
[style]:  to add hover effect on the user icons of the contributors page.

### ISSUE THREAD

**Issue by divyansh2212** [priyankarpal/ProjectsHut#699]
### What's the style idea?

I have an idea to add hover effect on the user icons of the contributors page.
Please assign me this issue as GSSOC 2023 Contributor.

### Add screenshots

![Uploading image.png…]()

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share a demo like which type of hover efffect?

**Comment by khadesamrudhi** [comment]
please assigm me this issue

**Comment by priyankarpal** [comment]
hey @divyansh2212 & @khadesamrudhi we removed the contributor's page & we don't need to add so I'm closing this issue.
