### ISSUE TITLE
Rock Paper Scissors : project addition by Swapnil Singh

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [priyankarpal/ProjectsHut#703]
## Rock Paper Scissors

 I want to add a new project to the list.
 This project is a simple Rock Paper Scissors app using HTML, CSS, JS.

## Screenshot
![image](https://github.com/priyankarpal/ProjectsHut/assets/85278243/e7fab6ff-1de9-411f-b2f3-6d6e99e6644d)

Please assign me this task under GSSOC'23
I'm in GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
