### ISSUE TITLE
data: project addition by using HTML ans CSS 

### ISSUE THREAD

**Issue by KhushiVaiskyar** [priyankarpal/ProjectsHut#706]
### Add a new project to the list

 I want to add a new project to the list  My project is a clone of a site named  Usability Hub. I did this using html and css basically Usability Hub is a remote user research platform that takes the guesswork out of design decisions by validating them with real users.
I am in GSSOC'23.
Kindly assign this issue this to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
