### ISSUE TITLE
data: project addition by SJ-Kumar

### ISSUE THREAD

**Issue by SJ-Kumar** [priyankarpal/ProjectsHut#707]
### Add a new project to the list

I want to add a new project to the list. My project is a Chat Based PortFolio Page. I developed this using HTML, CSS and JavaScript.

Description of the project - 
This is a chat based portfolio page that displays education, skills, projects, and resume (pdf) version from repository based on the word user types in a dynamic chat window.

I am in GSSOC'23.
Kindly assign this issue this to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
