### ISSUE TITLE
data: project addition by sonam

### ISSUE THREAD

**Issue by rajputsingh808** [priyankarpal/ProjectsHut#708]
### Add a new project to the list

 I want to add a new project to the list 
This is a e-book website using html, css and Javascript and it is fully responsive website.
I'm in GSSOC'23 
kindly, assign this to me

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
