### ISSUE TITLE
data: project addition by AgamK18

### ISSUE THREAD

**Issue by AgamK18** [priyankarpal/ProjectsHut#710]
### Add a new project to the list

I want to add a new project to the list which is CrypTracker. User can search for any cryptocurrency and see details about the same. The user can also follow latest news about the domain.
I'm in GSSoC'23. Kindly assign me this issue.
Tech Stack: ReactJS, Tailwind CSS, tsParticles. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
