### ISSUE TITLE
data: project addition by Hardikaz

### ISSUE THREAD

**Issue by Hardikaz** [priyankarpal/ProjectsHut#714]
### Add a new project to the list

I want to add a new project to the list
I'm in GSSoc'23.
I want to add a front-end project which created by using GitHub Users API.
Here is the project's link- https://hardikaz.github.io/GitHubUsersAPI/

Tech Stack Used- HTML , CSS, JavaScript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
