### ISSUE TITLE
[style]: add a default bg for scroll to top button 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#715]
### What's the style idea?

add a default colour for `ScrollToTop` button for all theme  

the 

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/4008460a-0c64-47b0-8eab-757114675090)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> I'm in gssoc'23. Can you assign me this

yeah sure assigned to you

**Comment by priyankarpal** [comment]
> Thank you Can you tell me which colour add to it

you can add purple for bg & white for the arrow icon

**Comment by hemant14050** [comment]
Assign this task to me

**Comment by priyankarpal** [comment]
> Assign this task to me

I have already assigned someone, so please refrain from requesting another assignment. Kindly review the label and assignment status.

**Comment by hemant14050** [comment]
> > I'm in gssoc'23. Can you assign me this
> 
> yeah sure assigned to you

Assign this to me

**Comment by hemant14050** [comment]
Okay thanks

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
