### ISSUE TITLE
[Docs]:  Fix spelling and grammatical error in the README.md file

### ISSUE THREAD

**Issue by IfeoluwaAroboto** [priyankarpal/ProjectsHut#716]
### what's wrong in the documentation?

I'm in GSSOC'23
We need to add the following; 
1. The word "installed" in the phrase "Make sure you have NodeJs installed in your system" should be "install" to match the action time. The sentence should be "Make sure you install Node.js on your system."
2. In the sentence "As a user, you have the ability to translate the documentation of this project to new languages," the word "to" should be "into." The sentence should be "As a user, you have the ability to translate the documentation of this project into new languages.
3. In the sentence "Don't spam if you do it your PR/issue will be closed," the word "it" should be "so" or "then."

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/654
