### ISSUE TITLE
[style]: change hover color to purple according to theme 

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#717]
### What's the style idea?

We need to change the hover colour of `back to projects` to purple according to the theme in the users' ProjectsPage

## Normal
![Screenshot from 2023-05-24 14-22-12](https://github.com/priyankarpal/ProjectsHut/assets/88102392/c3bbf551-00d6-4209-83b5-c42e873f818f)

## Hover
![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/24354454-2291-485d-bb67-1cdf07803846)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by harmeetsingh11** [comment]
I'm in GSSOC'23. Can I work on this issue?

**Comment by Bhanuteja01** [comment]
Can you assign me this issue

**Comment by priyankarpal** [comment]
> I'm in GSSOC'23. Can I work on this issue?

yeah sure assigned to you

**Comment by Bhanuteja01** [comment]
I'm also in gssoc

**Comment by priyankarpal** [comment]
> I'm also in gssoc

I can assign the first one.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
