### ISSUE TITLE
[Feat]:  Refactor code to use consistent function declaration.

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#721]
### What feature?

Currently, some of the components are using arrow functions syntax, some are using regular function syntax. We can refactor so use the same format throughout the codebase. Either arrow function or regular functions.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by kailashchoudhary11** [comment]
What do you think?
 @priyankarpal

**Comment by priyankarpal** [comment]
we are adding a features such as search bar after completing the work you can work on this issue

**Comment by kailashchoudhary11** [comment]
> we need to use arrow functions for more concise syntax. we are adding features such as a search bar after completing the work you can work on this issue

Should I start working on this issue or wait?

**Comment by priyankarpal** [comment]
> > we need to use arrow functions for more concise syntax. we are adding features such as a search bar after completing the work you can work on this issue
> 
> Should I start working on this issue or wait?

yeah you can start working
