### ISSUE TITLE
[Feat]: Refactor the hero section code on the home page.

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#723]
### What feature?

The hero section consists of seven image URLs that were hard-coded. These URLs can be transformed into an array of objects that include both the image URLs and alt attributes. By mapping them into their respective grid containers, we can eliminate unnecessary repetition. I'm in GSSOC'23

### Add screenshots

Add screenshots
![Screenshot (84)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/1e6711d4-dbaa-42ba-ad61-11f6a6fabd2c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah we need to refractor

assigned to you

**Comment by jibola2588** [comment]
Thanks sir

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
