### ISSUE TITLE
[style]: The background color in the dark mode can be enhanced from simple black to some different color gradient

### ISSUE THREAD

**Issue by parag477** [priyankarpal/ProjectsHut#724]
### What's the style idea?

# Aim

- The idea is that when dark mode is enabled simple black color appears. We could change that background color to some different color gradient which would look more beautiful. 

Please assign me this issue under GSSoC-2023

### Add screenshots

![Capture](https://github.com/priyankarpal/ProjectsHut/assets/60110529/63a07666-a24f-401f-9876-32940f29fda6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
cool I'm also thinking like this. you can work on it.

**Comment by priyankarpal** [comment]
ig we don't change the bg colour so I'm closing this PR
