### ISSUE TITLE
data: project addition by neeka

### ISSUE THREAD

**Issue by neekamhrzn** [priyankarpal/ProjectsHut#730]
### Add a new project to the list

 I want to add a new project to the list 
 The project is File Zipping Software 
 It can compress a text file so that it takes less storage space on disc as well as decompress the file back into the original one.

 I'm in GSSOC '23
 Tech stack used : C++ / For graphics: SFML

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
