### ISSUE TITLE
[Bug]: Only first index project is showing 

### ISSUE THREAD

**Issue by KawishAli6578** [priyankarpal/ProjectsHut#731]
### What happened?

I found a BUG 🐞if their are multipe projects of any user then the project at first index is showing as you can see by the code 

### Add screenshots

Add screenshots![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/bcd5e206-fbcf-41b3-8bf8-62e96abe4dc4)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we already have separate profiles for users 

https://github.com/priyankarpal/ProjectsHut/assets/88102392/e5bfab05-c755-4676-be03-f6edd8b9a158
