### ISSUE TITLE
Technology increament 

### ISSUE THREAD

**Issue by Deepanshu0703** [priyankarpal/ProjectsHut#736]
### What feature?

I want to add more option of project like solidity and php projects option  in to the projects sort option 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig there are no projects made using `php`, or `solidity`.  so we can't add these right now if we got projects made using `php` or something we will add
