### ISSUE TITLE
[Feat]: Addition and improvising Css tags used in footer.jsx

### ISSUE THREAD

**Issue by HarshMN2345** [priyankarpal/ProjectsHut#737]
### What feature?

I made the following improvements to the CSS styling:

Added font-medium class to the license link for better visibility.
Adjusted the mt-2 margin-top class for the year paragraph.
Added rel="noopener noreferrer" to the license link for security best practices.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/127186841/ab5c5533-e806-4737-a396-5e8a0970dbda)
[Issue1.pdf](https://github.com/priyankarpal/ProjectsHut/files/11555283/Issue1.pdf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig previous one is ok
