### ISSUE TITLE
[Feat]: Refactor ContributorsCard component 

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#745]
### What feature?

We can refactor the contributors card component to use loader for fetching data instead of useEFfect.

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kailashchoudhary11** [comment]
> we have assigned you to an issue so we're unable to assign you to this issue now. so you need to work on thise issues first.
> 
> #681

I've already made a PR for it Sir.

**Comment by priyankarpal** [comment]
assigned to you @kailashchoudhary11
