### ISSUE TITLE
Suggestion - Translation Guide

### ISSUE THREAD

**Issue by Hamthoven** [priyankarpal/ProjectsHut#75]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it's an improvement as a suggestion.   
This is a wonderful project. I think it would be good if it is translated in various languages. It will increase the possibility of adding various projects.

**Describe the solution you'd like**
I would like to create a translation document separately or create a translation-related item in the contribution guide. And it would be helpful to link the translated language to README.md. It would be nice if the following contents were included in the translation contribution.

1. List of currently translated languages
2. Translated version of content
3. How to contribute to translation

I wish following documents will be translated.

- [CODE_OF_CONDUCT.md](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [contributing.md](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [README.md](https://github.com/priyankarpal/ProjectsHut/blob/main/README.md)

**Additional context**
I can translate Korean, and if a translation system is established, I would like to translate Korean.
Please feel free to express your opinion.

**Comment by priyankarpal** [comment]
Great idea @Hamthoven Assign to you you can work. 💯

**Comment by priyankarpal** [comment]
merged it.
