### ISSUE TITLE
[Feat]: We can show more more project related to teck stack at /projects/username page

### ISSUE THREAD

**Issue by KawishAli6578** [priyankarpal/ProjectsHut#751]
### What feature?

so the idea is that by clicking on these chips we can show all the project related to these tech
that would be an intersting feature

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/95257675/4bff33cb-3258-4ab2-815b-31637f678375)

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we already have projects page & there we will add search option there we will show more projects related tech stack
