### ISSUE TITLE
[Feat]: A section for review/testimonial of each projects

### ISSUE THREAD

**Issue by kunalkashyap-1** [priyankarpal/ProjectsHut#752]
### What feature?

I have an idea that we should have a review/testimonial for each project that could be used to provide the review for the projects showcased by the people. So that they could potentially improve and address those reviews, Making this website more useful and providing people more reason to showcase their projects here.

we can do this by making a new file in DB "testimonials.json" which has testimonials stored for each project and is easily accessible, the structure is shown below...

there will be a button in projectList component on the right hand side of tech stack, and below that reviews are shown.
I'm in GSSOC'23.

If this is something you would like to have do assign me this.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/91254500/0f8a17bf-5ad1-45c9-a225-b8317785e7b7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we will add buttons with testimonial features using the backend later for now ig it's ok
