### ISSUE TITLE
[Bug]: Project Info page opens with scroll bar in the middle

### ISSUE THREAD

**Issue by komalioruganti** [priyankarpal/ProjectsHut#755]
### What happened?

I found a BUG 🐞
When I try to click the "More" button on the project page, it redirects to the Project page but the scroll bar is in the middle of the page rather than staring from the top.

### Add screenshots

Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/95839946/5244ba66-8dc4-4bf7-840d-6814b725f326

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah! assigned to you

**Comment by coder12git** [comment]
@priyankarpal Can you assign this issue to me?
 I am in GSSOC 2023.

**Comment by priyankarpal** [comment]
> @priyankarpal Can you assign this issue to me? I am in GSSOC 2023.

he already created a PR

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
