### ISSUE TITLE
[Docs]: Issue - Missing "to" and "." in Paragraph

### ISSUE THREAD

**Issue by shaikahmadnawaz** [priyankarpal/ProjectsHut#756]
### what's wrong in the documentation?

We need to add missing "to" and "." in Paragraph.

I'm in GSSOC'23

### Add screenshots

![Screenshot 2023-05-24 213653](https://github.com/priyankarpal/ProjectsHut/assets/96189881/b9af3a7b-effc-4c15-ad39-b8ba16d7ea1f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by shaikahmadnawaz** [comment]
> Completed. Thanks for your contributions 🎉 ❤️

Most welcome @priyankarpal ❤️
