### ISSUE TITLE
[Feat]:paginate the contributors 

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#759]
### What feature?

To improve the user experience, I recommend to paginate the data instead of displaying all the contributors on a single page. This approach allows for a limited number of contributors to be shown at a time, reducing the need for excessive scrolling.

### Add screenshots

Add screenshots
![Screenshot (86)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/8cee855f-a635-48a7-b843-f6088bc096ad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishnu9865** [comment]
@priyankarpal, Sir I am interested to Contribute to this issue.
I already put up a PR for my previous one.
Thank you,
Regards,
Jeyavishnu @vishnu9865

**Comment by priyankarpal** [comment]
> @priyankarpal, Sir I am interested to Contribute to this issue. I already put up a PR for my previous one. Thank you, Regards, Jeyavishnu @vishnu9865

assigned to you @vishnu9865

**Comment by jibola2588** [comment]
okay sir

**Comment by vishnu9865** [comment]
@priyankarpal Sir, Is it okay for me to add any extra libraries for pagination ?

**Comment by priyankarpal** [comment]
> @priyankarpal Sir, Is it okay for me to add any extra libraries for pagination?

yeah
