### ISSUE TITLE
[Feat]: Authentication feature in the website.

### ISSUE THREAD

**Issue by ShreyaDhiman24** [priyankarpal/ProjectsHut#764]
### What feature?

I have an idea to add authentication by using firebase. I want to work on it under GSSoC'23.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
duplicate of https://github.com/priyankarpal/ProjectsHut/issues/364
