### ISSUE TITLE
[style]:  adding hover effects to project cards

### ISSUE THREAD

**Issue by TheXro** [priyankarpal/ProjectsHut#766]
### What's the style idea?

Right now the cards in the project section doesn't have any hover effects we can try to add tilt effect or any other effect to make it look more attractive.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/368
