### ISSUE TITLE
Please add prettier rules to maintain same format structure to prevent this problem

### ISSUE THREAD

**Issue by abhidadhaniya23** [priyankarpal/ProjectsHut#77]
**Describe the bug**
- When someone changes in db.json it can format according to their vscode settings
- There's a solution to fix this problem and maintain the same format structure in code is to add `.prettierrc` in root directory. I've already added this file in one of my pull request.
- Another solution is to add `.vscode` folder in root directory and inside that we can configure `settings.json` file for some common configurations.

**Screenshots**
![image](https://user-images.githubusercontent.com/70057423/223914845-06a72094-ea1e-44dc-8bae-eee6eb3de16b.png)

**Comment by priyankarpal** [comment]
> **Describe the bug**
> 
> * When someone changes in db.json it can format according to their vscode settings
> * There's a solution to fix this problem and maintain the same format structure in code is to add `.prettierrc` in root directory. I've already added this file in one of my pull request.
> * Another solution is to add `.vscode` folder in root directory and inside that we can configure `settings.json` file for some common configurations.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/70057423/223914845-06a72094-ea1e-44dc-8bae-eee6eb3de16b.png)

Yes. thanks
