### ISSUE TITLE
[style]:  Redesigning Projects Page and Footer with Feature Column

### ISSUE THREAD

**Issue by exploring-solver** [priyankarpal/ProjectsHut#773]
### What's the style idea?

** I'm in GSSOC'23**
I would like to propose a redesign of the projects page and project card layout, as well as the footer with a feature column for the [Project Name] project on GitHub. This redesign aims to improve the visual appeal and user experience of the website while maintaining a color scheme of indigo, white, and black.

The new design should focus on a modern and clean aesthetic, utilizing a combination of TailwindCSS and ReactJS. Here are some style ideas to consider:
Projects Page:
providing a visually pleasing arrangement.
Enhance the project cards with better typography, such as using a larger font size for the project titles and a smaller font size for the project descriptions.
Use indigo as the primary color for the project cards, with contrasting white or black text for better readability.
Add hover effects to the project cards, such as subtle animations or a shadow effect, to make them more interactive.
Project Card:
Redesign the project card to have a modern and sleek appearance.
Utilize a card component with a prominent project image or logo at the top.
Include project details such as the project name, description, and number of contributors.
Use a consistent color scheme with black bg and indigo white text and vice versa for light theme

Create a visually appealing footer section with a feature column.
Divide the footer into multiple columns, one of which can be dedicated to highlighting key features or information about the project.
Use a contrasting color scheme of indigo, white, and black to maintain consistency with the rest of the website.
Include links to relevant resources, such as documentation, project guidelines, and the project's GitHub repository.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/123443485/e2e3eef8-4d20-4bbc-afb3-4ad9aa6e3c5a)
![image](https://github.com/priyankarpal/ProjectsHut/assets/123443485/54cd345c-6e48-45bc-9842-8d74fe46745d)
![image](https://github.com/priyankarpal/ProjectsHut/assets/123443485/e5d8d721-e21e-42d4-9aca-e9e763c9f6ba)

**Please Note that these are just draft designs and final work will be better than them and there will be beautiful hover effects and animations.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
so we are working on new features like a search bar, project card redesign, and analytics. So it will be good to close this issue right now.
