### ISSUE TITLE
[style]: Want to design project page 

### ISSUE THREAD

**Issue by Ks103** [priyankarpal/ProjectsHut#774]
### What's the style idea?

We need to improve  the project designing section . AS it can be more attractive by replacing buttons to other style, also by changing the box style. As a designer I want you to please assign me this task so that I can start working for this project.

### Add screenshots

Add screenshots
![Screenshot 2023-05-25 101820](https://github.com/priyankarpal/ProjectsHut/assets/86292101/72366073-7bde-4876-9843-4a07efc00b2d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Ks103 someone is working on this page. we will also add a search bar & some features.
