### ISSUE TITLE
[Bug]: Lack of gap between nav items in responsive nav bar of size between 1025px and 1250px

### ISSUE THREAD

**Issue by hemant14050** [priyankarpal/ProjectsHut#775]
### What happened?

I have identified a specific bug related to the responsiveness of the navigation bar between screen widths of 1025 pixels and 1250 pixels. Within this range, there is no gap between the navigation items, leading to a visually cramped and cluttered appearance.

### Add screenshots

Add screenshots
![Screenshot 2023-05-25 101850](https://github.com/priyankarpal/ProjectsHut/assets/112842857/49b9d1c8-22a4-406f-9974-812c2c19ccd5)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we need to fix this bug. 

assigned to you
