### ISSUE TITLE
[Bug]: Component is overlapping Scroll to top button

### ISSUE THREAD

**Issue by rushabhpanbude** [priyankarpal/ProjectsHut#783]
### What happened?

I found a BUG 🐞 while testing in responsive
Have to fix z-index of scroll to top button

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share us a demo?

**Comment by rushabhpanbude** [comment]
![Capture](https://github.com/priyankarpal/ProjectsHut/assets/63780356/7327421b-200c-4a63-a950-7b417855ca31)

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
