### ISSUE TITLE
[Feat]: Add Project Feature Component

### ISSUE THREAD

**Issue by Ahtaxam** [priyankarpal/ProjectsHut#785]
### What feature?

I have an idea that if we add **Feature link** in Navbar. In this component we can display projects  based on technology  (that we defined in search filter)  in form of charts. 

**Example:**
![chart](https://github.com/priyankarpal/ProjectsHut/assets/64573767/928272bd-d842-46fc-9a2f-48815c3516fb)

and also we can add one more thing, add two link **open issue** and **unassigned issue** when user click anyone,  he navigate to respective issues on GitHub.

**Note**: Would like to work on this issue.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah we are working on search features that we will add only projectspage
