### ISSUE TITLE
[style]: Improving the Heading by adding the Typewriter Effect

### ISSUE THREAD

**Issue by Anshika-Jain02** [priyankarpal/ProjectsHut#790]
## Adding Typewriter Effect in the Heading of the Home page

*We can improve the overall look of the website by adding the Typewriter Effect in the heading "Share your Projects". It would improve the appearance of the web page*

**Please Assign this issue to me under Gssoc'23 @priyankarpal**

### Add screenshots

![projectshut](https://github.com/priyankarpal/ProjectsHut/assets/104912087/a2a9c774-531c-48e2-a028-48f87fb76dd3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @Anshika-Jain02 we already had this effect & after we removed it so ig we don't need
