### ISSUE TITLE
[Bug]: Page Not found Error when clicking on Check Documentation 

### ISSUE THREAD

**Issue by Anshika-Jain02** [priyankarpal/ProjectsHut#792]
## I found a BUG 🐞

*When we are clicking on "Check Documentation" under the Project section it is showing us this error. We can fix this.*

**Please assign this issue to me under Gssoc'23 @priyankarpal**

Thankyou

### Add screenshots

Add screenshots
![projecthut 2](https://github.com/priyankarpal/ProjectsHut/assets/104912087/47a8d3bb-1134-4e24-aa95-7818dbcf71dc)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/484
