### ISSUE TITLE
[style]: Image in this div section

### ISSUE THREAD

**Issue by DivyanshiNarang** [priyankarpal/ProjectsHut#793]
### What's the style idea?

*We need to improve the styling of image in div section as the image is not placed correctly.*

**Please assign this issue to me under Gssoc'23** @priyankarpal  

### Add screenshots

<img width="932" alt="Screenshot 2023-05-25 155312" src="https://github.com/priyankarpal/ProjectsHut/assets/74779601/32876d3c-c78b-4fde-a04c-02f23cc83cb7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @DivyanshiNarang the design is like that. so we don't need to change it.
