### ISSUE TITLE
[Bug]: Redirect User's Profile Picture in the Project List Section to their GitHub Profile

### ISSUE THREAD

**Issue by Saurav-Pant** [priyankarpal/ProjectsHut#800]
### What happened?

I want to implement a feature where, upon clicking on a user's profile picture in the project list section, it will redirect them to their respective GitHub profile. This functionality aims to enhance the user experience by providing easy access to the GitHub profiles of contributors.

**Please Assign this issue to me under Gssoc'23 @priyankarpal**

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/103263909/ee8f024e-18bd-4d8c-9917-534fe7f68495

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @Saurav-Pant we already have a dedicated profile page for users & we already added social icons so we don't need to add this feature. 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/73b6fdfd-a3d3-4d73-b21f-8fa8be8cb41c)
