### ISSUE TITLE
data: project addition by  slayerrr12

### ISSUE THREAD

**Issue by slayerrr12** [priyankarpal/ProjectsHut#801]
### Add a new project to the list

 I want to add a new project to the list  which is a repo that contains some cloned web apps like spotify , flipkart etc which are help full for beginners 
 @priyankarpal hoping to get assigned asap :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
