### ISSUE TITLE
[Feat]: Implement Login and Signup Feature for User Authentication in MERN Stack

### ISSUE THREAD

**Issue by exploring-solver** [priyankarpal/ProjectsHut#804]
### What feature?

Backend Setup: Develop the necessary backend APIs and routes using Express.js and Node.js to handle user authentication. This includes creating endpoints for user registration, login, and logout. Implement proper validation and encryption techniques to ensure secure storage and transmission of user credentials.

Database Integration: Utilize MongoDB as the database to store user information such as usernames, passwords (hashed), and any additional user data required. Implement the necessary models and schemas to interact with the database and perform user-related operations.

User Registration: Create a user registration form on the frontend using React, allowing users to provide their desired username, email address, and password. Implement form validation to ensure the data is entered correctly. On submission, send the user data to the backend API for registration.

User Login: Design a login form where users can enter their credentials (username/email and password) to authenticate themselves. Implement client-side validation for login credentials and send the data to the backend for verification. On successful login, generate and store a session token or JWT (JSON Web Token) to maintain user authentication.

User Authentication and Authorization: Implement middleware on the backend to authenticate user requests for protected routes. Ensure that only authenticated users can access specific features and perform certain actions. Manage user sessions or JWTs to maintain persistent authentication across requests.

Frontend Integration: Integrate the login and signup forms into the ProjectHut frontend using React components and TailwindCSS for styling. Implement error handling and display appropriate feedback messages for successful registrations, login failures, and validation errors.

User Profile and Account Management: Extend the functionality to allow users to view and manage their profiles, update account information, and reset passwords if necessary.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/123443485/1845c1ba-04f2-434b-8790-c0de3bb17965)
Just a draft Design

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
why should we need a registration form? we are using a simple front-end web app also, we are thinking of adding github Auth & backend later.

**Comment by exploring-solver** [comment]
a registration and login feature would help in fetching user specific data and they can simply add their repository in the database from the website and this will automate the process of adding projects in ProjectHut also yes we can also use github auth but we should try to make it such that user can see his/her dashboard and it would help in later adding the feature of comments and discussion on a project in the website

**Comment by priyankarpal** [comment]
> a registration and login feature would help in fetching user specific data and they can simply add their repository in the database from the website and this will automate the process of adding projects in ProjectHut also yes we can also use github auth but we should try to make it such that user can see his/her dashboard and it would help in later adding the feature of comments and discussion on a project in the website

yes, but we will add it later. currently, we're working on new features so ig we don't need to log in for now.
