### ISSUE TITLE
[Feat]: Add "Getting Started" Button to Direct Users to Comprehensive Documentation and Feature Overview

### ISSUE THREAD

**Issue by exploring-solver** [priyankarpal/ProjectsHut#805]
### What feature?

I am in GSSOC'23
I propose adding a "Getting Started" button to the ProjectHut website, which will provide users with easy access to a dedicated page containing comprehensive documentation and a detailed overview of the website's basic features. This feature aims to enhance user onboarding, improve user engagement, and provide a clear understanding of the platform's functionalities.

The implementation of this feature involves the following steps:

Button Placement: Add a prominently placed "Getting Started" button on the homepage, navigation bar, or any other relevant location where it is easily visible to users.

Getting Started Page: Create a dedicated page that serves as the entry point for new users. This page will provide a comprehensive overview of the website's basic features, functionalities, and their benefits. Include detailed documentation, guides, and tutorials to assist users in getting started with the platform.

Feature Description: Clearly describe the core features of the website, including project sharing, project filtering, sorting, project details page, project discussion forum, project ratings, collaboration tools, user profiles, and any other significant features. Explain how each feature enhances the user experience and contributes to the overall functionality of the platform.

UI Showcase: Include screenshots or interactive elements that showcase the website's user interface (UI). Highlight the visually appealing design, intuitive navigation, responsive layout, and the use of ReactJS and TailwindCSS to create a seamless and user-friendly experience.

Documentation: Provide detailed documentation that covers the various aspects of using the platform, such as account creation, project submission, collaboration tools, project management, and any other relevant topics. Include code samples, step-by-step instructions, and best practices to help users navigate and utilize the platform effectively.

Benefits and Value Proposition: Clearly communicate the advantages and benefits of using ProjectHut for open-source projects. Emphasize the platform's unique selling points, such as increased project visibility, streamlined collaboration, and a vibrant community. Highlight how ProjectHut simplifies the process of project sharing and fosters a collaborative environment for developers.

By implementing the "Getting Started" button and creating a comprehensive documentation and feature overview page, we aim to provide users with a clear understanding of the platform's functionalities and facilitate a smooth onboarding experience.

I'm excited to contribute to this feature and improve the user experience on ProjectHut. Your feedback and guidance on the content and presentation of the "Getting Started" page will be greatly appreciated.

Thank you for considering this proposal!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
@exploring-solver please try to add valid points don't add unnecessary points. 

also, we already have a docs page & ig we don't need to add this button.
