### ISSUE TITLE
[style]: Improve Card UI Layout

### ISSUE THREAD

**Issue by Ayush9951** [priyankarpal/ProjectsHut#806]
### What's the style idea?

Hi, @priyankarpal, I am a GSSOC'23 Contributor.
I want to work on Improving the UI of card.
I will add proper whitespace inside the card this will Improve it's UI, Increase Row and Column margin between cards.
please assign me this task under label gssoc'23 

### Add screenshots

Add screenshots
![Screenshot 2023-05-25 202933](https://github.com/priyankarpal/ProjectsHut/assets/60573378/735ea679-a32e-4217-add7-898d453baab6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
so @Ayush9951 we are thinking to change the card design.
