### ISSUE TITLE
data: project addition by Kumudha

### ISSUE THREAD

**Issue by Kumudhaart** [priyankarpal/ProjectsHut#813]
### Add a new project to the list

 I want to add a new project to the list.
My project is an e-commerce website. This e-commerce website is exclusively for dogs. The website is made using HTML, CSS, javascript, and Bootstrap.
I'm in GSSOC'23".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
