### ISSUE TITLE
[Feat]: Use Caching and Search Params for ContributorsPage

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#816]
### What feature?

We can using caching to store the contributors data fetched from API. Also the pagination can be achieved using searchParams.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we are thinking to remove the contributors page & adding a new page for new features
