### ISSUE TITLE
[Bug]: We are not fetching all the contributors

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#819]
### What happened?

![image](https://github.com/priyankarpal/ProjectsHut/assets/75559082/3d37ac03-e9b5-404a-99a7-30889dd32036)

The max limit is 100 contributors for per_page. We should change the endpoint.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig we have fixed this bug

**Comment by kailashchoudhary11** [comment]
> ig we have fixed this bug

Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.

**Comment by priyankarpal** [comment]
> > ig we have fixed this bug
> 
> Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.

yeah is there any possible to fetch all contributors?

**Comment by kailashchoudhary11** [comment]
> > > ig we have fixed this bug
> > 
> > 
> > Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.
> 
> yeah is there any possible to fetch all contributors?

I don't think so. I'll try to research on it.

**Comment by kailashchoudhary11** [comment]
@priyankarpal #816 Pehle ye wala review karna

**Comment by priyankarpal** [comment]
> > > > ig we have fixed this bug
> > > 
> > > 
> > > Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.
> > 
> > 
> > yeah is there any possible to fetch all contributors?
> 
> I don't think so. I'll try to research on it.

yeah I'm also

**Comment by kailashchoudhary11** [comment]
> > > > > ig we have fixed this bug
> > > > 
> > > > 
> > > > Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.
> > > 
> > > 
> > > yeah is there any possible to fetch all contributors?
> > 
> > 
> > I don't think so. I'll try to research on it.
> 
> yeah I'm also

We can resolve this using search params in our code. As I've mentioned in #816 @priyankarpal

**Comment by priyankarpal** [comment]
> > > > > > ig we have fixed this bug
> > > > > 
> > > > > 
> > > > > Nope. We can only fetch 100 contributors at a time using the `per_page` query parameter.
> > > > 
> > > > 
> > > > yeah is there any possible to fetch all contributors?
> > > 
> > > 
> > > I don't think so. I'll try to research on it.
> > 
> > 
> > yeah I'm also
> 
> We can resolve this using search params in our code. As I've mentioned in #816 @priyankarpal

thinking to remove the contributors page & adding a new page

**Comment by vishnu9865** [comment]
@kailashchoudhary11 @priyankarpal You guys are right, when implementing the Pagination, I scoured the internet for other options, for any api endpoint that would return all contributors.
( including using page number params)  seemed to return only top 100 contributors.
This was also the same with other repositories I was contributing to.
I even used my github personal access token in the headers to fetch more contributors, but no avail.
Please do update here, if you guys find anything 😊

**Comment by kailashchoudhary11** [comment]
@priyankarpal @vishnu9865 It is possible to fetch all the contributors by using `page` query parameter along with `per_page` we can keep changing the page number.

**Comment by priyankarpal** [comment]
> @priyankarpal @vishnu9865 It is possible to fetch all the contributors by using `page` query parameter along with `per_page` we can keep changing the page number.

ok

**Comment by vishnu9865** [comment]
@kailashchoudhary11 Yes you are right, the paginated links come back with the response in header as the value of 'Link' key.
I just checked in Postman API.
![image](https://github.com/priyankarpal/ProjectsHut/assets/91585213/a945c8e7-4006-4a91-96d8-505dca4fc7e0)
The code already has a easy react-paginate lib for pagination, If we find a way to get total number of contributors through the API, we can implement pagination without manually fetching and storing the data.

**Comment by kailashchoudhary11** [comment]
Yes there is a way to find total number of contributors. we can keep making requests until rel="last"

**Comment by priyankarpal** [comment]
we are thinking to remove the contributors page & adding a new page for new features

**Comment by kailashchoudhary11** [comment]
> we are thinking to remove the contributors page & adding a new page for new features

ok
