### ISSUE TITLE
data: project addition by Vivek Kumar Tiwari

### ISSUE THREAD

**Issue by vk20july** [priyankarpal/ProjectsHut#823]
### Add a new project to the list

I want to add a new project to the list 
I want to add a new open source project to the list under GSSoC'23.

Legendary Nokia Snake Game which would take you back to the good old days.
Tech-stack: python

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by vk20july** [comment]
Sir i will complete this within 2 days
That's my guarantee
I am right now noting down the points of making this game

**Comment by priyankarpal** [comment]
> Sir i will complete this within 2 days That's my guarantee I am right now noting down the points of making this game

ok

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
