### ISSUE TITLE
[style]: Adding infinite scroll to the Contributors section

### ISSUE THREAD

**Issue by dhruvishavaghani** [priyankarpal/ProjectsHut#828]
### What's the style idea?

We need to improve  :
Instead of the previous,1,2,3, and the next buttons we can add an infinite scroll to the contributors section which will vertically load all contributors' profiles.
It will be more user-friendly and improve the contributors page appearance.

### Add screenshots

![Screenshot 2023-05-26 123214](https://github.com/priyankarpal/ProjectsHut/assets/109460833/8618b98e-5030-42f2-9778-eb2fe8d74868)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we are thinking to remove the contributors page & adding a new page for new features
