### ISSUE TITLE
data: project addition by Manoj Sai

### ISSUE THREAD

**Issue by manojsai1** [priyankarpal/ProjectsHut#829]
### Add a new project to the list

Hey, I would like to propose the inclusion of a new open-source project for the GSSoC'23 list.

The core focus of this project revolves around real-time tracking of cryptocurrency prices through the utilization of APIs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
