### ISSUE TITLE
[style]: dispaly command is vs code format

### ISSUE THREAD

**Issue by noobtuber20103152** [priyankarpal/ProjectsHut#830]
### What's the style idea?

In docs page json and command should be in this format(In a code format using react code blocks)

![image](https://github.com/priyankarpal/ProjectsHut/assets/81584747/90647188-428f-4d55-a095-ac69b18dcffa)

Please assign this to me if neccesary.
Thank you!
@priyankarpal 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes, you're correct we need to add it like this. ig we need to use package to show this format

**Comment by noobtuber20103152** [comment]
yes @priyankarpal 
package name is react-code-blocks https://www.npmjs.com/package/react-code-blocks

**Comment by priyankarpal** [comment]
> yes @priyankarpal package name is react-code-blocks https://www.npmjs.com/package/react-code-blocks

ok cool assigned to you

**Comment by noobtuber20103152** [comment]
thank you

**Comment by priyankarpal** [comment]
could you share your progress on this issue?

**Comment by noobtuber20103152** [comment]
I am working on it. But my laptop is not working properly, it need to be repair. so that it take some times to repair.

**Comment by noobtuber20103152** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/81584747/ade020f1-65d3-49ca-a27e-70b3e44bad49)

and while i am running command pnpm install it gives me this error, do you have any solution?

**Comment by noobtuber20103152** [comment]
ohhh it works 🥳🥳 after 3-4 days 🥲🥲. I am working on it

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
