### ISSUE TITLE
Footer Need Improvement 

### ISSUE THREAD

**Issue by 9520prashant** [priyankarpal/ProjectsHut#834]
### What feature?

I have an idea to improve footer to adding social of project hub. Hey @priyankarpal I am a GSSOC'23 contributor kindly assign this issue to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we are changing the footer design also we don't have any separate social media for projectshut

**Comment by 9520prashant** [comment]
Sure
