### ISSUE TITLE
[style]: Docs page need more styling

### ISSUE THREAD

**Issue by Kumudhaart** [priyankarpal/ProjectsHut#838]
### What's the style idea?

We need to improve the document page. I will make all steps as card components. I attached a screenshot as a reference. I am in GSSOC 23

### Add screenshots

![Screenshot (52)](https://github.com/priyankarpal/ProjectsHut/assets/79578963/8ef9fc44-771f-4e7c-9732-d283b12bf1d4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Kumudhaart could you please check our updated docs?

**Comment by Kumudhaart** [comment]
Hello, I couldn't see the updated docs.
![Screenshot (53)](https://github.com/priyankarpal/ProjectsHut/assets/79578963/ffe7861c-0861-4749-81f3-8bfb24d60cd9)
I am able to see the above screenshot only.
Whether styling for docs already done?

**Comment by priyankarpal** [comment]
we just updated the docs.

**Comment by Kumudhaart** [comment]
Ok fine.
