### ISSUE TITLE
[style]: Add Animations and Improve Loading State

### ISSUE THREAD

**Issue by kunalkashyap-1** [priyankarpal/ProjectsHut#840]
### What's the style idea?

I would like to propose some enhancements to the Contributors Page component to improve the user experience and visual appeal. This issue addresses two specific points:
1. Add Animations and Transitions:
   Currently, the rendering of the contributors' list lacks visual smoothness and interactivity. 

   - Implement a fade-in effect when rendering each contributor card.
   - Apply smooth fade-out transitions when removing contributors.

2. Improve Loading State:
   The current loading state of the Contributors Page component simply displays the text "Loading...". We can enhance this by incorporating a loader or spinner animation to provide a more engaging loading experience.

I'm in GSSOC'23.
Do assign me this issue.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you add animation using Framer Motion? ig it will be super crazy if we add Framer Motion.

**Comment by kunalkashyap-1** [comment]
I personally haven't worked with this library before, But sure i can do it using framer motion.
do tell me the deadline for this as i would have to adjust it according to it

**Comment by priyankarpal** [comment]
> I personally haven't worked with this library before, But sure i can do it using framer motion. do tell me the deadline for this as i would have to adjust it according to it

according to the GSSoC guideline you need to complete this task by 3-4 din

**Comment by priyankarpal** [comment]
so we're thinking to remove the contributor's page.
