### ISSUE TITLE
data: project addition by  Dhruvisha Vaghani

### ISSUE THREAD

**Issue by dhruvishavaghani** [priyankarpal/ProjectsHut#843]
### Add a new project to the list

 I want to add a new project to the list 

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @dhruvishavaghani

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
