### ISSUE TITLE
[style]: Change the text and button background color in HomePage

### ISSUE THREAD

**Issue by iamharshkr** [priyankarpal/ProjectsHut#850]
### What's the style idea?

In dark mode color light cyan will looks awesome with dark background.

### Add screenshots

Screenshot
![homepage](https://github.com/priyankarpal/ProjectsHut/assets/54257619/4bbdea9c-52fe-4dc8-86c6-754b0f41c563)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
ig white is looking good in dark mode
