### ISSUE TITLE
[Feat]: Sitemap addition

### ISSUE THREAD

**Issue by krishnamangal98** [priyankarpal/ProjectsHut#854]
### What feature?

I have an idea to add a sitemap to the site to make it easier for the user to navigate the site.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we can add a sitemap for SEO. do you want to work on this issue? also, are you a GSSoC contributor? @krishnamangal98

**Comment by krishnamangal98** [comment]
Yes, I want to work on this issue and I am also a GSSoC contributor.

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
