### ISSUE TITLE
[Feat]: Adding search option on every web page

### ISSUE THREAD

**Issue by mayank123op** [priyankarpal/ProjectsHut#857]
### What feature?

 Having a search option in every  page will give user a option to find particular topics or things faster. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/400
