### ISSUE TITLE
data: project addition by Sai Kiran Reddy

### ISSUE THREAD

**Issue by saikiranreddy201** [priyankarpal/ProjectsHut#860]
### Add a new project to the list

 I want to add a new project to the list
I aim to introduce a new project that will provide a valuable add-on for this project under the gssoc'23 program

I want to add a project called Web Crawler The crawler will traverse websites starting from a given seed URL, following links to discover and crawl additional pages within the defined scope, It will scrape all the front add files like HTML, php except the backend code files to ensure safety!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
