### ISSUE TITLE
[style]: The scroll to the top button's index is positioned under the footer.

### ISSUE THREAD

**Issue by jibola2588** [priyankarpal/ProjectsHut#861]
### What's the style idea?

The scroll to the top button's index should be positioned above the footer.

### Add screenshots

Add screenshots
![Screenshot (88)](https://github.com/priyankarpal/ProjectsHut/assets/76418445/10d97ac7-4f84-4dfc-baa7-ce60fdee160e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we need to fix it. 

assigned to you

**Comment by jibola2588** [comment]
thanks sir

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
