### ISSUE TITLE
fix: add a clear bio of the site

### ISSUE THREAD

**Issue by engorgedspirit** [priyankarpal/ProjectsHut#870]
### what's wrong in the documentation?

There is very less details about what your project does in about section. I'm a GSSoC contributor please assign me this issue. I will add a detailed explanation for about section

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
could you share where we need to add good details?

**Comment by engorgedspirit** [comment]
![image](https://github.com/priyankarpal/ProjectsHut/assets/85272049/9a2851dc-b75c-4bfc-87df-ea794c59c2cf)
This about section could use more information so that users clearly understand what type of project is this. 
![image](https://github.com/priyankarpal/ProjectsHut/assets/85272049/ab93082d-f041-4d4a-b1db-fa3ef6029a50)
In this home page there should be more explanation about how the whole system works, why you should chose this etc. Actually Readme.md is more informative to new users than the site itself, but when it comes to accessibility having information on site is better.

**Comment by priyankarpal** [comment]
yes, we need to change assigned to you.
