### ISSUE TITLE
Add your projects link

### ISSUE THREAD

**Issue by engorgedspirit** [priyankarpal/ProjectsHut#871]
### What happened?

![image](https://github.com/priyankarpal/ProjectsHut/assets/85272049/b71abe3a-4055-481a-b7b0-af10dbfab147)
This is the page that opens if you click add your project from homepage. Anchor tag is misplaced so it opens in wrong position. 
I'm a GSSoC contributor please assign me this issue, I will correct it.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we already habe the tag
