### ISSUE TITLE
visibility in pages

### ISSUE THREAD

**Issue by engorgedspirit** [priyankarpal/ProjectsHut#872]
### What happened?

Currently selected page is not properly visible due to color selection. 
![image](https://github.com/priyankarpal/ProjectsHut/assets/85272049/70f4fe02-fa18-4aed-83f3-35cb6f92385f)
I'm a GSSoc contributor. Please assign me this issue. I will change color and decrease the size of rest buttons by just a little bit along with hover effect so that current page selected is properly visible.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we will remove the pagination after a few days & will add new features so ig we don't need.
