### ISSUE TITLE
[style]: Improve the responsiveness of page (text and  images)  in `/docs` 

### ISSUE THREAD

**Issue by Pursottam6003** [priyankarpal/ProjectsHut#880]
### What's the style idea?

Just a small issue in the style I have figured out here when someone tries to read the documentation by clicking the button ```Documentation```  or  ``` how to add  own projects inside the project hub```  

The text and images were partially hidden so we need to update the styles. 

Steps to reproduce the issue 
1. Inspect the website using ```ctrl + shift +i ```
2. Navigate to the documentation button inside the website
3. Choose the device toggle option in the top left of the developer options 
4. Select any small devices 

How we can fix this issue?  

Well we have two options either we would update the styles using CSS or we can replace the long images with the phone-size images using media query 

I would be happy  to resolve this issue  respected mentor please assign me @priyankarpal @hariketsheth @swapnilgarg7
Thanks 

### Add screenshots

The issue on Small sized devices like  iPhone SE  (375 X 667)  and Even in iPhone XR (414 X 896) and other devices 

![image](https://github.com/priyankarpal/ProjectsHut/assets/81693090/966d8e66-4ddb-492c-9205-290d61b6b863)

![image](https://github.com/priyankarpal/ProjectsHut/assets/81693090/d61eba11-37ef-4c84-8cd5-271514e0bff8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we need to fix the issue. assigned to you

**Comment by Pursottam6003** [comment]
Hii @priyankarpal  

I have fixed the issue from my side and was just about to commit  it  before making the PR I got another small issue regarding the contrast of background color ```priyankarpal/projectshut ``` should i update the styles and background color of ```priyankarpal/projectshut ``` or create a another issue for it ?

![image](https://github.com/priyankarpal/ProjectsHut/assets/81693090/950cda5e-4799-4589-93cf-fe1428387ef3)

**Comment by priyankarpal** [comment]
> Hii @priyankarpal
> 
> I have fixed the issue from my side and was just about to commit it before making the PR I got another small issue regarding the contrast of background color `priyankarpal/projectshut ` should i update the styles and background color of `priyankarpal/projectshut ` or create a another issue for it ?
> 
> ![image](https://user-images.githubusercontent.com/81693090/241723919-950cda5e-4799-4589-93cf-fe1428387ef3.png)

yeah we need to change the bg you can change the bg of `priyankarpal/projectshut ` in the same pr

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
