### ISSUE TITLE
[Feat]: Need Update the category filter layout and design change to multiselect filter with improved UI   

### ISSUE THREAD

**Issue by Pursottam6003** [priyankarpal/ProjectsHut#881]
### What feature?

I have an idea since we know there will be times when the ```ProjectHub``` may have multiple category tech stack eg suppose it may have ```Machine Learning```, ``` Artificial Intelligence```, ``` Object Detection```, ```Reinforcement Learning``` etc 

Might the whole hero section will be filled with tech stack only so we can have either a scrollable/expendable multi select tech stack design?  
Because maybe the student might use more than one tech stack such as react and MongoDB so give the multi select option to filter the projects 
 
![Screenshot from 2023-05-27 03-39-31](https://github.com/priyankarpal/ProjectsHut/assets/81693090/cf940422-bc7b-41d9-ac5b-a87923df9adc)

### Add screenshots

Just I am giving an example from a famous website ie leetcode.com 

Note: Forgot the button styles and content 

![image](https://github.com/priyankarpal/ProjectsHut/assets/81693090/57a7938a-e1d5-437f-8043-84c751d59cb3)

Here we can add a ```button``` to sort on the basis of maximum project repository ```stars``` and there should be  a button to ```expand``` other tech stack details view 

A ```search box``` to search the required ```tech stack``` query by the user and the ```multi-select``` option to filter the tech stack  

![image](https://github.com/priyankarpal/ProjectsHut/assets/81693090/e4d06118-c351-4c31-bc4a-1f498f166057)

@swapnilgarg7 @priyankarpal 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yes someone is working on that feature & will add in a few days with search bar https://github.com/priyankarpal/ProjectsHut/issues/400
