### ISSUE TITLE
Refactor code and following the convention in naming jsx files

### ISSUE THREAD

**Issue by coder12git** [priyankarpal/ProjectsHut#882]
### What feature?

Hey, I found that main.jsx which is basically a js file, therefore it's name should be main.js to follow the convention. Also some of the jsx files name are not starting with capital letters. There are few rules to keep in mind while working with JSX: A React component name must be capitalized. Component names that do not begin with a capital letter are treated like built-in components. 
Therefore, I want to fix this issue and also I want to refactor main.jsx and App.jsx file.

Please assign me this Issue. I am in GSSOC 2023.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
this is our reactjs project & ig if we don't rename `main.jsx` to `main.js` it would be great.

we don't know when we will add code to the `main.jsx`.


which file name do we need to capitalize?
