### ISSUE TITLE
data: project addition by @Hypertext-Workaholics

### ISSUE THREAD

**Issue by Hypertext-Workaholics** [priyankarpal/ProjectsHut#890]
### Add a new project to the list

 I want to add a new project to the list that is bullseye game. I created using HTML, CSS, JS. It would be a fun game for children.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
