### ISSUE TITLE
Feat: sticky navbar 

### ISSUE THREAD

**Issue by SINJINI-G** [priyankarpal/ProjectsHut#897]
### What feature?

I have an idea to make the navbar sticky.

Can I work on this under gssoc?

### Add screenshots

![Screenshot 2023-05-27 131453](https://github.com/priyankarpal/ProjectsHut/assets/98143022/e0a052a6-4126-4739-8765-a643d5f857f7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah, we can do it too. also, we are thinking to add a transparent background for only Navbar. 

do you want to work on this issue? & are you a GSSoC contributor?

**Comment by engorgedspirit** [comment]
Im a GSSoc cntributor, please assign me this issue, I will resolve it

**Comment by SINJINI-G** [comment]
> yeah, we can do it too. also, we are thinking to add a transparent background for only Navbar.
> 
> do you want to work on this issue?

Yes I am a gssoc contributor.. and am willing to work on this issue.. please assign this to me.

**Comment by priyankarpal** [comment]
> > yeah, we can do it too. also, we are thinking to add a transparent background for only Navbar.
> > do you want to work on this issue?
> 
> Yes I am a gssoc contributor.. and am willing to work on this issue.. please assign this to me.

assigned
