### ISSUE TITLE
[Bug]: Back to project path is wrong

### ISSUE THREAD

**Issue by Sh4dab** [priyankarpal/ProjectsHut#898]
### What happened?

Hello, I am a GSSOC'23 Contributor.
While viewing more about any project when you tries to go back to project page by clicking back to page, it shows page not found.
I would like to solve this issue.

### Add screenshots

Add screenshots
![c4](https://github.com/priyankarpal/ProjectsHut/assets/97034961/7bfbd733-b592-4dd5-9438-f7b734878e79)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah we need to add the path `/projects`

assigned to you @Sh4dab

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
