### ISSUE TITLE
[Bug]: Link not working in navitem projects

### ISSUE THREAD

**Issue by Soulpurr** [priyankarpal/ProjectsHut#901]
### What happened?

I found a BUG 🐞
In mobile screens the link of navitem projects is not working ,it is redirecting to 404 not found.
Affected Devices-Mobiles 
Please assign this to me under gssoc 23
[scrnli_27_05_2023_13-57-33.webm](https://github.com/priyankarpal/ProjectsHut/assets/92094765/a4f390d2-9d22-4643-bcf8-3e66e33ac4fa)

### Add screenshots

Add screenshots

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah we need to add the path `/projects` assigned to you

**Comment by Soulpurr** [comment]
Thanku for assigning will do it by today

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️

**Comment by Soulpurr** [comment]
Thx
