### ISSUE TITLE
[Feat]: Contact Us

### ISSUE THREAD

**Issue by whizzy23** [priyankarpal/ProjectsHut#903]
### What feature?

I think there should be a contact us section where user can send feedback message . 
I can create it using html and css .

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @whizzy23 we will add a testimonial section & review section later. Currently we don't need a contact us form
