### ISSUE TITLE
[Feat]: UI card update

### ISSUE THREAD

**Issue by engorgedspirit** [priyankarpal/ProjectsHut#908]
### What feature?

You raised this issue 
![image](https://github.com/priyankarpal/ProjectsHut/assets/85272049/e15e88b4-1d31-4544-b5b3-3a181e0e253b)
https://github.com/priyankarpal/ProjectsHut/issues/906#issue-1728633753
I wasnt able to comment so I'm writing here. 
Im a GSSoc cntributor, please assign me this issue, I will resolve it
Here is my UI/UX profile for your reference if you want to check out my work https://github.com/engorgedspirit/UI-UX

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @engorgedspirit you don't need to create an issue for this you will see the label `status: ready for dev` if the issue is ready. 

Currently, that issue is not ready.
