### ISSUE TITLE
[style]: scroll to top

### ISSUE THREAD

**Issue by Vraj1103** [priyankarpal/ProjectsHut#911]
### What's the style idea?

We need to improve the animation scroll to top button and color of the button on hover, so user can know its working!

### Add screenshots

Before Hover:
![image](https://github.com/priyankarpal/ProjectsHut/assets/94098866/7a69ece7-fdc4-4593-a8fc-538e21e4dde9)
After Hover:
![image](https://github.com/priyankarpal/ProjectsHut/assets/94098866/5332899e-cd8f-4660-815d-aa4622db013f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
I believe users can understand the scroll to the top button without needing an animation.
