### ISSUE TITLE
[style]: improve the shadow of the project cards & add hover effect

### ISSUE THREAD

**Issue by Vraj1103** [priyankarpal/ProjectsHut#913]
### What's the style idea?

We need to improve the card styling by adding some depth effect, also we can add some hover effects on the same card.

### Add screenshots

Without depth effect:
![image](https://github.com/priyankarpal/ProjectsHut/assets/94098866/4d3a1579-04eb-431f-aa32-cd66834c1b29)
With depth effect:
![image](https://github.com/priyankarpal/ProjectsHut/assets/94098866/3ae561b4-44db-4ae2-b040-8cb067774bd8)
Hover effect:
![image](https://github.com/priyankarpal/ProjectsHut/assets/94098866/e4ac44b5-2101-4574-a3e6-b3f72f158dab)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Vraj1103 we will change the card design so currently we don't need to add effect.

https://github.com/priyankarpal/ProjectsHut/issues/906
