### ISSUE TITLE
Pagination numbering issue and inactive side navigation links on mobile

### ISSUE THREAD

**Issue by manaver** [priyankarpal/ProjectsHut#917]
### Pagination numbering

The pagination on the project list page should display numbers as 1, 2, 3...10 instead of 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. This will provide better clarity on the total number of pages available.

![image](https://github.com/priyankarpal/ProjectsHut/assets/78682260/7ca37d4b-d00e-4d5c-b9da-ec693d068d0f)

### Inactive side navigation links on mobile

On the mobile version of our website, the side navigation links are not active when clicked. This prevents users from accessing the corresponding sections of the page.
![image](https://github.com/priyankarpal/ProjectsHut/assets/78682260/554b28d8-3b37-437a-8fc5-f04cf1a9083c)

### Steps color in dark mode on the documentation page

Currently, in dark mode on the documentation page, the color of the steps is not consistent with the overall theme. To improve the visual experience, the steps should have a light purple color when viewed in dark mode.

![image](https://github.com/priyankarpal/ProjectsHut/assets/78682260/6ca2051a-6db0-40b6-ba13-75d459cc2ee0)

**Comment by priyankarpal** [comment]
hey, @manaver thanks for raising an issue we will remove the pagination soon so we don't need to change it right now.

Someone is working on the docs page.

Also, we need to fix the mobile navbar active issue. if you want to work on this issue you can work. 
also, please mention if you're a GSSoC contributor

**Comment by manaver** [comment]
> hey, @manaver thanks for raising an issue we will remove the pagination soon so we don't need to change it right now.
> 
> Someone is working on the docs page.
> 
> Also, we need to fix the mobile navbar active issue. if you want to work on this issue you can work. also, please mention if you're a GSSoC contributor

Thanks for answering, I am a gssoc'23 contributor please assign this issue to me. I'll work on navbar active issue😃

**Comment by priyankarpal** [comment]
> > hey, @manaver thanks for raising an issue we will remove the pagination soon so we don't need to change it right now.
> > Someone is working on the docs page.
> > Also, we need to fix the mobile navbar active issue. if you want to work on this issue you can work. also, please mention if you're a GSSoC contributor
> 
> Thanks for answering, I am a gssoc'23 contributor please assign this issue to me. I'll work on navbar active issuesmiley

yeah sure assigned to you

**Comment by manaver** [comment]
Hi, @priyankarpal  please add gssoc tags
