### ISSUE TITLE
[Docs]: translate to Kannada

### ISSUE THREAD

**Issue by engorgedspirit** [priyankarpal/ProjectsHut#918]
### in which language do you want to translate?

I want to translate documentation to kannada.
Im a GSSoc cntributor, please assign me this issue, I will resolve it

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
according to the guidelines of GSSoC we have assigned you to an issue so we're unable to assign you to this issue now. so you need to work on those issues first.


if anyone messages here for assigning this issue I can assign him/her if your previous PR haven't got merged.

**Comment by engorgedspirit** [comment]
There are no guidelines in GSSoC saying we can work on more than one issue simultaneously. Infact I'm working on many in other projects too.

**Comment by priyankarpal** [comment]
you can check the guidelines from GSSoC 

![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/ece0e82e-d1fa-4970-b545-af358f62ad7c)

https://docs.google.com/document/d/1FWsgZjC-WMrEHmP1bUbM3x3prZeV5DHf/edit

also, you can check from their Discord server.

**Comment by priyankarpal** [comment]
I don't have any problem I just said what they have mentioned

**Comment by engorgedspirit** [comment]
Okay sure, then ill complete is first

**Comment by Bhanuteja01** [comment]
i'm gssoc contributor can you assign me this

**Comment by priyankarpal** [comment]
> i'm gssoc contributor can you assign me this

yeah sure assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
