### ISSUE TITLE
[style]: Footer and Body's backround color should be different in light mode

### ISSUE THREAD

**Issue by ritik48** [priyankarpal/ProjectsHut#923]
### What's the style idea?

We need to improve the background color of the footer in light mode, as in light mode footer's and the body's background is same so we cannot differentiate the footer.

### Add screenshots

Add screenshots
- Before
![projecthut light before](https://github.com/priyankarpal/ProjectsHut/assets/84488726/be86c59e-dd4c-40c2-b773-baf0a2576732)

- After
![projecthut light](https://github.com/priyankarpal/ProjectsHut/assets/84488726/9788e6ae-1767-4de7-ba5b-a4cea08af86a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @ritik48 thanks for raising this issue regarding the footer. we will add new footer design so we don't need to change it right now
