### ISSUE TITLE
[Feat]: Automate rearrangement of projects in user profile

### ISSUE THREAD

**Issue by ujjawaltyagii** [priyankarpal/ProjectsHut#924]
### What feature?

I have an idea !

- As of now all the projects each user has in their profiles are in unsorted manner that is the projects are getting added in each profile in statistically manner. And if user wants to sort all projects in his profile then <b>they have to do it manually</b>.

- So if we could <b>automate</b> this thing, i.e no matter in which order user adds project in `projects.json` system will automatically arrange all the projects of a user in their profile in sequential alphabetical order then it would be great !

#### This will improve the user experience while browsing projects on ProjectsHut
<br>

- Please assign this issue to me so I can work on this enhancement 
- I am a gssoc contributor so please add required labels as well

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
automate like? Could you share a demo with us?

**Comment by ujjawaltyagii** [comment]
@priyankarpal like we can write code so that whenever user enters project data in whatever order code will automatically rearrange all the projects of a user in alphabetical order

**Comment by priyankarpal** [comment]
mean you want to sort projects alphabetically?

**Comment by ujjawaltyagii** [comment]
@priyankarpal  yes ! so for a user all the projects in their profile will be shown in sorted order

**Comment by ujjawaltyagii** [comment]
@priyankarpal could you assign this to me ? and add gssoc labels

**Comment by ujjawaltyagii** [comment]
@priyankarpal  ????

**Comment by priyankarpal** [comment]
ig, it appears to be unnecessary.

**Comment by ujjawaltyagii** [comment]
@priyankarpal okay ! I was talking about this by the way (instead of showing projects in the order user typed the code to add projects I was thinking that we could show user projects in alphabetically sorted order where no matter in what order user enters project detail they will be sorted automatically on their profile)

https://github.com/priyankarpal/ProjectsHut/assets/115401171/e5e669c5-72d7-4070-9308-2df9908cdbe6

**Comment by priyankarpal** [comment]
> @priyankarpal okay ! I was talking about this by the way (instead of showing projects in the order user typed the code to add projects I was thinking that we could show user projects in alphabetically sorted order where no matter in what order user enters project detail they will be sorted automatically on their profile)
> 
>  fx.mp4

yeah ik
