### ISSUE TITLE
[Bug]: Home Page responsiveness

### ISSUE THREAD

**Issue by parasss19** [priyankarpal/ProjectsHut#929]
### What happened?

I found a BUG 🐞
Home Page text and floating images overlap each other at approx. 740px of screen size

### Add screenshots

Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/101205226/fc485f39-2ee9-4c74-98af-95265717fc43

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parasss19** [comment]
Hi @priyankarpal i have created the same issue by mistake 
This is the main issue #929

**Comment by priyankarpal** [comment]
do you want to work on this issue?

**Comment by parasss19** [comment]
> do you want to work on this issue?

Yes

**Comment by Hareesh108** [comment]
@parasss19 you can add keyframes and set the images with different screen sizes. great one feature!!

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
