### ISSUE TITLE
[Feat]: Add code blocks to add your project guide

### ISSUE THREAD

**Issue by akshaya-hub** [priyankarpal/ProjectsHut#934]
### What feature?

I have an idea 

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/830
