### ISSUE TITLE
[Feat]: Improving the styling of pagination 

### ISSUE THREAD

**Issue by Sh4dab** [priyankarpal/ProjectsHut#935]
### What feature?

Hello, I am a GSSOC'23 Contributor.
I would like to improve the styling of pagination in Projects section by adding the background color on the active page.

### Add screenshots

It will look like this:
![c5](https://github.com/priyankarpal/ProjectsHut/assets/97034961/6e4445e1-858c-4d71-88d5-c7350e6be511)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Sh4dab thanks for raising an issue for pagination problem we will remove the pagination so currently we don't need to change it right now.
