### ISSUE TITLE
[Bug]: Documentation page Responsiveness

### ISSUE THREAD

**Issue by vishnubansal001** [priyankarpal/ProjectsHut#939]
### What happened?

I found a BUG 🐞
All the other pages are responsive as they can be veiwed on any of the device like mobile , tablet , laptop , but the in the documentation page the data is going out of the view box and disappeared due to this which is i think not good 

I am a GSSOC'23 contributor 
I want to resolve this issue please assign this to me 

### Add screenshots

![Screenshot (111)](https://github.com/priyankarpal/ProjectsHut/assets/101445306/e9c42c88-cf5b-4822-b9b8-00e9b7ce7c88)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/880
