### ISSUE TITLE
[Feat]:  Proposal for Automating Project Management with Supabase Integration

### ISSUE THREAD

**Issue by murtazajoo** [priyankarpal/ProjectsHut#940]
### What feature?

I have an idea 

**Title:** Proposal for Enhancing Project Management in ProjectHut

## Problem Statement
Currently, adding projects to ProjectHut involves forking the repository and manually updating the `Db/project.json` file with project details. Over time, this file accumulates numerous projects, leading to potential scalability and management issues. To address this, I propose implementing a serverless database solution, such as Supabase, to automate project management and enhance user experience.

## Proposed Solution
The proposed solution aims to streamline the project submission process and provide users with a more efficient way to manage their projects on ProjectHut. The implementation will involve the following key features:

1. Serverless Database: Integrate Supabase, a free and user-friendly serverless database, to store project data securely. Supabase offers a free tier with ample storage capacity (500MB) that aligns with our current needs.

2. User Authentication: Implement a login/signup page to allow users to create profiles. Once registered, users can access a personalized dashboard to manage their projects effectively.

3. Profile and Project Management: Upon logging in, users will have the ability to provide their profile details only once. This information will be associated with their account and can be used for future project submissions. Users can add, edit, and remove projects seamlessly from their dashboard, offering a similar experience to platforms like Product Hunt.

4. Improved User Experience: By automating project management, users will no longer need to manually fork the repository and update the `Db/project.json` file. The proposed solution simplifies the process, encourages more project submissions, and enhances the overall user experience.

## Benefits
The adoption of a serverless database and user authentication system brings several benefits to ProjectHut:

1. Scalability: With the implementation of Supabase, ProjectHut will be able to handle a growing number of projects without facing limitations imposed by a single file approach.

2. Efficiency: The automated project submission process saves time and effort for both users and maintainers. Users can focus on showcasing their projects, while maintainers can allocate resources to other important tasks.

3. Enhanced User Engagement: By providing users with a personalized dashboard and project management capabilities, ProjectHut will encourage greater user engagement and foster a vibrant community around project sharing.

4. Seamless Integration: Supabase's documentation and compatibility with React/JS projects make it an ideal choice for integrating the proposed solution into ProjectHut. The ease of use and robustness of Supabase simplify the development and maintenance process.

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @murtazajoo we will add `appwrite/firebase` later but we don't need to add this moment.
also, why do we need login/logout features? the main motive of projectshut is adding projects by creating a PR so newbies can know how to create a pr & issue

**Comment by murtazajoo** [comment]
Ok
