### ISSUE TITLE
Bug in  the  project section[Bug]: 

### ISSUE THREAD

**Issue by HimanshuNarware** [priyankarpal/ProjectsHut#943]
### What happened?

I found a BUG 🐞
In the project section, one box size is not similar to another, I want to resolve that, kindly assign me this issue

### Add screenshots

Add screenshots

![70](https://github.com/priyankarpal/ProjectsHut/assets/83147410/33f98c6a-1185-4b07-99ca-2a45e432bd2d)

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
It's happening for small description

**Comment by murtazajoo** [comment]
I got this

**Comment by HimanshuNarware** [comment]
> It's happening for small description

@priyankarpal But it's affecting the UI of the website we can fix this by giving additional styling

**Comment by priyankarpal** [comment]
> > It's happening for small description
> 
> @priyankarpal But it's affecting the UI of the website we can fix this by giving additional styling

so we are changing the UI of the project card ig currently we don't need to add.

**Comment by HimanshuNarware** [comment]
> > > It's happening for small description
> > 
> > 
> > @priyankarpal But it's affecting the UI of the website we can fix this by giving additional styling
> 
> so we are changing the UI of the project card ig currently we don't need to add.

ok
