### ISSUE TITLE
[Bug]: fix docs page bug

### ISSUE THREAD

**Issue by priyankarpal** [priyankarpal/ProjectsHut#946]
### What happened?

when we click on the `Add your projects` button it redirects to the docs page but the docs page starts from last not from first. we need to fix this problem 

## How to fix this issue? 
- Go to `src/pages/AddYourProjectsGuide.jsx` 

- add the sample code after the line `const AddYourProjectsGuide = () => {`

   ```
    window.scrollTo(0, 0)
   ```

 

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/88102392/767942ba-8bfa-4e59-b4d5-6f27ddbad96f

### What browsers are you seeing the problem on?

Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coder12git** [comment]
@priyankarpal Assign this to me!
I am in GSSOC 2023.

**Comment by priyankarpal** [comment]
> @priyankarpal Assign this to me! I am in GSSOC 2023.

assigned
