### ISSUE TITLE
data: project addition by govardhan-26

### ISSUE THREAD

**Issue by govardhan-26** [priyankarpal/ProjectsHut#947]
### Add a new project to the list

 I want to add a new project to the list. 
 I am in gssoc'23.
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @govardhan-26

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
