### ISSUE TITLE
[Feat]: Refactor search bar to provide real time updates

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#949]
### What feature?

We can keep sorting the projects based on Changes in the search bar input. 

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
@kailashchoudhary11 could you elaborate a little bit?

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 could you elaborate a little bit?

Yeah, I mean as soon as the user starts typing in the searchbox, we will update the projects list. For example the user wants to search for the project 'ProjectsHut'. The user will type P in the search box. After typing P, he will be able to see only those projects whose name starts with P on the projects page. Again, when he types r after P, he'll see only the projects starting with 'Pr' or containing 'Pr' in their name.

**Comment by priyankarpal** [comment]
> > @kailashchoudhary11 could you elaborate a little bit?
> 
> Yeah, I mean as soon as the user starts typing in the searchbox, we will update the projects list. For example the user wants to search for the project 'ProjectsHut'. The user will type P in the search box. After typing P, he will be able to see only those projects whose name starts with P on the projects page. Again, when he types r after P, he'll see only the projects starting with 'Pr' or containing 'Pr' in their name.

yeah, amazing idea 👍🏻 
assigned to you
