### ISSUE TITLE
Med.Ez: project addition by Raj Motwani

### ISSUE THREAD

**Issue by raj3000k** [priyankarpal/ProjectsHut#955]
### Add a new project to the list

 I want to add a new project to the list 
"Med.Ez" a medicine management system that can sort the medicines as per their expiry dates and data, also notifies the admin about the expiry medicines 2 weeks prior date of exp and also maintains sales and profit data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
