### ISSUE TITLE
[Docs]:  translating the languages

### ISSUE THREAD

**Issue by akshaya-hub** [priyankarpal/ProjectsHut#958]
### in which language do you want to translate?

 In the translation guide only the Tamil language is translated to its language all other languages are written in English

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey @akshaya-hub we already have tamil docs https://github.com/priyankarpal/ProjectsHut/tree/main/translations/Tamil
