### ISSUE TITLE
🆕 [FEAT]: IMAGE OPTIMIZATION FEATURE 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [priyankarpal/ProjectsHut#959]
### What feature?

- The feature is about incorporating image optimization with `wsrv`'s api
- The api can convert the Github user's profile image to `png` into `webp` and manually we can shrink the size of the image
- This feature is going to added on the `ProjectCard.jsx` file, the primary idea of this issue is to compress and optimized the images with api
- Take a look at below screenshots
   1. We already added explicit width & height of `2.5rem`
   2. But the image actually resolutioned to `460px` here the image is served in `png` format
   3. My idea is to convert the `png` to `webp` and along with resizing the image to `2.5rem` on serving from server itself
   4. It can drastically improves page performance and minimizes the bandwidth though

<br>

> **Note**
> #### I'm a participant of `GSSoC'23` and kindly assign this issue to me with `GSSoC'23` and `level 3` label for adding this new feature

### Add screenshots

1. ![Screenshot_2023-05-28-21-54-00_1366x768](https://github.com/priyankarpal/ProjectsHut/assets/92252895/5b70db12-37c0-44e8-96f5-84dbb7ecb262)

2. ![Screenshot_2023-05-28-21-54-27_1366x768](https://github.com/priyankarpal/ProjectsHut/assets/92252895/68ace0b9-63ca-47a8-852a-31170b8bfc34)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah! great idea @0xabdulkhalid 👏🏻  we need to optimize images for SEO, loading times, storage etc.

I will assign you
