### ISSUE TITLE
[Feat]:  Enhance Filtering Functionality with Multiple Selected Options and Context Integration

### ISSUE THREAD

**Issue by Rohan3011** [priyankarpal/ProjectsHut#969]
### What feature?

Hello, I am a GSSOC'23 Contributor.
Multiple selected options: Enhance the filtering functionality to allow users to select multiple options for filtering instead of being restricted to a single regex pattern or index. This improvement will provide users with greater flexibility and precision when filtering projects.

Adding FilterContext: Adding the filtering functionality with the FilterContext to ensure consistent state management and persistence of filters when navigating back to the projects list page. By leveraging the FilterContext, filters can be easily accessed and maintained across different components, resulting in a seamless user experience

I would like to work on this feature.

### Add screenshots

![Screenshot 2023-05-29 115403](https://github.com/priyankarpal/ProjectsHut/assets/76813454/1cc273b1-81ba-447b-bc09-ebb2f3e18614)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/956

**Comment by priyankarpal** [comment]
sorry, I mistakenly closed your issue before.

yeah great idea! can we add `projects?filter=techstacknames` instead of `projects?filter=0%2C1`?

**Comment by Rohan3011** [comment]
sure, I will add the `projects?filter=techstacknames` . Can you assign this issue to me?

**Comment by priyankarpal** [comment]
> sure, I will add the `projects?filter=techstacknames` . Can you assign this issue to me?

yeah assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
