### ISSUE TITLE
[Bug]: Typo in Footer

### ISSUE THREAD

**Issue by abhinav-m22** [priyankarpal/ProjectsHut#970]
### What happened?

In the footer section, the tag says "All right reserved".
Instead it should be as "All rights reserved".

### Add screenshots

<img width="413" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/113239388/8b0d0365-d645-43b8-b001-4e3af3b8cba1">

I want to work on this issue.
Please assign me the task under GSSoC'23.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
