### ISSUE TITLE
"Create your first Pull Request to ProjectsHut" Section Image Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [priyankarpal/ProjectsHut#971]
### What feature?

Alignment of image in the "Create your first Pull Request to ProjectsHut" Section.

### Current Design
![projecthut ss (2)](https://github.com/priyankarpal/ProjectsHut/assets/115794049/ae9cbc75-5314-4a74-89cd-3b3eab26bd5f)

### Expected Updated Design
![projecthut ss (1)](https://github.com/priyankarpal/ProjectsHut/assets/115794049/223a0fea-886c-48d5-acb6-79664d9b711b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
it seems like this issue has already been raised before. We kindly request you review the existing issues and, if necessary, create a new one accordingly. https://github.com/priyankarpal/ProjectsHut/issues/956
