### ISSUE TITLE
[Docs]: translation.md page

### ISSUE THREAD

**Issue by akshaya-hub** [priyankarpal/ProjectsHut#975]
### what's wrong in the documentation?

only the Tamil language is written in Tamil what about the other languages !

### Add screenshots

![Screenshot (1538)](https://github.com/priyankarpal/ProjectsHut/assets/76612327/034848b8-1ef0-4a46-9039-565416ad2214)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akshaya-hub** [comment]
@priyankarpal can you suggest to me if should  leave it or should I make changes

**Comment by priyankarpal** [comment]
hey @akshaya-hub we need to improve the translation guide page do you want to work on this 
issue?

## What do we need to do?
- fix all typos, mistakes, and grammar
- add a proper translation guide
- mention all contribution docs for translation
- update all translated languages links
  etc

**Comment by priyankarpal** [comment]
> @priyankarpal as i mentioned the above issue can you tell me should i make changes

yes we need to change 

assigned to you

**Comment by akshaya-hub** [comment]
@priyankarpal sure!
