### ISSUE TITLE
[Feat]: sticky Navbar creating bad user experiance

### ISSUE THREAD

**Issue by piyush-mahajan** [priyankarpal/ProjectsHut#978]
### What feature?

I would love to contribute to navbar which is not good designed and it disturbing the flow of site😇

### Add screenshots

![projecthunt-nav](https://github.com/priyankarpal/ProjectsHut/assets/98900169/1c57cfeb-b484-40de-ad56-6224c3c6cf2b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hi @piyush-mahajan  we fixed this issue please check the site if there are anything problems you can create an issue. (also, check existing issues)

Thank you. 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/a0dfecad-ea55-4b1c-8b52-b3c6bb0b03f8
