### ISSUE TITLE
[Bug]: Rollback on clicking links

### ISSUE THREAD

**Issue by ujjawaltyagii** [priyankarpal/ProjectsHut#980]
#### We have lot of hyperlinked pages i.e. 1 to 11  and each page contains clickable content/cards (of each project) , If  we are on 2nd page and then we click the content/project link on it and after that when we try to come back from the content link page to the second page we automatically gets redirected to 1st page everytime instead of latest visited page.

I think we should improve that, what do you think about it ?

### Add screenshots

https://github.com/priyankarpal/ProjectsHut/assets/115401171/e6fc3371-ef9d-4a72-8a69-593075d96b4d

### What browsers are you seeing the problem on?

Chrome, Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we will remove paginations & will add an infinity scroll with a skeleton loader so ig we don't need to fix it.

### issue https://github.com/priyankarpal/ProjectsHut/issues/941
