### ISSUE TITLE
data: project addition by Anurag 

### ISSUE THREAD

**Issue by AnuragJha003** [priyankarpal/ProjectsHut#984]
### Add a new project to the list

I want to add a restaurant site clone to the website 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you @AnuragJha003

**Comment by AnuragJha003** [comment]
I have developed a restaurant clone site shall I create a PR then?

**Comment by priyankarpal** [comment]
> I have developed a restaurant clone site shall I create a PR then?

yeah you can

**Comment by AnuragJha003** [comment]
I am creating  a PR by today for this issue
