### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AnuragJha003** [priyankarpal/ProjectsHut#985]
### What happened?

The NavBar is made responsive but there is an issue specially when converted to light mode the navbar sometime collides and gets immersed in the image so betterment in the UI and design of the Response NavBar would be great .

As can be seen in the given image the navbar is not at all visible completely when given this view .

### Add screenshots

<img width="958" alt="bug" src="https://github.com/priyankarpal/ProjectsHut/assets/97457228/37b86745-30e9-4eca-8f80-5d3c0442897d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hi, @AnuragJha003  we fixed this issue please check the site if there are anything problems you can create an issue. (also, check existing issues)

Thank you. 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/a0dfecad-ea55-4b1c-8b52-b3c6bb0b03f8
