### ISSUE TITLE
Adding Likes for each project

### ISSUE THREAD

**Issue by AlfiyaSiddique** [priyankarpal/ProjectsHut#986]
## Introducing the Feature
My idea is to add a like button on project cards where users can click and create a collection of their liked projects.

## How To implement it?
As we don't have a proper Database management system we can store the liked project record on the local web storage and whenever the user access the website it can easily retrieve all the liked project data.

Then We can add a link on the navbar called favorites for a separate route where the user can see only those projects that are liked by Him/Her.

## Request
If you find this feature worth implementing please assign me this issue under the GSSoC'23 label as I am a GSSoC'23 Contributor.

## Sample
The feature will be somewhat like the below screenshot. The difference is that we will display the project cards instead of images.

<img width="533" alt="desktop" src="https://github.com/priyankarpal/ProjectsHut/assets/86224794/134ce1aa-9d9e-4954-a2b3-4c006e95c142">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @AlfiyaSiddique thanks for raising the issue. we will add a like button, and testimonial section with the backend later. currently we don't need
