### ISSUE TITLE
[style] : Issue with header styles

### ISSUE THREAD

**Issue by md-abid-hussain** [priyankarpal/ProjectsHut#987]
The navigation section overlap with other section and cause style issue

![Screenshot (59)](https://github.com/priyankarpal/ProjectsHut/assets/101964499/1f6e0daa-489c-4f69-bb34-d6e63328569f)
![Screenshot (58)](https://github.com/priyankarpal/ProjectsHut/assets/101964499/ad601250-1b2a-4844-87f1-b47ac3b6cba4)

**Comment by priyankarpal** [comment]
hi @md-abid-hussain we fixed this issue please check the site if there are anything problems you can create an issue. (also, check existing issues)

Thank you. 


https://github.com/priyankarpal/ProjectsHut/assets/88102392/a0dfecad-ea55-4b1c-8b52-b3c6bb0b03f8
