### ISSUE TITLE
[Feat]: Adding Validation and Authentication for all my form 

### ISSUE THREAD

**Issue by Princessayomide53** [priyankarpal/ProjectsHut#990]
### What feature?

I want to add Authentication and into my web app using Firebase, Added validation with the help of using Formik and Yup

### Add screenshots

[https://jadoo-blond.vercel.app/](url)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Princessayomide53 thanks for raising the issue. currently, we don't need the form validation. we will add the backend later.  

Thanks for understanding
