### ISSUE TITLE
[Bug]: Using index as a key

### ISSUE THREAD

**Issue by kailashchoudhary11** [priyankarpal/ProjectsHut#991]
### What happened?

There are bugs on the projects page since we are using the index as a key in various places.
Instead, we should provide an id attribute in the project's data itself.
I've mentioned the screenshots of error and react docs.

### Add screenshots

![image](https://github.com/priyankarpal/ProjectsHut/assets/75559082/916b32ed-761c-4255-8ba9-be5f690b89fa)

![image](https://github.com/priyankarpal/ProjectsHut/assets/75559082/357e93bc-e39c-4944-85b4-2687880930f7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
assigned to you

**Comment by kailashchoudhary11** [comment]
> assigned to you
isko resolve karne ke liye pura data change karna padega. data ka structure sahi nahi hai sabhi projects ke paas unique id nahi hai 🥺
what we can do is projects aur users ko seperately store kar sakte hai projects array and users array mai aur project object ko ek property denge user jisme user ki id dal denge aur user object mai ek property denge projects jo ki ek array hoga aur usme user ki sabhi projects ki id dal sakte hai 🤔
but iske liye code mai bohot sare changes karne padenge to tum suggest karo kya karna hai 🤔🤔🤔 @priyankarpal

**Comment by priyankarpal** [comment]
then if we change right now we will get errors. so don't need to change & also, we will add the backend after a few days so then we will change according to the problems

**Comment by kailashchoudhary11** [comment]
> then if we change right now we will get errors. so don't need to change & also, we will add the backend after a few days so then we will change according to the problems

thik hai bro dusra koi issue assign kardo aur 2 issues raise kiye hai @priyankarpal

**Comment by priyankarpal** [comment]
so I'm closing this
