### ISSUE TITLE
[Feat]: Improve Navbar responsiveness on small devices

### ISSUE THREAD

**Issue by abhinav-m22** [priyankarpal/ProjectsHut#993]
### What feature?

On small devices like mobile phones, the navbar components are aligned to the left. Instead, if the components are aligned at the center, it will look more standard are appealing to the user.

### Add screenshots

<img width="214" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/113239388/7523d0be-c107-48f3-96d5-101c19b1ba94">

I want to work on this feature implementation.
Please assign me the task under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
we removed from the center. which device are you using? I'm not facing any issues


![image](https://github.com/priyankarpal/ProjectsHut/assets/88102392/e46074e9-cbb9-4906-81b5-8fcf9f41cab0)

**Comment by abhinav-m22** [comment]
@priyankarpal I'm using the Chrome DevTools.
It's just a suggestion to center the components so as to look good since most of the websites have centered navbar components and the page looks filled and even makes more appealing to the user.
Thanks!

**Comment by priyankarpal** [comment]
> @priyankarpal I'm using the Chrome DevTools. It's just a suggestion to center the components so as to look good since most of the websites have centered navbar components and the page looks filled and even makes more appealing to the user. If not possible, then atleast some icons can be added in front of the names. Please let me know... Thanks!

can you give us a demo?

**Comment by abhinav-m22** [comment]
@priyankarpal 
<img width="185" alt="image" src="https://github.com/priyankarpal/ProjectsHut/assets/113239388/12ff090f-f8c3-405c-9dbb-fd433b41d273">

Similar to this... There are alignment issues in this image... It's just for illustration!

**Comment by priyankarpal** [comment]
> @priyankarpal <img alt="image" width="185" src="https://user-images.githubusercontent.com/113239388/242184616-12ff090f-f8c3-405c-9dbb-fd433b41d273.png">
> 
> Similar to this... There are alignment issues in this image... It's just for illustration!

we had icons previously & we removed them.

**Comment by abhinav-m22** [comment]
@priyankarpal 
As these changes are not required, are there any other updates to be made in the navbar? 
Please let me know... I will work on the implementation of there are any... 
Or else this issue can be closed.

**Comment by priyankarpal** [comment]
> @priyankarpal As these changes are not required, are there any other updates to be made in the navbar? Please let me know... I will work on the implementation if there are any... Or else this issue can be closed.

ig we don't need to add/change anything in the navbar. if we need we will create an issue.
