### ISSUE TITLE
[Feat]: Icons optimization to improve project size

### ISSUE THREAD

**Issue by Sanchitbajaj02** [priyankarpal/ProjectsHut#995]
### What feature?

While scrolling through the package.json commits, I found out that the project is using both Material Icons as well as React Icons library.
The size of [React Icons](https://www.npmjs.com/package/react-icons) is 56.7 MB and the size of [Material Icons](https://www.npmjs.com/package/@mui/icons-material) is 18.5 MB.

### Proposal
My proposal is that I will remove the react icons library and try to optimize the code where it is implemented so that the size will be reduced. 

### Screenshot from the package.json

![image](https://github.com/priyankarpal/ProjectsHut/assets/55249639/1cf263ac-2052-4857-94a1-8e68b8c7cce6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
yeah! sounds good 🚀 can we use heroicons? it's size `459 kB`

**Comment by Sanchitbajaj02** [comment]
Yeah sure.
Also, I forgot to mention that I am in GSSOC'23, so can you mark the label, thanks

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
