### ISSUE TITLE
[UI Improvement] - Revamping the Docs page

### ISSUE THREAD

**Issue by kartikkc** [priyankarpal/ProjectsHut#998]
I am from GSSOC'23 and I have noticed that,

On the Docs page of the website the background SVG can be made a little bit transparent and same SVG can be added just above the footer. So, It would look better. 

I want to contribute to this. Could you assign me this issue?

**Comment by priyankarpal** [comment]
hey @kartikkc we need to just change the opacity of the SVG image. we don't need to add to above the footer. also, we are changing the footer.

assigned to you

**Comment by priyankarpal** [comment]
Completed. Thanks for your contributions 🎉 ❤️
