### ISSUE TITLE
data: project addition by 

### ISSUE THREAD

**Issue by Mukesh751** [priyankarpal/ProjectsHut#999]
### Add a new project to the list

Want to add Fruit Ninja Game built using HTML,CSS and JavaScript.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
hey, @Mukesh751 you've created another same issue. you don't need to add multiple issues to add multiple projects at a time. You can add multiple projects by creating a single issue.

so I'm closing this issue.
